### PR TITLE
Eliminate dead code in dagster_pipes

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Dead code in dagster_pipes. Delete.

[seedeadcode](https://app.graphite.dev/macros/dagster-io) 

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by schrockn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16907" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16907?utm_source=stack-comment).

**Comment by schrockn** [comment]
[seedeadcode](https://app.graphite.dev/macros/dagster-io)

**Review by smackesey — APPROVED** [review]
I added a few validations here that use some of these functions:

https://github.com/dagster-io/dagster/pull/16922

If you stack on top of that (or just wait to merge) and then merge this removing the remaining unused functions then it's all good.

**Comment by schrockn** [comment]
Will let #16922 ( https://github.com/dagster-io/dagster/pull/16922 ) land first

**Pull request closed without merging**
