### PR TITLE
deprecate asset_partition_*_for_output on AssetExecutionContext

### PR DESCRIPTION
**Pull request by jamiedemaria**
## Summary & Motivation
Since we are wrapping up active work on the AssetExecutionContext for now, there are a couple of easy deprecations we'd like to get in that will improve user experience until we can more actively work on API development.

This PR deprecates the following methods in favor of:
`asset_partition_key_for_output` -> `partition_key`
`asset_partition_keys_for_output` -> `partition_keys`
`asset_partitions_time_window_for_output` -> `partition_time_window`
`asset_partition_key_range_for_output` -> `partition_key_range`

The majority of the changes in this PR are updating tests to use the non-deprecated APIs

## How I Tested These Changes
updates unit tests

### CODE REVIEW

**Comment by jamiedemaria** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19436?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #17554** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17554?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #18573** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18573?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #17339** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17339?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #18549** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18549?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #19436** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19436?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
          * **PR #18971** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18971?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #19324** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19324?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #18820** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18820?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #19027** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19027?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #19286** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19286?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #19199** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19199?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #19283** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19283?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #19236** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19236?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #19037** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19037?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #19032** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19032?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #18543** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18543?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #18553** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #17972** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17972?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #18044** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18044?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/19436?utm_source=stack-comment).

**Review by sryza — APPROVED** [review]
It looks like these get used frequently in docs, so we should make sure to fix those too before releasing this change.

**Comment by sryza** [comment]
We should also make sure that users don't hit deprecation warnings when they invoke non-deprecated methods that invoke these deprecated methods under the covers.

**Comment by jamiedemaria** [comment]
docs PR https://github.com/dagster-io/dagster/pull/19437

> We should also make sure that users don't hit deprecation warnings when they invoke non-deprecated methods that invoke these deprecated methods under the covers.

Good point. I don't know of any methods calling these methods but I will do a search just to make sure

**Pull request merged**
