### PR TITLE
[docs] Apply max width to docs pages

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Proposal stemming from #13780 which adds a max width to main docs body content. Currently uses 1280px (`max-w-7xl`), which reads nicely in my subjective opinion.

A few comparisons

Unaltered
Screen Shot 2023-04-19 at 2 17 16 PM

5xl
Screen Shot 2023-04-19 at 2 17 44 PM

7xl (in this PR)
Screen Shot 2023-04-19 at 2 17 59 PM

### CODE REVIEW

**Comment by benpankow** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13785** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13785" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13785?utm_source=stack-comment).

**Comment by yuhan** [comment]
should this be the max width including the left and right sidebars? cc @braunjj for design 👀

**Comment by braunjj** [comment]
I like it. I think centering the content like this is the correct approach IMO.

**Review by braunjj — APPROVED** [review]

**Comment by benpankow** [comment]
Screen Shot 2023-04-21 at 10 46 00 AM

I'm noticing some strange clipping as I collapse the page. Any chance someone with more tailwind experience can take a look? 😅 @salazarm @hellendag

**Comment by salazarm** [comment]
my tailwind experience is near 0. It looks like the left/right side bars of the page are a fixed width though and max-7xl is not taking that into account.

**Comment by salazarm** [comment]
fixed it using my raw css powers but its probably not the tailwind way.

**Pull request merged**
