### PR TITLE
Process sensor daemon metadata

### PR DESCRIPTION
**Pull request by dpeng817**
Scaffolding to process sensor daemon metadata

### CODE REVIEW

**Comment by dpeng817** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #18710** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18710?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/18710?utm_source=stack-comment).

**Comment by dpeng817** [comment]
Easier approach has been found

**Review by rexledesma — CHANGES_REQUESTED** [review]
To your queue -- I'm not convinced that this is needed, since the override can happen in `core_loop`.

**Comment by dpeng817** [comment]
Closing in favor of a method that makes more use of existing functionality.

**Pull request closed without merging**
