### PR TITLE
remove graph-backed asset note

### PR DESCRIPTION
**Pull request by sryza**
### Summary & Motivation

I wasn't able to figure out the meaning of this note, and I think it might have more to do with multi-assets than graph-backed assets? I'm also very open to rewording it if it's important.

### How I Tested These Changes

-

### CODE REVIEW

**Comment by clairelin135** [comment]
This message is here because we don't technically allows graph-backed asset subsetting yet. So, when a graph-backed asset outputs multiple assets, if you do an asset selection in Dagit's UI (or via python) we force you to select all of the outputted assets from the graph.

That being said, I'm putting out a PR today that will enable graph-backed asset subsetting. I think we can hold off on deleting this message until that PR is merged.

**Comment by erinkcochran87** [comment]
Related to https://github.com/dagster-io/dagster/pull/9466

**Comment by sryza** [comment]
@clairelin135 would it make sense to remove this note now?

**Comment by clairelin135** [comment]
@sryza lets do it!

**Review by clairelin135 — APPROVED** [review]

**Pull request merged**
