### PR TITLE
[dagster-airlift] dagster cloud proxy operator example

### PR DESCRIPTION
**Pull request by dpeng817**
Copy-paste example for a dagster plus proxy operator

### CODE REVIEW

**Comment by dpeng817** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24195?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24195** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24195?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#24193** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24193?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — CHANGES_REQUESTED** [review]
Given in other case we are subclassing, seems like we should be subclassing here as well? Dynamically generating a class seems a little odd in this case.

**Review by schrockn — DISMISSED** [review]
Per discussion let's hold off on this for now and just have a copy-paste example to see how it lands.

**Review by schrockn — APPROVED** [review]
okie dokie. Can we please add a test so at least we know it doesn't have syntax errors etc.

**Comment by dpeng817** [comment]
@schrockn added a unit test for both operators.

**Pull request merged**
