### PR TITLE
[dagster-airlift] support checks in combine_defs

### PR DESCRIPTION
**Pull request by dpeng817**
combine_defs previously couldn't handle checks correctly (would incorrectly read as an asset)

### CODE REVIEW

**Comment by dpeng817** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23870?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23848** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23848?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23846?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23871** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23871?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23870** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23870?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#23869** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23869?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — APPROVED** [review]
This doesn't hurt, but AssetChecksDefinition does inherit from AssetsDefinition as this point so seems unnecessary?

**Comment by dpeng817** [comment]
@schrockn I think it's necessary, if it just gets slurped as an asset I don't think it behaves properly (at least, that's what I experienced)

**Review by schrockn — APPROVED** [review]
Ok. That's unfortunate.

**Review by schrockn — COMMENTED** [review]
Can you add a linear issue with any relevant context on that? Users will probably run into that issue.

**Pull request merged**
