### PR TITLE
1.4 remove asset methods from OpExecutionContext

### PR DESCRIPTION
**Pull request by alangenfeld**
complete the migration of asset related methods off of `OpExecutionContext` on to `AssetExecutionContext`

## How I Tested These Changes

existing coverage

### CODE REVIEW

**Comment by alangenfeld** [comment]
Current dependencies on/for this PR:
* master
  * **PR #14814** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14814" target="_blank">Graphite</a> 
    * **PR #14822** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14822" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14822?utm_source=stack-comment).

**Comment by sryza** [comment]
Is this not a breaking change? At least for type warnings?

**Comment by alangenfeld** [comment]
> Is this not a breaking change? At least for type warnings?

ya thats why this is waiting til `1.4.0` , do you think requiring users using asset related context methods to have to update to `AssetExecutionContext` to satisfy their type checkers should wait til 2.0?

**Comment by sryza** [comment]
> do you think requiring users using asset related context methods to have to update typehint to AssetExecutionContext to satisfy their type checkers should wait til 2.0?

Hmm yeah this is an interesting question. I do think there's benefit from a user perspective of having that guarantee, though I don't think we strictly have to do this. What do you see as the main advantage of removing them?

**Comment by alangenfeld** [comment]
> What do you see as the main advantage of removing them?

I don't think theres a particularly strong case:
* cleaning things up 
* encouraging adoption of `AssetExecutionContext` which maybe someday we want to break away from being a child of `OpExecutionContext` 

we could certainly defer this

**Comment by sryza** [comment]
did we decide not to go this direction?

**Comment by alangenfeld** [comment]
yea this is invalid after moving back towards just having the same object with a type alias

**Pull request closed without merging**
