### PR TITLE
Spanner kind icon

### PR DESCRIPTION
**Pull request by AdamSkarboJonsson**
## Summary & Motivation
I'm using Dagster and Spanner so I'd like to add the Spanner kind to all Spanner-related assets for a cleaner UI.
I downloaded the `.svg` from https://cloud.google.com/icons?hl=en.

## How I Tested These Changes
Followed https://github.com/dagster-io/dagster/pull/25781 exactly:

> Regenerated the kind tags, ran the Dagster documentation website locally and verified that the kind was visible in the overview.

image

### CODE REVIEW

**Review by salazarm — APPROVED** [review]

**Comment by salazarm** [comment]
Can you follow https://github.com/dagster-io/dagster/pull/25839 instead.
The PR you followed caused the build to fail the same way yours is failing right now.

**Review by salazarm — CHANGES_REQUESTED** [review]
comment

**Comment by AdamSkarboJonsson** [comment]
The [build step](https://buildkite.com/dagster/unit-tests/builds/1206#_:~:text=time%20cd%20docs%20%26%26%20time%20make%20next%2Ddev%2Dinstall%20%26%26%20time%20make%20mdx%2Dformat%20%26%26%20time%20git%20diff%20%2D%2Dexit%2Dcode) ran `time cd docs && time make next-dev-install && time make mdx-format && time git diff --exit-code` and failed. It doesn't fail when I run it locally with the new commit. So the build show succeed :)

**Comment by AdamSkarboJonsson** [comment]
@salazarm Could you unblock the build? 🙏

**Comment by AdamSkarboJonsson** [comment]
:shipit:

**Review by salazarm — APPROVED** [review]

**Pull request merged**
