### PR TITLE
[module-loaders] Delete extra_source_assets param from assets_from_modules

### PR DESCRIPTION
**Pull request by dpeng817**
This PR was used to accumulate the upstack.
## Changelog

> Insert changelog entry or delete this section.

### CODE REVIEW

**Comment by dpeng817** [comment]
* **#26484** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#26494** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26494?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26494?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by OwenKephart — COMMENTED** [review]
ah i see -- sadly this is a public API so we can't actually delete this arg, right?

we could at least make it a hidden param

**Comment by dpeng817** [comment]
@OwenKephart i don't think this is a public api actually. Searched for reference at top level and couldn't find. Was added pre 1.0

**Comment by OwenKephart** [comment]
@dpeng817 huh I swear I tried `from dagster import assets_from_modules` last week and it worked but maybe I mixed it up with something else -- seems good to ditch

**Review by OwenKephart — APPROVED** [review]

**Comment by dpeng817** [comment]
closing because the commits here are now contained within https://github.com/dagster-io/dagster/pull/26494/files - ideally this would be merged but there seems to be some trouble with a graphite command which got this PR into a bad state.

**Pull request merged**
