### PR TITLE
[docathon] swizzle basic 404

### PR DESCRIPTION
**Pull request by cmpadden**
## Summary & Motivation
```
yarn run swizzle @docusaurus/theme-classic NotFound                                                                                │
```
image

Edit: updated to include '404' and helpful links. It's lost some character, but we can always add a cool image later.

image
image

## Changelog [New | Bug | Docs]

NOCHANGELOG

### CODE REVIEW

**Comment by PedramNavid** [comment]
Looks nice! I think it needs to say 404 Not Found somewhere. 





Maybe have some references to other pages in the body? 

> Docs / Getting Started / Tutorial

**Comment by braunjj** [comment]
Love it!

**Comment by cmpadden** [comment]
> Looks nice! I think it needs to say 404 Not Found somewhere.
> 
> 
> 
> 
> 
> Maybe have some references to other pages in the body?
> 
> > Docs / Getting Started / Tutorial

Updated it to include a stylized "404" along with some helpful links. Not as much cowboy character, but pretty clean.
image

But if you want I can add this failed generation of cowboy daggy.
image(2)

**Review by PedramNavid — APPROVED** [review]
like it picasso

**Pull request merged**
