### PR TITLE
Ruff docstrings D301 (Raw string for backslash in docstring))

### PR DESCRIPTION
**Pull request by smackesey**
### Summary & Motivation

This rule is part of [PEP 257](https://peps.python.org/pep-0257/#what-is-a-docstring), I believe the reason is that any literal backslashes should be in raw strings generally to reduce the likelihood of performing an unintended escape.

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11212** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11212" target="_blank">Graphite</a> 
    * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a> 
      * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 
        * **PR #10907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10907" target="_blank">Graphite</a> 
          * **PR #10992** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10992" target="_blank">Graphite</a> 
            * **PR #10993** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10993" target="_blank">Graphite</a> 
              * **PR #10994** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10994" target="_blank">Graphite</a> 
                * **PR #10995** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10995" target="_blank">Graphite</a> 
                  * **PR #10996** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10996" target="_blank">Graphite</a> 
                    * **PR #11329** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11329" target="_blank">Graphite</a>  👈
                      * **PR #10997** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10997" target="_blank">Graphite</a> 
                        * **PR #10998** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10998" target="_blank">Graphite</a> 
                          * **PR #10999** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10999" target="_blank">Graphite</a> 
                            * **PR #11000** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11000" target="_blank">Graphite</a> 
                              * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
                                * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
                                  * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
                                    * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 
                                    * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11329?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11212** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11212" target="_blank">Graphite</a> 
    * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a> 
      * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 
        * **PR #10907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10907" target="_blank">Graphite</a> 
          * **PR #10992** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10992" target="_blank">Graphite</a> 
            * **PR #10993** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10993" target="_blank">Graphite</a> 
              * **PR #10994** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10994" target="_blank">Graphite</a> 
                * **PR #10995** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10995" target="_blank">Graphite</a> 
                  * **PR #10996** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10996" target="_blank">Graphite</a> 
                    * **PR #11329** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11329" target="_blank">Graphite</a>  👈
                      * **PR #10997** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10997" target="_blank">Graphite</a> 
                        * **PR #10998** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10998" target="_blank">Graphite</a> 
                          * **PR #10999** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10999" target="_blank">Graphite</a> 
                            * **PR #11000** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11000" target="_blank">Graphite</a> 
                              * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
                                * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
                                  * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
                                    * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 
                                    * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11329?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11212** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11212" target="_blank">Graphite</a> 
    * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a> 
      * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 
        * **PR #10907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10907" target="_blank">Graphite</a> 
          * **PR #10992** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10992" target="_blank">Graphite</a> 
            * **PR #10993** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10993" target="_blank">Graphite</a> 
              * **PR #10994** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10994" target="_blank">Graphite</a> 
                * **PR #10995** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10995" target="_blank">Graphite</a> 
                  * **PR #10996** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10996" target="_blank">Graphite</a> 
                    * **PR #11329** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11329" target="_blank">Graphite</a>  👈
                      * **PR #10997** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10997" target="_blank">Graphite</a> 
                        * **PR #10998** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10998" target="_blank">Graphite</a> 
                          * **PR #10999** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10999" target="_blank">Graphite</a> 
                            * **PR #11000** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11000" target="_blank">Graphite</a> 
                              * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
                                * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
                                  * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
                                    * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 
                                    * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11329?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11212** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11212" target="_blank">Graphite</a> 
    * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a> 
      * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 
        * **PR #10907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10907" target="_blank">Graphite</a> 
          * **PR #10992** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10992" target="_blank">Graphite</a> 
            * **PR #10993** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10993" target="_blank">Graphite</a> 
              * **PR #10994** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10994" target="_blank">Graphite</a> 
                * **PR #10995** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10995" target="_blank">Graphite</a> 
                  * **PR #10996** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10996" target="_blank">Graphite</a> 
                    * **PR #11329** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11329" target="_blank">Graphite</a>  👈
                      * **PR #10997** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10997" target="_blank">Graphite</a> 
                        * **PR #10998** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10998" target="_blank">Graphite</a> 
                          * **PR #10999** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10999" target="_blank">Graphite</a> 
                            * **PR #11000** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11000" target="_blank">Graphite</a> 
                              * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
                                * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
                                  * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
                                    * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 
                                    * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11329?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11212** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11212" target="_blank">Graphite</a> 
    * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a> 
      * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 
        * **PR #10907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10907" target="_blank">Graphite</a> 
          * **PR #10992** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10992" target="_blank">Graphite</a> 
            * **PR #10993** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10993" target="_blank">Graphite</a> 
              * **PR #10994** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10994" target="_blank">Graphite</a> 
                * **PR #10995** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10995" target="_blank">Graphite</a> 
                  * **PR #10996** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10996" target="_blank">Graphite</a> 
                    * **PR #11329** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11329" target="_blank">Graphite</a>  👈
                      * **PR #10997** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10997" target="_blank">Graphite</a> 
                        * **PR #10998** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10998" target="_blank">Graphite</a> 
                          * **PR #10999** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10999" target="_blank">Graphite</a> 
                            * **PR #11000** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11000" target="_blank">Graphite</a> 
                              * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
                                * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
                                  * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
                                    * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 
                                    * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11329?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11212** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11212" target="_blank">Graphite</a> 
    * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a> 
      * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 
        * **PR #10907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10907" target="_blank">Graphite</a> 
          * **PR #10992** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10992" target="_blank">Graphite</a> 
            * **PR #10993** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10993" target="_blank">Graphite</a> 
              * **PR #10994** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10994" target="_blank">Graphite</a> 
                * **PR #10995** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10995" target="_blank">Graphite</a> 
                  * **PR #10996** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10996" target="_blank">Graphite</a> 
                    * **PR #11329** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11329" target="_blank">Graphite</a>  👈
                      * **PR #10997** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10997" target="_blank">Graphite</a> 
                        * **PR #10998** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10998" target="_blank">Graphite</a> 
                          * **PR #10999** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10999" target="_blank">Graphite</a> 
                            * **PR #11000** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11000" target="_blank">Graphite</a> 
                              * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
                                * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
                                  * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
                                    * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 
                                    * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11329?utm_source=stack-comment).

**Review by schrockn — CHANGES_REQUESTED** [review]
It is not immediately obvious to me why this is a good and/or necessary. Can you add to the summary and motivation section of the PR to explain this.

**Comment by smackesey** [comment]
@schrockn Updated summary/motivation as requested.

**Review by schrockn — APPROVED** [review]

**Comment by smackesey** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: AncAnsoKDhLPxZ3352Xl.
See details on [graphite.dev](https://app.graphite.dev/github/pr/dagster-io/dagster/11329)

**Pull request merged**
