### PR TITLE
add api doc for run_request_for_partition

### PR DESCRIPTION
**Pull request by sryza**

### CODE REVIEW

**Comment by clairelin135** [comment]
Can we also make this show up in the docs? Noticed that it doesn't seem to appear in the run request api docs

**Comment by sryza** [comment]
@clairelin135 when the release runs, it will automatically become part of the JobDefinition and UnresolvedAssetJobDefinition API docs (because it's a method of them). Is that what you're thinking about, or is there somewhere you think it would be useful for it to show up as well?

**Comment by clairelin135** [comment]
@sryza I think it would be nice for it to show up here: https://docs.dagster.io/_apidocs/schedules-sensors# since we show `RunRequests`

**Comment by sryza** [comment]
> @sryza I think it would be nice for it to show up here: https://docs.dagster.io/_apidocs/schedules-sensors# since we show RunRequests

That makes sense. I added a note to the docstring for RunRequest.

**Comment by sryza** [comment]
@clairelin135 mind taking another look?

**Review by clairelin135 — APPROVED** [review]
Looking good!

**Pull request merged**
