### PR TITLE
[refactor] Make RepositoryDefinition.asset_defs_by_key public

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

`RepositoryDefinition._asset_defs_by_key` was externally accessed in enough places that it made sense to just make it (internally public).

---

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12889** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12889" target="_blank">Graphite</a> 
    * **PR #12912** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12912" target="_blank">Graphite</a> 
      * **PR #12913** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12913" target="_blank">Graphite</a> 
        * **PR #12890** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12890" target="_blank">Graphite</a> 
          * **PR #12891** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12891" target="_blank">Graphite</a> 
            * **PR #12892** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12892" target="_blank">Graphite</a> 
              * **PR #12900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12900" target="_blank">Graphite</a> 
                * **PR #12901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12901" target="_blank">Graphite</a> 
                  * **PR #12914** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12914" target="_blank">Graphite</a> 
                    * **PR #12915** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12915" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12915?utm_source=stack-comment).

**Review by dpeng817 — APPROVED** [review]

**Comment by smackesey** [comment]
@smackesey queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12915).

**Comment by smackesey** [comment]
[Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12915) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by smackesey** [comment]
@smackesey queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12915).

**Comment by smackesey** [comment]
[Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12915) rebased this pull request as part of a merge.

**Comment by smackesey** [comment]
@smackesey merged this pull request with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12915).

**Pull request merged**
