### PR TITLE
[DS][42/n] Add labels to eager and cron policies

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

After some changes to the UI, this will make it much easier to understand what's happening inside a given complex policy

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21844?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#21844** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21844?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#21839** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21839?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — APPROVED** [review]

**Comment by ion-elgreco** [comment]
@OwenKephart are you planning on adding this still? :) It would help with reading the automation evaluations with the new conditions

**Comment by OwenKephart** [comment]
@ion-elgreco absolutely still planning this! we're working on a larger redesign of the page which goes a bit beyond just in-place labeling, hence the delay on this specific PR.

**Comment by ion-elgreco** [comment]
@OwenKephart ah awesome! Looking forward to these changes

**Pull request closed without merging**
