### PR TITLE
RFC: map partitionInLast parameter to latestMaterializationByPartition

### PR DESCRIPTION
**Pull request by prha**
## Summary & Motivation
This is more for discussion than for serious merging.

To power the `byPartition` views for assets, we generally want the last materialization per partition.  We used to fake this by fetching all the materializations filtered for some set of partitions, in reverse chronological order.  This will match exactly if we do not limit the number of materializations.  However, we do limit in Cloud.

The `AssetEventsQuery` as it is, is fetching all the materializations for a given set of partitions (as determined by the definition).

We have a number of options, to force this to use a smarter query:
1. Change the `assetMaterializations` resolver of `Asset` to effectively do the same call as the `latestMaterializationByPartition` resolver of `AssetNode` (this PR).
2. Change the frontend code to make a different query, to actually use the existing `latestMaterializationByPartition` resolver off of the asset definition (`AssetNode`).
3. Add `latestMaterializationByPartition` / `latestObservationByPartition` resolvers to `Asset` to match the resolvers on `AssetNode`.  The definition is not required if we pass in the partitions.  If they are not provided, we can do the same check as https://github.com/dagster-io/dagster/blob/7ea5bc7e6208e3a2fd750ff69dbb59e9708e3022/python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py#L248 to get the partitions off of the definition.

The `useRecentAssetEvents` is used in more than one spot, so may need to verify that the same option is desired in all callers.

We should also discuss if we need to do more in OSS to support the `latestXByPartition` calls.

## How I Tested These Changes
TBD

### CODE REVIEW

**Comment by gibsondan** [comment]
(or option 3 could also work too)

**Comment by bengotow** [comment]
Hey gang - I think this PR or #2 are both good solutions here. A few more call-outs:

- As far as I know, `latestMaterializationByPartition` is not in use

- The `useRecentAssetEvents` hook has two uses: 1) powering the asset plots and 2) powering the timeline on the asset overview of recent materializations (which is always last 100, not by partition - not impacted by this change)

I think the question here is essentially how to power the asset plots when they're displaying "last N partitions".  Our current solution of fetching EVERY materialization + observation in the last 100 partitions is nice because it supports sparsely-emitted metadata. But what we're after is numerical event metadata for that day.  Right now, we take all the events for each partition, group them together, sort them by timestamp, and then flatten the metadata key-value pairs into single object for that partition.

If we want to double down on asset plots as a feature, we could move that to the backend somehow. If we need a faster implementation, we could switch to just the last materialization + observation for each day and only lose things in the sparse-metadata case, which seems like an edge case.

Somewhat related, but we currently have separate GraphQL APIs for asset observation and materialization history, and we'd love to have a single `assetEvents()` that takes an optional type parameter (to support the filter checkboxes on the events page). Having to pull them separately requires a bunch of post-processing client side because we paginate them with a single cursor.

**Comment by prha** [comment]
@bengotow would you be able to change `useRecentAssetEvents` to swap to use the `definition` > `latestMaterializationByPartition` field in the case of the by 'partition' view (option 2)?  I think we'll actually want to deprecate the `partitionInLast` parameter.

**Comment by bengotow** [comment]
Yep I believe we can do that, I'll give it a shot 👍

**Pull request closed without merging**
