### PR TITLE
improve sqlalchemy pin

### PR DESCRIPTION
**Pull request by alangenfeld**
1.4 added `subquery` to `Select` which is a code path we use in our sql storage base class

## Test Plan

bk

### CODE REVIEW

**Comment by alangenfeld** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6835** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6835" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by prha — DISMISSED** [review]
thanks... I spent 20 minutes trying to write backwards compatible queries, but I think this is probably better?

**Review by alangenfeld — COMMENTED** [review]
1.4 was almost a year ago. I do have some concern that this may cause conflicts for end users.

Probably best to have the pin accurate in the near term and then relax it in a PR that includes back compat queries if this pin is causing issues for users.

**Review by alangenfeld — COMMENTED** [review]
hmm the airflow conflicts are real and may present a challenge to users who may wish to migrate from airflow 1 to dagster 😞

**Review by alangenfeld — COMMENTED** [review]
trying to remove our pin there to see if that problem remains

**Comment by alangenfeld** [comment]
hmm not sure what to do about this

**Comment by alangenfeld** [comment]
resolved by https://github.com/dagster-io/dagster/pull/6841

**Pull request closed without merging**
