### PR TITLE
chore: move databricks pipes to dagster-databricks-pipes

### PR DESCRIPTION
**Pull request by ion-elgreco**
## Summary & Motivation
Databricks-pipes should be it's own library since it has no dependency on spark or other component of dagster-databricks. Keeping this in it's seperate library allows you to do lazy importing on spark because otherwise dagster-databricks installs dagster-pyspark and then also spark, which we want to avoid.

I tried replacing all docs and all references to new locations. I believe everything is replaced.

- closes https://github.com/dagster-io/dagster/issues/22724

### CODE REVIEW

**Comment by ion-elgreco** [comment]
@alangenfeld @yuhan @smackesey can you kick of the CI please

**Comment by ion-elgreco** [comment]
@alangenfeld @yuhan @smackesey @garethbrickman  can you kick of the CI again please?

**Comment by ion-elgreco** [comment]
Current failures are related to other libraries, there is still one import failure on the docs. Would be great if a core dev can look at this

**Comment by cmpadden** [comment]
Hey @ion-elgreco - after some more discussion around this, we would like pipes to be the primary implementation in `dagster-databricks`, and the heavy pyspark dependent implementation an optional installation, or even deprecated / removed from the library.

For the time being I'm going to close this PR, but thank you for bringing to our attention the problem with embedding the pipes implementation in an existing library.

**Pull request closed without merging**
