### PR TITLE
Fix asset partitions on build i/o contexts

### PR DESCRIPTION
**Pull request by dpeng817**
Fixes asset partitions on build input/output contexts. has_asset_partitions is used to determine whether we add partitions to the path for UPathIOManager - but is currently completely unsupported by the build_x_context functions.

### CODE REVIEW

**Comment by dpeng817** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13974** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13974" target="_blank">Graphite</a> 
    * **PR #13975** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13975" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13975?utm_source=stack-comment).

**Review by sryza — APPROVED** [review]
Would it be difficult to add a test for this?

**Review by sryza — COMMENTED** [review]
Sorry approved by accident. Also just saw your comment about asking for someone to take it on. Will see if I can do.

**Review by sryza — CHANGES_REQUESTED** [review]
Oops actually requesting changes this time

**Comment by dpeng817** [comment]
closing this until someone wants to take a look at it again

**Pull request closed without merging**
