### PR TITLE
Pinning Pydantic to < 2.0.0. Fixes #15147

### LINKED ISSUE #15147: ImportError when importing ConstrainedFloat from pydantic for pydantic>=2.0.0
### Dagster version

1.3.13

### What's the issue?

The following error occurs when running Dagster with pydantic>=2.0.0:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/base_env/lib/python3.10/site-packages/dagster/__init__.py", line 100, in <module>
    from dagster._config.pythonic_config import (
  File "/base_env/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 23, in <module>
    from pydantic import ConstrainedFloat, ConstrainedInt, ConstrainedStr
  File "/base_env/lib/python3.10/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
  File "/base_env/lib/python3.10/site-packages/pydantic/_migration.py", line 285, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:ConstrainedFloat` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.0.2/u/import-error
```

### What did you expect to happen?

_No response_

### How to reproduce?

_No response_

### Deployment type

Dagster Cloud

### Deployment details

_No response_

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by zyd14**
## Summary & Motivation

Fixing #15147 

## How I Tested These Changes

Reinstalled dagster development env from scratch with pin and ran unit tests

### CODE REVIEW

**Comment by jamiedemaria** [comment]
not sure why the diff isn't showing this, but we already have this pin in latest! https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/setup.py#L104C37-L104C37

**Comment by jamiedemaria** [comment]
cc @benpankow

**Comment by zyd14** [comment]
Oh cool, well then this can just get closed I suppose!

**Comment by zyd14** [comment]
Wonder why the pin didn't show up when I pulled down master, quite strange

**Comment by jamiedemaria** [comment]
> Wonder why the pin didn't show up when I pulled down master, quite strange 

that's what i'd like to know as well. this pin has been in for 3 weeks now i think, so it's very strange

**Comment by jamiedemaria** [comment]
ah yeah looks like your fork is ~300 commits behind. Closing this as resolved!

**Comment by zyd14** [comment]
Ah okay, my bad. Thanks Jamie!

**Pull request closed without merging**
