### PR TITLE
[rfc] replace_attributes(spec, ...) and merge_attributes(spec, ...)

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Adds two new type-hinted methods to let users replace `AssetSpec` attributes or merge new metadata, tag, owner, dep values. Shipped as standalone methods for us to use internally, at first.

These methods pass through `dagster_internal_init`, so they correctly post-process any coercible inputs (e.g. `AssetKey` to `AssetDep`).

```python
spec = AssetSpec(key="foo", owners=["original@dagsterlabs.com"])

spec_with_replaced_owner = replace_attributes(spec, owners=["replacement_owner@dagsterlabs.com"])

spec_with_additional_owner = merge_attributes(spec, owners=["additional_owner@dagsterlabs.com"])
```

## Changelog

`NOCHANGELOG`

### CODE REVIEW

**Comment by benpankow** [comment]
* **#25094** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25094?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
Something like this makes a lot of sense to me. I'd suggest we check them in as standlone functions for now for internal use to reduce discoverability until we have higher confidence they are good public APIs.

And then we need some end-to-end example with real use cases. But I think either way this is a good direction.

**Comment by OwenKephart** [comment]
Just a consideration on naming is that I found it hard to intuit the difference between "replace" and "merge" without looking at the code / docstring. At some level, the "replace" method is still "merging" attributes, just not on a per-field basis. Maybe "add_attributes" would make it a bit more obvious? i.e. it feels pretty predictable what `spec.add_attributes(owners=["..."])` will do.

**Comment by benpankow** [comment]
> Just a consideration on naming is that I found it hard to intuit the difference between "replace" and "merge" without looking at the code / docstring. At some level, the "replace" method is still "merging" attributes, just not on a per-field basis. Maybe "add_attributes" would make it a bit more obvious? i.e. it feels pretty predictable what `spec.add_attributes(owners=["..."])` will do.

Hmm, I don't disagree that the names could be better. I think you do end up running into a similar problem if the two verbs are `merge` and `add` - I would not expect `merge` to be destructive in that it replaces the existing value of any of the keys I specify, e.g. `my_spec.merge_attributes(metadata=...)`

**Comment by benpankow** [comment]
Updated to ship as standalone functions (non-`@public`) so we can use them internally

**Comment by OwenKephart** [comment]
I think `replace_attributes()` feels natural to me, and in my mind slightly preferable to `update_attributes()` for that use case.

Re: the add_attributes() stuff, I don't hate the idea of separate methods for adding owners and adding metadata, although the asymmetry feels a bit off to me.

**Review by schrockn — APPROVED** [review]
I think these are solid

**Pull request merged**
