### PR TITLE
RFC: Code Location API

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

I am not sure of the status of the project to build some asset checks from persisted state, but just wanted to throw something out there that has stewed in my head since we chatted about it.

In order to implement that feature successfully, I believe we will need to iterate on our APIs to be a little more flexible. Along the way, I think we can build a more transparent API for users that understand code servers, code locations, and Definitions objects and want to use them for more advanced use cases. This is no way eliminates the current user experience of `defs = Definitions(...)`. It builds on that when it is not sufficient.

The idea here is pretty simple. We add two new classes to our public-facing API: `CodeServer` and `CodeLocation`.

A `CodeServer` contains a `List[CodeLocation]`. 

`CodeLocation` has an explicit `name` attribute, and an abstract method that returns a `Definitions` object. This is key as it allows a `Definitions` object to be lazily loaded and it enables a first-class API for specifying multiple named code locations within a single code server (as opposed to using `create_repository_using_definitions_args`)

```python
@asset
def an_asset_a() -> None:
    pass


class ACodeLocation(CodeLocation):
    name = "a_code_location"

    def load_definitions(self) -> Definitions:
        return Definitions([an_asset_a])

@asset
def an_asset_b() -> None:
    pass

class BCodeLocation(CodeLocation):
    name = "b_code_location"

    def load_definitions(self) -> Definitions:
        return Definitions([an_asset_b])

code_server = CodeServer(code_locations=[ACodeLocation(), BCodeLocation()])
```

This is much more explicit that we have today, and leaks our core ontology in a good way, in my opinion. It would require a slight change in our vocabulary: we use code location and code server interchangeable today, which is a source of confusion. We would completely remove the vocabulary of "repository", even for advanced use cases. Instead one would have multiple, named code locations per code server to handle that use case.

Where this gets more interesting is if we do more surgery and take advantage of lazily constructed definitions. Consider the case where we want to build Definitions based on persisted state. E.g. UI-driven checks or assets definitions. `CodeServer` enables that:

```class CustomCodeServer(ICodeServer):
    def load_code_locations(self) -> Iterable[CodeLocation]:
        return [
            ACodeLocationWithDefsBuiltFromPersistedState()
        ]

class ACodeLocationWithDefsBuiltFromPersistedState(CodeLocation):
    name = "a_code_location"

    def load_definitions(self) -> Definitions:
        return Definitions(
            build_assets_defs(
                get_serialized_representation_of_assets_from_storage()
            )
        )


code_server = CustomCodeServer()
```

We would then add a grpc method to invoke `load_definitions` on a CodeLocation _without_ requiring code server restart, dramatically improving iteration speed. 

I also think this would serve as a successor to `CacheableAssetsDefinition`. Definitions that require interaction with storage or an API would happen after the code server has successfully loaded.

## How I Tested These Changes

I did not.

### CODE REVIEW

**Comment by schrockn** [comment]
* **#20382** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20382?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by gibsondan** [comment]
Very thought provoking, lots to like here. Some initial thoughts based on just reading the summary of the PR:

- I like the CodeLocation construct but I don't love the CodeServer name - I don't have a better alternative yet but it's weird to me that the first thing a run process does on startup is to load a CodeServer object, since there is no server in the mix there. Do we actually need a separate object for that, or could we get away with a list of CodeLocation objects?

- Big fan of adding more explicit lazy-loading functionality to help with import-time performance problems, the fewer expensive things that need to happen as a side-effect on import the better off we will be for users with large amounts of definitions. We should think carefully about what public APIs we want to support on this code location object to give it the power to do fancy lazy-loading stuff - in the past I have been reduced to recommending people do something like this (making use of an env var that happens to be present on run process startup and step process startup) to avoid jobs that are expensive just to import, hoping that can become a thing of the past and we can develop a better recommended pattern there:

```
runtime_jobs = []
if os.getenv("DAGSTER_RUN_JOB_NAME"):
    runtime_jobs = [job for job in all_jobs if job.name == os.getenv("DAGSTER_RUN_JOB_NAME")]

defs = Definitions(
    assets=all_assets,
    resources=deployed_resources,
    sensors=all_sensors,
    jobs=runtime_jobs,
    schedules=all_schedules
)
```

What gets really tricky is when there's something like a slow dbt manifest that powers some of the assets in the graph, that may or may not need to be loaded in a run or step process depending on the context - if we can develop a recommended pattern there for only loading what we need to in each process, that would be very cool

- This one is easy to fix, but we have an existing CodeLocation object that would need to be renamed to HostedCodeLocation or ExternalCodeLocation or whatever the latest nomenclature is for "thing that can be loaded in a system process"

**Review by gibsondan — COMMENTED** [review]
A concrete example of what it would look like for this to replace CacheableAssetsDefinition (for something like, say, dbt cloud assets) would be pretty instructive I think. Maybe that's the example of where you would need the on_code_server_start hook, to pull the data out of dbt cloud and stuck it the object that's currently called RepositoryLoadData and is persisted on the execution plan snapshot for each run?

**Comment by schrockn** [comment]
> A concrete example of what it would look like for this to replace CacheableAssetsDefinition (for something like, say, dbt cloud assets) would be pretty instructive I think. Maybe that's the example of where you would need the on_code_server_start hook, to pull the data out of dbt cloud and stuck it the object that's currently called RepositoryLoadData and is persisted on the execution plan snapshot for each run?

I'm imaginging something like:

```python
class BCodeLocation(CodeLocation):
    name = "b_code_location"

    def on_load(self):
        serialized_data = do_some_expensive_thing()
        return LoadResult(serialized_data=serialized_data)
    
    def load_definitions(self, context) -> Definitions:
        return Definitions(build_assets_from_serialized_data(context.serialized_data))
```

And having lifecycle hooks at code location and code server level.

**Comment by gibsondan** [comment]
What's an example of where you would want a lifecycle hook at the code server and but not at the definition/CodeLocation level? I'm still trying to see if we can get away with allowing you to have multiple named Definitions and making them smarter about lazy-loading and caching, but without having to also add a new CodeServer name and concept to have to worry about

**Comment by schrockn** [comment]
Anything infra-related to the compute resource (pod, ecs task, etc) that is running the code server.

I don't really see how we can avoid two concepts, unless we completely eliminate the notion of having multiple repositories/code locations per code server.

**Comment by gibsondan** [comment]
Usually those types of infra-related things (secrets/resource limits/etc.) have to be defined outside of code (e.g. in a dagster_cloud.yaml file), because you often need to know them before you load the code in the first place

**Comment by schrockn** [comment]
Here's a version that eliminates `CodeServer` and instead just uses `CodeLocation` but still supports the multiple repositories in a process case with `MultiDefinitionCodeLocation`

```python
from typing import Mapping

from dagster import Definitions, asset
from dagster._core.definitions.code_server import CodeLocation, MultiDefinitionsCodeLocation


@asset
def an_asset_a() -> None:
    pass


class ACodeLocation(CodeLocation):
    # could put metadata here
    # team = "some team name"
    def load_definitions(self) -> Definitions:
        return Definitions([an_asset_a])


code_location = ACodeLocation()


@asset
def an_asset_b() -> None:
    pass


class ABCodeLocation(MultiDefinitionsCodeLocation):
    def load_definitions_dict(self) -> Mapping[str, Definitions]:
        return {"a_defs": Definitions([an_asset_a]), "b_defs": Definitions([an_asset_b])}


code_location = ABCodeLocation()
```

**Comment by alangenfeld** [comment]
> We would then add a grpc method to invoke load_definitions on a CodeLocation without requiring code server restart, dramatically improving iteration speed.

I worry about the subtlety between being able to rebuild in process because only the data source for definition generation changed versus needing a process restart because code changed. I expect you would need to be pretty heavy handed about the difference and how its communicated in the code and product.

**Comment by schrockn** [comment]
Btw another thing you could have  in this structure is lifecycle hooks for branch deployment lifecycle stuff. You could run code when branch deployments are created, redeployed, or destroyed.

**Pull request closed without merging**
