### PR TITLE
[dagster- snowflake-pandas] Fix Loading Empty Dataframe crashes Snowflake Pandas IO Manager #24172

### PR DESCRIPTION
**Pull request by reinthal**
## Summary & Motivation

Fix SnowflakePandasIOManager crashing when empty dataframes are sent to Snowflake

## How I Tested These Changes

- Unit test `test_handle_empty()` which sends empty dataframe
- Integration test `test_io_manager_with_snowflake_pandas_only_columns()` which sends columns but no data

## Changelog [Bug]

* Fixed bug where SnowflakePandasIOManager crashes when sent an empty data frame

### CODE REVIEW

**Review by jamiedemaria — COMMENTED** [review]
Hey @reinthal thanks for contributing this! 

One of the reasons we hesitated to add this functionality is because it means empty dataframes will be provided as input to ops/assets whos upstreams have not run. I added a couple tests to this PR to demonstrate. For example, if a user has two assets  `A -> B` and ` materializes  `B` before `A` is ever materialized, should B get an empty dataframe? What if A has been materialized, but the table was dropped for some external reason? 

@sryza and @yuhan i'm interested in your thoughts on this. I think it  goes against some of the decisions we made last year about how to handle loading None inputs, where we decided **not** to load `None` if the storage location for the upstream asset doesn't exist (some I/O managers will fail if the upstream file doesnt exist), but i can be convinced otherwise

**Comment by sryza** [comment]
> For example, if a user has two assets A -> B and materializes B before A is ever materialized, should B get an empty dataframe?

In this case, does the physical table A exist on in the database? If not, I would expect an error.

**Comment by jamiedemaria** [comment]
>  In this case, does the physical table A exist on in the database? If not, I would expect an error.

Yeah, the case where the physical table does not exist

**Comment by jamiedemaria** [comment]
I think the three cases are:
`A -> B`

1. B is materialized before A is ever materialized. So the table for A does not exist 
2. A is materialized, but the table is dropped before B is materialized. So the table for A does not exist 
3. The first materialization of A returns an empty dataframe. No table is created in snowflake. Then B is materialized 
4. A is materialized with a non-empty dataframe, and a table is created. Then A is materialized again and returns an empty dataframe. The table still exists, but has no values in the columns. Then B is materialized. 

It's tough because scenarios 1, 2 and 3 all look the same to the `load_input` fn. For 1 and 2 I think it makes sense to error, but 3 is a little more iffy. I think we could justify either erroring or returning an empty dataframe. 

For scenario 4 it makes sense to load the "empty" dataframe (it'll have columns but no rows). And this PR does fix the issue where the I/O would error when the empty df is returned in the second materialization

**Comment by reinthal** [comment]
Hi, 

@jamiedemaria @sryza 

The use case that we tried to cover here is for letting downstream assets for a pipeline to continue to run even though a partition is empty. Currently, an empty partition will stop the subsequent assets of the pipeline to build.

I can code for scenario 1, 2 and 3. The usecase we wanted to cover is for scenario 4 where we have partition the upstream A and the current day of A is empty, we still want to build B.

for more details on our use case we opened this issue

https://github.com/dagster-io/dagster/issues/24172

**Comment by sryza** [comment]
> For scenario 4 it makes sense to load the "empty" dataframe (it'll have columns but no rows). And this PR does fix the issue where the I/O would error when the empty df is returned in the second materialization

Agreed.

> The use case that we tried to cover here is for letting downstream assets for a pipeline to continue to run even though a partition is empty. Currently, an empty partition will stop the subsequent assets of the pipeline to build.

That makes sense to me.

> I can code for scenario 1, 2 and 3. The usecase we wanted to cover is for scenario 4 where we have partition the upstream A and the current day of A is empty, we still want to build B.

Which scenarios does this existing PR change the behavior of? Is my understanding correct that it only changes the behavior of 3? If so, then would the way to handle it be to just fail if the dataframe is empty and the table does not exist, and succeed otherwise? That would fix 3 and leave 1 and 2 unchanged? Which seems desirable?

**Comment by reinthal** [comment]
Moved on  to other things  : )

**Pull request closed without merging**
