### PR TITLE
RFC: add request counts for instance calls

### PR DESCRIPTION
**Pull request by prha**
## Summary
This will only work in OSS (using flask calls), but this is a way of counting calls to DagsterInstance for methods that read from storage.

## Test Plan
BK

### CODE REVIEW

**Comment by prha** [comment]
Screen Shot 2021-12-08 at 9 02 18 AM

**Comment by bengotow** [comment]
This seems super useful to me - I think we'd pretty much always want it turned on in Dagit when dev logging is enabled. 

I pulled it down to see if I could debug a perf issue I'm seeing and I guess it's not a storage read problem, which is also good to know :-) It was able to spot one potentially problematic fan-out in another query though! (fetching the last materialization for each asset in the mega asset graph)
 
image

**Comment by prha** [comment]
@bengotow, yeah, I already started working on a `lastAssetMaterializations` batch call at the top-level query root.  It's a little hairy to implement, but mostly because we have a bunch of tech debt in the asset storage layer.

**Review by alangenfeld — CHANGES_REQUESTED** [review]
as discussed on call - lets set this up to have somthing like `@traced` as our decorator then a way to register (and unregister) being informed about the traced calls

**Comment by prha** [comment]
I think this will work with asyncio (set up a test), but not sure I have a complete handle on the requirements for the threaded case.

**Review by alangenfeld — APPROVED** [review]

**Review by alangenfeld — COMMENTED** [review]
I can build on top of this for the more complex tracing

**Comment by prha** [comment]
👍  .  yeah, started messing with  before/after parameters, but was just building it blind.

**Pull request merged**
