### PR TITLE
Update the target Python version for Ruff commands

### PR DESCRIPTION
**Pull request by deepyaman**
## Summary & Motivation

Fix a minor inconsistency. ~There's no effect, because most pyupgrade rules aren't included.~

~(I'd be happy to introduce the pyupgrade rules, if people are open to it.)~

### CODE REVIEW

**Comment by danielgafni** [comment]
@deepyaman hey, looks like `ruff` actually wants to reformat some files.

It wasn't kicked off in CI, probably because of the lack of changes in this PR. 

Do you mind running `make ruff` locally? 

As for the `UP` rule, I am already working on this here: https://github.com/dagster-io/dagster/pull/25703, so I'd suggest to keep the current scope of this PR.

**Review by danielgafni — DISMISSED** [review]
Please run `make ruff`

**Comment by deepyaman** [comment]
> @deepyaman hey, looks like `ruff` actually wants to reformat some files.
> 
> ```
> ❯ make ruff
> ruff check --fix .
> All checks passed!
> ruff format .
> 27 files reformatted, 4359 files left unchanged
> ```
> 
> It wasn't kicked off in CI, probably because of the lack of changes in this PR.

Got it. Pre-commit was actually making these changes for me, but I didn't commit them, since I thought something was wrong with my Ruff setup. 🙈 I didn't understand why upgrading the target version would make these changes; I thought maybe Ruff wasn't picking up `line-length` configuration or something on my end, but seems not.

> As for the `UP` rule, I am already working on this here: #25703, so I'd suggest to keep the current scope of this PR.

Ah, I didn't see this! I've gone ahead and made the requested change, but if you want to just close my PR in favor of yours, that's also understandable!

**Comment by danielgafni** [comment]
It's fine, there shouldn't be conflicts with my PR! Or they are going to be easy to resolve.

**Review by danielgafni — APPROVED** [review]
lgtm

**Pull request merged**
