### PR TITLE
Remove RunsFilter serialization?

### PR DESCRIPTION
**Pull request by johannkm**
Am I missing somewhere this is used? Somewhere in user space? If not, any reason to keep it?

### CODE REVIEW

**Comment by johannkm** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17430** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17430" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17430?utm_source=stack-comment).

**Comment by alangenfeld** [comment]
what does blame reveal ? when did the whitelisting get added?

**Comment by johannkm** [comment]
That was fun.

It's been whitelisted since the beginning, in this ben gotow diff https://github.com/dagster-io/dagster/commit/b2f96902ba550237c393646fbfcf399d55d6ee35#diff-3968d932c73d00a729ad9876052a56528ff6f3ab192cb1191cc9c30087431f7eR491

Along the way I found this message from @prha https://github.com/dagster-io/dagster/pull/8415#discussion_r898344933 which mentions deserializing it on cloud, but I haven't been able to find what that was referring to. Might have been speculation. The gql storage is the obvious place to look, but it doesn't seem like we ever used serdes there https://github.com/dagster-io/internal/blame/f1ccca7c91cf15020cbd66e509f3dab33b431e8a/dagster-cloud/python_modules/dagster-cloud/dagster_cloud/storage/runs/storage.py#L70

**Comment by johannkm** [comment]
Any appetite to stamp? I'm also ok to back down (could add a deprecation warning?)

**Pull request merged**
