### PR TITLE
Reduce mypy errors (use sys.info instead of try-fail)

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by MartinThoma** [comment]
(I've seen and understand the issue; I'll fix it in roughly 12h)

**Comment by alangenfeld** [comment]
Nice, thanks! Running our full CI then will merge

**Comment by MartinThoma** [comment]
I'll have a look at that tomorrow:

```

************* Module dagster.seven
--
  | python_modules/dagster/dagster/seven/__init__.py:14:4: E0611: No name 'tempfile' in module 'backports' (no-name-in-module)
  | python_modules/dagster/dagster/seven/__init__.py:14:4: E0401: Unable to import 'backports.tempfile' (import-error)
  | python_modules/dagster/dagster/seven/__init__.py:30:4: E0401: Unable to import 'functools32' (import-error)
```

(Other topic: I'm a bit confused by seeing "buildkite/dagster/black — Passed (49 seconds)" - do you use the black formatter? Why does that pass? I'm pretty sure I have seen non-black formatted code)

**Comment by alangenfeld** [comment]
>  do you use the black formatter? Why does that pass?

Ya you can check the Makefile in the root to see what args we use

**Comment by MartinThoma** [comment]
When I run `make check_black` I get `53 files would be reformatted, 740 files would be left unchanged, 7 files would fail to reformat.`

Picking just one of many examples: https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/seven/abc.py#L45-L62 is not `black` formatting because of the `'` - [black would use `"`](https://black.readthedocs.io/en/stable/the_black_code_style.html#strings). Hence my confusion.

**Comment by alangenfeld** [comment]
huh - which version of `black` are you running? We pin to `19.10b0` via `python_modulesdagster/dev-requirements.txt` and use `-S` / `--skip-string-normalization` which avoids coercing quotes.

**Comment by MartinThoma** [comment]
Good catch! Yes, my black version was a bit outdated. I didn't have the `-S` flag.

**Comment by MartinThoma** [comment]
Going back to the bug: I'm still a bit puzzled by it. If I read https://buildkite.com/dagster/dagster/builds/8064#f1449ea8-72ea-4350-a1b6-19b68d7a7726 correctly, then it runs from a docker image 968703565975.dkr.ecr.us-west-1.amazonaws.com/buildkite-integration:py3.7.4-v6 - the name indicates that Python 3.7 is executed there. But the failure (`__init__.py:14:4: E0611: No name 'tempfile' in module 'backports'`) indicates that `sys.version_info[0] <= 2` is true.

**Comment by MartinThoma** [comment]
I understand the problem now, but it might be that it is not possible to make pylint and mypy happy at the moment. https://github.com/python/mypy/issues/1393#issuecomment-560165876 could be a blocker. Let's see, maybe somebody knows a work-around: https://stackoverflow.com/q/59295045/562769

**Comment by alangenfeld** [comment]
> not possible to make pylint and mypy happy

I think we would be fine with suppression comments to disable pylint assuming it's just in a few spots.

**Comment by mgasner** [comment]
apologies, these test failures on windows are my fault -- if you rebase on master these should go away

**Comment by mgasner** [comment]
Windows failures are resolved on master so I think this is gtg.

**Comment by mgasner** [comment]
Let's rebase on master to kick the CI off again and then should be good to go when all checks are green.

**Pull request closed without merging**
