### PR TITLE
Remove poetry lockfile from dagster-celery

### PR DESCRIPTION
**Pull request by gibsondan**
Summary:
Dependabot is complaining about one of the dependencies here that was added recently in a poetry.lock file 

Test Plan: BK

### CODE REVIEW

**Comment by alangenfeld** [comment]
Yea i went back and forth in my head about trimming it from the original PR but decided to let it through. 

Thoughts on just removing just the lock file and adding a warning to the example that it was a community contribution and is not under active test?

**Comment by gibsondan** [comment]
Is the lock file needed to run it? The pyproject.toml mentions poetry

**Comment by alangenfeld** [comment]
fairly certain it will just generate a new one on first use if there isn't an existing lock file

**Comment by gibsondan** [comment]
updated to just removing the lockfile

**Review by alangenfeld — APPROVED** [review]

**Pull request merged**
