### PR TITLE
Rename DataDogClientResource to DatadogResource; DataDogClient to DatadogClient

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Per our new naming conventions, rename DataDogClientResource to DatadogResource. And DataDogClient to DatadogClient as that appears to be more consistent with Datadog's capitalization norms.

Despite this url's (https://github.com/DataDog/datadogpy ) indication to the contrary, it refers to the "Datadog Python Library" in the body of its readme, so we are following that.

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by schrockn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13700** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13700" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13700?utm_source=stack-comment).

**Review by benpankow — APPROVED** [review]

**Review by yuhan — CHANGES_REQUESTED** [review]
according to [datadog wiki](https://en.wikipedia.org/wiki/Datadog) and for naming consistency with e.g. https://github.com/dagster-io/dagster/pull/13701, i think this should be `DatadogResource` as opposed to `DataDogResource`

**Review by yuhan — APPROVED** [review]

**Comment by joshuataylor** [comment]
Should this have been listed as a breaking change in the changelog? We were relying on this and had to change it.

Not a big deal, but should still be listed.

**Comment by schrockn** [comment]
@joshuataylor are you referring specifically to DataDogClientResource that went out with 1.2.7?

If so yes this was a bit of an oversight. The original sin here was putting DataDogClientResource in the public API in that release in the first place as we were still settling on our naming conventions. This will be stable going forward.

I hope this didn't cause you too much inconvenience.

**Comment by joshuataylor** [comment]
Nope, didn't have any major impact, didn't mean the comment to sound that way, sorry! 🙇 

We always test major updates, and always have no hassles because the documentation and changelog for updates is great. 👍

**Comment by schrockn** [comment]
No worries. I just want to understand what problem you hit precisely, to make sure that this won't impact a bunch of users.

To be clear you started using `DatadogClientResource` right after 1.2.7, and the rename to `DatadogResource` broke you with 1.3?

**Pull request merged**
