### PR TITLE
[docs] fix GCS api docs page

### PR DESCRIPTION
**Pull request by jamiedemaria**
## Summary & Motivation
The new resources didn't get added to the api docs page (my bad). This adds them and restructures the page a bit so that it's easier to parse imo

### CODE REVIEW

**Comment by jamiedemaria** [comment]
Current dependencies on/for this PR:
* master
  * **PR #14498** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14498" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14498?utm_source=stack-comment).

**Comment by erinkcochran87** [comment]
@jamiedemaria Would you mind seeing if you can get the Vercel preview to deploy? There are some things I want to point out but can't due to the source files not changing in this PR, so I was opening to leave preview comments instead

**Comment by jamiedemaria** [comment]
done! since the changed pages didn't get picked up, here's the link https://dagster-l32m9bkwe-elementl.vercel.app/_apidocs/libraries/dagster-gcp

**Review by erinkcochran87 — COMMENTED** [review]
I left some comments on the preview - I really dig the new structure! let me know if you have any trouble seeing the Vercel comments

**Review by erinkcochran87 — APPROVED** [review]

**Pull request merged**
