### PR TITLE
[library template] add registry call

### PR DESCRIPTION
**Pull request by alangenfeld**
update to comply with new library registry 

### How I Tested These Changes

```
python scripts/create_dagster_package.py -n dagster-testing-gen
pip install -e python_modules/libraries/dagster-testing-gen
python> import dagster_testing_gen
```

### CODE REVIEW

**Review by jamiedemaria — APPROVED** [review]
nice! thanks

**Comment by alangenfeld** [comment]
is there a good way to test it? or are you confident in this from inspection

**Comment by jamiedemaria** [comment]
not a great way to test rn other than making a fake package and looking that the files are correct. the template looks right to me though

do you have ideas on testing? i'm not sure what we'd do other than automating creating a fake package, and maybe running pytest on it?

**Comment by alangenfeld** [comment]
test idea
* run it in to a temp dir 
* pip install -e it
* verify you can import it

**Pull request merged**
