### PR TITLE
Change `AssetsDefinition._from_node()` to use output prefixes globally

### PR DESCRIPTION
**Pull request by tghanken**
## Summary & Motivation

We are trying to use Freshness Policies to make our pipelines easier to manage, but were running into issues where they were not being applied to specific assets.  After investigating, I narrowed down the issue to the `key_prefix` parameter in `AssetsDefinition.from_op()` and opened up issue #13450.

I looked into the underlying code a bit, and it seems like this is a very straightforward fix, so I threw together a PR.

## How I Tested These Changes

Using the following test file, I verified that `test_table_wo_freshness` doesn't show a freshness policy with Dagster v1.2.6, but does with this patch.

```python
from dagster import AssetsDefinition, FreshnessPolicy, Out, op

@op(out={"test_table_w_freshness": Out()})
def test_table_w_freshness():
    return ""

@op(out={"test_table_wo_freshness": Out()})
def test_table_wo_freshness():
    return ""

# Freshness policy correctly applies to this asset
asset_w_freshness_policy = AssetsDefinition.from_op(
    op_def=test_table_w_freshness,
    freshness_policies_by_output_name={
        "test_table_w_freshness": FreshnessPolicy(maximum_lag_minutes=60)
    },
)

# This asset doesn't have a freshness policy in dagit
asset_wo_freshness_policy = AssetsDefinition.from_op(
    op_def=test_table_wo_freshness,
    key_prefix=["test"],
    freshness_policies_by_output_name={
        "test_table_wo_freshness": FreshnessPolicy(maximum_lag_minutes=60)
    },
)
```

### CODE REVIEW

**Comment by clairelin135** [comment]
Hi @tghanken, thanks for reporting and pushing out a fix for this!

This looks great to me. Would you mind adding a test for this to ensure that this behavior is preserved? This file is probably a good place: https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

I think we just need to make sure that `assets_def.freshness_policies_by_key` fetches the freshness policy when the asset key contains a prefix.

**Comment by tghanken** [comment]
Of course!  Do you prefer that I add assertions to the existing `test_from_op_w_key_prefix()` and `test_from_graph_w_key_prefix()` tests, or add new test functions?

**Comment by clairelin135** [comment]
Adding additional assertions to `test_from_op_w_key_prefix` sounds great

**Review by clairelin135 — APPROVED** [review]
Looks great to me! Thanks for making this change

**Pull request merged**
