### PR TITLE
Add type hints for OpDefinition

### PR DESCRIPTION
**Pull request by zen-xu**
## Summary & Motivation
The `op` lack type hints

image

with this pr can fix it

image

### CODE REVIEW

**Comment by jamiedemaria** [comment]
@smackesey can you take a look at this?

**Comment by smackesey** [comment]
Hi @zen-xu, thanks for this contribution. I'm going to pull it down and tweak it to see if I can get it past our CI.

**Comment by smackesey** [comment]
I've now looked this over a bit and am remembering why we don't do this already. It's no fault of yours @zen-xu, as this is a good idea, but there is a quirk in Dagster's APIs that makes it untenable.

The problem is that an `OpDefinition` can be used for both direct invocation _and_ in a graph composition function:

```
@op
def foo(bar: int) -> int:
    return bar + 1

foo(3 + 2)  # `int` type hints make sense

@op
def bar() -> int:
    return 1

@graph
def foobar():
    foo(bar())  # `int` type hints don't work here
```

Basically the `OpDefinition` can be called in entirely different contexts that require entirely different arg types, and the solution in this PR only fits one of those contexts. I wish we could do this but I am going to close the PR.

**Comment by zen-xu** [comment]
I see, this is indeed something I had not thought of.

**Comment by zen-xu** [comment]
I found a [solution](https://github.com/zen-xu/dagster/commit/92b7cc9c3dfd1245b97f8b51e01def7a669616c7) to handle graph composition function.

image

**Pull request closed without merging**
