### PR TITLE
[asset diffs] special case ignore code reference diffs

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Code reference metadata values often incorporate ever-changing data, such as the git sha of a deployed image. This changes with every deploy, which can add a ton of noise to the list of changed assets in branch deployments or in the asset history dialog. We explicitly block that key to alleviate this problem.

This is a very narrowly tailored solution, but it might speak to a broader need for evaluating changes in metadata beyond equality, e.g. maybe we still want to highlight adding, removing, or changing the number of code references but ignore any internal changes to the references themselves.

## Test Plan

Unit test.

### CODE REVIEW

**Comment by benpankow** [comment]
* **#23271** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23271?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — COMMENTED** [review]
I don't love the bespoke-ness of this, but also don't have a better idea. Presumably, the factors that are leading code references to act like this could be present in other metadata that we don't control.

Before going forward with this, I think it's worth at least trying to imagine what a more general solution would be.

A meta-observation behind this PR is it sounds like our diffing algorithm is to some degree a matter of opinion. That makes me wonder if we should have asset diffs objects record some sort of version or other piece of metadata that encodes what opinions we had at the time we generated the diff? Or maybe it will already be clear from the Dagster version stored on the code location?

Sidenote is that this makes me think it would be valuable for our asset diffs to track which metadata keys have changed, instead of a single blanket "metadata changed".

**Comment by benpankow** [comment]
> I don't love the bespoke-ness of this, but also don't have a better idea. Presumably, the factors that are leading code references to act like this could be present in other metadata that we don't control.
> 
> Before going forward with this, I think it's worth at least trying to imagine what a more general solution would be.
> 
> A meta-observation behind this PR is it sounds like our diffing algorithm is to some degree a matter of opinion. That makes me wonder if we should have asset diffs objects record some sort of version or other piece of metadata that encodes what opinions we had at the time we generated the diff? Or maybe it will already be clear from the Dagster version stored on the code location?
> 
> Sidenote is that this makes me think it would be valuable for our asset diffs to track which metadata keys have changed, instead of a single blanket "metadata changed".

One option is to make this determination on the serverside, specific to the asset change tracking code, once we track more specific information about changes as in #23278

**Comment by sryza** [comment]
> One option is to make this determination on the serverside, specific to the asset change tracking code, once we track more specific information about changes as in https://github.com/dagster-io/dagster/pull/23278

I find this direction appealing, because it seems more flexible / easy to change.

**Pull request closed without merging**
