### PR TITLE
[docs-beta] Selection syntax reference

### PR DESCRIPTION
**Pull request by hellendag**
## Summary & Motivation

Add an "Asset syntax selection" document to `guides/tbd`. The content is very similar to https://docs.dagster.io/concepts/assets/asset-selection-syntax, with a few changes.

## How I Tested These Changes

Load doc at `/guides/tbd/selection-syntax`. Verify rendering.

## Changelog [New | Bug | Docs]

`NOCHANGELOG`

### CODE REVIEW

**Comment by hellendag** [comment]
* **#24063** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24063?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hellendag and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by erinkcochran87 — COMMENTED** [review]
@hellendag This looks great! I'm gonna make a few copy tweaks, but otherwise this is good to go. I'll stamp when I'm finished to give others time to comment.

**Review by erinkcochran87 — APPROVED** [review]

**Comment by hellendag** [comment]
Looks like the `sidebars` definition needs the dir name to be `guides/tbd`. Pushing up a fix.

**Review by cmpadden — APPROVED** [review]
Where has this been all my life!

**Pull request merged**
