### PR TITLE
Renamed the auto created job prefix from '__ASSET_GROUP' to '__ASSET_JOB'

### PR DESCRIPTION
**Pull request by shalabhc**
### Summary & Motivation

The old name is confusing because we now have asset groups and these jobs are not related to asset groups.

### How I Tested These Changes

Ran adjusted tests.

### CODE REVIEW

**Review by sryza — APPROVED** [review]
Lgtm. Did you try clicking around Dagit to make sure it still works?

**Review by bengotow — APPROVED** [review]
This looks good to me! I think those are all the front-end occurrences 👍

**Comment by shalabhc** [comment]
@sryza yes clicking around and materializing assets without jobs works, but I just noticed that the UI shows '__ASSET_JOB' in some places where it doesn't on main.

Eg new:
image

vs old:
image

So something is amiss. Looking into it.

**Comment by shalabhc** [comment]
> So something is amiss. Looking into it.

Running 'make rebuild_dagit' fixed it.

**Pull request merged**
