### PR TITLE
request based schedule

### PR DESCRIPTION
**Pull request by prha**
## Summary
We want to support `RunRequest`/`SkipReason` - based evaluation functions with the `@schedule` decorator. This diff enables that by using a wrapper function that evaluates the return value of the function and generates RunRequest objects accordingly.  We also change the signature of the `ScheduleDefinition` object to take in a helper class (`DecoratedScheduleFunction`) from the decorator, to better support direct invocation.

## Test Plan
BK

### CODE REVIEW

**Comment by gibsondan** [comment]
did we consider also having the existing @schedule decorator assume its an evaluation function if it's a generator? I think that would not be a breaking change? (But maybe too magical)

**Comment by prha** [comment]
Oh, that's interesting.  I did not consider it.

I think it is a little magical, but if we change all of our documentation to be oriented around evaluation changes, it would eventually become hidden magic.

**Comment by schrockn** [comment]
My bias would be for a little magic and to no add another public symbol to the API surface.

**Review by gibsondan — CHANGES_REQUESTED** [review]
i like hidden magic

**Review by sryza — COMMENTED** [review]
I think it would be useful to include a test with `yield`, and to verify the expected behavior for direct invocation with `yield` (should return a generator, right?).  Otherwise, looks good to me.

**Review by sryza — APPROVED** [review]
Looks great

**Pull request merged**
