### PR TITLE
add definition label to StepExecutionContext / SolidExecutionContext

### PR DESCRIPTION
**Pull request by prha**
## Summary
Adds a property to StepExecutionContext / SolidExecutionContext that enables error messages to appropriately reference the definition label (e.g. `op` | `solid`).

## Test Plan
None

### CODE REVIEW

**Review by dpeng817 — COMMENTED** [review]
Naming seems fine to me, deferring to @alangenfeld  on that.

Thoughts on, instead of using a property, using a method, so we can pass a bool or something to make it uppercase 😅

**Review by alangenfeld — COMMENTED** [review]
I feel like a `step_context.describe_op()` that printed "op {node_handle}" or "solid {node_handle)" would be worth it. I feel like printing the handle is an improvement in the places where we are not.

**Comment by alangenfeld** [comment]
theres also a concern around distinguishing between `op` and `solid` for our library code which may have a misalginment between the user facing api and whether it generates an op or a soild internally, so just printing "op/solid" may be the move

**Review by alangenfeld — CHANGES_REQUESTED** [review]
to your queue to consider the above

**Comment by prha** [comment]
It'll be easy to change to `op / solid`, but I don't understand what `may have a misalginment between the user facing api and whether it generates an op or a soild internally` means.

**Comment by alangenfeld** [comment]
the idea if we pursue an aggressive form of library migration, we may have something like
```
def make_library_solid(...):
   ...
  
make_library_op = make_library_solid
```
where the outer api doesn't necessarily align with whether its internally actually an op or solid

**Review by dpeng817 — CHANGES_REQUESTED** [review]
Per discussion, naming should probably be full-handle aware.

**Review by dpeng817 — APPROVED** [review]
Actually already full handle aware. LGTM

**Pull request merged**
