### PR TITLE
feat(sidebar): remove references to runs

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
Title says it all. Also, this goes more in line with how we display this information in the asset details page.

## How I Tested These Changes
eyes

### CODE REVIEW

**Comment by rexledesma** [comment]
* **#20699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20699?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rexledesma and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by bengotow — APPROVED** [review]
This looks good to me but @sryza may have thoughts -- I think he advocated for the current wording because it makes it explicit that "Latest" means "last run" and not "Today's partition" (which it may not be, if there was a backfill etc)

**Comment by rexledesma** [comment]
> This looks good to me but @sryza may have thoughts -- I think he advocated for the current wording because it makes it explicit that "Latest" means "last run" and not "Today's partition" (which it may not be, if there was a backfill etc)

Would we have the same problem with that in the asset details page? We also use "Latest materialization" there

**Comment by sryza** [comment]
This seems reasonable to me

**Comment by rexledesma** [comment]
### Merge activity

* **Mar 29, 7:01 AM PDT**: @rexledesma merged this pull request with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/20699).

**Pull request merged**
