### PR TITLE
add `MultiPartitionKey` to `OpExecutionContext.partition_key` return type hint

### PR DESCRIPTION
**Pull request by askvinni**
## Summary & Motivation
Noticed the type hint for `OpExecutionContext.partition_key` is set to only `str`, but it can also return a `MultiPartitionKey`.

### CODE REVIEW

**Comment by tacastillo** [comment]
I'm not actually sure who would own this module, so we're going to play some hot potato for it to find the right reviewer. I'm gonna throw it over to @clairelin135 for once she gets back from PTO tomorrow.

**Comment by clairelin135** [comment]
Hi @askvinni, thanks for filing. Makes a lot of sense to change the return type, but unfortunately I think this would constitute a breaking change as mypy will complain for any user who is relying on the return type to be a string.

I think in order to make this change we'd probably have to do it in the next major release. And ideally for full coverage we'd change the return types of all the partition key methods (context.partition_key_range, context.asset_partition_keys_for_output, etc).

**Comment by askvinni** [comment]
@clairelin135 gotcha, makes sense. Probably best to close the PR then?

**Comment by clairelin135** [comment]
Yep, I think so. Appreciate you contributing nonetheless, hopefully we can get this in in 1.4.0

**Pull request closed without merging**
