### PR TITLE
fix links on Concepts landing page

### PR DESCRIPTION
**Pull request by yuhan**
## Summary
fix https://github.com/dagster-io/dagster/issues/5462
we missed it in the migration is bc 1) the redirects don't work when the links are inside a custom mdx component 2) tests didn't capture links inside custom mdx components.

follow up is to improve the tests: https://github.com/dagster-io/dagster/issues/3540

## Test Plan

eye

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by sryza — APPROVED** [review]

**Comment by sryza** [comment]
Are we planning to set up redirects?

**Comment by yuhan** [comment]
@sryza the redirects have been set up but they don’t cover the internal links like this, i.e. the link is broken when someone clicks it on the page but it’ll get redirected when you go to docs.dagster.io/concepts/solids-pipelines/solids directly

**Comment by sryza** [comment]
@yuhan - got it, makes sense

**Comment by yuhan** [comment]
saw enough user reports today so i'm gonna backfill this particular content for yday's release

**Pull request merged**
