### PR TITLE
Add AssetCheckHandle to top level exports

### PR DESCRIPTION
**Pull request by johannkm**
We'll use this in selected_asset_checks on OpExecutionContext, and for the define_asset_job selection

### CODE REVIEW

**Comment by johannkm** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16600** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16600" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16600?utm_source=stack-comment).

**Comment by schrockn** [comment]
This is the first time we've introduce one of our internal "Handle" classes to top-level exports. Not sure we should.

Even though it seems worse, I think we might just want to return raw typed tuples here and document what each one means. The `AssetKey` type hint helps a lot with that.

**Comment by schrockn** [comment]
If it causes problems we can introduce AssetCheckHandle and it will be totally backwards compat since it is a tuple as well.

**Review by schrockn — CHANGES_REQUESTED** [review]
Asking q about whether we should publicly export this.

**Comment by johannkm** [comment]
We'll try with regular tuples

**Pull request closed without merging**
