### PR TITLE
Add RunsFilter to top level API

### PR DESCRIPTION
**Pull request by dpeng817**
https://github.com/dagster-io/dagster/issues/9545

### CODE REVIEW

**Comment by dpeng817** [comment]
Current dependencies on/for this PR:
* master
  * **PR #9549** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9549" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/9549?utm_source=stack-comment).

**Comment by sryza** [comment]
What's the motivation for this?

**Review by sryza — COMMENTED** [review]
This should go in api docs. Also, do we want to mark the `mode` param in some way that avoids us needing to support it in the future?

**Review by sryza — APPROVED** [review]
This looks great

**Pull request merged**
