### PR TITLE
[dagit] Use Array flat

### PR DESCRIPTION
**Pull request by hellendag**
### Summary & Motivation

Clean up some array flattening now that TS will allow it.

### How I Tested These Changes

Buildkite

### CODE REVIEW

**Comment by hellendag** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7754** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/7754" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/7754?utm_source=stack-comment).

**Comment by hellendag** [comment]
@OwenKephart I'm not sure where to go to test this within Dagit.

**Review by OwenKephart — APPROVED** [review]
nice very clean

**Comment by hellendag** [comment]
Tested event log for a run on a sample asset from @OwenKephart, output looked correct.

**Pull request merged**
