### PR TITLE
Add `node_info_to_auto_materialize_policy_fn` to `load_assets_from_dbt_*`

### PR DESCRIPTION
**Pull request by askvinni**
## Summary & Motivation
With the launch of `AutoMaterializePolicy`s, I had an immediate use case to implement them into my dbt assets. The proposed solution follows the same pattern as the `node_info_to_freshness_policy_fn`, where users can specify the auto materialization policy by default by adding it to the dbt model config under `dagster_auto_materialize_policy: {"type": "eager" | "lazy"}`.

## How I Tested These Changes
Added unit test and tested locally, run was successfully kicked off. Granted, I'm not sure this small test will be enough, but happy to add more if necessary.

### CODE REVIEW

**Comment by askvinni** [comment]
Just noticed the `AutoMaterializePolicy` argument in `AssetsDefinition` is marked as experimental. Let me know if I should add a similar flag here.

**Comment by OwenKephart** [comment]
hey @askvinni ! This looks great, thanks for putting this out :)

Just one small issue, this new argument needs to be added here: https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py?L321 as well (it's fine if it's just locked to the default function)

**Comment by askvinni** [comment]
@OwenKephart Thanks for catching! Though since `AssetsDefinitionCacheableData` doesn't take `AutoMaterializePolicy`s, I took the liberty to take this offline so we can discuss a possible extension to this functionality, otherwise dbt cloud users would be missing out. I'm happy to take that as well (maybe in a separate PR) since I'm already on it.

**Review by OwenKephart — APPROVED** [review]
thanks again for implementing this!

**Pull request merged**
