### PR TITLE
[docs] - Fix IS_BRANCH_DEPLOYMENT docs examples

### PR DESCRIPTION
**Pull request by gibsondan**
Summary:
This variable is set to "1" or "0" and sadly if("0") is True :( Here's one way we could recommend people check it correctly. We'll have to update the example serverless repo too.

Test Plan: View docs pages

### CODE REVIEW

**Comment by gibsondan** [comment]
Will also want to land https://github.com/dagster-io/dagster/pull/9730

**Review by erinkcochran87 — COMMENTED** [review]
@gibsondan Could you take a look at these guys to see if they also need to be updated?

- [Testing against production using branch deployments guide](https://docs.dagster.io/guides/dagster/branch_deployments#step-2-configure-our-job-for-each-environment)
- [Cloud environment variables reference](https://docs.dagster.io/dagster-cloud/developing-testing/environment-variables#all-deployment-variables)

**Comment by gibsondan** [comment]
@erinkcochran87 believe I got everywhere the offending env var is mentioned

**Review by erinkcochran87 — APPROVED** [review]
:shipit:

**Pull request merged**
