### PR TITLE
Putting is_str into dagster.utils #2779

### LINKED ISSUE #2779: check.is_str is problematic
The issue here is that every other check method throws on failure, and `is_str` returns true or false. Note the different in behavior between `is_str` and `is_list`. 

I believe the the best fix would be to move `is_str` to dagster.utils, where the is prefix can more credibly mean returns True or False.

### PR DESCRIPTION
**Pull request by monicayao**
Hi all, just checkout out the repository and wanted to do a first time contributor issue, closes #2779. Hope I didn't misinterpret what the issue was asking for. 

In this PR: 
- Puts `is_str` logic into `dagster.utils` near `is_enum_value(value)`
- Importing all `is_str` for all required files from `dagster.utils`

Notes: I ran `make black` and `make pylint` but the pylint gave me lots of output that I overlooked, but I made sure it did not involve `is_str`

### CODE REVIEW

**Comment by natekupp** [comment]
thanks for contributing this! Adding @mgasner to take a look

**Comment by alangenfeld** [comment]
looks like its a circular dependency issue in python 2.7

`pytest python_modules/dagster/dagster_tests/core_tests/`

is how to run the core tests

**Comment by monicayao** [comment]
> looks like its a circular dependency issue in python 2.7
> 
> `pytest python_modules/dagster/dagster_tests/core_tests/`
> 
> is how to run the core tests

@alangenfeld oh I see. I'll pay more attention to the Azure pipeline! Which 2.7 version should I use? There's 2.7.0 to 2.7.18.

**Comment by alangenfeld** [comment]
`2.7.18`

**Comment by monicayao** [comment]
Sorry for getting back to this late. The circular reference is at the `__init__.py` files for `dagster.check` and `dagster.utils`. A couple of fixes I can think of: 

1. For the 5 functions in `dagster.check`, import `is_str` inside the function
2. For the 5 functions in `dagster.check`, change `is_str(obj)` to just `isinstance(obj, string_types)`, which is consistent with the other functions in the file.
3. Keep the `is_str` inside `dagster.check`

**Comment by alangenfeld** [comment]
option 1 seems fine, there are plenty of other inline `from dagster.utils import` in `check`

**Comment by schrockn** [comment]
I would prefer to have duplicated code that a reverse reference from dagster.check to dagster.utils. We could also add dagster.check.utils.

**Comment by monicayao** [comment]
> I would prefer to have duplicated code that a reverse reference from dagster.check to dagster.utils. We could also add dagster.check.utils.

I made a new file that is dagster.check.utils!

**Comment by mgasner** [comment]
Hi @monicayao I think we have some merge conflicts / test failures -- can we resolve those to push this forward?

**Comment by monicayao** [comment]
> Hi @monicayao I think we have some merge conflicts / test failures -- can we resolve those to push this forward?

Of course, it's just import differences I think 👍

**Comment by mgasner** [comment]
we have a few lint issues:

```
>>> Lint for python_modules/dagster/dagster/check/__init__.py:

               3 
               4 from future.utils import raise_with_traceback
               5 from six import integer_types, string_types
    >>> +        
               6 from .utils import is_str
               7 
               8 if sys.version_info[0] >= 3:
               9     type_types = type
```

```
>>> Lint for python_modules/dagster/dagster/cli/pipeline.py:

              48 from dagster.utils import (
              49     DEFAULT_WORKSPACE_YAML_FILENAME,
              50     delay_interrupts,
    >>> -     51     load_yaml_from_glob_list,
        -     52     merge_dicts,
        -     53     is_str,
        +            is_str,
        +            load_yaml_from_glob_list,
        +            merge_dicts,
              54 )
              55 from dagster.utils.error import serializable_error_info_from_exc_info
              56 from dagster.utils.hosted_user_process import recon_pipeline_from_origin
              57 from dagster.utils.indenting_printer import IndentingPrinter
```

**Comment by mgasner** [comment]
running buildkite tests: https://dagster.phacility.com/D4722

**Comment by mgasner** [comment]
sorry, looks like we have a few more cosmetic issues. can you run `make black` and `make isort` from the root of the repo

**Comment by monicayao** [comment]
> sorry, looks like we have a few more cosmetic issues. can you run `make black` and `make isort` from the root of the repo

oops, apologies. I ran it through the linter before I made my initial PR and I didn't know that some styles have changed since then.

**Comment by monicayao** [comment]
@mgasner looks like 37 core tests are failing. I ran the core tests on my local machine with python 3.7 and it's passing

**Comment by mgasner** [comment]
Yep, these are windows tests which may be failing for unrelated reasons. I'm going to go ahead and merge and we will resolve afterwards if the failures continue. Thank you so much! 🙏

**Pull request merged**
