### PR TITLE
3.5/n example overhaul: modern_data_stack_assets to recommended project layout + rename

### PR DESCRIPTION
**Pull request by yuhan**
### Summary & Motivation
- renamed it to starting with `assets_*` (plan to rename all assets related to `assets_*` so they could show up nicely in the examples folder - in alphabetical order): modern_data_stack_assets -> assets_modern_data_stack
  * image

- converted the new folder structure (scaffolded this example with `dagster project scaffold` and ported the contents over)
  * `assets/` dir now has: `assets/airbyte`, `assets/dbt`, `assets/forecasting` - so it's more clear what assets are there just by looking at the folder structure.
  * removed extra layer: resources.py -> shoved `resource_defs` in repository.py
  * added a test to test repo can load. there was no test in modern_data_stack_assets. i still need to write more tests to cover assets.
- updated [README](https://github.com/dagster-io/dagster/tree/yuhan/07-31-example_overhaul_modern_data_stack_assets_to_recommended_project_layout_rename/examples/assets_modern_data_stack) to include desc and dagster project from-example cmd

see full overhaul plan in [this spreadsheet](https://elementl.quip.com/bPbFArMkloDp/Dagster-Example-Overhaul#temp:C:CZV1c9ece717ec2477aaf338ba54)
and more diffs coming in stack later

### How I Tested These Changes
- tox
- `dagster project from-example --name my-dagster-project --example assets_modern_data_stack_assets`
- dagit loads:
Screen Shot 2022-07-31 at 3 08 15 AM

### CODE REVIEW

**Comment by yuhan** [comment]
Current dependencies on/for this PR:
* master
  * **PR #9071** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9071" target="_blank">Graphite</a> 
    * **PR #9116** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9116" target="_blank">Graphite</a> 
      * **PR #9117** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9117" target="_blank">Graphite</a> 
        * **PR #9120** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9120" target="_blank">Graphite</a> 
          * **PR #9121** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9121" target="_blank">Graphite</a> 
            * **PR #9122** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9122" target="_blank">Graphite</a> 
              * **PR #9123** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9123" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/9123?utm_source=stack-comment).

**Comment by sryza** [comment]
It looks like this includes changes from some other PRs

**Comment by yuhan** [comment]
yea i accidentally merged https://github.com/dagster-io/dagster/pull/9149 and https://github.com/dagster-io/dagster/pull/9151 into this branch.

**Comment by yuhan** [comment]
@sryza sorry for the thrash - it should be now ready for review.

i plan to clean up the requirements.txt all at once in a final pr

**Review by sryza — COMMENTED** [review]
Should we rename "mds_dbt" to "dbt_project" for consistency with other examples like hacker_news?

Also, I don't feel strongly about this, but I think it can be helpful to have all the assets in one file for this example, as a way to show people in a single code snippet how they can combine MDS tools.

E.g. I used it as the basis for the code in the "dbt-native orchestration" tab on the dagster.io landing page: https://dagster-website-git-bg2022-site-refresh-elementl.vercel.app/.

**Comment by yuhan** [comment]
My original thinking was separating MDS assets into individual files will help clearly communicate "dagster orchestrates various MDS". But I think your point of showing how to combine MDS tools in single code snippet is great and keeping it consistent with the io is better too. updating.

**Review by sryza — APPROVED** [review]
Awesome

**Pull request merged**
