### PR TITLE
[3/n][resources ui] Serialize parent resource information in resource snapshots, surface via GQL

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Exposes nested resources' parent information in the repo serialization bundle, used so that we can backlink to parent resources in the UI in the stacked commit.

## Test Plan

Added unit tests.

### CODE REVIEW

**Comment by benpankow** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12728** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12728" target="_blank">Graphite</a> 
    * **PR #12729** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12729" target="_blank">Graphite</a> 
      * **PR #12832** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12832" target="_blank">Graphite</a>  👈
        * **PR #12833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12833" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12832?utm_source=stack-comment).

**Review by dpeng817 — APPROVED** [review]

**Comment by benpankow** [comment]
@benpankow queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12832).

**Comment by benpankow** [comment]
[Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12832) couldn't merge this pull request because a downstack PR #12729 failed to merge.

**Comment by benpankow** [comment]
@benpankow queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12832).

**Comment by benpankow** [comment]
[Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12832) rebased this pull request as part of a merge.

**Pull request merged**
