### PR TITLE
RFC: Create core development environment

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Note: This is not working and not for commit as of yet. But this is enough to be a discussion.

This PR proposes the creation of a "core" development environment to replace the "master" (we also call it dev) development environment that has much fewer dependencies, and that it should be our default environment for development.

We currently develop locally on the "master" environment, which includes as many of our integration modules as possible. We adopted this strategy prior to development of `uv`, which has changed the tradeoffs here. It was so expensive and fragile to create virtual environments, and the notion of having to regenerate them frequently was unacceptable.

Developing against the maximal superset of integrations has a lot of downsides. We are subject to _all_ the dependency constraints imposed by those integrations of all _their_ dependencies. I ran into this while trying to get typehinting to work with `pendulum` code and it was pinned to `2.12` because of a constraint caused by airflow, which is included by `dagster-airflow`. I was very confused why we were not using pendulum 3.

I believe this has real cost, as we are developing against dependencies that our users are _unlikely_ to encounter, since no one in practice installs this many of our integrations.  For example we are pinned to an old version of dbt in master.

I think we should maintain an additional environment, `core`, that is used in the common case where we are modifying `dagster` or `dagster-webserver`.  We can also include common integrations like `dagster-dbt`.

`core` is much lighter than `dev`. It has 197 installed modules rather than 616. Recreating core from scratch is takes around 3 seconds. 

## How I Tested These Changes

`>time make install_core_python_modules_verbose`

```make install_core_python_modules_verbose  3.63s user 1.83s system 261% cpu 2.085 total```

### CODE REVIEW

**Comment by schrockn** [comment]
* **#20931** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20931?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
@smackesey I think you would have to take this over to do it "properly"

**Comment by sryza** [comment]
Very in favor of this change

**Comment by schrockn** [comment]
@smackesey friendly ping here. Definitely your domain here but I think this would be nice

**Pull request closed without merging**
