### PR TITLE
add managing concurrency to sidebar

### PR DESCRIPTION
**Pull request by cnolanminich**
## Summary & Motivation

I forgot to add managing concurrency to the sidebar. In the old docs this was in an "Advanced" section. I think it might make sense under "Build/Configure", but am open to moving it to a different or even a new section!

### CODE REVIEW

**Review by cmpadden — APPROVED** [review]
The location makes sense to me. Thanks @cnolanminich !

**Comment by cnolanminich** [comment]
getting this error in the deploy docs revamp step: 

>/home/runner/work/dagster/dagster/docs/docs-beta/docs/dagster-plus/deployment/serverless.md
  13:31  error  Parsing error: Could not parse expression with acorn
> /home/runner/work/dagster/dagster/docs/docs-beta/docs/dagster-plus/deployment/serverless/security.md
  [37](https://github.com/dagster-io/dagster/actions/runs/11581899923/job/32243686131?pr=25621#step:6:42):46  error  Parsing error: Could not parse expression with acorn

Those are from a different PR that was merged -- any ideas on how to resolve?

**Comment by cmpadden** [comment]
> getting this error in the deploy docs revamp step:
> 
> > /home/runner/work/dagster/dagster/docs/docs-beta/docs/dagster-plus/deployment/serverless.md
> > 13:31  error  Parsing error: Could not parse expression with acorn
> > /home/runner/work/dagster/dagster/docs/docs-beta/docs/dagster-plus/deployment/serverless/security.md
> > [37](https://github.com/dagster-io/dagster/actions/runs/11581899923/job/32243686131?pr=25621#step:6:42):46  error  Parsing error: Could not parse expression with acorn
> 
> Those are from a different PR that was merged -- any ideas on how to resolve?

Yeah, I believe those appear to be unrelated. Working on a fix here:

https://github.com/dagster-io/dagster/pull/25622

**Comment by cmpadden** [comment]
@cnolanminich if you rebase off master, the deploy issue should be fixed.

**Pull request merged**
