### PR TITLE
add deprecated message to managed elements docs

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Updates our docs to indicate that managed Airbyte will be deprecated w/ 2.0

### CODE REVIEW

**Comment by benpankow** [comment]
Current dependencies on/for this PR:
* master
  * **PR #18005** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18005?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #18006** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18006?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/18006?utm_source=stack-comment).

**Review by schrockn — CHANGES_REQUESTED** [review]
This is deprecated now and will be deleted in 2.0

**Review by schrockn — DISMISSED** [review]
rerequest when merge conflict fixed

**Comment by sryza** [comment]
> With experimental features I think we should allow ourselves to delete before major revisions (especially since 2.0 is not scheduled right now).

I fully agree

**Review by schrockn — APPROVED** [review]

**Pull request merged**
