### PR TITLE
[backcompat-tests] Remove tests against older webserver than code server

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

Removes backcompat tests that use an older webserver version that code server version. We explicitly state that we do not support this in our docs.

## How I Tested These Changes

Modified backcompat test suite.

## Changelog

NOCHANGELOG

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

### CODE REVIEW

**Comment by smackesey** [comment]
* **#24576** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24576?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @smackesey and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by smackesey** [comment]
* **#24576** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24576?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @smackesey and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by smackesey** [comment]
* **#24576** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24576?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @smackesey and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by smackesey** [comment]
* **#24578** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24578?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24576** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24576?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @smackesey and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by smackesey** [comment]
* **#24578** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24578?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24576** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24576?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @smackesey and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alangenfeld — APPROVED** [review]

**Pull request merged**
