### PR TITLE
Exploration of complete separation of metadata and compute: observable assets

### PR DESCRIPTION
**Pull request by schrockn**

### CODE REVIEW

**Comment by schrockn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16424** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16424" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16424?utm_source=stack-comment).

**Comment by Ramshackle-Jamathon** [comment]
Nice, I'm still optimistic about this. Most of the questions I have about the ergonomics kinda boil down to the question of wether the Asset Graph is strictly derived from the python definitions or if its derived from some DB state + the python definitions.
1. How are changes in the external assets reconciled with dagster?
2. Do I need to create an asset definition in python for each ExternalAsset? Maybe require the python definition if you want to mark them as the upstream for dagster-native Assets?
3. Many of the External systems might be dynamically generating new Assets, will those be automatically picked up? is there a way to detect and promote those into dagster Assets?

**Comment by petehunt** [comment]
Seems really cool. A few thoughts:

* Would be great if the UI had a copy-pastable `curl` command (that included a one-off auth token) to be able to update this metadata.
* I think you should be able to "pull" metadata via a sensor in addition to the push method you have here.
* Would these eventually replace source assets / observable source assets? Seems like it to me, and I would love for the number of nouns in the system to stay stable or trend downward over time.
* Do you envision codegen tools to import these definitions from external systems eventually?

**Comment by slopp** [comment]
```python
def report_asset_materialization(asset_key: str, metadata: dict):
    instance = DagsterInstance.get()
    dagster_event = DagsterEvent.from_external(
        event_type=DagsterEventType.ASSET_MATERIALIZATION,
        event_specific_data=StepMaterializationData(
            AssetMaterialization(asset_key=asset_key, metadata=metadata)
        )
    )
    instance.report_dagster_event(dagster_event, run_id="dummy")
```

This is almost exactly what some larger Dagster Cloud customers have done on their own. One such iuser created a job that looped through a bunch of asset partitions emitting materializations in order to represent an external backfill in Dagster. So a few questions:

1. Will we support partitions and partition ranges?
2. What is the performance implications? eg  a big challenge this particular user faced was enumerating thousands of the events. Because each materialization event happens through a Python log handler, the performance became a major blocker. We'd want an option that could emit events for years worth of hourly partitions in, ideally, seconds or minutes (not hours as is the naive approach today).

**Comment by schrockn** [comment]
> Will we support partitions and partition ranges?

For sure

> What is the performance implications? 

I mean it does a db insert and a log per event. Is the problem for sure in the Python log handler? Either way it would be straightforward to provide a bulk insertion capability for backfills.

**Comment by schrockn** [comment]
> Seems really cool. A few thoughts:
> 
> * Would be great if the UI had a copy-pastable `curl` command (that included a one-off auth token) to be able to update this metadata.

Agreed. Great idea.

> * I think you should be able to "pull" metadata via a sensor in addition to the push method you have here.

That should not be a problem. I'll add an example.

> * Would these eventually replace source assets / observable source assets? Seems like it to me, and I would love for the number of nouns in the system to stay stable or trend downward over time.

Yes this should be straightforward. The only capability that this does not replicate is ad hoc observation from the UI. However I've wanted to consolidate the "observe sources" and "materialize" buttons for some time, so this would be a good excuse to address sure.

> * Do you envision codegen tools to import these definitions from external systems eventually?

For sure. `AssetSpec` is designed to make it easier to be a target for codegen as well as hydrate from other serializable formats (e.g. yaml).

**Review by schrockn — COMMENTED** [review]
I moved this to an internal discussion (6739)

**Pull request closed without merging**
