### PR TITLE
17389 schema metadata

### PR DESCRIPTION
**Pull request by jrstats**
## Summary & Motivation

#17389

## How I Tested These Changes

Added additional assertions to `test_asset_schema_defaults` successful

``` bash
pytest -s python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py -k test_asset_schema_defaults
```

### CODE REVIEW

**Comment by clairelin135** [comment]
@jamiedemaria noticed you commented on the original issue, are you able to review this PR?

**Review by jamiedemaria — COMMENTED** [review]
This looks good to me. I'll make sure CI passes before approving though.

One kind of annoying thing is that BigQuery doesn't use the terminology "schema" instead they have "dataset".  I need to think on this for a minute and see if there's a way to allow for the BQ terminology 

@sryza  I'm also interested in your take on this change since you wrote the og DBIOManager. is there a reason you didn't include setting the schema via metadata that we should be considering here?

**Comment by sryza** [comment]
>  is there a reason you didn't include setting the schema via metadata that we should be considering here?

nope!

**Comment by jrstats** [comment]
@jamiedemaria , I had a thought that I also needed to update the docstring to explain the changes. Have added a commit for that now.

**Review by jamiedemaria — APPROVED** [review]
looking good! once CI passes I'll merge it in

**Comment by jrstats** [comment]
Thanks @jamiedemaria . It seems the CI has failed one test, which is strange as all passed on the first commit, and I have only updated the docs since :thinking:. It looks like the issue is with the `storage.get_event_tags_for_asset` method for `MySQLEventLogStorage` which I haven't touched. Is this a test that has failed anywhere else?

**Comment by jrstats** [comment]
Have rebased from `dagster-io:master`. Hopefully it passes this time :)

**Comment by jamiedemaria** [comment]
hey @jrstats  could you bring in updates from master one more time?  it looks like the fix to the CI pipeline got merged in just after your latest merge

**Comment by jrstats** [comment]
Have pushed again @jamiedemaria :)

**Comment by jamiedemaria** [comment]
cool, thank you for your patience!

**Comment by jrstats** [comment]
No problem at all - looks like it's all done now!

**Pull request merged**
