### PR TITLE
dagster_model_with_new on AssetSpec

### PR DESCRIPTION
**Pull request by sryza**

### CODE REVIEW

**Comment by sryza** [comment]
@alangenfeld I'm running into this issue with checks and generics:

```
python_modules/dagster/dagster/_core/definitions/asset_graph.py:203: in normalize_assets
    AssetSpec(key=key, metadata={SYSTEM_METADATA_KEY_AUTO_CREATED_STUB_ASSET: True})
python_modules/dagster/dagster/_core/decorator_utils.py:203: in wrapped_with_pre_call_fn
    return fn(*args, **kwargs)
python_modules/dagster/dagster/_core/decorator_utils.py:203: in wrapped_with_pre_call_fn
    return fn(*args, **kwargs)
python_modules/dagster/dagster/_core/definitions/asset_spec.py:123: in __new__
    return super().__new__(
python_modules/dagster/dagster/_model/__init__.py:104: in __checked_new__
    fn(kwargs[key])
python_modules/dagster/dagster/_check/__init__.py:638: in inst_param
    if not isinstance(obj, ttype):
../.pyenv/versions/3.10.4/lib/python3.10/typing.py:994: in __instancecheck__
    return self.__subclasscheck__(type(obj))
../.pyenv/versions/3.10.4/lib/python3.10/typing.py:997: in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
E   TypeError: Subscripted generics cannot be used with class and instance checks
```

**Comment by alangenfeld** [comment]
Oh ya the auto check stuff is not very fleshed out in my first draft so no surprise it broke. 

Thanks for trying this out to push on it!

I will let you know when i update https://github.com/dagster-io/dagster/pull/22043 to a more usable state

**Comment by alangenfeld** [comment]
ok give this a rebase, the check stuff at minimum is fixed up

**Comment by alangenfeld** [comment]
I spoke too soon, missed the annotation thing

**Comment by sryza** [comment]
Ah no worries. Just rebased and pushed. Let me know when you want me to do the next round.

**Comment by alangenfeld** [comment]
ok `PublicAttr` handling added and under test , fire at will

**Comment by sryza** [comment]
Sweet, just re-rebased

**Comment by alangenfeld** [comment]
choking on `Iterable["AssetDep"]` since at runtime thats just a string and not a real type yet. Hmmmmm

**Comment by sryza** [comment]
> choking on Iterable["AssetDep"] since at runtime thats just a string and not a real type yet. Hmmmmm

I think we could just ban this. Pydantic doesn't support this either. It feels generally healthy to remove these circular imports anyway.

**Comment by sryza** [comment]
I.e. when I converted some stuff to pydantic I moved stuff around to avoid circular imports and it felt good.

**Comment by alangenfeld** [comment]
Makes sense. Looks like they special the string for the class currently being defined which we could do. Might be able to handle `ForwardRef` as well. 

Alright well if you shuffle stuff around in this PR maybe things will work after thats resolved

**Comment by sryza** [comment]
👍 did the shuffle

**Comment by alangenfeld** [comment]
main thing from pyright `_replace`

**Comment by alangenfeld** [comment]
so i see
* some circular import issues - i assume so more shuffle follow up
* pyright yelling about `_replace` and `_asdict` call sites. Can add some class to inherit `Legacy` / `Migrating` / `NTMethods` that supports those & lets the type checker know about em if we think that cutting over shouldn't require updating those call sites

**Review by alangenfeld — CHANGES_REQUESTED** [review]
this is a bit out of date, back to you to re-spin or close

**Pull request closed without merging**
