### PR TITLE
[ui] Filter hidden definitions tags

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

For run tags, we identify three tag types:
- User-defined tags, which users can attach to their jobs and which flow through to runs of those jobs
- System tags, which Dagster attaches to runs, signaled by the `dagster/` prefix
- Hidden tags, which do not appear in the UI, signaled by the `.dagster/` prefix

For asset definition tags, we already use the `dagster/` prefix as a form of "namespacing", but no asset definition tags match the run-tag notion of "system tags."
Still, it would be useful to have a set of asset definition tags we hide from the UI entirely for things like the kind system.

This PR introduces the `.dagster/` prefix as a hidden tag indicator for the definition tag system. These tags are filtered out on the frontend from display.

## Test Plan

Tested locally

### CODE REVIEW

**Comment by benpankow** [comment]
* **#23771** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23771?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — COMMENTED** [review]
How does this compare so the system tags that happen on materializations? Right now we hide those from the UI by default, for example. I think the treatment should uniform between tags here and tags there.

**Comment by benpankow** [comment]
> How does this compare so the system tags that happen on materializations? Right now we hide those from the UI by default, for example. I think the treatment should uniform between tags here and tags there.

Are you talking about this toggle?
Screenshot 2024-08-20 at 2 31 42 PM

As far as I can tell that's all handled on the frontend - the backend doesn't handle system tags differently with the sole exception that we don't validate them:
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/events.py#L763

**Comment by schrockn** [comment]
Why don't we just do the same here for now?

**Comment by benpankow** [comment]
At second blush I'm not convinced there's a reason to thread this through tags - see https://github.com/dagster-io/dagster/pull/23778

**Comment by schrockn** [comment]
I'm still not convinced we need this.

**Review by schrockn — CHANGES_REQUESTED** [review]
queue mgmt. I'm still not sold on supporting hidden tags like this. We should discuss.

**Pull request closed without merging**
