### PR TITLE
interpret solid selection as op selection for querying runs.

### PR DESCRIPTION
**Pull request by dpeng817**
Until https://github.com/dagster-io/dagster/pull/9280 lands, we have been writing selection tags as `solid_selection` instead of `op_selection`. We want to be able to filter runs s.t. when searching for the op_selection tag, historic runs which still stored using the solid_selection tag, show up.

In order to test this; I created some fresh runs on current-master in my local dagster installation using selection; which persisted those runs with the `solid_selection` tag clearly visible. I then rebased Dish's change from https://github.com/dagster-io/dagster/pull/9280 on top of this PR, and re-launched another run, which launched with the `op_selection` tag. Searching by the op_selection tag surfaces the runs with a matching solid selection:
Screen Shot 2022-08-10 at 10 41 25 AM

Searching by solid_selection only surfaces items with the solid_selection tag, which I think is fine.

Requires a companion PR for dagster-cloud; https://github.com/dagster-io/internal/pull/3317

### CODE REVIEW

**Review by prha — COMMENTED** [review]
Have we considered other options, like doing a data migration over the solid selection run tags?  Or having the op selection tag permanently be represented in the DB as solid selection and transforming in the storage layer?

**Comment by dpeng817** [comment]
@prha I assumed we wouldn't be comfortable with inducing a data migration, but I guess since the functionality is pretty niche, it's probably OK? How would we surface that a migration is necessary you think?

**Comment by prha** [comment]
We have data migrations which will run when users run `dagster instance migrate`.  We can just put something in the release notes saying that if they see something odd when they search for runs with op selections (e.g. missing runs), they can run `dagster instance migrate`.

The functionality degrades nicely, in that if they do nothing, maybe some run views look wrong, but it'll only be old runs (new runs should have the proper tags).

**Comment by dpeng817** [comment]
Right - was just wondering if we'd want to do anything more in terms of telling users "hey you have runs whose tags might need to be migrated - or something but that makes sense to me.

**Review by dpeng817 — COMMENTED** [review]
Closed in favor of https://app.graphite.dev/github/pr/dagster-io/dagster/9284

**Pull request closed without merging**
