### PR TITLE
remove references to op jobs from schedule docs

### PR DESCRIPTION
**Pull request by sryza**

### CODE REVIEW

**Comment by erinkcochran87** [comment]
I just wrapped up an overhaul of the schedule docs, which included putting op jobs into its own dedicated guide and making assets more front-and-center. I'm not sure we need this PR at this point - how about we revisit after I make things public, which will be by the next release?

**Comment by sryza** [comment]
Gotcha - sounds good

**Review by PedramNavid — CHANGES_REQUESTED** [review]
I think we can close this one right?

**Comment by sryza** [comment]
Yessir

**Pull request closed without merging**
