### PR TITLE
Feature/databricks oauth

### LINKED ISSUE #16126: Enable oauth authentication flow for Databricks jobs launched with dagster-databricks
### What's the use case?

Databricks now has the ability to delegate permissions to a [service principal](https://docs.databricks.com/en/dev-tools/service-principals.html) for interacting with their REST APIs in an automated / programmatic fashion. When using a service principal it is possible to authenticate using an oauth client ID and secret. The `databricks-sdk` supports authentication with oauth credentials, and will automatically refresh the temporary token retrieved using the client ID and secret. 

The security and auditing benefits of using a service principal with temporary credentials via oauth are obvious, and in order to support secure best practices we should expose this as an optional way to authenticate with Databricks.

### Ideas of implementation

Oauth client ID and secret could be exposed at the same configuration level that exposes the API token configuration. A runtime check would ensure either the API token, or both oauth client ID and secret were provided by the user.

### Additional information

One blocker to implementing this is that the `DatabricksClient` class still maintains (deprecated) support for the `databricks-api` and databricks-cli` clients, which only take an API token. If the oauth configuration was exposed and used on the step launcher, the clients implemented from `databricks-api` and `databricks-cli` would not be able to be initialized, leaving public attributes of the step launcher in an unexpected state.

One solution would be to throw an exception if a user tries to access the `_api_client` or `_client` properties when the `DatabricksClient` has been initialized with oauth creds. This would maintain backwards compatibility for now for users still using tokens who may have a dependency on those attributes. Although in general I'd expect the number of users who might have a dependency on that in the first place to be pretty small.

If that feels too messy it could also just wait until the next minor release if the plan is to drop the `databricks-api` and `databricks-cli` clients. I'm happy to put in a PR for this, just let me know if the error-throwing solution is reasonable for now or if y'all would rather wait until the next minor release and implement it clean.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by zyd14**
## Summary & Motivation
Fixes #16126 about enabling oauth authentication for Databricks service principals
## How I Tested These Changes
Unit tests + manually tested that Databricks steps can be launched via the step launcher using either a personal access token or oauth client ID + client secret. 

During this manual testing I also uncovered a few bugs around the `submit()` call to the `databricks-sdk` which were preventing jobs from being launched (databricks-sdk requires a [task_key parameter](https://github.com/dagster-io/dagster/commit/7d2466c4490acaa017e3c1002f258cd0a5edb708), and reading a file that doesn't exist now raises a [DatabricksError](https://github.com/dagster-io/dagster/commit/fd91538bddea0821b1b8a94e94b709e2e8f8790b)). Currently the step launcher is broken as-is and will not work without these changes, so if this whole PR doesn't get merged before the next release then those two commits should probably at least get cherry-picked into a different PR and merged in. I should also note that it appears that the most recent release 0.20.10 works, and that the breaking changes must have been made since the last release.

### CODE REVIEW

**Comment by sryza** [comment]
@rexledesma are you able to take a look at this one?

**Comment by rexledesma** [comment]
> @rexledesma are you able to take a look at this one?

@smackesey Could you take a look? Some bugs were uncovered that look like fallout from https://github.com/dagster-io/dagster/pull/14673

**Comment by zyd14** [comment]
@smackesey / @rexledesma - just tested the latest dagster / dagster-databricks release and it did in fact break the step launcher. Attempting to run a job with the step launcher configured gives this error:
```
databricks.sdk.core.DatabricksError: Task requires key (`task_key`).
  File "/Users/zach/Documents/empirico/projects/etxlib/.venvs/dagster-test-env/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_plan.py", line 273, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/zach/Documents/empirico/projects/etxlib/.venvs/dagster-test-env/lib/python3.9/site-packages/dagster_databricks/databricks_pyspark_step_launcher.py", line 257, in launch_step
    databricks_run_id = self.databricks_runner.submit_run(self.run_config, task)
  File "/Users/zach/Documents/empirico/projects/etxlib/.venvs/dagster-test-env/lib/python3.9/site-packages/dagster_databricks/databricks.py", line 371, in submit_run
    return self.client.workspace_client.jobs.submit(
  File "/Users/zach/Documents/empirico/projects/etxlib/.venvs/dagster-test-env/lib/python3.9/site-packages/databricks/sdk/service/jobs.py", line 3575, in submit
    op_response = self._api.do('POST', '/api/2.1/jobs/runs/submit', body=body)
  File "/Users/zach/Documents/empirico/projects/etxlib/.venvs/dagster-test-env/lib/python3.9/site-packages/databricks/sdk/core.py", line 1003, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
```
Would you like me to cherry-pick my fixes into another PR?

**Comment by zyd14** [comment]
@smackesey  Ah okay, honestly I'm not as familiar with rebase strategies. I thought I clicked through rebasing from master in my IDE but must've messed something up along the way. If you don't mind taking over that's totally fine with me.

**Review by smackesey — APPROVED** [review]

**Pull request merged**
