### PR TITLE
ExecutionPlan serialization engine

### PR DESCRIPTION
**Pull request by schrockn**
Adds a serialization engine for execution plans.

Execution plans as currently designed are difficult to serialize. The contain references to lambdas, Solid instances, DagsterType instances and other such objects that are difficult to serialize. Even if one *could* serialize them with pickle or dill, the process breaks invariants that are assumed through the system (e.g. that there is only a single type instance per type name in the whole system). I also do not trust serializing and deserializing code in this manner.

This PR separates execution plans into two separate families of classes. One are "Meta" classes, that are just "values" in the Rich Hickey sense of the word. They only contain serializable scalars, lists, dicts, or other "values" themselves. This is the structure that can be reliably serialized to and from disk.

However we still need to hook up the execution plan to code that gets executed. This is what the non "Meta" classes do.

This all comes to together in the recreation step. In that step you give the recreation function a PipelineDefinition, an environment, and an execution plan meta (that could have come from disk) and it will reconstruct a fully executable execution plan. If you look through recreate.py you'll note that it looks up solid instances, dagster types instances, and recreate creates the necessary compute_fn lambdas to stitch together an executable plan.

This diff relies heavily on the library https://github.com/tobgu/pyrsistent to do it's work. There's a lot to like about this library but this is quite the dependency to take so it is worthy of discussion.

### CODE REVIEW

**Comment by schrockn** [comment]
We should be able to replace all instances of the "namedtuple" base class shenanigans in the codebase with PClass's if we take this dependency

**Comment by schrockn** [comment]
Upon reflection. This subsystem may be largely unnecessary, actual. Given 1) an environment config 2) a pipeline and 3) a set of execution node keys you can reconstruct a fully functional execution plan.

**Comment by mgasner** [comment]
I don't fully understand what problem this is solving. I take your point that our system assumes various invariants wrt type instances, but in general I think we want to serialize/deserialize execution plans and other internal constructs (as opposed to intermediate outputs) not within a single Python process but in order to ship code to faraway compute. The hard part of this serialization problem isn't the reliably serializable stuff that gets packaged up here in the Meta classes, but the external dependencies that get brought in when we create a PipelineDefinition. 

My sense is that the work here is largely separable in principle from the question whether to adopt pyrsistent more broadly throughout the codebase. If I'm not mistaken, the work that PClass is doing here to help us serialize the values packed in Meta objects could also be done by our implementing the copy/pickle protocol on top of ExecutionPlan, etc., directly, without introducing the Meta objects. (https://docs.python.org/3/library/pickle.html#pickling-class-instances) The reason to stick to the existing protocol, imho, is to maintain interop with other ecosystem tools (dill, cloudpickle, etc.).

**Comment by schrockn** [comment]
Abandoning this for now. Ended up being unnecessary.

**Pull request closed without merging**
