### PR TITLE
[embedded-elt] Resolve EnvVars passed to permissive config

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Stopgap fix for #18188 which resolves all `EnvVars` passed to non-specified permissive config fields as string env vars.

This is a bit tricky to solve at a global level, but this fixes this behavior for `dagster-embedded-elt`.

## Test Plan

New unit test.

### CODE REVIEW

**Comment by benpankow** [comment]
Current dependencies on/for this PR:
* master
  * **PR #18517** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18517?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/18517?utm_source=stack-comment).

**Comment by tacastillo** [comment]
This looks like it works for the highly experimental API that we haven't announced it. Can this be backported to work with the `SlingResource`? which is what our docs currently recommend.

**Comment by benpankow** [comment]
> This looks like it works for the highly experimental API that we haven't announced yet. Can this be backported to work with the `SlingResource`? which is what our docs currently recommend.

https://github.com/dagster-io/dagster/pull/18517/files#diff-df0e57c2a323348ef1d9838ed4fee83887ef68ee950079179fa5850b160f79b2R108 

it should support `SlingResource`, e.g. as in this test case, unless there's another structure I'm missing

**Comment by tacastillo** [comment]
> > This looks like it works for the highly experimental API that we haven't announced yet. Can this be backported to work with the `SlingResource`? which is what our docs currently recommend.
> 
> https://github.com/dagster-io/dagster/pull/18517/files#diff-df0e57c2a323348ef1d9838ed4fee83887ef68ee950079179fa5850b160f79b2R108
> 
> it should support `SlingResource`, e.g. as in this test case, unless there's another structure I'm missing

Oh nice, saw that the `_setup_config` for `SlingResource` also does it. ty for clarifying. lgtm then!

**Pull request merged**
