### PR TITLE
Add CLI support

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

As title. Does two things:

1. create a global component registry with some hard-coded components pre-loaded
2. adds a template for generating instances of a component

## How I Tested These Changes

```
dg generate deployment my_deployment
cd my_deployment
dg generate code-location my_location
cd my_location
dg generate component sling_replication file_ingest
```

, also a unit test which does the same

## Changelog

NOCHANGELOG

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26261?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26261** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26261?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26261?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26260** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26260?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by schrockn — COMMENTED** [review]
Please put the CLI commands used in the test plan

**Comment by schrockn** [comment]
Ok `dg generate component sling_replication file_ingest` works? I was assuming it would have to be `dg generate component __internal__.sling_replication file_ingest` or something.

**Comment by OwenKephart** [comment]
> Ok `dg generate component sling_replication file_ingest` works? I was assuming it would have to be `dg generate component __internal__.sling_replication file_ingest` or something.

@schrockn yeah just `sling_replication` works -- I can namespace it if that feels safer, right now this is just a function of the name I chose in `components/__init__.py` (the `__component_registry__` variable)

**Review by schrockn — APPROVED** [review]

**Comment by OwenKephart** [comment]
### Merge activity

* **Dec 3, 9:50 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/26261).

**Pull request merged**
