### PR TITLE
[ui] Replace uses of replaceAlpha in asset graph, not possible with new vars

### PR DESCRIPTION
**Pull request by bengotow**
Fixes FE-341

### CODE REVIEW

**Review by salazarm — APPROVED** [review]
Mind posting a video of the animations working?

**Comment by bengotow** [comment]
Yep definitely - here's what it looks like now. I think this is right @salazarm? https://www.loom.com/share/7058f3de75a44ca4a215ec95fef81084

**Comment by salazarm** [comment]
yeah lgtm. the storybook is broken :( https://bengotow-2024-05-fe-341.core-storybook.dagster-docs.io/?path=/story/asset-graph-assetnode--live-states

**Comment by bengotow** [comment]
Ahh hrmm, i'll take a look at the storybookr real quick - looks like that's probably been broken for a while if it's mad about liveData :/

**Pull request merged**
