### PR TITLE
Allow passing in a string to StaticPartitionsDefinition

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

As title -- this was allowed before, so we should keep allowing it

## Changelog

NOCHANGELOG

### CODE REVIEW

**Comment by OwenKephart** [comment]
* **#25294** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25294?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alangenfeld — APPROVED** [review]
bummer

**Comment by OwenKephart** [comment]
gonna close this for now, we can reevaluate how we want to move forward on the original PR

**Comment by alangenfeld** [comment]
could you check in the test still?

**Comment by OwenKephart** [comment]
@alangenfeld the nasty thing is that get_partition_keys() actually ends up returning "abcdef" (rather than a list with individual strings)... so the rot extends further into the system. I think we'll want to retune this test once we figure out how we want to handle this situation

**Pull request closed without merging**
