### PR TITLE
Asset tags in the UI

### PR DESCRIPTION
**Pull request by sryza**
## Summary & Motivation

This PR passes tags up through graphql to the UI and displays them on the asset overview page. It doesn't yet support the no-value tags introduced in this PR: https://github.com/dagster-io/dagster/pull/20388.

Stacks on top of https://github.com/dagster-io/dagster/pull/20351.

image

### CODE REVIEW

**Review by hellendag — COMMENTED** [review]
JS looks fine to me. Can you also add a screenshot?

**Review by schrockn — COMMENTED** [review]
Will defer to the UI folks on this one

**Comment by sryza** [comment]
@hellendag - added a screenshot to the PR description. I haven't handled individual tags that exceed the width, and was hoping to pass that off to someone on the frontend team as a followup.

**Review by hellendag — APPROVED** [review]
That sounds fine. Thanks for the screenshot!

**Pull request merged**
