### PR TITLE
Fixed _TypedPythonTuple appending elements to dagster_type

### PR DESCRIPTION
**Pull request by jan-eat**
## Summary

Encountered https://github.com/dagster-io/dagster/issues/5083 when using the `dagster.Tuple` type with inner types.

The issue itself is pretty silly - whenever the property `_TypedPythonTuple(...).inner_types` got accessed, the `_TypedPythonTuple(...).dagster_types` list was mutated. A simple `.copy` fixes this.
Thought about replacing the loop with a list comprehension, but the `.copy()` actually feels more readable.

And while I don't know what `.inner_types` is used for, it's pretty clear that you're not trying to mutate `.dagster_types` every time it gets accessed.

## Test Plan

No tests added.

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by jan-eat** [comment]
Hello @sryza 
I was out of office for 2 weeks, will have a look at implementing the test this week

**Comment by sryza** [comment]
Thanks - the test looks great. It look like CI is complaining about import ordering.  To fix that, you can run `make isort` from the repo root (`pip install isort` before if you don't already have it).  Then should be good to merge.

**Comment by jan-eat** [comment]
should be fixed now

**Comment by sryza** [comment]
The remaining failure looks unrelated - I'm going to merge this. Thanks for the contribution @jan-eat !

**Pull request merged**
