### PR TITLE
update black 22.3.0 -> 22.12.0 and enable --preview

### PR DESCRIPTION
**Pull request by smackesey**
### Summary & Motivation

Updates `black` from 22.3.0 to 22.10.0 and enables `--preview` mode.

The version bump gives a small performance boost and bugfixes. Enabling `--preview` mode uses tweaks to the black style that are highly likely to be included in next major release, it's kind of like a conservative "enable-experimental-features". The rule changes that make up 99% of changes in this changeset include:

- Formatting of long string literals. There are a lot of these in the repo that had to be manually adjusted before, so this is a win. 
- Parens around return annotations now managed
- Deletion of blank lines at the start of a code block
- Several cases where extraneous parentheses are removed (awaited objects, with statements)

Comprehensive list is in [Black's changelog](https://black.readthedocs.io/en/stable/change_log.html).

### How I Tested These Changes

Existing BK tests.

Internal companion PR: https://github.com/dagster-io/internal/pull/4323

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a>  👈
    * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10900?utm_source=stack-comment).

**Review by schrockn — CHANGES_REQUESTED** [review]
So obviously this PR is too large to review. Why I'm requesting changes is for you to update the PR summary to include all the new rules changes.

For example, I'm seeing deleted lines, `.format` calls that are aligned differently, the multi-line string change (which seems great). An explicit list of all the new additional rules.

Also the name `--preview` is confusing. If you could note that what it really means is `--enable-experimental-features` that would make things clearer.

**Comment by schrockn** [comment]
Also before merging this I would give a heads up to the team that this may cause conflicts.

**Comment by smackesey** [comment]
@schrockn I added a list of the rules that cause 99% of changes and a link to the comprehensive list.

>Also before merging this I would give a heads up to the team that this may cause conflicts.

Intend to merge at the same time as the large changeset from the Ruff PR's so that people only need to resolve conflicts once.

**Review by schrockn — APPROVED** [review]
Great stuff.

Let's sync with ruff changes so we can provide with a single set of instructions for upgrading their local python dev environments with the right tools and versions.

**Pull request merged**
