### PR TITLE
patch assetNode resolution for solids

### LINKED ISSUE #6574: GraphQL Error: Location  not in workspace (Windows 10, default minimal settings with sqlite backend)
## Summary
dagster version 0.13.18

Received this error when trying to view a past run snapshot ID:

```
Operation name: PipelineExplorerRootQuery

Message: Location  not in workspace

Path: ["assetNodes"]

Locations: [{"line":2,"column":3}]

Stack Trace:
  File "C:\Users\yo_mama\apps\Python39\envs\dagster_dev\lib\site-packages\graphql\execution\executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "C:\Users\yo_mama\apps\Python39\envs\dagster_dev\lib\site-packages\graphql\execution\executors\sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "C:\Users\yo_mama\apps\Python39\envs\dagster_dev\lib\site-packages\dagster_graphql\schema\roots\query.py", line 433, in resolve_assetNodes
    repo_loc = graphene_info.context.get_repository_location(repo_sel.location_name)
  File "C:\Users\yo_mama\apps\Python39\envs\dagster_dev\lib\site-packages\dagster\core\workspace\context.py", line 140, in get_repository_location
    raise Exception(f"Location {name} not in workspace")
```

Windows 10 OS
Python 3.9.8 in virtual environment created with just venv module

Using just default settings, bare minimal settings, sqlite backend.

Contents of dagster.yaml file:
```
telemetry:
  enabled: false
```

## Reproduction
```
from dagster import job, op, get_dagster_logger
from random import randint
import time


@op
def some_expensive_task():
    # This will print to standard output
    print("Running an expensive task...")

    # Simulating a long-running task with a delay of 5 seconds
    time.sleep(5)

    # This will print in the dagit UI and standard output (aka "terminal")
    get_dagster_logger().info(f"I am performing an expensive task")

    # We will pass along a special message to the next task
    return "Hi!"


@op
def maybe_an_expensive_task(message):
    # What message did we get from some_expensive_task?
    print(f"Message from some_expensive_task: {message}")

    # This will print to standard output
    print("Maybe running an expensive task...")

    # Simulating a task that may take anywhere between 2 and 20 seconds
    time.sleep(randint(2, 20))

    # This will print in the dagit UI and standard output (aka "terminal")
    get_dagster_logger().info(f"Perhaps I will be performing an expensive task")

    return "Hello there!"


@op
def very_expensive_task(message):
    # What message did we get from maybe_an_expensive_task?
    print(f"Message from maybe_an_expensive_task: {message}")

    # This will print to standard output
    print("Running a very expensive task")

    time.sleep(20)

    # This will print in the dagit UI and standard output (aka "terminal")
    get_dagster_logger().info(f"I am performing a very expensive task")


@job
def execute_simple_example_tasks():
    expensive_task = some_expensive_task()
    maybe_expensive_task = maybe_an_expensive_task(expensive_task)
    very_expensive_task(maybe_expensive_task)
```

The above job ran fine.  Ran it twice.  Then click on link to view first previous run snapshot ID and then error occurred.

**EDIT:**
The script above was executed by way of: `dagit -f simple_example.py`   No workspace.yaml was used or created.

## Additional Info about Your Environment
Contents of dagster.yaml file:
```
telemetry:
  enabled: false
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by smackesey**
Patches asset node resolver for `ISolidDefinitionMixin` so that it works with solid defs that are part of HistoricalPipeline. Addresses: https://github.com/dagster-io/dagster/pull/6496#discussion_r805984158

Also fixes #6574.

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6588** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6588" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by alangenfeld — APPROVED** [review]
Does the page fully load after this change? 

Then this would address https://github.com/dagster-io/dagster/issues/6574 as well

**Comment by smackesey** [comment]
>Does the page fully load after this change?

I think so? No GraphQL error, so I think it addresses the linked issue. But under "Info" in the right sidebar it says "Could not load ops.", not sure if that's expected though.

**Review by alangenfeld — COMMENTED** [review]
> "Could not load ops.", not sure if that's expected though.

Same behavior as `0.13.17` at least so ill consider that expected (but improvable)

**Pull request merged**
