### PR TITLE
[rfc][Asset graph] Allow filtering for paths between nodes

### PR DESCRIPTION
**Pull request by salazarm**
## Summary & Motivation

Adds an asset selection syntax to filter for nodes between two paths.

When we detect "->" in the selection string we switch the sidebar to render as a tree view instead.

Things that work:

- Typing `->` to get a global tree view in the sidebar
- Typing `A ->` to get a tree view in the sidebar that is rooted at A while showing the graph equivalent to A*
- Typing `A -> B` to get a tree view of all paths starting from any node including "A" to any including "B"
- Typing `"A"-> "B"` to get a tree view of all paths starting from exactly node "A" to node "B"
- Typing `"A"-> "B" "C"->D` to show multiple tree views together
- Typing some other selection `A++ ->` and rendering the sidebar as a tree view.

Doesn't work:
- Typing `A++ -> B++`, you can't nest this operator, so this is the equivalent of `A++ B++ ->`

Open to a different symbol

## How I Tested These Changes

Screenshot 2024-04-18 at 2 48 49 AM
Screenshot 2024-04-18 at 2 38 13 AM
Screenshot 2024-04-18 at 2 34 30 AM

### CODE REVIEW

**Comment by braunjj** [comment]
This is great

**Comment by sryza** [comment]
I am very in favor of making it easier for users to see the path between two assets. A couple thoughts & concerns about this approach though:
- I don't think the asset selection syntax should control _how_ assets are displayed. There are many contexts where we'll want to be able to represent sets of assets (e.g. list, graph). Expanding the asset selection syntax to be a combined selection & display syntax adds more complexity here and might lock us in to certain UIs.
- We'll probably want to eventually support "and" or "&" in the selection syntax. Once we do that, someone would be able to get the path between a and b using "a* & *b", right? "a->b" is more elegant, so maybe we should just support this anyway though. The main downside is that I think it would mean ">" is no longer available to us as a reserved character (because "a-" is a valid asset key), and there are a limited number of characters for us to use for special purposes in selection syntax.

**Comment by salazarm** [comment]
> We'll probably want to eventually support "and" or "&" in the selection syntax. Once we do that, someone would be able to get the path between a and b using "a* & *b", right? 

First time hearing about this syntax change. I guess we'll have to build an actual parser soon if we are going to nest these expressions. I don't feel strongly about what the selection syntax exactly is, I did think however that if you're filtering by paths we would want to default the view to tree view but yeah being able to use "->" and I do think typing something like "A->" would be useful for people to understand who is consuming their data with the tree view sidebar (it's much easier to navigate than the graph itself because panning can be pretty slow).

**Comment by sryza** [comment]
> fwiw I think "A->" would be useful for people to understand who is consuming their data with the tree view sidebar (it's much easier to navigate than the graph itself because panning can be pretty slow).

If we think the tree view sidebar is a better experience when viewing the assets up/downstream of an asset, maybe we should:
- Show it whenever someone uses "a*" or "*a".
- Always show it on the lineage tab of the asset details page.

Thoughts?

**Comment by bengotow** [comment]
Ahh awesome! One other related thought here - we've discussed moving the asset selection syntax parser to python (eg: so that the UI could pass the user's intent rather than the blown-out list of 1000 assets, and it could also work in command-line settings).

Probably a separate design jam for another day, but I still have a really hard time groking what I'm looking at in the sidebar in the last screenshot... (eg: why are there 4 asset 16s?)  I get it from a technical standpoint, I just can't read it easily :-p   I wonder if there's a middle ground that works more like lineage, but in a list form.  Specifically, it feels like there should only be ONE of the currently selected node in the left sidebar, and the expanding / collapsing should unfold layers "away" from the selected node, not "down" only?

**Comment by salazarm** [comment]
Hmm I do like the idea of making "a* & *a" work for this purpose, and then finding some other way to toggle the tree view. 

> I get it from a technical standpoint, I just can't read it easily

Hmm, is this a one time thing though? Like once you get it... then it's easier to use? I mean this only happens if your graph is actually this complex. I think in a lot of common cases it won't be this confusing.

**Comment by krukowski** [comment]
> We'll probably want to eventually support "and" or "&" in the selection syntax. Once we do that, someone would be able to get the path between a and b using "a* & *b", right? "a->b" is more elegant, so maybe we should just support this anyway though.

Take this with a grain of salt since this is my first foray into asset selection syntax, but I would not expect `&` to indicate finding a path between two assets.

One alternative to that and `->` I'll suggest I think is more common is `a .. b` and/or `a ... b` (if we want to support both, the former could be inclusive of the edges and the latter could be exclusive).

**Comment by sryza** [comment]
> Take this with a grain of salt since this is my first foray into asset selection syntax, but I would not expect & to indicate finding a path between two assets.

@krukowski I'm not proposing that `&` should directly indicate this. What I'm saying is that "a*" already means "a and everything downstream of it" and "*b" already means "b and everything upstream of it".  The set of assets in "the path from a to b" is identical to "all the assets that are both downstream of a and upstream of b".

**Comment by cmpadden** [comment]
I think this is really cool, but one concern of mine is that we might be limiting ourselves in syntax that could be used for more expressive asset key selection. For example, `"dim_*"` to match all keys matching a prefix, and `"*_organizations"` to match a suffix.

If we delineate this using quotes, that could get pretty strange, like `"dim_*"*` could match all assets prefixed with dim, and their respective downstream assets (not saying we'd want to do this, but just a thought).

I do like the use of the `+` for upstream and downstream, as that's similar to [dbt graph operators](https://docs.getdbt.com/reference/node-selection/graph-operators), see:

```
dbt run --select "my_model+"         # select my_model and all children
dbt run --select "+my_model"         # select my_model and all parents
dbt run --select "+my_model+"        # select my_model, and all of its parents and children

dbt run --select "my_model+1"        # select my_model and its first-degree children
dbt run --select "2+my_model"        # select my_model, its first-degree parents, and its second-degree parents ("grandparents")
dbt run --select "3+my_model+4"      # select my_model, its parents up to the 3rd degree, and its children down to the 4th degree
```

I like their use of `+2` instead of something like `++` or `+++`.

dbt also uses the `@` symbol to select the parents of the children of the selected model:

```
dbt run --models @my_model           # select my_model, its children, and the parents of its children
```

I guess right now my confusion is around the necessity of quotes, and how that could impact wildcard key selection.

**Comment by sryza** [comment]
> I think this is really cool, but one concern of mine is that we might be limiting ourselves in syntax that could be used for more expressive asset key selection. For example, "dim_*" to match all keys matching a prefix, and "*_organizations" to match a suffix.

@cmpadden this is definitely a problem with our use of "*". When we added this syntax a long time ago, I think we actually based it on the syntax that dbt used at the time. Alas, given that it has worked this way for a long time, and users are relying on it, I don't think we can change it easily.

**Comment by salazarm** [comment]
> For example, "dim_" to match all keys matching a prefix, and "_organizations" to match a suffix.

Ah yeah right now you can do partial matches but you can't specify where the match is (could be in the middle).

**Pull request closed without merging**
