### PR TITLE
[dagit] Fix run ordering in Gantt panel

### LINKED ISSUE #5579: Dagit previous runs ordering
## Summary

Dagit ordering of previous runs looks wrong to me, I think I've seen this before but couldn't find a github issue related to it, looks like it's ordered by run id rather than timestamp

## Dagit UI/UX Issue Screenshots

Screenshot 2021-11-09 at 08 29 28

## Additional Info about Your Environment

dagster 0.13.4

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by hellendag**
## Summary

Resolves #5579.

In the Gantt status panel, where we show previous runs for that job, we aren't really defining how we order the runs and it appears that they end up in order of run ID.

Instead, render them in order of `startTime`, with the most recent runs first. I also moved "Root" to the last item in the list -- I'm not really sure what this tag means, so I'm not sure this is the right thing to do here.

Screen Shot 2021-11-18 at 3 33 48 PM

## Test Plan

Kick off a `sleepy` run, repeat from the Run view until I have a bunch of them all in a row. Verify proper ordering in the panel.

When kicking off a new run, verify that the list loads without it initially (since it has no start time) but then prepends the new run properly.

### CODE REVIEW

**Review by prha — APPROVED** [review]
I think this makes sense to me... + yuhan

**Comment by yuhan** [comment]
> Instead, render them in order of startTime, with the most recent runs first. I also moved "Root" to the last item in the list -- I'm not really sure what this tag means, so I'm not sure this is the right thing to do here.

Root is the root run of the entire re-execution group - it means if the root run has op selection (not the full graph), all the re-execution would run under that op selection scope.

I might make the order with the least recent run first - my argument is bc the root has always been the first one, ordering the most recent first could break users assumptions (more cognitively tho bc it's what they were used to), but open to objections.

**Comment by yuhan** [comment]
All great implementation-wise. But I'm not certain what's the right order either - maybe worth having @braunjj's weight in.

**Comment by bengotow** [comment]
This looks good to me as well - I think this ordering (with the ROOT run at the top) was feedback from Nick when we were building this out, but there used to be a disclosure triangle on it which made it a bit more logical

**Pull request merged**
