### PR TITLE
Update the last iteration timestamp on stopped scheduler ticks as well

### PR DESCRIPTION
**Pull request by gibsondan**
Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

### CODE REVIEW

**Review by prha — APPROVED** [review]
this should have no behavior change, right?  it's only to power the grace period?

**Comment by prha** [comment]
I guess the only thing to note here is that we're increasing the number of writes per iteration cycle for workspaces with a large number of stopped schedules

**Comment by gibsondan** [comment]
It would have an effect if you:

- start a new schedule with default status running (so a row is created with DECLARED_IN_CODE)
- redeploy it with default status off for a while (so the row still sits with its old start time, not updating the last_iteration_timestamp)
- redeploy it with default status on (so the last_iteration_timestamp has not updated, and it tries to backfill the last tick even though it is before the new 'start time')

**Comment by prha** [comment]
can we add a test for that case?  seems orthogonal to the case in https://github.com/dagster-io/dagster/pull/24601

**Pull request closed without merging**
