### PR TITLE
[dagster-embedded-elt] add _is_dagster_maintained to sling and dlt resources

### PR DESCRIPTION
**Pull request by cmpadden**

### CODE REVIEW

**Comment by cmpadden** [comment]
* **#21101** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21101?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cmpadden and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rexledesma — COMMENTED** [review]
There should be a test for this here: https://github.com/dagster-io/dagster/blob/00516c1e6528972d62f208ed972478d34fe43334/python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py#L22

`dagster_embedded_elt` is added there, which makes sense for why it's ignored.

But `dagster_dbt` is not added there, and we're also missing this classmethod on `DbtCliResource`. I think we need to fix the test to comprehensively solve this, since it doesn't seem like we're actually enforcing telemetry on our integrations.

cc @jamiedemaria

**Comment by cmpadden** [comment]
> There should be a test for this here:
> 
> https://github.com/dagster-io/dagster/blob/00516c1e6528972d62f208ed972478d34fe43334/python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py#L22
> 
> `dagster_embedded_elt` is added there, which makes sense for why it's ignored.
> 
> But `dagster_dbt` is not added there, and we're also missing this classmethod on `DbtCliResource`. I think we need to fix the test to comprehensively solve this, since it doesn't seem like we're actually enforcing telemetry on our integrations.
> 
> cc @jamiedemaria

@rexledesma setting a breakpoint in the telemetry test for the dagster-embedded-elt package, we can see that the `package.__dict__.values()` call does not contain any resource classes  (too noisy to include here).

```
(Pdb) package.__dict__.keys()
dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', 'DagsterLibraryRegistry', 'version', '__version__'])
```

Curious if this was working for other packages, and if there's a change required to the dagster-embedded-elt library, or if we just need a different approach altogether to extract all classes from the package.

**Review by rexledesma — APPROVED** [review]
Approving to unblock, but we should note a task to do the comprehensive fix.

**Pull request merged**
