### PR TITLE
docs(dbt): add more API docs examples for `@dbt_assets`

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation

Adds the following for `@dbt_assets`:
- How to run dbt commands with flags
- How to run dbt commands with `--vars`
- How to retrieve dbt artifacts
- How to run multiple dbt commands
- How to run dbt alongside other Dagster resources
- How to run dbt alongside Dagster config
- Added headers to describe each API docs example

## How I Tested These Changes
N/A

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #15840** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15840" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15840?utm_source=stack-comment).

**Review by slopp — COMMENTED** [review]
lgtm

**Review by slopp — APPROVED** [review]

**Review by PedramNavid — APPROVED** [review]
Looks great, only think that's a little confusing to me is what the `yield from dbt.stream()` line is doing, perhaps worth talking about it in the function description?

Something along the lines of? 

> Create a definition for how to compute a set of dbt resources, described by a manifest.json. `yield from` the `stream()` method after invoking a dbt command to retrieve a set of Asset definitions.

Not a blocker though.

**Review by erinkcochran87 — APPROVED** [review]
This is great, Rex - I love having lots of examples in the API docs. <3

I think a future improvement would be to have example headings be clickable anchors, like we do elsewhere in the docs, so we can link users right to a specific example if needed. I'm not sure if formatting text as a header in Sphinx would automatically create the headings, though - no need to block this to figure that out. I'll add that to my ongoing API doc improvements list.

**Pull request merged**
