### PR TITLE
[dagster-aws] ignore pyright errors with boto3-stubs

### PR DESCRIPTION
**Pull request by danielgafni**
## Summary & Motivation

Ignore pyright errors in `dagster-aws` which popped out after the introduction of `boto3-stubs-lite`. 

I suggest we slowly remove these ignore comments and fix the code for pyright to pass over time. 

I made a script to do it automatically. 

## How I Tested These Changes

pyright should be passing now

## Changelog [New | Bug | Docs]

> NOCHANGELOG

### CODE REVIEW

**Comment by danielgafni** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23954?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23954** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23954?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#23568** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23568?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#23569](https://github.com/dagster-io/dagster/pull/23569) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23569?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#23949](https://github.com/dagster-io/dagster/pull/23949) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23949?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#23509** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23509?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23440** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23440?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23353** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23353?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#23354](https://github.com/dagster-io/dagster/pull/23354) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23354?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#23441](https://github.com/dagster-io/dagster/pull/23441) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23441?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @danielgafni and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
Can you give some more context on these type errors, why the code is working now, and what the likely fix is? Is there a pattern here?

**Comment by danielgafni** [comment]
Most of them are because of accessing keys in boto3 response dicts. 
For some reason most of them are flagged as `NonRequired`, so accessing with `[]` instead of `.get()` raises a pyright error now. 
I think it's fine to ignore these errors since this code actually never raised runtime errors (so in practice these keys are always set).

**Comment by schrockn** [comment]
Ok. It would be great if in a follow up you could fix the trivial ones (even if it is just doing check.not_none(response.get("Whatever"))

**Review by schrockn — APPROVED** [review]
Script is pretty great

**Comment by danielgafni** [comment]
I wonder why `pyright` doesn't have an option to autoignore errors (`ruff` does)

**Pull request merged**
