### PR TITLE
Improve error message

### PR DESCRIPTION
**Pull request by mgasner**

### CODE REVIEW

**Comment by mgasner** [comment]
ok, I'll raise a `CheckError` as at https://github.com/dagster-io/dagster/pull/549/commits/0c41cf4f8254b368296c9e0259b8f1c163d81e22#diff-c60836aa27690f42ff73f299179e6124R74 immediately following

**Comment by schrockn** [comment]
that works. we might want to get more coherent as far as when we throw Check versus not at some poitn

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
It'd be straightforward to let `check.invariant` etc take an optional exception class to throw

**Comment by mgasner** [comment]
I've tended to like to use a lot of very thin, informatively-named exception classes so that the code base is easy to navigate when debugging

**Pull request merged**
