### PR TITLE
Fix: my-tutorial-project -> tutorial-project

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

Current tutorial scaffolding command is wrong, this fixes it.

## How I Tested These Changes

Ran command.

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #15014** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15014" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15014?utm_source=stack-comment).

**Review by erinkcochran87 — APPROVED** [review]
ty!

**Comment by tacastillo** [comment]
Thanks for catching this! I think the `my-` was a last minute addition and I didn't update the rest of the text.

Sandy just merged making `--name` optional, so mind if I drop a commit into this branch that just removes that arg completely?

**Comment by smackesey** [comment]
>Sandy just merged making --name optional, so mind if I drop a commit into this branch that just removes that arg completely?

Go for it-- I don't think it would require other downstream changes (if the default is `tutorial-projecti).

**Pull request merged**
