### PR TITLE
[docs] restructure navigation for top level dagster+, open source deployment

### PR DESCRIPTION
**Pull request by cmpadden**
## Summary & Motivation

In preparation for re-structuring our "deployment" related integration docs out of the "Integrations" section, and into an open-source deployment section, this moves "Dagster+" and "Open Source Deployments" to their own to-level navigation menu items.

The top level `Deployments` section has been removed, and children (`Dagster+` and `Open Source`) have been moved up one level. A _plus_ icon has been introduced for Dagster+.

## How I Tested These Changes

- Local render

### CODE REVIEW

**Comment by cmpadden** [comment]
* **#22478** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22478?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cmpadden and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by erinkcochran87 — COMMENTED** [review]
A few thoughts:

1. If we delete `deployment.mdx`, that results in a 404 when navigating to `docs.dagster.io/deployment`.
2. Using `/deployment/open-source` made sense when we presented Dagster+ as an alternative to OSS deployment, but it seems odd now that we're no longer doing that. We could rename the directory to `open-source-deployment`, but updating links is a PITA
3. Wherever we link to the OSS deployment category, we should specifically say "OSS deployment" and not just "Deployment" to make it very clear what we're referring to. Ex: _If you haven't set up a Dagster daemon yet, refer to the [Open Source Deployment guides](/deployment/open-source) for more info._

To get around 2 and having to update a bunch of links, what if we:

- Resurrect `deployment.mdx` and replace its content with that from `/deployment/open-source.mdx`
- Update links to `/deployment/open-source.mdx` where needed
- Add a redirect for `/deployment/open-source` to `/deployment`

**Comment by cmpadden** [comment]
@erinkcochran87 thanks for the feedback - I agree with your suggestions, and have implemented them in this commit: https://github.com/dagster-io/dagster/pull/22478/commits/2ecd5c0af61d340370a607de11043abacea59b21

**Review by erinkcochran87 — APPROVED** [review]
🤌 perfect

**Pull request merged**
