### PR TITLE
[pipes][fix] make DagsterK8sPipesClient.run public APi

### PR DESCRIPTION
**Pull request by dpeng817**
## Summary & Motivation
Noticed that this wasn't in API docs, felt like it should be
## How I Tested These Changes
N/A
## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [x] `DOCS` Added PipesK8sClient.run to api docs.

### CODE REVIEW

**Comment by dpeng817** [comment]
* **#24678** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24678?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — APPROVED** [review]

**Comment by danielgafni** [comment]
Should we rename this class to PipesK8sPodClient? 

I believe this name will be more specific.

**Comment by danielgafni** [comment]
As to the API itself... 

The current trend with other Pipes is to prefer a single large argument which is usually passed to a client as is (with injected env vars etc). 

In our case this can just be a single "pod" dict, a full kubernetes manifest. 

What are your thoughts on this? 

Should we standardize all Pipes clients to have a single input (when the underlying client also has a single input?

**Comment by dpeng817** [comment]
@danielgafni I think I share your preference towards having a single large argument for flexibility's sake. I wonder if there are things we could do to improve ergonomics for the simple cases though.

In any case, worth creating a github discussion so that the broader team can review!

**Pull request merged**
