### PR TITLE
Issue #21695 terminate runs

### PR DESCRIPTION
**Pull request by baumann-t**
## Summary
This PR adds an extra method to the DagsterGraphQL python client to enable the possibility to terminate multiple runs at the same time.

This PR is related to the following issue: https://github.com/dagster-io/dagster/issues/21695

## How I Tested These Changes

The PR contains a suit of unit tests similar to the other methods defined on the client, testing multiple edge cases for error handling.

### CODE REVIEW

**Comment by gibsondan** [comment]
Hi @baumann-t - thanks for sending this out. It looks like this needs a 'make ruff' and `dagster-graphql-client query snapshot` - can you run those and re-submit?

**Comment by baumann-t** [comment]
Hello @gibsondan! I've ran `make ruff` and `dagster-graphql-client query snapshot`, let me know if this is ok with you now!

**Review by gibsondan — COMMENTED** [review]
@baumann-t I realized one thing from looking at your query again - I don't think the TERMINATE_RUNS_JOB_MUTATION mutation is actually using the termationPolicy argument? you could either add it to the graphql query (being sure to re-run the snapshot command again) or remove it from the python

**Comment by baumann-t** [comment]
@gibsondan good catch thank you!. 
I removed it for now to keep it consistent with the other function `terminate_run`. If we want to, we could add it to both as well

**Review by gibsondan — APPROVED** [review]
thanks!

**Pull request merged**
