### PR TITLE
make asset execution context a standalone class

### PR DESCRIPTION
**Pull request by jamiedemaria**
## Summary & Motivation
Removes the `OpExecutionContext` parent class from `AssetExecutionContext`

### CODE REVIEW

**Comment by jamiedemaria** [comment]
* **#23212** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23212?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jamiedemaria and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — COMMENTED** [review]
I don't have much background on the original conversations here, but, based on the deprecation warnings we had, assuming this was part of the original plan behind `AssetExecutionContext`.

After this change, are there invariants that we want to maintain about the relationship between `AssetExecutionContext` and `OpExecutionContext`? Should `AssetExecutionContext` include all the methods on `OpExecutionContext`, or is there more of venn diagram? If the latter, what's our criteria for deciding what should be on `OpExecutionContext` but not `AssetExecutionContext`?

**Comment by jamiedemaria** [comment]
> assuming this was part of the original plan behind AssetExecutionContext

This is correct. The history of it was that `AssetExecutionContext` was introduced as a alias for `OpExecutionContext` so that users weren't exposed to the concept of ops. But then we decided that we had an opportunity to make a better, more asset specific, api for `AssetExecutionContext` by splitting it away from `OpExecutionContext`. And the subclassing and type checking stuff removed in this PR was the strategy to make `AssetExecutionContext` independent of `OpExecutionContext` without making a breaking change.


>  Should AssetExecutionContext include all the methods on OpExecutionContext, or is there more of venn diagram?

More of a venn diagram. For example, some of the deprecated methods on `AssetExecutionContext`, are just getting removed ([this is the list](https://github.com/dagster-io/dagster/blob/2bb34110b92d4e22e24306cdaae54f60143f4b4b/python_modules/dagster/dagster/_core/execution/context/asset_execution_context.py#L53-L60)). We don't have a set of standards though about what should be included in both. I can try to put together some general guidelines though, if that would be useful. 

However, if a method gets added to op context and erroneously not to asset context, we can direct users to do `context.op_execution_context.op_only_method()` until we add the method to asset context

**Comment by jamiedemaria** [comment]
@alangenfeld I had to make some changes to pipes to get pyright passing. It looks like all of the context methods that pipes uses are on both asset and op context, but would appreciate a second review in case there's more nuance here

**Comment by alangenfeld** [comment]
pipes changes look fine to me

**Comment by alangenfeld** [comment]
Does this PR review represent just validating the code changes or does it include validating the overall decision to remove this inheritance? I remember reviewing some of the earlier PRs but less the higher level discussions.

**Comment by jamiedemaria** [comment]
both validating the code changes and the decision to remove inheritance. We set the deprecation warning to say we'd remove inheritance in 1.8. I don't have an argument for keeping the inheritance, but we can bump that to 1.9 if needed. 

There are more type signature changes in this pr than i expected and with the offsite slowing down review, this pr will have less time to bake in the release branch than originally intended. So if it seems too rushed at this point we can bump the deprecation version and make the type signature changes in 1.8.x versions so that the eventually removal of inheritance is a smaller pr

**Comment by jamiedemaria** [comment]
PR stalled out during the offsite and now would be rushed in to 1.8. bumping the breaking version to 1.9 and we'll revisit then

**Comment by jamiedemaria** [comment]
https://github.com/dagster-io/dagster/pull/23381

**Pull request closed without merging**
