### PR TITLE
fix worker_start_command for windows when use --config-yaml

### PR DESCRIPTION
**Pull request by rubikplanet**
## Summary & Motivation

--config-yaml option is not working on windows because it uses a colon as the path seperator.

use os.pathsep to join the path make it work both on linux and windows.

## How I Tested These Changes

Yes, I tested manually on windows.

### CODE REVIEW

**Comment by yuhan** [comment]
@alangenfeld @gibsondan mind taking a look? (tagging you because you two showed up in git blame, but plz feel free to re-route!)

**Comment by alangenfeld** [comment]
looks reasonable, @rubikplanet  did you test this manually on windows? Could you update the `How I Tested These Changes` section?

**Review by alangenfeld — DISMISSED** [review]
for previous comment

**Comment by rubikplanet** [comment]
fix: f-string instead of `format`

**Comment by rubikplanet** [comment]
I don't know how to split them. Instead, create another PR https://github.com/dagster-io/dagster/pull/14317.
And please close this one.

**Pull request closed without merging**
