### PR TITLE
[docs] wildcard dagster plus redirects

### PR DESCRIPTION
**Pull request by cmpadden**
**NOTE** - Erin to confirm that there are no `dagster-cloud` domains that we do _not_ wish to redirect

---

## Summary & Motivation

- Support nested `:slug*` redirects for all `dagster-cloud` to `dagster-plus` routes
- In reference to @johannkm's comment
    * https://github.com/dagster-io/dagster/pull/21662#pullrequestreview-2041373296

## How I Tested These Changes

- Local cherry-picked links

### CODE REVIEW

**Review by johannkm — COMMENTED** [review]
nice!

**Review by erinkcochran87 — COMMENTED** [review]
I *think* I got everything!

**Comment by cmpadden** [comment]
Thanks for the review, @erinkcochran87.  I've re-introduced the two redirects that do not directly map to the _dagster-cloud_ to _dagster-plus_ wildcards. Tested links:

- https://colton-dagster-plus-wildcard.dagster.dagster-docs.io/dagster-cloud/managing-deployments/setting-up-alerts
- https://colton-dagster-plus-wildcard.dagster.dagster-docs.io/dagster-cloud/managing-deployments/dagster-cloud-cli

Hopefully that covers it - let me know if you'd like me to do any more testing specifically.

**Review by erinkcochran87 — APPROVED** [review]
lgtm, this is baller 🙏

**Pull request merged**
