### PR TITLE
[dagit] React Router v6 compatibility

### PR DESCRIPTION
**Pull request by hellendag**
### Summary & Motivation

Implement the first step toward upgrading to React Router v6.

https://github.com/remix-run/react-router/discussions/8753

### How I Tested These Changes

View Dagit, verify that there are no ill effects from adding the `CompatRouter`.

### CODE REVIEW

**Comment by hellendag** [comment]
Current dependencies on/for this PR:
* master
  * **PR #8708** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8708" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/8708?utm_source=stack-comment).

**Comment by bengotow** [comment]
This looks good to me! I read through the migration doc over here (https://github.com/remix-run/react-router/discussions/8753) and it actually seems like this will be pretty smooth, happy to help push this along! It's pretty incredible they've set this up so you can do it bit by bit.

**Review by bengotow — APPROVED** [review]
(I think it's safe to merge if you want to so I stamped it - Not sure if it was waiting on a corresponding cloud PR)

**Comment by salazarm** [comment]
Looking at the ReadMe and it says:
>Change a <Route> inside of a <Switch> to a <CompatRoute>

**Comment by salazarm** [comment]
So I think we're missing  a change to convert all of our Routes to CompatRoute.

**Pull request merged**
