### PR TITLE
s/AssetRecord/LatestAssetInfo

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Rename AssetRecord to LatestAssetInfo per discussion here https://github.com/dagster-io/dagster/pull/21470#issuecomment-2083414711

Also add methods `get_latest_asset_infos` to replace `get_asset_records`.

As part of this we would also add properties at the top-level of `LatestAssetInfo` (next PR in stack) so that we don't have to deal
with `asset_entry` in product code. `AssetEntry` should probably just go away entirely.

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by schrockn** [comment]
* **#21495** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21495?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#21494** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21494?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#21493** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21493?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sryza** [comment]
> with asset_entry in product code. AssetEntry should probably just go away entirely.

My recollection of the reason we have this separation is that we don't know the storage ID before we write out the data. `AssetEntry` contains everything we want to write, then `AssetRecord` represents the written row.

**Comment by prha** [comment]
I'm not 100% sure why we need to expose the storage_id at all for this data.  I'm in favor of getting rid of `AssetEntry` / `AssetRecord` distinction and just going with a single `LatestAssetInfo` thing.

One thing I want to stick in your head though is whether in the future we'll want to have a separate object for a specific asset partition, and whether we'd distinguish for the latest info for the specific partition or the latest info for the asset overall.

**Comment by schrockn** [comment]
I would like to move forward with this. Moved to non-draft (alone with #21494 and #21495)

**Comment by gibsondan** [comment]
There is other stuff here that I wouldn’t necc classify as “latest” (for example, the status cache value) but maybe that’s fine.

**Comment by schrockn** [comment]
Actually I'm just going to do this fresh since `BatchAssetRecordLoader` landed

**Comment by schrockn** [comment]
@gibsondan very unattaced to the "latest" terminology so very open to suggestions

**Pull request closed without merging**
