### PR TITLE
Hide compute details for source assets

### PR DESCRIPTION
**Pull request by salazarm**
## Summary & Motivation
as titled

### CODE REVIEW

**Review by sryza — COMMENTED** [review]
Will this hide compute details for observable source assets? We'd still want those to show up. I believe a more reliable way to check whether an asset has an associated computation is to see whether it has an `opName`.

**Comment by bengotow** [comment]
> Will this hide compute details for observable source assets? We'd still want those to show up. I believe a more reliable way to check whether an asset has an associated computation is to see whether it has an `opName`.

Hmm, would `asset.isExecutable` work? I believe we have that loaded in more places

**Comment by sryza** [comment]
Yeah I'd expect that to work too

**Comment by sryza** [comment]
You should only need to check for `isExecutable`

**Comment by salazarm** [comment]
@sryza updated

**Review by sryza — APPROVED** [review]

**Pull request merged**
