### PR TITLE
[dagster-airlift][misc] use automapped metadata key

### PR DESCRIPTION
**Pull request by dpeng817**
## Summary & Motivation
Previously, we were only checking for the non-automapped metadata key.

## How I Tested These Changes
Existing tests. Previously kitchen sink wasn't running on airlift branches, which is how this got missed, but https://github.com/dagster-io/dagster/pull/24970 fixed that.

## Changelog
NOCHANGELOG

### CODE REVIEW

**Comment by dpeng817** [comment]
* **#25002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25002?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alangenfeld — APPROVED** [review]
stamping to unbreak build but i dont really understand the change - worth post hoc validation

**Review by schrockn — CHANGES_REQUESTED** [review]
I think we should just use the same key for both.

**Review by schrockn — APPROVED** [review]
approving to unbreak build. can fix in post

**Pull request merged**
