### PR TITLE
added solid_from_func helper to generate solids from arbitrary functions

### PR DESCRIPTION
**Pull request by david-alexander-white**
this lets you avoid solid creation boilerplate by creating a solid from any function

default parameters and varargs are dropped for simplicity

this has been massively helpful for my own pipeline development, but not sure of the community's views on using dynamic functions in this way

have discussed a bit with @prha

### CODE REVIEW

**Comment by schrockn** [comment]
So I would rather not merge this and let you try it out in your own codebase first. I think this adds some pretty subtle behavior (for example magically dropping default values will lead to confusing behavior) and I think forcing the user to explicitly wrap the existing functions results in far more predictable behavior.

**Comment by david-alexander-white** [comment]
Totally agree this solution is a little hacky and confusing. If you have recommended fixes I'd love to hear them.

That said, let me lay out some of the pain behind why I did this: 

In my use case, I have a *lot* of solids. Some of them clean dataframes, but some of them just generate input and output file paths (btw I would *LOVE* to talk about why that's necessary and if it can be fixed, it's caused me hours of headaches).

All of these functions need to be usable outside of dagster, so they can't be solely defined as solids. Let's say I have 20 such functions in my pipeline. Without something like this pull request, for each one, I'm writing something like

@solid
def my_solid(arg1, arg2):
  return my_func(arg1, arg2)

Which is at least 60 lines, if I'm not commenting. 

Then, I have to put each solid... somewhere -- either in the module my_func is defined in, or in the pipeline module, or else in a special holding area for solids.

Both of these are doubly frustrating if I'm trying to use a function from a publicly available library.

Overall I'd imagine problems like this would pop up with any workflow that has multiple steps and needs some degree of dynamic configuration -- I think one big difference between my case and the ones I see in the examples is that it's dealing with dated files as opposed to database storage. But it's also possible I'm missing something critical, or that my tolerance for boilerplate is just way below the norm.

**Comment by mgasner** [comment]
I'm very interested in something like this (maybe `as_solid` or `as_dagster_solid`), especially to make it easier to wrap existing utility libraries. I had earlier considered a convention that would convert kwargs into config values, though this also has its drawbacks (default values for non-literal/scalar inputs -- you would need custom types and some way to hydrate them, etc.).

It's also possible to imagine implementing default inputs with a more complex optional outputs/composite solid-based setup, though the ergonomics would be terrible.

We could consider barfing on signatures that didn't meet some fairly strict restrictions, but this might limit the utility of the method so much that it wasn't worth implementing.

Complicating matters, `inspect.signature` was introduced in Python 3.3, so we need some kind of solution for py2. There are likely nits around bound/unbound methods and possibly other callables as well. Consider also #1643 -- if a function is imported from somewhere, it won't have access to `context.log` and will presumable just use Python `logging`.

A more magical solution (@schrockn will hate this) in the pipeline definition DSL would be to allow bare python functions where we currently have solid definitions, so you could write:

```
def my_util_fn(foo, bar):
    return 'baz'

@solid
def my_explicit_solid(quux):
     ...

@pipeline
def my_pipeline():
    my_explicit_solid(my_util_fn())
```

This could "just work" if we autowrap the bare python functions in `@lambda_solid` or equivalent -- and just barf with an error if the conditions aren't met. This is more like sugar and less like claiming that we know how to convert arbitrary python signatures (maybe with `*` and `**`, concepts we probably don't have good equivalents for in the solid input/config domains) into solid signatures.

**Comment by mgasner** [comment]
@alangenfeld suggests `@as_lambda_solid`

**Comment by mgasner** [comment]
Anothe approach from https://dagster.slack.com/archives/CCCR6P2UR/p1582656151050200

```
import dagster
import inspect
def solid_from_func(func, alias=None):
    # capture the signature of func
    sig = inspect.signature(func)
    params = list(sig.parameters.values())
    params.insert(0, inspect.Parameter('context', kind=inspect.Parameter.POSITIONAL_OR_KEYWORD))
    new_sig = sig.replace(parameters=params)
    type_map = { 
        bool: dagster.Bool,
        float: dagster.Float,
        int: dagster.Int,
        str: dagster.String,
        list: dagster.Array,
        dict: dagster.Dict
    }
    config_from_params = {}
    for k, v in sig.parameters.items():
        try:
            if v.default is not inspect.Parameter.empty:
                config_from_params.update({k: dagster.Field(type_map[type(v.default)], default_value=v.default, is_required=False)})
            else:
                config_from_params.update({k: dagster.Field(type_map[type(v.default)], is_required=True)})
        except KeyError:
            config_from_params.update({k: dagster.Field(dagster.Any, is_required=False)})
    # create our solid
    @dagster.solid(
        name=alias or func.__name__,
        config=config_from_params
    )
    def new_solid(context):
        # call the original function with the config values
        return func(**context.solid_config)    return new_solid


from pandas import read_excel
from os import getcwd
from os.path import join, dirname, abspath

def test_solid_from_func_wrapper():
    excel_solid = solid_from_func(read_excel, "excel_solid")
    res = execute_solid(
        excel_solid,
        environment_dict={
            "solids": {
                "excel_solid": {
                    "config": {
                        "io": join(dirname(abspath(__file__)), "cereals.xlsx"),
                        "header": 1,
                        "skiprows": 1
                    }
                }
            }
        }
    )
    assert res.success
```

**Comment by schrockn** [comment]
Going to call this stale and close the pull request.

Please let us know if you have used this pattern in your codebase!

**Pull request closed without merging**
