### PR TITLE
fix(dbt): support dotted dbt dependency names

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
Resolves https://github.com/dagster-io/dagster/issues/19620.

Reworks https://github.com/dagster-io/dagster/pull/19627 on top of https://github.com/dagster-io/dagster/pull/19752 and uses a separate dbt project to test out the changes, rather than modifying `dagster_dbt_test_project`.

Our output names when materializing dbt resources weren't always unique since we only used the last part of the dbt unique id when creating an output identifier. Instead of doing that, just convert the entirety of the unique id.

This pretty much makes our functions that create input/output names the same, so consolidate that logic into `dagster_name_fn`.

## How I Tested These Changes
Added a new test case, and existing test cases should continue to pass.

### CODE REVIEW

**Comment by rexledesma** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19769?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #19767** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19767?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #19768** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19768?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #19769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19769?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/19769?utm_source=stack-comment).

**Review by OwenKephart — APPROVED** [review]
very nice 🙏

**Comment by tehunter** [comment]
This should also fix an issue related to #16046. Even with the Translator fix provided in that issue, if you have multiple versioned models, dagster will drop some of the dependencies. This is because the output name for multiple dbt models will end up mapping to `v1`, so the earlier instances of versioned models will be overwritten.

**Comment by rexledesma** [comment]
> This should also fix an issue related to #16046. Even with the Translator fix provided in that issue, if you have multiple versioned models, dagster will drop some of the dependencies. This is because the output name for multiple dbt models will end up mapping to `v1`, so the earlier instances of versioned models will be overwritten.

Cool, thanks for letting me know! I can add an explicit test case with dbt versioning in a later PR to assert that the issue is actually fixed.

**Comment by rexledesma** [comment]
@tehunter The version issue will be resolved by https://github.com/dagster-io/dagster/pull/19799.

**Comment by tehunter** [comment]
> @tehunter The version issue will be resolved by https://github.com/dagster-io/dagster/pull/19799.

Just want to say thank you for these changes! I literally just started using Dagster yesterday and it's great to see how actively issues are addressed.

**Pull request merged**
