### PR TITLE
Add config selector

### PR DESCRIPTION
**Pull request by freiksenet**

### CODE REVIEW

**Comment by schrockn** [comment]
Btw seeing this error

screenshot 2018-11-21 08 34 14

**Comment by freiksenet** [comment]
Should handle errors better now.

**Comment by schrockn** [comment]
Ok this is interesting, but I don't think it's exactly what we want. I think we will want something more lightweight. Most specifically, we want to be able to hop into the config editor without having to name it etc. I think a lighterweight tab-style interface a la graphql playground might be the way to go. Why don't we discuss with @bengotow when we meet up on Monday morning. I think this is also part of the overall conversation about how to layout the entire app.

**Comment by freiksenet** [comment]
Sure.

**Pull request closed without merging**
