### PR TITLE
Export build_reconstructable_target to match cragified docs

### PR DESCRIPTION
**Pull request by prha**
## Summary
Updates apidoc for `build_reconstructable_target` and exports it from the top-level dagster module.

Also adds the api entries and rebuilds the sphinx indices.

## Test Plan
BK

### CODE REVIEW

**Comment by sryza** [comment]
Why not `build_reconstructable_job`?

**Comment by gibsondan** [comment]
@yuhan reasonable point but I think the name already existed before this PR - so we'd have to either make yet another alias or risk breaking existing users that are importing it.

**Comment by sryza** [comment]
@gibsondan how would users have known to import it? The only mention I can find of it is in an error message, and that error message doesn't even say what package to find it in.

That said, if we do think users are relying on it, then IMO aliasing is the right way to go. Better another alias than another term.

**Comment by gibsondan** [comment]
i did point one user to it in support after grepping :/ but agree a rename would be low-cost.

**Review by sryza — DISMISSED** [review]
Requesting changes with respect to the recent comments I left

**Pull request merged**
