### PR TITLE
Update pylint and associated config

### PR DESCRIPTION
**Pull request by smackesey**
Pylint updates:

- Update to 2.13.7-- the update introduces some new linter rules, for which associated changes are made throughout codebase:
    - Many `disables` added for newly detected violations (only if the violation made sense)
    - `open()` calls now pass `encoding="utf8"` if not in binary mode
    - Few other tweaks (some logging calls were updated before I decided to just set the log rules to be ignored)
- Move pylint config to pyproject.toml and add comments for all config
- Config changes
    - Disable the `typecheck` checker and delete all config for it (it is redundant with mypy and a source of duplicates/false positives)
    - Disable new logging interpolation rules (too much existing code uses older style with prob infinitesimal perf impact)
    - Disable `redefined-outer-name` so that the recommended SDA API doesn't raise lint warnings
    - Remove old `generated-members`/`ignored-modules` settings that didn't seem to be doing anything
    - Set target Python version to 3.6
- Fix `Makefile` command so that it runs in single-process mode on macOS instead of crashing.

### CODE REVIEW

**Review by sryza — COMMENTED** [review]
Definitely helpful to replace the warning codes with the names. Can we get rid of some of the comments above?

I'm a little worried that ignoring redefined-outer-name will make us less sensitive to the plight of users who need to deal with this lint warning when using Dagster in their own code. I wonder if we should at least find somewhere in our documentation to tell users to do this as well before disabling it for ourselves?

**Review by sryza — APPROVED** [review]
If I understand correctly, this is delaying the redefined-outer-name ignore for later and making other lint improvements. If so, would be good to make sure the PR and commit have a title that reflects the actual change.

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6714** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6714" target="_blank">Graphite</a> 
    * **PR #6517** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6517" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Comment by smackesey** [comment]
@sryza You should have another look at this bc it's changed a lot since you last did:

- pylint config migrated to pyproject.toml (with black and isort downstack)
- enforced `encoding=utf8` for all `open` calls (new lint rule for newer pylint) to ensure we don't get weird behavior on windows
- added a bunch of explanatory comments
- changed Makefile invocation of pylint so that it works on mac and matches what gets tested in CI

**Review by sryza — APPROVED** [review]
* The utf-8 encoding thing is ugly and annoying, but I suppose we should do it.
* Deleting typecheck seems reasonable.

I was not 100% comprehensive, but did a skim through of the disables and they all seemed reasonable to me.

@alangenfeld - do you mind taking a look at this as well?

**Comment by smackesey** [comment]
> The utf-8 encoding thing is ugly and annoying, but I suppose we should do it.

It is annoying, but the more successful the project becomes the more likely we run into weird issues stemming from names with non-English characters from people using windows. Ran into this kind of thing multiple times when working on scientific literature informatics stuff in a past life (author names are all over the place), I'm glad pylint added a rule to nip this in the bud.

> did a skim through of the disables and they all seemed reasonable to me

Almost all of the disables were already there but listed under their numeric codes instead of names.

**Review by alangenfeld — APPROVED** [review]
> [clairelin135](https://github.com/clairelin135) dismissed [sryza](https://github.com/sryza)’s [stale review ](https://github.com/dagster-io/dagster/pull/6517#pullrequestreview-908289104)via [495885d ](https://github.com/dagster-io/dagster/commit/495885da11df26c55e0229d4dbec2f59b0c2c00d)[2 days ago](https://github.com/dagster-io/dagster/pull/6517#event-6422994949)

very weird dismissal

I started trying to review the changes in this PR but found it unreasonable:
* github and graphite web experiences choke trying to review the whole change
* going through 54 separate commits is very unpleasant. maybe I'm missing some way of tracking incremental progress.

In the future i think splitting out bulk changes like

> open() calls now pass encoding="utf8" if not in binary mode

in to their own PRs is worth while. Especially if those changes are automated or tool driven. I don't need to look at all the changes in that PR if i can reference a couple examples and pretty safely assume the rest match that. 

I will approve this again since it was already approved before, and is very likely fine if it passes buildkite.

**Comment by alangenfeld** [comment]
Is there an internal variant of these changes lined up to keep the repos in sync?

**Pull request merged**
