### PR TITLE
:bug: UPathIOManager: call correct method when loading single partition

### PR DESCRIPTION
**Pull request by danielgafni**
## Summary & Motivation

A small fix for the `UPathIOManager` - calling `_load_partition_from_path` instead of `_load_single_input` when loading a single partition. 

This makes a difference when subclassing the `IOManager`. I expect the `_load_partition` to be called for loading partitions (even if it's just one partition) and `_load_single_input` for loading the whole asset at once. 

## How I Tested These Changes
Added a test which checks that `_load_single_input` isn't called when loading a single partition

### CODE REVIEW

**Comment by jamiedemaria** [comment]
looks like a couple tests and pyright failed. this general change looks fin e to me, once the tests are fixed it'll probably be good to go

**Comment by danielgafni** [comment]
Hey @jamiedemaria , can we try again?

**Comment by jamiedemaria** [comment]
when was the last time you merged in latest changes to this branch? I made some updates to the UPath  I/O manager a couple weeks ago and it would be good to make sure the new tests are run with your code changes

**Comment by danielgafni** [comment]
Ok I see, it was a while ago.

In this case I would like to work on also resolving #19220 (as I was planning to do it next anyway)

I think the `UPathIOManager` should expose an interface for loading multiple partitions as a single object, and this method would have a default implementation of loading them into a `Dict` object by invoking `load_single_partition` in a for loop. 

Something like (a rough draft): 

```python
def load_single_partition(
    self,
    base_path,
    partition_key
)

def load_multiple_partitions(
    self,
    base_path,
    partition_keys: list[str]
)
    return {self.load_single_partition(base_path, key) for key in partition_keys}
```

This would keep the current behavior with returning `Dict` with multiple partitions by default, but would allow downstream IOManagers (for example, working with tabular data) to easily change this behavior. 

Of course, the mandatory `Dict` type check would have to go.

I think we can include these changes in this PR. 

Does it sound good?

**Comment by jamiedemaria** [comment]
tagging in @clairelin135  and @smackesey  for their opinions on the partition behavior! I think it would be fine since it would keep the default behavior the same but allow downstream classes to implement different behavior

**Comment by clairelin135** [comment]
Looks reasonable to me!

**Comment by danielgafni** [comment]
Closing the PR in favor of https://github.com/dagster-io/dagster/pull/21135

**Pull request closed without merging**
