### PR TITLE
fix: prevent runs filter from accepting an empty list of run ids

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary
Currently, applying a run filter with `run_ids` as `None` or `[]` has the same result of fetching all the runs. This is because both values are falsey.

We could change the logic to treat `[]` as a short-circuit and skip fetching any runs, but then the API consumer would need to be wary that passing in `[]` has this particular behavior.

Instead, if `[]` is passed in, throw an error. The API consumer should explicitly guard for this case in their business logic, rather than relying on the underlying API to skip the fetching of any runs.

## Test Plan
pytest

run dagit locally, fill out `id:` field with random values

https://user-images.githubusercontent.com/16431325/160492995-11d5aaff-48f9-4594-8302-07a309d2cbea.mov

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7217** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/7217" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by alangenfeld — COMMENTED** [review]
> Test Plan
> pytest

can you do a quick sanity check in dagit to make sure you can't get this fire messing around with filters in the runs page?

**Comment by rexledesma** [comment]
> > Test Plan
> > pytest
> 
> can you do a quick sanity check in dagit to make sure you can't get this fire messing around with filters in the runs page?

Locally verified this behavior and added a video. Though funny enough, found an unrelated error when doing this manual test.

**Review by alangenfeld — APPROVED** [review]
thanks

**Pull request merged**
