### PR TITLE
protobuf ceiling bump

### PR DESCRIPTION
**Pull request by alangenfeld**
resolves https://github.com/dagster-io/dagster/issues/25398

## How I Tested These Changes

existing coverage

### CODE REVIEW

**Comment by alangenfeld** [comment]
* **#26271** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26271?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26271?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by alangenfeld** [comment]
i aspire to add a nightly pipeline test for tracking when the defensive ceiling should get checked and ideally bumped

**Review by gibsondan — APPROVED** [review]
probably worth test-all / SKIP_NONE on this one?

**Comment by gibsondan** [comment]
(to get all python versions covered)

**Pull request merged**
