### PR TITLE
RFC: AssetObservation

### PR DESCRIPTION
**Pull request by sryza**
This PR proposes a new kind of event that records metadata about an asset without signifying that the asset has been mutated.

Here are some situations where these would be useful:
* Each time you read an asset, you want to record how many missing records it has.
* You have an asset that isn't maintained by a Dagster job, but that's depended on by assets that are maintained by a Dagster job. You want to run a job on a regular cadence that records metadata about how many missing records it has.
* You run an hourly job that scans your data warehouse and yields an AssetObservation for every table inside it. This allows you to discover assets that don't have a corresponding definition.

Example user request from @GeorgePearse: https://dagster.slack.com/archives/C01U954MEER/p1637142917300800.

### CODE REVIEW

**Comment by dpeng817** [comment]
Fwiw, I can imagine this being useful from a memoization perspective as well. The current memoization functionality doesn't provide a great way to track the state of external resources that you may be reading, which can affect memoization status.

For example, consider a job that reads from some external table. If that table has new records, you probably want the job to re-run. Right now, the only way to model this would probably be to use AssetMaterializations, but that's not really the right abstraction. AssetObservation seems like it is exactly the right abstraction though.

**Comment by schrockn** [comment]
I'm really excited to see this yielded from _sensors_. I think that will be a very common, very useful pattern.

**Comment by OwenKephart** [comment]
I really like this -- seems like it would be useful in a ton of different contexts. You should probably be able to yield this from inside a load_input() function as well (particularly if you're using a RootInputManager or something of the sort).

**Comment by prha** [comment]
I think this looks great.  In favor of this, for sure.

Some random comments/questions:
- Should asset observations show up in the asset catalog?
- I think sql-based storages will error on these events without changing.
- I think the Run view in dagit will break if we introduce a new type without handling.

@schrockn oh interesting.  Just to state what I think you mean, our current asset sensors check for materialization events from a managed asset.  You're saying we'd have storage-specific sensors that poll for some observed change of an unmanaged asset?

**Comment by sryza** [comment]
> Should asset observations show up in the asset catalog?
I think definitely, though not entirely sure what the ideal UI looks like.

**Comment by schrockn** [comment]
@prha For example if there is an s3 sensor that is triggered on some random s3 file not managed by Dagster computations, I think it should be standard practice to emit an AssetObservation in the sensor loop to track it's properties. One is already undoubtedly do an existence check. Just make it a metadata query or something and then track the information in the asset catalog. We could also hook up asset lineage to that observed asset.

**Comment by clairelin135** [comment]
This is really useful. I can imagine that many users would like to surface specific metadata (e.g. number of rows added) in Dagit. Would be very useful to view alongside materializations over time in the Assets page.

**Review by prha — APPROVED** [review]

**Review by prha — COMMENTED** [review]
this already should work, but maybe we can add a test where an asset_sensor does not fire for an observation, but does for a materialization?

This probably also needs a follow-up PR where we tweak the graphql layer to see if we need to fetch both observations / materializations or just materializations.

**Pull request merged**
