### PR TITLE
docs: improve search 3/ handle GH discussion entries in search results

### PR DESCRIPTION
**Pull request by yuhan**
### Summary & Motivation
See https://github.com/dagster-io/internal/pull/2166

### How I Tested These Changes
image

### CODE REVIEW

**Comment by sryza** [comment]
Very cool. I think these should show up underneath guides and concept pages. What do you think?

**Comment by yuhan** [comment]
@sryza makes total sense - i played around with algolia's custom ranking. now i set the rule to rank apidocs (it could get noisy so i ranked it lower) and gh discussions lower than other docs pages - see changes here: https://github.com/dagster-io/internal/pull/2166/commits/2d8be89dabbfae70e87e2ae6274db97751a31ef4

so we get:
image

moving forward, i think we should also implement a "see all results" or pagination functionality so we have a place to find lower ranking results as well. tracking it here: https://linear.app/elementl/issue/DREL-338/[docs]-implement-standalone-search-result-page

**Review by erinkcochran87 — APPROVED** [review]
This looks good to me! I agree with your idea for a future iteration that includes 'see all' functionality. :tada:

**Comment by sryza** [comment]
Ranking those both lower sounds right to me!

**Comment by yuhan** [comment]
Current dependencies on/for this PR:
* master
  * **PR #8252** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8252" target="_blank">Graphite</a>  👈
    * **PR #8273** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8273" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/8252?utm_source=stack-comment).

**Pull request merged**
