### PR TITLE
[blueprints] Use jinja to populate string YAML fields, support env var access

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Alternate impl of #22149 which more conservatively applies Jinja2 templating logic to string values in Blueprint YAML files before they're loaded into Pydantic models. This is useful for templating behavior, e.g. this PR adds the ability to fetch environment variables for use in Blueprints.

Because these templates are only resolved in string values, this means our YAML-position-to-Pydantic-field-mapping logic won't be affected by things like Jinja control structures, and means users will be pushed to move complexity to Python instead of attempting it in YAML land.

## Test Plan

Unit tests.

### CODE REVIEW

**Comment by benpankow** [comment]
* **#22153** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22153?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — COMMENTED** [review]
A couple thoughts here:
- How would we explain what env is being used when someone uses `env_var`?
- I wonder if we should have a special type that enables this, rather than having it on for all string fields. Imagine that someone wanted to build something like dbt inside the blueprints framework - i.e. embed jinja-templated SQL inside blueprints. They'd have trouble doing so if all strings are automatically jinja-ized.

**Comment by benpankow** [comment]
> * How would we explain what env is being used when someone uses `env_var`?

The env is the environment that your code location is being loaded in - so it would be expected that the env var is set in the code location server and run environment.

Do you think there's room for confusion here? It feels relatively straightfoward to me (e.g. no harder to understand than `EnvVar`), with the caveat that it needs to be set in the code location pod & not just the run env.

> * I wonder if we should have a special type that enables this, rather than having it on for all string fields. Imagine that someone wanted to build something like dbt inside the blueprints framework - i.e. embed jinja-templated SQL inside blueprints. They'd have trouble doing so if all strings are automatically jinja-ized.

Hmm, I almost wonder if we should have a type that explicitly disables this/opt-out. From the user point of view there isn't a clear differentiator of what fields I can use jinja in vs not (even editor schema/autocomplete won't help much there). If we go with opt-in, I think the much more common case is going to be that you run into a field that for whatever reason forgot to opt in (in Dagster library code or from your data platform team) and get frustrated that you can't put env vars there.

**Comment by sryza** [comment]
Are there other use cases for this that we can think of than secrets?

**Comment by benpankow** [comment]
> Are there other use cases for this that we can think of than secrets?

Environment configuration (e.g. getting branch deployment ID or dagster deployment ID, varying behavior in a test context), other non-secret credentials (such as username, schema name, database name etc).

**Pull request closed without merging**
