### PR TITLE
[docs] - [definitions] Code location concept page 

### PR DESCRIPTION
**Pull request by erinkcochran87**
This PR:

- Fleshes out the Code locations concept page ([Preview](https://dagster-git-erin-definitions-code-location-concept-elementl.vercel.app/concepts/code-locations))
- Removes `Repositories and Workspaces` from the sidenav
- Adds `Code locations` to the sidenav

### CODE REVIEW

**Comment by erinkcochran87** [comment]
@yuhan @schrockn I think there's still more work to be done on this, but I wanted to pass it over to get a headstart on feedback. See the PR description for deets + a preview link. I left some comments on the Vercel preview as well, especially for things that need more info or input.

**Comment by yuhan** [comment]
looking great! i left a few comments in the preview

**Review by erinkcochran87 — COMMENTED** [review]
@yuhan @schrockn - this is ready for you again!

**Comment by yuhan** [comment]
commented

**Review by schrockn — CHANGES_REQUESTED** [review]
popping back in your queue for last vercel comments

**Review by schrockn — CHANGES_REQUESTED** [review]
I made some vercel comments that need resolving. Almost there!

**Review by schrockn — APPROVED** [review]
yay

**Pull request merged**
