### PR TITLE
fix: update contributing documentation

### PR DESCRIPTION
**Pull request by piotrmarczydlo**
## Summary & Motivation
[Contributing](https://docs.dagster.io/community/contributing) 6 days ago there was [update of](https://github.com/dagster-io/dagster/commit/9a85245c18254e20b4c14d0820c04fcebfdb7079) ipython to 8.23.0 which [requires](https://github.com/ipython/ipython/blob/main/pyproject.toml#L23) mentioned python version.

## How I Tested These Changes
installed env from zero

### CODE REVIEW

**Comment by piotrmarczydlo** [comment]
@tacastillo here you go :)

**Comment by tacastillo** [comment]
Thanks for doing this!

CI for PRs from community members needs to be manually kicked off from the team, so I just started it

I highly doubt this will break CI, but gonna way wait on approving until CI passes just in case!

**Comment by piotrmarczydlo** [comment]
is there anything I can do? Looks like Vercel issue

**Review by tacastillo — APPROVED** [review]

**Comment by tacastillo** [comment]
@piotrmarczydlo nope! don't worry about that! approved and merged. thanks for contributing!

**Pull request merged**
