### PR TITLE
docs: make sidenav sticky [DREL-329]

### PR DESCRIPTION
**Pull request by yuhan**
### Summary & Motivation
make sidenav + search bar sticky
refactor right nav code to remove duplicates

### How I Tested These Changes
before:
Screen Shot 2022-06-09 at 4 19 08 PM

after: https://dagster-3derweoxm-elementl.vercel.app/getting-started
Screen Shot 2022-06-09 at 4 19 16 PM

### CODE REVIEW

**Comment by yuhan** [comment]
Current dependencies on/for this PR:
* master
  * **PR #8310** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8310" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/8310?utm_source=stack-comment).

**Review by erinkcochran87 — COMMENTED** [review]
I am *so* excited about this. :tada:

Is it possible to have the sidenav scroll when its contents exceed the current page height, similar to what the on-page nav does? Other than this, I think it works perfectly!

**Comment by yuhan** [comment]
@erinkcochran87 mind taking another look?

https://user-images.githubusercontent.com/4531914/173131855-b90fd343-92da-46cb-9341-e8610bd81835.mov

**Review by erinkcochran87 — APPROVED** [review]
Looks great!

**Pull request merged**
