### PR TITLE
Add apidocs for PartitionKeyRange

### PR DESCRIPTION
**Pull request by clairelin135**
Existing context methods (`context.partition_key_range` etc.) return `PartitionKeyRange`s, but there are no existing apidocs.

This PR adds apidocs for PartitionKeyRange. It also fixes an outdated reference to `context.asset_partition_key_range`, which has since been deprecated.

### CODE REVIEW

**Comment by clairelin135** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16343** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16343" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16343?utm_source=stack-comment).

**Review by erinkcochran87 — COMMENTED** [review]
Thoughts on adding an example? One of the most frequent pieces of feedback I hear about our API docs is that they lack examples. I think it's good practice to have at least one, even if it seems like something really simple.

**Comment by clairelin135** [comment]
@erinkcochran87 Added an example!

**Review by erinkcochran87 — COMMENTED** [review]
🎉 Thanks @clairelin135! This lgtm - I'll leave it to others to stamp on code/correctness.

**Review by OwenKephart — APPROVED** [review]
nice 👍

**Pull request merged**
