### PR TITLE
Add community meeting graph-backed asset example

### PR DESCRIPTION
**Pull request by clairelin135**

### CODE REVIEW

**Comment by sryza** [comment]
@clairelin135 I see that this is marked as a Draft - are there particular changes you're planning to make?

**Comment by clairelin135** [comment]
@sryza nope--mistakenly marked this as a draft. It's ready for review

**Review by sryza — CHANGES_REQUESTED** [review]
Currently, for historical reasons, the "software_defined_assets" example folder refers to this particular example: https://docs.dagster.io/guides/dagster/software-defined-assets. We should probably rename that folder to something like "software_defined_assets_pandas_pyspark", though you don't need to do that unless you feel motivated.  A new example should get its own folder though.

**Review by sryza — APPROVED** [review]
This looks great

**Pull request merged**
