### PR TITLE
Add syntax highlighting to metadata markdown in dagit

### PR DESCRIPTION
**Pull request by smackesey**
### Summary & Motivation

When a language-specified code block is inside a `MarkdownMetadataValue`, the code block is now rendered with syntax highlighting.

A user requested this functionality [here](https://dagster.slack.com/archives/C01U954MEER/p1666916513841459).

This required adding the `rehype-highlight` and `highlight.js` package, as well as updating some other markdown-related packages.

### How I Tested These Changes

Loaded this repo and observed syntax highlighting:

```python
from dagster import MetadataValue, asset, repository

CODE = """
print("Hello, world!")
"""

@asset(
    metadata={
        "python": MetadataValue.md(f'Testing testing testing\n\n```python\n{CODE}\n```\n\nTesting testing testing'),
    }
)
def alpha():
    return 100

@repository
def repo():
    return [alpha]
```

image

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10371** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10371" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10371?utm_source=stack-comment).

**Review by hellendag — APPROVED** [review]
Seems fine to me -- can you add a screenshot of an example?

**Review by hellendag — CHANGES_REQUESTED** [review]
Ah, looks like there are some build failures we'll need to iron out.

**Comment by smackesey** [comment]
>Ah, looks like there are some build failures we'll need to iron out.

Just glancing over the Jest output, I think this is from importing a `css` file directly in JS (I imported the highlight.js css file in `js_modules/dagit/packages/ui/src/components/Markdown.tsx`. Is there an alternative place I should import this?

**Comment by smackesey** [comment]
Rendered moot by https://github.com/dagster-io/dagster/pull/13092

**Pull request closed without merging**
