### PR TITLE
rename several internal submodules

### LINKED ISSUE #4439: Dagster getting started code raises immediate issues with PyRight type checker
## Summary
This is not exactly a "bug", but it is something that isn't working correctly in concert with commonly used dev tools.

Dagster's type annotations are (preventably) incompatible with the popular PyRight language server, and the problem manifests itself in the first code block of the tutorial. AFAICT there are two problems:

1. `dagster.core.definitions` both has `from .decorators import solid` and `from .solid import ...`. This introduces ambiguity into the value assigned to `solid` in `dagster.core.definitions`. It is difficult for static analyzers to determine the type of `solid` under these circumstances, and different ones make different assumptions. PyRight's assumption is incorrect-- it thinks `solid` is the `dagster.core.definitions.solid` submodule, when the runtime value is the imported decorator function. This problem is discussed with PyRight's maintainer [here](https://github.com/microsoft/pyright/issues/2140) and in a Slack thread with a Dagster dev [here](https://dagster.slack.com/archives/C01U954MEER/p1627923215076700).

One can work around the above problem by importing `solid` directly from `dagster.core.definitions.decorators` instead of `dagster`. However, the result causes another problem.

2. The `solid` decorator can either function as a "direct" decorator (with no args) or take args. Thus the return value of `solid` is of type `_Solid | SolidDefinition`. When used directly (no args), the result is a `SolidDefinition`, when it gets args the result is a `_Solid`. But PyRight does not understand the conditions that will lead to the return of either type:

```python
@solid
def get_name():  # get_name is a `SolidDefinition` but PyRight thinks it's `SolidDefinition | _Solid`
    return 'dagster'
```

This leads PyRight to complain when you try to call `get_name` in another solid, because you are calling it as a `SolidDefinition` but PyRight thinks maybe it is a `_Solid`:

```python
@pipeline
def hello_pipeline():
    hello(get_name())  # Error: Argument missing for parameter "fn"
```

There are two possible workarounds.

A. You can always invoke the decorator as `@solid()` instead of `@solid`. This gets rid of the error, but for reasons I don't understand this makes the type of the decorated function `SolidDefinition | Any`. Not sure exactly what effect the extra `Any` has or why it's there.

B. You can explicitly cast each decorated solid to a `SolidDefinition`, but this is a PITA/extra complexity/highly undesireable.

## Reproduction

Just load the code-block in Dagster [Getting Started](https://docs.dagster.io/getting-started) into an editor running PyRight and observe the errors:

```python
from dagster import pipeline, solid


@solid
def get_name():
    return "dagster"


@solid
def hello(context, name: str):
    context.log.info(f"Hello, {name}!")


@pipeline
def hello_pipeline():
    hello(get_name())
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by smackesey**
Renames some internal modules to avoid naming collisions with exports. This is a subtle issue, but if a submodule has the same name as an export from its parent, then you end up with an unstable referent for that name that is particularly problematic for static analysis. There were several places in the Dagster codebase where this collision was occurring, I renamed the modules accordingly:

- All submodules of `dagster.core.definitions.decorators` (e.g. `dagster.core.decorators.solid` conflicted with the solid export from `dagster.core.decorators`, was renamed to `dagster.core.decorators.solid_decorator`)
- `dagster.core.definitions.reconstructable` > `dagster.core.definitions.reconstructable_definition`
- `dagster.core.asset_defs.asset` > `dagster.core.asset_defs.assets`

Broken out into its own PR from #7017.

Fixes #4439

## Test Plan

Existing tests.

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7134** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/7134" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by alangenfeld — COMMENTED** [review]
is there any way to put a test in place to prevent future cases?

**Comment by smackesey** [comment]
I think a test would be tricky, but a `pylint` rule might work-- will look into it, but I think any preventative solution should be in a separate PR.

**Comment by smackesey** [comment]
Updated the "toys" imports to be top-level and changed to `reconstruct.py`.

>If I understand correctly, an alternative fix for the some of the decorator files would be to remove the entries in core/definitions/__init__.py right?

Did you mean `core/definitions/decorators/__init__.py`? It is true that the problem would be solved if we removed those (since there would no longer be an export to collide with the submodule name). But IMO this is not a great solution because then you either always have to import the decorator directly from the deep submodule where it's defined, or you have to unintuitively "skip a level" in imports (e.g. importing values from `definitions.decorators.XXX` directly into `definitions`).

Removing the entries from `core/definitions/__init__.py` would not have the same effect, because there would still be a collision between e.g. `solid` the decorator and `solid` the submodule in `core.definitions.decorators`.

>The duplication of "decorator" in core/definitions/decorators/job_decorator.py feels rough to me, so i think alternatives are worth considering if valid.

Agree it's not ideal. I tried to think of other options but nothing jumped out as particularly attractive. Also:

- The only place we ever have to reference these submodules is when importing into `decorators/__init__.py`.
- It matches a pattern already seen in definitions, with several submodules named `X_definition`.

> It's also unclear to me why asset_defs diverges from the general organization pattern of definitions.

Agree, I assume this is some kind of historical artifact of it previously being experimental. But IMO it should be folded into the general structure there are no objections. This PR would be a reasonable place to do it.

**Comment by rexledesma** [comment]
@smackesey there are some API docs that weren't updated as part of this: e.g. https://github.com/dagster-io/dagster/blob/ff8d594386356b77e4ab42666ef6c19b49dc6d5b/python_modules/dagster/dagster/core/definitions/reconstruct.py#L280. Wish there was a way to catch these with the linter

**Comment by smackesey** [comment]
@rexledesma Thanks for the pointer, yeah I was assuming docs errors were caught in the docs build BK step but that's not true of docstrings, will fix.

**Pull request merged**
