### PR TITLE
fix(dbt): yield `AssetMaterialization` when invoking `DbtCliResource` in ops

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
Resolves https://github.com/dagster-io/dagster/issues/17292.

## How I Tested These Changes
pytest

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17405** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17405" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17405?utm_source=stack-comment).

**Review by OwenKephart — APPROVED** [review]
nice

**Comment by rexledesma** [comment]
@benpankow As a heads up, the implementation for https://github.com/dagster-io/internal/issues/7163 will need to be revisited once this lands.

**Review by PedramNavid — APPROVED** [review]
nice

**Pull request merged**
