### PR TITLE
fix asset_partition_key_range and has_asset_partition for load_asset_…

### PR DESCRIPTION
**Pull request by sryza**
…value

### Summary & Motivation

reported on Slack: https://dagster.slack.com/archives/C01U954MEER/p1669069865850209

### CODE REVIEW

**Comment by Nintorac** [comment]
I copy and pasted these files into my site packages and am still getting an error (is there a way to pip install dagster from git? I tried `pip install git+https://github.com/dagster-io/dagster@2d8b69b41edc7a1d11740baf965633f226ae0169`)

```
---------------------------------------------------------------------------
DagsterInvariantViolationError            Traceback (most recent call last)
/home/ubuntu/paper/notebooks/classifier_analysis.py in line 2
      [16](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=15) #%%
----> [17](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=16) best_model_path = paper_title_repo.load_asset_value(
      [18](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=17)     AssetKey("model"), 
      [19](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=18)     partition_key='dev_medium'
      [20](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=19) )
      [21](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=20) loader = paper_title_repo.load_asset_value(
      [22](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=21)     AssetKey("validate_loader"), 
      [23](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=22)     partition_key='dev_medium'
      [24](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=23) )
     [26](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=25) # best_model_path = "/home/ubuntu/.dagster/storage/model_store/model/dev_medium/epoch=30-step=18290.ckpt"
     [27](file:///home/ubuntu/paper/notebooks/classifier_analysis.py?line=26) # loader_path = "~/.dagster/storage/validate_loader/dev_medium"

File ~/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition.py:1425, in RepositoryDefinition.load_asset_value(self, asset_key, python_type, instance, partition_key)
   [1422](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition.py?line=1421) from dagster._core.storage.asset_value_loader import AssetValueLoader
   [1424](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition.py?line=1423) with AssetValueLoader(self._assets_defs_by_key, instance=instance) as loader:
-> [1425](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition.py?line=1424)     return loader.load_asset_value(
   [1426](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition.py?line=1425)         asset_key, python_type=python_type, partition_key=partition_key
   [1427](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition.py?line=1426)     )

File ~/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py:114, in AssetValueLoader.load_asset_value(self, asset_key, python_type, partition_key)
     [94](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py?line=93) io_manager_config = get_mapped_resource_config({io_manager_key: io_manager_def}, {})
     [96](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py?line=95) input_context = build_input_context(
     [97](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py?line=96)     name=None,
     [98](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py?line=97)     asset_key=asset_key,
   (...)
    [111](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py?line=110)     else None,
    [112](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py?line=111) )
--> [114](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/asset_value_loader.py?line=113) return io_manager.load_input(input_context)

File ~/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py:171, in UPathIOManager.load_input(self, context)
    [161](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=160)     return check.failed(
    [162](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=161)         f"Received `{context.dagster_type.typing_type}` type "
    [163](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=162)         f"in input of DagsterType {context.dagster_type}, "
   (...)
    [167](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=166)         f"should not be a typing.Dict, but a single partition type."
    [168](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=167)     )
    [170](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=169) # we are dealing with a single partition of a non-partitioned asset
--> [171](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=170) paths = self._get_paths_for_partitions(context)
    [172](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=171) assert len(paths) == 1  # should only have 1 partition
    [173](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=172) path = list(paths.values())[0]

File ~/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py:92, in UPathIOManager._get_paths_for_partitions(self, context)
     [86](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=85) if not context.has_asset_partitions:
     [87](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=86)     raise TypeError(
     [88](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=87)         f"Detected {context.dagster_type.typing_type} input type "
     [89](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=88)         f"but the asset is not partitioned"
     [90](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=89)     )
---> [92](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=91) partition_keys = context.asset_partition_keys
     [93](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=92) asset_path = self._get_path_without_extension(context)
     [94](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=93) return {
     [95](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=94)     partition_key: (asset_path / partition_key).with_suffix(self.extension)
     [96](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=95)     for partition_key in partition_keys
     [97](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/storage/upath_io_manager.py?line=96) }

File ~/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py:352, in InputContext.asset_partition_keys(self)
    [345](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=344) @public  # type: ignore
    [346](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=345) @property
    [347](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=346) def asset_partition_keys(self) -> Sequence[str]:
    [348](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=347)     """The partition keys for input asset.
    [349](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=348) 
    [350](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=349)     Raises an error if the input asset has no partitioning.
    [351](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=350)     """
--> [352](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=351)     return self.asset_partitions_def.get_partition_keys_in_range(self.asset_partition_key_range)

File ~/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py:275, in InputContext.asset_partitions_def(self)
    [273](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=272) """The PartitionsDefinition on the upstream asset corresponding to this input."""
    [274](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=273) asset_key = self.asset_key
--> [275](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=274) result = self.step_context.pipeline_def.asset_layer.partitions_def_for_asset(asset_key)
    [276](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=275) if result is None:
    [277](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=276)     raise DagsterInvariantViolationError(
    [278](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=277)         f"Attempting to access partitions def for asset {asset_key}, but it is not partitioned"
    [279](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=278)     )

File ~/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py:286, in InputContext.step_context(self)
    [283](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=282) @property
    [284](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=283) def step_context(self) -> "StepExecutionContext":
    [285](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=284)     if self._step_context is None:
--> [286](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=285)         raise DagsterInvariantViolationError(
    [287](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=286)             "Attempting to access step_context, "
    [288](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=287)             "but it was not provided when constructing the InputContext"
    [289](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=288)         )
    [291](file:///home/ubuntu/.conda/envs/paper/lib/python3.10/site-packages/dagster/_core/execution/context/input.py?line=290)     return self._step_context

DagsterInvariantViolationError: Attempting to access step_context, but it was not provided when constructing the InputContext
```

**Comment by sryza** [comment]
Mmm, you are right - added a more comprehensive test.

**Comment by Nintorac** [comment]
Awesome! thanks :)

**Review by OwenKephart — APPROVED** [review]

**Comment by Nintorac** [comment]
Similar issue, lines 103-108 does not forward the `partition_key`, maybe can sneak into this PR as well?

**Pull request merged**
