### PR TITLE
Adding SchedulingPolicy to asset API via metadata key

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

We are going to start working on Declarative Scheduling (DS) this week so adding some groundwork here. Adding `SchedulingPolicy` and passing it via metadata as to not pollute the public API surface

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by schrockn** [comment]
* **#20934** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20934?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by OwenKephart** [comment]
Is this pattern necessary? An alternative would be to pass it inside of the existing `AutoMaterializePolicy` object, which is what I did so that we could test custom `asset_condition`s. Technically, that's polluting the public API surface at least a little bit (as the constructor to AutoMaterializePolicy is public), but that seems fairly minor compared to adding an arg to `@asset` or something like that.

**Comment by schrockn** [comment]
I think it is a quite valid use of the metadata API to stash objects on it in this fashion. Very lightweight way for integratios to attach information to assets that they can access later. `dagster-dbt` does this and I think it is a good approach.

The right answer here IMO is change this so that the code feels more first-class @OwenKephart

**Review by OwenKephart — COMMENTED** [review]
I guess the main difference between this and the dbt usage of the metadata system is that dbt is purely making the attached metadata available when executing the underlying op, and it does not matter if that data gets erased when transferring that information to the host (in fact, you wouldn't want for your entire manifest file to get serialized and passed to the host to begin with)

In the scheduling policy case, because the host is responsible for executing the given scheduling policy, it needs to survive the metadata serialization process, which this would not, as far as I'm aware.

i.e. if you tried to build a RemoteAssetGraph with this scheme, no asset would have a SchedulingPolicy

**Pull request closed without merging**
