### PR TITLE
use correct return types for some partition key methods on context

### PR DESCRIPTION
**Pull request by jamiedemaria**
## Summary & Motivation

The `asset_partition_key_for_input` method on the context can return a `MultiPartitionKey` when an asset has a multi partition definition. However, the type signature for the method only says a string can be returned. This makes pyright unhappy. 

This PR updates the return annotation so that `context.asset_partition_key_for_input("asset").keys_by_dimension` doesn't cause the linter to complain

### CODE REVIEW

**Review by clairelin135 — CHANGES_REQUESTED** [review]
It's annoying, but changing the type signature to include `MultiPartitionKey` would break users' type checks. For that reason we didn't originally add multipartition keys to the type annotation.

Sandy and I discussed adding another context method (`context.partition_key_for_dimension`) to bridge this gap, though wondering if you have thoughts on that given the move toward method consolidation.

**Comment by jamiedemaria** [comment]
oh interesting. I was running into type check issues because there was no `MultiPartitionKey` return type annotation. Are we just putting pyright ignores for those?

**Comment by clairelin135** [comment]
Odd... I don't think that I've run into the type check issues before. But agree that we should just add pyright ignores for those if they don't already exist

**Comment by jamiedemaria** [comment]
cool, will close this PR then. Is there a path to eventually updating this signature? it would be really nice if it included the MultiPartitionKey at some point

**Comment by clairelin135** [comment]
I think if we did update the signature, we'd have to just do it at a major release. I think we'd need to decide between:
- updating the signatures to contain multi partition keys, which adds more work for the user to check whether the return object is a multipartition key or not
- adding new multipartition specific context methods, which adds additional surface area and potential confusion for the user

Given the move toward consolidation I'd lean toward the first option, but would want to gather other opinions

**Pull request closed without merging**
