### PR TITLE
AssetSubset -> EntitySubset

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

This converts the AssetSubset class into a generic EntitySubset class. This allows us to create subsets of arbitrary types without needing to create new subclasses, while at the same time allowing us to indicate via the type system what kind of EntitySubsets are allowed for certain methods / properties. For example, AssetGraphSubset currently only supports EntitySubset[AssetKey] (although this will likely change in the future).

## Changelog [New | Bug | Docs]

NOCHANGELOG

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23907?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23907?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#23905** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23905?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23904** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23904?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23843** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23843?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#23842](https://github.com/dagster-io/dagster/pull/23842) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23842?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — CHANGES_REQUESTED** [review]
I'd like to discuss this today as well. In particular I'd like to understand how we are going to handle partitioning across all entities.

**Comment by OwenKephart** [comment]
@schrockn do you have additional thoughts regarding the partition bit? my basic thesis is that in the long run, any entity should be able to be partitioned, but that this capability does not need to be implemented immediately (i.e. with AssetChecks).

The natural result is that all EntitySubset[AssetCheckKey] will be unpartitioned for now, but all code written to process EntitySubset[AssetCheckKey] will be written in a way that can handle partitioned versions in the future, which should make the process of making AssetChecks partitioned much easier.

**Review by schrockn — APPROVED** [review]

**Comment by OwenKephart** [comment]
### Merge activity

* **Sep 19, 12:04 PM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/23907).

**Pull request merged**
