### PR TITLE
[DA-Internals][2/n] AssetsDefinition updates

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

As title. Here, we immediately convert input AutoMaterializePolicy objects to AutomationConditions.

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22889?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22890** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22890?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#22889** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22889?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#22888** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alangenfeld — APPROVED** [review]
should we be emitting deprecation warnings on use of the old field at all? or adding that later?

**Comment by OwenKephart** [comment]
@alangenfeld good call re: deprecation warnings -- I think i'll end up adding those later so that they go out exactly with the 1.8 release (whereas the current PRs are safe to land before that point because they're backwards-compatible)

**Comment by OwenKephart** [comment]
### Merge activity

* **Jul 9, 6:59 PM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22889).

**Pull request merged**
