### PR TITLE
Bump our buildkite image to use Node 21

### PR DESCRIPTION
**Pull request by jmsanders**
## Summary & Motivation

Jest on Node16+ and <Node21 has a bug with how it handles ESM modules that causes test runs not clean up their memory leading to 3GB of RAM usage for running dagster cloud jest tests.

### CODE REVIEW

**Comment by salazarm** [comment]
We'll need to add node21 as an acceptable "engine" here to avoid failures in buildkite. https://github.com/dagster-io/internal/blob/c0e0810ef7625d27ae71c75d92c3162cb706dc6e/dagster-cloud/js_modules/app-cloud/package.json#L143

**Comment by salazarm** [comment]
Need to add node 21 here: https://github.com/dagster-io/dagster/blob/50ba4abccbbf888ac0f89d21bc5ecd61d88619b9/js_modules/dagster-ui/package.json#L26

**Comment by salazarm** [comment]
i believe you need to point this branch to the internal branch and the internal one to this one to get buildkite to pass

**Comment by jmsanders** [comment]
The specific thing I'm working on right now is getting tox to properly install. The latest build silently failed on py3.11 and py3.12 so I'm going through the (very long) build process again.

**Review by alangenfeld — APPROVED** [review]

**Pull request merged**
