### PR TITLE
Use fs_io_manager for AssetGroup.materialize and execute_in_process

### PR DESCRIPTION
**Pull request by clairelin135**
Modifies `execute_in_process` to use `fs_io_manager` as the default IO manager for asset jobs.

Addresses https://github.com/dagster-io/dagster/issues/8128

### CODE REVIEW

**Review by sryza — COMMENTED** [review]
Imagine a dystopian future where we want to allow constructing jobs that include some assets but then also include some free-floating ops after. What behavior would we want in that case? Is there some possibility it would make the most sense for `execute_in_process` to default to the in-mem IO manager, but for `materialize` to efault to the FS one?

**Comment by clairelin135** [comment]
@sryza Ok, thats fair. I've adjusted `materialize` to use the `fs_io_manager` instead. I think this is ready for review!

**Comment by sryza** [comment]
`_called_from_materialize` here is a little gnarly. I think that the changes we're making to asset jobs might make this less necessary, because you basically won't be able to call `execute_in_process` on an asset job.

**Comment by clairelin135** [comment]
@sryza Ok, gotcha. I will leave this open for now in case if there are any changes needed later, and close otherwise in a few days.

**Pull request closed without merging**
