### PR TITLE
[airlift] add script to rebuild readme from snippets

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Moves scripts to the `scripts` subdir, introduces small script to copy labeled snippets into the readme so we can ensure everything in the readme is under test.

### CODE REVIEW

**Comment by benpankow** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24036?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24036** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24036?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#24031** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24031?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — APPROVED** [review]
This is cool, but we need to make sure that we aren't reimplementing the docs site.

**Comment by benpankow** [comment]
agreed, worth moving to docs site sooner rather than later I think - but feel like it's a priority to keep the readme and actual tested code in sync otherwise we'll inevitably hit bugs as we iterate

**Comment by schrockn** [comment]
> agreed, worth moving to docs site sooner rather than later I think - but feel like it's a priority to keep the readme and actual tested code in sync otherwise we'll inevitably hit bugs as we iterate

oh 100% we should land this and its great, but I think ups the priority of getting it over

**Pull request merged**
