### PR TITLE
[docs] show snowflake resource w update api docs

### PR DESCRIPTION
**Pull request by jamiedemaria**
## Summary & Motivation
Noticed that pythonic snowflake resource never got added to the docs (oops). Also updates the doc strings to be more explicit about what connection objects are being returned in what circumstances

### CODE REVIEW

**Comment by jamiedemaria** [comment]
Current dependencies on/for this PR:
* master
  * **PR #14493** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14493" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14493?utm_source=stack-comment).

**Comment by erinkcochran87** [comment]
@jamiedemaria Same comment as the GCP PR ya have open - could you take a look at getting the Vercel preview to work? You may only have to pull in master and push it back to this branch to get it to work - that's the usual for me anyhow!

**Comment by jamiedemaria** [comment]
done! the changed page is wrong, here's the right link https://dagster-7rcvd9qt7-elementl.vercel.app/_apidocs/libraries/dagster-snowflake

**Review by erinkcochran87 — COMMENTED** [review]
Back to you! Left my comments on the preview.

**Review by erinkcochran87 — APPROVED** [review]
The code looks good to me, but I'm not seeing the changes on the preview. I'm not sure if this is something that needs to be addressed before merging, but I'm stamping this to unblock ya.

**Comment by jamiedemaria** [comment]
ok thanks for pointing that out. i'll make sure the preview shows correctly before merging just to be sure. not sure what's going on there...

**Comment by erinkcochran87** [comment]
I'm not sure either - I'm not sure if it's something with the build or if Vercel is being cranky. -.-

**Comment by jamiedemaria** [comment]
@erinkcochran87  the vercel preview is still showing the old code, even after rebasing and running the build a couple times. Any ideas on what else i can try?

**Comment by yuhan** [comment]
maybe submit another pr just to trigger the preview?

**Comment by jamiedemaria** [comment]
good idea. i think i need to close this one then. see you in the new pr!

**Pull request closed without merging**
