### PR TITLE
Feat/run retry enhancements

### PR DESCRIPTION
**Pull request by jobicarter**
## Summary & Motivation

I need the ability to only restart jobs that fail due to a timeout when `STARTING`. 

The specific situation I'm solving for is on ecs fargate when an az encounters capacity issues, code location runs will time out during STARTING and fail in dagster when the run's ecs task starts and fails without launching a container (assuming timeouts are enabled). We need to retry to see if the job can launch in another az that has capacity. We also occasionally have issues pulling docker images (resulting in a timeout) where a retry would be useful.

Jobs deployed to the cluster I support cannot all be restarted from arbitrary points in the case of infra or other failures. But restarting from a timeout is safe, since the code never ran. The current `retry_on_asset_or_op_failure` configuration isn't sufficient to guarantee that a job won't restart for other reasons (e.g., unexpected termination / ecs task is killed).

To preserve the interface pattern established by `retry_on_asset_or_op_failure`, we can enumerate all run failure reasons and similarly map them to configs.

This PR adds a `START_TIMEOUT` RunFailureReason, and updates the run monitor to fail jobs that time out with `START_TIMEOUT`. Then, all RunFailureReasons are mapped to `retry_on` configs, and run retry logic is updated to only retry jobs if the failure reason matches a corresponding config set to `True`.

There are other ways this could be done, I welcome any discussion here, and ended up doing more than I'd wanted to, in order to solve for "only restart jobs that fail due to a timeout when `STARTING`".

## How I Tested These Changes
I have written tests for the new configurations to validate expected retry behavior. Wasn't sure how to run these locally, hoping they will pass.. or that the PR CI will let me know what fails so they can be fixed. Also would very much appreciate any input, adjustments, thoughts from your side!

I have deployed this modified code to ecs and ran some manual validations related to `START_TIMEOUT`, `STEP_FAILURE`, and `UNEXPECTED_TERMINATION`. I know how to trigger these with infra/code, but not sure on the others. Additional testing could be done, but I'm hoping to lean on the integration tests.

ECS was deployed with the following configuration:
```
run_retries:
  enabled: true
  max_retries: 3
  retry_on_unexpected_termination: false
  retry_on_run_exception: false
  retry_on_asset_or_op_failure: false
  retry_on_job_initialization_failure: false
  retry_on_start_timeout: true
  retry_on_unknown_failure: false

run_monitoring:
  enabled: true
  start_timeout_seconds: 45
  cancel_timeout_seconds: 45
  poll_interval_seconds: 5
```

I ran a no-op job and it succeeded and did not restart.

For `STEP_FAILURE` / `retry_on_asset_or_op_failure` validation I ran a job that has an op which fails (`exit(1)` in code).
The job fails and does not restart. When setting the tag `dagster/retry_on_asset_or_op_failure = true`, it fails and then retries 3 times. When setting the `dagster/retry_on_asset_or_op_failure = false`, it fails and does not retry.

For `START_TIMEOUT`, I ran a no-op job and stopped the ecs task before the container spun up. It failed with a timeout, retried, and ran the retry job to completion. 

For `UNEXPECTED_TERMINATION`, I ran a job and stopped the ecs task while it was running. Dagster logged the infra error, and did not retry.

## Misc Points
An outstanding question is whether it would make sense to rename `retry_on_asset_or_op_failure` to match the other configs that are named after the RunFailureReasons. I didn't do that since it wouldn't be backward compatible.

I'm not sure if [this](https://github.com/dagster-io/dagster/pull/22635/files#diff-cf4c7be847fd482bca17afeac3b3bd5526a13b321b9d2ccd471edbbc83579648R105) is a good idea?
```
if failure_reason is None:
                failure_reason = RunFailureReason.UNKNOWN.value
```

The tests are pretty long and redundant with so many new configs, there's probably a better way.

### CODE REVIEW

**Comment by jobicarter** [comment]
@gibsondan, your input / thoughts here would be great, seems you're actively working on this functionality!

**Comment by gibsondan** [comment]
Hi @jobicarter - thanks for sending this out.  I think the use case here is 100% reasonable, but the other angle that I'd like to explore with here is what it would take for you to be able to write a run status sensor that accomplishes this goal instead of augmenting the built-in run retry feature. In situations like this where there are a lot of potential customizations you might want to apply, we generally bias towards supporting them through giving ways for you to write code vs. going in more of a rule engine direction. With rule engines you end up with a ton of different flags and customization options, and it takes PRs like this to support them every time a new one needs to be added - vs. a sensor which can be (relatively) arbitrarily customized. (Arguably this argument could have applied to the original retry_on_asset_or_op_failure tag too, but this would increase the number of possible configurations quite a bit compared to that)

I think a run failure sensor is very close to being able to handle this use case by scanning each failed run, checking its failure reason, and potentially yielding a RunRequest for the same job (once you add the new run failure reasons, which seems totally reasonable to me). A potentially relevant PR here is https://github.com/dagster-io/dagster/pull/12610 which was sent out to address a similar use case (writing a sensor that could retry arbitrary jobs in the code location without having to attach it to each job that might need to be replied) but never ended up getting landed. We could potentially bring that back if it would unblock you here, let me know your thoughts.

**Comment by jobicarter** [comment]
Thanks for getting back, definitely appreciate the review and conversation :)

Glad you're on board with the START_TIMEOUT, that should make things cleaner for any path forward. I'm familiar with the sensor as an option, and it's the current fall-back plan.

In looking to enable a "platform maintainer/provider" vs "client/dev/data engineer" operational model/division of responsibility, I'd hoped there might be an option (even if this implementation isn't it) to have this functionality in the platform vs go the sensor route. Since my specific need is really to solve for infra provisioning retries, and not any actual user code or runtime failure issues, a sensor approach seemed like pushing platform patches into userspace, vs providing a resilient baseline.

But, I can understand completely not wanting this full config map here.. I had also considered grouping failure reasons into provisioning, user code, and running infra type categories, but ended up just pushing the current pattern to a too extreme end :) Not sure if the config groups would be less maintenance over time, but it would be a cleaner interface.

Another option I considered was a root level `run_provisioning_retries` config, independent from `run_retries`. This would allow us to diverge from the `retry_on_asset_or_op_failure` flag convention, and directly address the need for retrying infra provisioning. `run_retries` disabled, but allow retries when attempting to _initiate_ a run via `run_provisioning_retries`.

Let me know if any of these alternatives seem somewhat palatable, and you still think solving outside of core would be best.

Otherwise, I can more seriously investigate the sensor solve. I did see https://github.com/dagster-io/dagster/discussions/7257#discussioncomment-2481403 which looks to have a good example to start from. I think needing to attach the jobs to the sensor wouldn't be a _blocker_, but https://github.com/dagster-io/dagster/pull/12610 would definitely make it more pluggable/viable as a bit of infra-maintained code that devs can inject into their code locations without needing to explicitly attach it to their jobs or otherwise modify their code. I'll need to investigate a bit more on this one.

**Comment by gibsondan** [comment]
to start, what do you think about splitting the addition of the START_TIMEOUT failure reason into its own smaller PR? That seems totally uncontroversial and would open up some of the other options, sensor or not.

**Comment by jobicarter** [comment]
Opened up https://github.com/dagster-io/dagster/pull/22684 with just those couple commits, and squashed em together. Adds the reason and also the code to fail timed out jobs with the reason.

**Comment by jobicarter** [comment]
Thanks for merging https://github.com/dagster-io/dagster/pull/22684! Will start work on a sensor based solution since that's within reach, and should be a bit simpler with START_TIMEOUT. (Sorry for the slow communication, was out for a bit).

Once that gets rolling and I have a chance to engage with devs a bit more, I should have a better understanding of how helpful https://github.com/dagster-io/dagster/pull/12610 would be, and I can let you know. I think it would definitely be an improvement for use cases like this, just unsure of the burden that attaching jobs to the sensor really imposes.

I figure you're still leaning to this being solved in a sensor? I can close out this PR, and move some of this conversation into a discussion or issue if we want to keep this on the radar. Let me know what you think.

**Pull request closed without merging**
