### PR TITLE
[1/n][dagster-tableau] Add dagster-tableau package

### PR DESCRIPTION
**Pull request by maximearmstrong**
## Summary & Motivation

Adds a barebones `dagster-tableau` package
Set up not to publish right now (no version.py)

## How I Tested These Changes

BK with additional tests

## Changelog [New | Bug | Docs]

> Replace this message with a changelog entry, or `NOCHANGELOG`

### CODE REVIEW

**Comment by maximearmstrong** [comment]
* **#24186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — APPROVED** [review]

**Comment by maximearmstrong** [comment]
* **#24545** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24545?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24387** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24385** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24385?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24332** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24332?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24322** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24322?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24233** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24233?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24190** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by maximearmstrong** [comment]
* **#24545** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24545?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24387** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24385** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24385?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24332** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24332?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24322** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24322?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24233** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24233?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24190** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by maximearmstrong** [comment]
* **#24545** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24545?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24387** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24385** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24385?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24332** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24332?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24322** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24322?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24233** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24233?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24190** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by maximearmstrong** [comment]
* **#24545** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24545?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24387** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24385** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24385?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24332** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24332?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24322** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24322?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24233** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24233?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24190** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Pull request merged**
