### PR TITLE
[docs][quick] SSHResource api docs

### PR DESCRIPTION
**Pull request by jamiedemaria**

### CODE REVIEW

**Comment by jamiedemaria** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17920?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17920?utm_source=stack-comment).

**Review by erinkcochran87 — COMMENTED** [review]
Did the Sphinx scripts get re-run as part of this? I don't see the updates on the preview.

**Comment by jamiedemaria** [comment]
I believe i did, but must not have committed the changes. Now I'm getting a series of errors that look like they're from pipes

```
Docstring not found for object.__dict__. All public methods and properties must have docstrings.
Docstring not found for object.__enter__. All public methods and properties must have docstrings.
Docstring not found for object.__exit__. All public methods and properties must have docstrings.
Docstring not found for object._instance. All public methods and properties must have docstrings.
Docstring not found for object._write_message. All public methods and properties must have docstrings.
Docstring not found for object.__doc__. All public methods and properties must have docstrings.
Docstring not found for object.__doc__. All public methods and properties must have docstrings.
Docstring not found for object.__dict__. All public methods and properties must have docstrings.
Docstring not found for object.__doc__. All public methods and properties must have docstrings.
Docstring not found for object.__dict__. All public methods and properties must have docstrings.
Docstring not found for object.__doc__. All public methods and properties must have docstrings.
Docstring not found for object.__dict__. All public methods and properties must have docstrings.
Docstring not found for object.__dict__. All public methods and properties must have docstrings.
Docstring not found for object.make_channel. All public methods and properties must have docstrings.
Docstring not found for object._upload_loop. All public methods and properties must have docstrings.
Docstring not found for object.buffered_upload_loop. All public methods and properties must have docstrings.
Docstring not found for object.flush_messages. All public methods and properties must have docstrings.
Docstring not found for object.upload_messages_chunk. All public methods and properties must have docstrings.
Docstring not found for object.write_message. All public methods and properties must have docstrings.
Docstring not found for object.upload_messages_chunk. All public methods and properties must have docstrings.
Docstring not found for object.load_context. All public methods and properties must have docstrings.
Docstring not found for object.open. All public methods and properties must have docstrings.
Docstring not found for object.write_message. All public methods and properties must have docstrings.
Docstring not found for object.write_message. All public methods and properties must have docstrings.
Docstring not found for object.is_dagster_pipes_process. All public methods and properties must have docstrings.
Docstring not found for object.load_context_params. All public methods and properties must have docstrings.
Docstring not found for object.load_messages_params. All public methods and properties must have docstrings.
Docstring not found for object.make_channel. All public methods and properties must have docstrings.
Docstring not found for object.upload_messages_chunk. All public methods and properties must have docstrings.
Docstring not found for object.load_context. All public methods and properties must have docstrings.
Docstring not found for object.get_opened_extras. All public methods and properties must have docstrings.
Docstring not found for object.make_channel. All public methods and properties must have docstrings.
```

they're happening in main too. is there a way to disable the API docstring check for a particular library so i can get these changes in while the pipes docs are written? @smackesey  you did some work with the requiring doc strings for all public methods right?

**Comment by jamiedemaria** [comment]
might also be this error? 
```
make: *** [json] Illegal instruction: 4
```

I'm not quite sure what's going on but i can't seem to build any docs locally, but master in buildkite looks fine

**Comment by jamiedemaria** [comment]
@erinkcochran87  I've been trying to fix my docs build for a couple weeks, but getting nowhere. Could you run the `apidoc-build` command for me and push the changes up?

**Pull request closed without merging**
