### PR TITLE
[ui] Upgrade Storybook, repair dependabot alerts

### PR DESCRIPTION
**Pull request by hellendag**
## Summary & Motivation

Upgrade Storybook to v8 to resolve some dependency issues, and handle a few others manually.

## How I Tested These Changes

Buildkite.

`yarn storybook` in both ui-core and ui-components, verify success.

`yarn why` to sanity check that packages flagged by dependabot have been updated.

### CODE REVIEW

**Comment by hellendag** [comment]
* **#22679** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22679?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hellendag and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by salazarm — APPROVED** [review]

**Comment by hellendag** [comment]
I think the Storybook build is ooming on the Vercel deployment, but I'm not sure why. I'll come back to this.

**Comment by salazarm** [comment]
Doesn't repro locally?

**Comment by hellendag** [comment]
Nope, it's fine locally. Not super fast, but fine.

**Pull request merged**
