### PR TITLE
Feat/add repository metadata

### PR DESCRIPTION
**Pull request by tnk-dev**
## Summary & Motivation

Implements a metadata dict for a code location, see https://github.com/dagster-io/dagster/issues/15090

What is missing is the UI implementation in `js_modules`.

### CODE REVIEW

**Comment by tnk-dev** [comment]
locally `python_modules/dagster/dagster_tests/core_tests/snap_tests/test_active_data.py` is failing and I don't know how the result comes about. Any ideas?

**Review by sryza — COMMENTED** [review]
Thanks for submitting this @tnk-dev!

I think you'll need to run 
```
pytest --snapshot-update ./python_modules/dagster/dagster_tests/core_tests/snap_tests/test_active_data.py
```
To update the relevant snapshot test

Also, these pyright complaints are coming up:
```
[2023-07-25T03:45:25Z] Running pyright for environment `master`...
[2023-07-25T03:45:25Z]   pyright --project=pyrightconfig-master.json --outputjson --level=warning --warnings
[2023-07-25T03:46:54Z]
[2023-07-25T03:46:54Z] /workdir/python_modules/dagster/dagster_tests/api_tests/api_tests_repo.py:
[2023-07-25T03:46:54Z]   175:21: Argument of type "dict[str, str | int]" cannot be assigned to parameter "metadata" of type "MetadataMapping | None" in function "repository"
[2023-07-25T03:46:54Z]   Type "dict[str, str | int]" cannot be assigned to type "MetadataMapping | None"
[2023-07-25T03:46:54Z]     "dict[str, str | int]" is incompatible with "MetadataMapping"
[2023-07-25T03:46:54Z]       TypeVar "_VT_co@Mapping" is covariant
[2023-07-25T03:46:54Z]         Type "str | int" cannot be assigned to type "MetadataValue[PackableValue]"
[2023-07-25T03:46:54Z]           "int" is incompatible with "MetadataValue[PackableValue]"
[2023-07-25T03:46:54Z]     Type cannot be assigned to type "None" (reportGeneralTypeIssues)
[2023-07-25T03:46:54Z]
[2023-07-25T03:46:54Z] /workdir/python_modules/dagster/dagster_tests/general_tests/test_repository.py:
[2023-07-25T03:46:54Z]   90:21: Argument of type "dict[str, str | int]" cannot be assigned to parameter "metadata" of type "MetadataMapping | None" in function "repository"
[2023-07-25T03:46:54Z]   Type "dict[str, str | int]" cannot be assigned to type "MetadataMapping | None"
[2023-07-25T03:46:54Z]     "dict[str, str | int]" is incompatible with "MetadataMapping"
[2023-07-25T03:46:54Z]       TypeVar "_VT_co@Mapping" is covariant
[2023-07-25T03:46:54Z]         Type "str | int" cannot be assigned to type "MetadataValue[PackableValue]"
[2023-07-25T03:46:54Z]           "int" is incompatible with "MetadataValue[PackableValue]"
[2023-07-25T03:46:54Z]     Type cannot be assigned to type "None" (reportGeneralTypeIssues)
```

You should be able to get these by running `make pyright`.

And one more small thing: I believe the docstring for the `repository` decorator needs to be updated.

**Comment by tnk-dev** [comment]
Thanks for the review @sryza ,

realizing I needed to fix pyright, I adjusted the metadata types. Let me know what ya think :)

**Comment by tnk-dev** [comment]
I assume I can't access buildkite/dagster and check the failing check

**Review by sryza — APPROVED** [review]
@tnk-dev looks good! I'm going to merge this. I'm kicked off a conversation with our UI folks to chat about getting this represented in the UI. To get that to work, I believe this also needs to be piped through to the GraphQL layer, i.e. added to `GrapheneRepository`.

**Pull request merged**
