### PR TITLE
Airline demo tempfile

### PR DESCRIPTION
**Pull request by mgasner**
3cc6359 illustrates a yielding tempfile resource built on top of the new resource machinery

### CODE REVIEW

**Comment by mgasner** [comment]
tests are broken on Circle because our Circle image doesn't have Java or Spark and a spark resource is being created somewhere post the change to the new resource machinery... will track it down and fix, but immaterial to the substance of 3cc6359

**Comment by mgasner** [comment]
Yep, the relevant diff is just https://github.com/dagster-io/dagster/pull/357/commits/3cc6359647aa3076c1deaa549f108eb9f2affcf9 -- this is just stacked on top of #349

**Comment by schrockn** [comment]
Just change the base of the PR?

**Comment by mgasner** [comment]
Sorry, to be more precise -- this is stacked on #349, and also on the changes in #351. I could create a dummy branch just to make the diff clearer?

**Comment by mgasner** [comment]
Let me close this and give you something a little clearer.

**Pull request closed without merging**
