### PR TITLE
[ruff] 0.0.289 -> 0.1.1, enable formatter, remove black

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

Internal companion PR: https://github.com/dagster-io/internal/pull/7286

Update `ruff` and remove `black`. Use new `ruff format` in place of `black`.

Ruff's formatter, designed as a drop-in replacement for `black`, is technically still in alpha but it works very well. This PR replaces `black` everywhere it is used with `ruff format` instead, and also drops all `black` configuration. This change will save on CI and make for a faster and simpler dev experience.

Caveats:

- `ruff format` does not support black's "preview" mode (i.e. experimental features), which we have had enabled for some time. Consequently there are a few formatting changes from adopting ruff in place of black. From perusing the changed files, I assembled a (likely incomplete) list below. AFAICT the changes are trivial.
- Our `alembic.ini` files invoked `black` as a hook and passed the `--skip-string-normalization` (`-S`) option. I don't think ruff has the equivalent of this option. Not sure if it matters (cc @prha).

Formatting changes:

- Some long string literals are no longer wrapped in `()`
- Location of some trailing comments is moved
- Location of args with `%` operator moved
- Line length calculation no longer incorporates trailing comments, so some lines are longer
- Some multiline `with` statements rearranged
- `...` always appears on a separate line for stub methods
- Some ternary (X if Y else Z) formatted differently

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17290** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17290" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17290?utm_source=stack-comment).

**Comment by schrockn** [comment]
From _brief_ perusal none of these changes seem particularly objectionable, and certainly not to the degree to counterbalance the consolidation and perf improvments.

**Review by schrockn — APPROVED** [review]
This approval is my asset, but I would like gut checked one other person.

**Comment by smackesey** [comment]
>but I would like gut checked one other person.

@gibsondan anything jump out to you?

**Comment by smackesey** [comment]
>I assume there will be a post with any instructions on what people need to do

yes, I believe it's as simple as flipping on a setting in the ruff LSP settings but I will confirm

**Pull request merged**
