### PR TITLE
[docs] small updates to duckdb tutorial

### PR DESCRIPTION
**Pull request by jamiedemaria**
## Summary & Motivation
Some small updates to the DuckDB tutorial based off comments on the BigQuery tutorial https://github.com/dagster-io/dagster/pull/15799

### CODE REVIEW

**Comment by jamiedemaria** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16050** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16050" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16050?utm_source=stack-comment).

**Comment by yuhan** [comment]
should this stack on top of https://github.com/dagster-io/dagster/pull/15799? little unclear whats the small update on this separate pr

**Comment by jamiedemaria** [comment]
yeah it can stack if that would be helpful for review! basically i'm just taking some of the comments left on the Bigquery tutorial and applying them to the duckdb tutorial as well so that everything is consistent

**Comment by yuhan** [comment]
ah i see - my bad. thought this was bigquery too. will review

**Review by yuhan — APPROVED** [review]

**Pull request merged**
