### PR TITLE
add role config to snowflake_io_manager

### PR DESCRIPTION
**Pull request by binhnefits**
### Summary & Motivation
[10622](https://github.com/dagster-io/dagster/issues/10622)

### CODE REVIEW

**Comment by sryza** [comment]
@jamiedemaria - mind taking a look?

**Review by jamiedemaria — CHANGES_REQUESTED** [review]
Hey @binhnefits thanks for the contribution! this looks great, but it's failing one of our code formatting checks. Can you run `make black` from the top level `dagster` directory and push up the changes? After that you should be good to go!

**Comment by binhnefits** [comment]
@jamiedemaria thanks for the help. I commited make black changes.

**Review by jamiedemaria — APPROVED** [review]
good to go! thanks for the contribution! i'll merge it for you

**Pull request merged**
