### PR TITLE
[RFC] lazy Definitions loading via `@defs_loader` decorator

### PR DESCRIPTION
**Pull request by sryza**
## Summary & Motivation

This PR proposes an API for loading definitions outside of import time. It supersedes https://github.com/dagster-io/dagster/pull/23253.

```python
from dagster import Definitions, DefinitionsLoadContext, defs_loader


@defs_loader
def defs(context: DefinitionsLoadContext) -> Definitions:
    my_assets = invoke_expensive_factory_to_build_asset_defs()

    return Definitions(assets=my_assets)
```

This API is useful when the code that generates the set of `Definitions` is heavyweight: e.g. involves parsing lots of YAML files or makes calls to an external service. This heavyweight code won't be invoked every time the user imports their Python modules (e.g. to run a unit test). It will only be invoked when the Dagster framework invokes it, e.g. to execute a step or populate the definitions for a code server.

### `DefinitionsLoadContext`

The user-defined loading function has access to a `DefinitionsLoadContext`, which contains metadata about the definitions are being loaded within.

I haven't though too deeply about the attributes that will live on this class, but it would likely have:
- Some sort of enum that represents the different places where definitions can be loaded. This PR has `load_type: Literal["code_server", "step_worker", "run_worker", ...].`
- (For step and run workers) a way to access cached metadata that was produced by the load process on the code server. This makes it so that step and run workers don't need to redo heavyweight work to assemble definition metadata that already occurred when loading definitions into the deployment . This would be a replacement for `CacheableAssetsDefinition`.
- Some sort of identifier for the definitions that are needed for the current process. This would enable optimizations in the future that allow step workers to avoid loading definitions that aren't needed for the execution they're carrying out.

### When should this be used?

One big question is whether this should supplant `defs = Definitions(...)` as the default way we recommend that users expose their definitions.  E.g. should it go into our tutorial? I lean slightly against but am not sure yet.

Arguments in favor of making it the new default:
- New users just need to learn one way of doing things. No discontinuity when they adopt one of the BI integrations.

Arguments against making it the new default:
- It's more verbose
- It can confuse users about what's happening when. Right now, everything happens at import time. As soon as there's a lazily invoked function, there's another time that things might be happening, and some users are sure to think things are happening at import time that are happening at load time and vice versa.
- Change. Would mean updating a lot of examples and content. And the old version will live on forever via ChatGPT.

### Decorator vs. inheritance

One of the ideas raised on https://github.com/dagster-io/dagster/pull/23253 was an inheritance-based API where the user overrides a function instead of using a decorator.

The main reason I opted for a decorator is consistency with our existing decorator-based convention. The second reason is that it's a little less verbose and doesn't require the user to name a class.

### `CodeLocation` vs. `DefinitionsLoader`

Is the object introduced here a "code location"? The stance that this PR takes is that this object is humbly responsible for producing a set of definition objects. A "code location" is an address where you can find code to run to produce a set of definition objects. I.e. "code location" is a concept that's only relevant from the perspective of a host process that needs to know where to go to load definitions.

Another angle is that "code location" doesn't feel right for an object whose primary function will sometimes be fetching definitions from Airbyte (which is not backed by code).

A third angle is that "code locations" can encompass multiple repositories, but this only supplies the definitions for a single repository. But repository is sort of a legacy concept so maybe this isn't important.

### What about other lifecycle methods?

@schrockn raised the question of supporting other lifecycle methods [here](https://github.com/dagster-io/dagster/pull/23253#pullrequestreview-2202069260). I think some of these, e.g. "Definitions are reloaded without restarting the process" and perhaps "The code server process is started" and "A worker process is started" could be addressed by branching on attributes exposed on the load context.

I think it's worth discussing these in more detail before committing to this direction. @schrockn – I'm interested in the use cases you have in mind.

### CODE REVIEW

**Comment by benpankow** [comment]
Thanks for sketching this out!

A few thoughts:

First, how would we recommend modeling a larger project which loads assets from multiple submodules? For instance, imagine a submodule which loads and modifies some Power BI asset specs. Would this submodule also define a 
```python
@defs_loader
def defs(context: DefinitionsLoadContext) -> Definitions:
    ...
```
method?

> Some sort of identifier for the definitions that are needed for the current process. This would enable optimizations in the future that allow step workers to avoid loading definitions that aren't needed for the execution they're carrying out.

This will be a very useful optimization for cutting down on run start times for orgs that do a lot of work on definitions load. To me this feels like a major motivating factor to pursue this pattern even outside of the cacheable assets work.


> The main reason I opted for a decorator is consistency with our existing decorator-based convention.

One reason that we moved to a class-based model for resource over the previous decorator-based convention was the ability to define lifecycle methods to setup and teardown resources. One avenue of future exploration we haven't yet ventured down was lifecycle methods that could trigger outside of the typical Dagster execution path - for instance, a lifecycle hook that could be run every time a code location was reloaded, or even in a CI context. If we were to implement such hooks on resources, it would make sense to also have them at the Definitions level.

**Comment by sryza** [comment]
> Would this submodule also define a method?

I think the main reason to do so would be if they want to be able to treat that submodule as a code location, i.e. be able to point Dagster at it directly.

Otherwise, I'd say they should just write a vanilla function.

**Review by PedramNavid — COMMENTED** [review]
I think some lazy loading utility seems like a good idea. Aside from unit tests being faster, are there other ways this improves the user experience? 

What does error propagation look like with lazy loading? Is it the same, or will the error messages be wrapped in a longer stack trace?

I do not think we should make this the default for many of the reasons you listed. We can address the continuity error explicitly in docs. "When defining assets against BI tools, Dagster needs to interface with a third-party API. This can be slow, so we can lazy load definitions instead."

I wonder if explicitly calling this a lazy loader of some sort `@lazy_load_defs` or something along those lines would help. 

Does this get picked up automatically, like a Definitions object, or does it need to be added to one too? e.g. `Definitions(lazy_defs=my_lazy_defs)`

If I understand correctly, this change doesn't help make Dagster load a code location any faster for dev/prod workflows?

**Comment by sryza** [comment]
@PedramNavid all great questions.

> Aside from unit tests being faster, are there other ways this improves the user experience?

I think the main one is that this allows us to replace the `CacheableAssetsDefinition` pattern, which doesn't play well with other stuff in Dagster:
- Freshness checks and other asset check factories
  - Relatedly, causes the problem @slopp hit here: https://dagsterlabs.slack.com/archives/C03A0D72A6T/p1723753342579909
- Future APIs we likely want to add to make it easy to – say – supply the same `automation_condition` to all assets that match a particular selection

The other one is that it will make it possible for steps to run more quickly in some cases.

> What does error propagation look like with lazy loading? Is it the same, or will the error messages be wrapped in a longer stack trace?

I think there shouldn't be a longer stack trace. Maybe one extra frame?

> Does this get picked up automatically, like a Definitions object, or does it need to be added to one too? e.g. Definitions(lazy_defs=my_lazy_defs)

It gets picked up automatically

> If I understand correctly, this change doesn't help make Dagster load a code location any faster for dev/prod workflows?

In the short term, it would not make the deploy process or "reload code location" UI action faster. But combined with other APIs that we could add in the future for loading definitions / blueprints at a more granular level, it could make these faster by only reloading a subset of definitions in some cases.

**Comment by petehunt** [comment]
Is this valid?

```python
@defs_loader
def my_lazy_defs(context: DefinitionsLoadContext) -> Definitions:
    my_assets = invoke_expensive_factory_to_build_asset_defs()

    return Definitions(assets=my_assets)

my_eager_defs = Definitions(assets=[...])

defs = Definitions.merge(my_lazy_defs, my_eager_defs)
```

**Comment by sryza** [comment]
My initial take is that it would be that `Definitions.merge(my_lazy_defs, my_eager_defs)` would be ambiguous about whether the result is eager or lazy, and I'd rather make the user make an explicit choice of one or the other:

i.e.
```python
defs = Definitions.merge(my_lazy_defs.load(), my_eager_defs)
```

or
```python
defs = DefinitionsLoader.merge(my_lazy_defs, defs_loader(lambda: my_eager_defs))
```

**Comment by schrockn** [comment]
I'm moving this discussion to https://github.com/dagster-io/internal/discussions/11054. I have some thought on this as this is actually a very large change.

**Review by schrockn — CHANGES_REQUESTED** [review]
queue management

**Pull request closed without merging**
