### PR TITLE
[feat][dagster-slack] add interval arg to make_slack_on_run_failure_s…

### PR DESCRIPTION
**Pull request by ldnicolasmay**
…ensor

## Summary & Motivation

Without exposing the `minimum_interval_seconds` parameter that's available in the `@run_failure_sensor` decorator in `dagster._core.definitions.run_status_sensor_definition`, anyone using the `dagster-slack` library's `make_slack_on_run_failure_sensor` function is forced to rely on a hard-coded global `DEFAULT_SENSOR_DAEMON_INTERVAL = 30` seconds set [here](https://github.com/ldnicolasmay/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/sensor_definition.py#L84).

This PR exposes the `minimum_interval_seconds` parameter in the `@run_failure_sensor` decorator so that users can change Slack failure sensor wait intervals to something other than 30 seconds.

## How I Tested These Changes

I ran `pytest .` from the `python_modules/libraries/dagster-slack` directory.

```
======================================== test session starts =========================================
platform linux -- Python 3.10.6, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/hynso/GitHub/ldnicolasmay/dagster, configfile: pyproject.toml
plugins: anyio-3.6.2, forked-1.6.0, cov-2.10.1, rerunfailures-10.0, buildkite-test-collector-0.1.7, mock-3.3.1, dependency-0.5.1, requests-mock-1.10.0, xdist-2.1.0, snapshottest-0.6.0
collected 15 items                                                                                   

dagster_slack_tests/test_hooks.py ....                                                         [ 26%]
dagster_slack_tests/test_resources.py .                                                        [ 33%]
dagster_slack_tests/test_sensors.py .........                                                  [ 93%]
dagster_slack_tests/test_version.py .                                                          [100%]

========================================= 15 passed in 1.39s =========================================
```

### CODE REVIEW

**Comment by smackesey** [comment]
Thanks for the PR @ldnicolasmay, I'll have a look

**Comment by ldnicolasmay** [comment]
Thanks kindly @smackesey!

**Review by smackesey — COMMENTED** [review]
lgtm, I'm going to run CI on it

**Comment by smackesey** [comment]
@ldnicolasmay change type annotation to `Optional[int]` (not `str`) and we're golden

**Comment by smackesey** [comment]
Hmm so I think the actual content of your change is good to go but it looks like your rebase went haywire-- notice it says "Files Changed: 94" and you have 24 commits in your branch. So we need to fix that before merging.

It's certainly possible to fix your state through some git manipulation and you're welcome to try if you want to learn some git tricks, but I think the simplest thing is to:

- copy the one file you changed
- delete the current branch
- fetch latest dagster master
- create new branch with same name as old branch (you can do this bc you deleted the old one) off master
- paste in the copied file from old branch
- push

That should get this PR back into a state where it's just your one commit changing one file.

**Pull request closed without merging**
