### PR TITLE
[components] Add env to the default ComponentLoadContext renderer

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

Copies over work from: https://app.graphite.dev/github/pr/dagster-io/dagster/26340/componenet-Enable-dsl-access-to-os-environ-as-var

## Changelog

NOCHANGELOG

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26496?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26496** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26496?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26496?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26495** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26495?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#26468** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26468?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by schrockn — CHANGES_REQUESTED** [review]
I think we shouldn't call env variables secrets without adding additional features. Let's just call them `var`, `env`, or `env_var`. I like `env` because it aligns with `.env` local file.

**Comment by schrockn** [comment]
Why not `env`?

**Comment by OwenKephart** [comment]
@schrockn updated to just `env()`

**Review by schrockn — APPROVED** [review]
Please update PR summary and title before commit!

**Comment by OwenKephart** [comment]
### Merge activity

* **Dec 17, 7:07 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/26496).

**Pull request merged**
