### PR TITLE
[dagster-airlift] in-airflow submodule

### PR DESCRIPTION
**Pull request by dpeng817**
removes the airflow dependency from airlift core, and creates a new "airflow"submodule for airflow-related dependencies.

Tested by setting up tox environment and ensuring that's working.

Moves "migration state" code into a neutral directory so it can be picked up by both the airflow submodule and the core submodule, and removes dependency on dagster project from that codepath.

### CODE REVIEW

**Review by schrockn — APPROVED** [review]
Probably not our final answer on how we'll organize, but a good start.

**Review by schrockn — COMMENTED** [review]
Hmmm in terms of naming the extra should we call in `in-airflow-cluster` or something?

Someone might get confused that `AirflowInstance` is not in `dagster-airlift[airflow]`

**Review by schrockn — CHANGES_REQUESTED** [review]
Just req'ing changes so you see followup comment

**Comment by dpeng817** [comment]
@schrockn maybe just in-airflow? I worry about using the "cluster" terminology

**Review by schrockn — APPROVED** [review]

**Pull request merged**
