### PR TITLE
[components] Allow generate_files to be paramterized

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

Reworks https://github.com/dagster-io/dagster/pull/26283/files to be less fancy.

Just a generic json blob that gets passed through params. Future PR will add an alternative entrypoint with fancier behavior so you don't have to pass in raw json.

## How I Tested These Changes

```
dg generate component dbt_project my_project --params "{\"project_path\": \"../../../dagster/\"}"

```

## Changelog

NOCHANGELOG

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26305?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26305** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26305?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26305?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26281** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26281?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#26283](https://github.com/dagster-io/dagster/pull/26283) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26283?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by schrockn — CHANGES_REQUESTED** [review]
K this makes sense. Looking forward to the sugar on top.

I think we should make the flag more exotic looking. E.g. --json-params or --params-as-json since this will be a pretty low-level API only invoked from scripts etc.

**Review by schrockn — APPROVED** [review]
K this makes sense. Looking forward to the sugar on top.

I think we should make the flag more exotic looking. E.g. --json-params or --params-as-json since this will be a pretty low-level API only invoked from scripts etc.

**Comment by OwenKephart** [comment]
### Merge activity

* **Dec 5, 10:36 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/26305).

**Pull request merged**
