### PR TITLE
[ruff] Enable D212 (multiline-docstring-first-line)

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

Enable ruff D212, multiline-docstring-first-line. This is part of Google-style docstrings.

This was previously temporarily ignored due to the large number of existing violations and lack of autofix but has become autofixable since we transitioned to `ruff`.

---

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12889** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12889" target="_blank">Graphite</a> 
    * **PR #12890** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12890" target="_blank">Graphite</a> 
      * **PR #12891** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12891" target="_blank">Graphite</a> 
        * **PR #12892** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12892" target="_blank">Graphite</a> 
          * **PR #12900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12900" target="_blank">Graphite</a>  👈
            * **PR #12901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12901" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12900?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12889** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12889" target="_blank">Graphite</a> 
    * **PR #12890** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12890" target="_blank">Graphite</a> 
      * **PR #12891** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12891" target="_blank">Graphite</a> 
        * **PR #12892** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12892" target="_blank">Graphite</a> 
          * **PR #12900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12900" target="_blank">Graphite</a>  👈
            * **PR #12901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12901" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12900?utm_source=stack-comment).

**Review by alangenfeld — APPROVED** [review]
in autofix we trust

**Comment by smackesey** [comment]
@smackesey queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12900).

**Comment by smackesey** [comment]
[Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12900) rebased this pull request as part of a merge.

**Comment by smackesey** [comment]
[Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12900) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
