### PR TITLE
[DA][16/n][asset-graph-entity] Convert AssetSubset to dataclass

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

This converts AssetSubset to use dataclass instead of NamedTuple. This will make further changes which change its inheritence structure easier, as NamedTuples don't play nicely with multiple inheritence, and I found records to be a little tricky with Generics.

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23630?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23630** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23630?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#23629** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23629?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — COMMENTED** [review]
What specific issues were you facing with generics and records? I think it's worth us trying to work out those kinks in the records framework, so we don't end up with multiple dataclass styles in our codebase.

**Comment by OwenKephart** [comment]
@sryza https://app.graphite.dev/github/pr/dagster-io/dagster/23832/record-Make-work-with-Generics# illustrates the problem -- i'll see if there's an easy fix

**Comment by OwenKephart** [comment]
@sryza I have spent enough time with the linked PR to determine that it is not an easy (for me) fix, but agree it's worthwhile to fix

**Pull request closed without merging**
