### PR TITLE
iteritems -> items

### PR DESCRIPTION
**Pull request by sethkimmel3**
### Summary & Motivation

Fixes https://github.com/dagster-io/dagster/issues/12604

`.iteritems` is [deprecated since 1.50 ](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#other-deprecations) and will be removed in a future version. Changing to `.items`. (https://github.com/pandas-dev/pandas/pull/45321).

### How I Tested These Changes

I did not, but https://github.com/pandas-dev/pandas/pull/45321 appears to indicate it's a safe change to make. If I can somehow install this version of dagster on my machine, I'm happy to test using the code that surfaced the issue, but I'm not sure how to do that.

### CODE REVIEW

**Comment by sryza** [comment]
@sethkimmel3 do you know when `items` was added? Just want to make sure we're not breaking people who are on older-but-still-used Pandas versions

**Comment by sethkimmel3** [comment]
@sryza looks like it's been around since 0.5.0 (or earlier): https://github.com/pandas-dev/pandas/blob/8f79f7c6e01874bbf7f3b9bc38af01551c90121e/pandas/core/series.py#L447 (pending python3 compatibility).

**Comment by sryza** [comment]
Great - that's a long time. This LGTM. Kicking off a build.

**Comment by sryza** [comment]
pyright has this complaint:

```
[2023-03-01T20:56:02Z] /workdir/python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py:
[2023-03-01T20:56:02Z]   79:41: Argument of type "Hashable" cannot be assigned to parameter "name" of type "str" in function "__new__"
[2023-03-01T20:56:02Z]   "Hashable" is incompatible with "str" (reportGeneralTypeIssues)
```

To avoid this, I think probably just casting to a string is best?

**Comment by sethkimmel3** [comment]
@sryza that seems sensible, but I'm also not sure why it would be suddenly flag this as an issue, as it appears `.itemitems` has just been an alias for `.items` and calls that function directly. What version of pandas is dagster using under the hood?

**Comment by sryza** [comment]
> What version of pandas is dagster currently using?

I don't believe we pin any particular version. In our CI, I believe we use the latest version (just `pip install pandas`).

**Comment by sethkimmel3** [comment]
I'm assuming this is what you meant by casting to str. Let's see if the build likes this!

**Review by sryza — APPROVED** [review]
Looks good!

**Pull request merged**
