### PR TITLE
[airlift] Fix DagsterOperator task->asset lookup

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

The Dagster Operator was still using the op name to figure out what assets to materialize. It was returning an empty list. Now, we perform that lookup using the asset tags.

Extra motivation to get https://linear.app/dagster-labs/issue/PLUS-1325/centralize-targeting-logic-on-asset-tags-instead-of-op-tags-naming in so we have a standard way of mapping back and forth.

Follow up from me is more aggressive errors if we dont' find any matching assets.

## Test Plan

Added integration test which parallels the existing switcheroo test (that relies on the naming convention) but uses the `dag_defs`, `task_defs` methods instead of naming convention.

## Changelog [New]

`NOCHANGELOG`

### CODE REVIEW

**Comment by benpankow** [comment]
* **#23985** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23985?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
Ok great. Needs at a minimum a test plan and ideally an automated repro.

**Comment by benpankow** [comment]
Added test

**Review by schrockn — APPROVED** [review]
Awesome

**Pull request merged**
