### PR TITLE
Add Playground Example folder and Observable source asset test

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

This PR serves two purposes:

1) To introduce an example I could load into `dagster-webserver` to test https://github.com/dagster-io/dagster/pull/16620
2) To add a generalized dumping ground for simple, standalone examples to keep under test. Often you want to have something you can easily load in the UI, but don't want to make any entire new module for. This provides a place where you can dump that sort of thing.

### CODE REVIEW

**Comment by schrockn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16617** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16617" target="_blank">Graphite</a> 
    * **PR #16618** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16618" target="_blank">Graphite</a> 
      * **PR #16620** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16620" target="_blank">Graphite</a> 
        * **PR #17063** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17063" target="_blank">Graphite</a>  👈
        * **PR #16621** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16621" target="_blank">Graphite</a> 
          * **PR #16716** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16716" target="_blank">Graphite</a> 
            * **PR #16718** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16718" target="_blank">Graphite</a> 
          * **PR #16712** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16712" target="_blank">Graphite</a> 
          * **PR #16623** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16623" target="_blank">Graphite</a> 
      * **PR #16619** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16619" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17063?utm_source=stack-comment).

**Comment by schrockn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16617** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16617" target="_blank">Graphite</a> 
    * **PR #16618** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16618" target="_blank">Graphite</a> 
      * **PR #16620** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16620" target="_blank">Graphite</a> 
        * **PR #17063** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17063" target="_blank">Graphite</a>  👈
        * **PR #16621** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16621" target="_blank">Graphite</a> 
          * **PR #16716** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16716" target="_blank">Graphite</a> 
            * **PR #16718** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16718" target="_blank">Graphite</a> 
          * **PR #16712** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16712" target="_blank">Graphite</a> 
          * **PR #16623** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16623" target="_blank">Graphite</a> 
      * **PR #16619** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16619" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17063?utm_source=stack-comment).

**Comment by alangenfeld** [comment]
whats the difference between this new examples playground and `python_modules/dagster-test/dagster_test/toys/`  ?

**Comment by schrockn** [comment]
I think nothing. I'll move it.

**Review by alangenfeld — CHANGES_REQUESTED** [review]
> ill move it

**Pull request closed without merging**
