### PR TITLE
[pyright] [scripts] misc

### PR DESCRIPTION
**Pull request by smackesey**
### Summary & Motivation

Fix type errors in scripts

### How I Tested These Changes

BK

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11923** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11923" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11923?utm_source=stack-comment).

**Review by schrockn — CHANGES_REQUESTED** [review]
Per discussion, investigate turning this off and if it's too high cost do it. These are very unintuitive fixes and will cause continual friction with folks writing integrations against libraries that very well may not follow modern python typing and py.typed public interface rules.

**Comment by smackesey** [comment]
For reasons stated in slack DM, these particular errors can't be turned off.

**Comment by schrockn** [comment]
For posterity, so that we have it here, and not the black death hole of useful knowledge that is Slack:


Screen Shot 2023-02-02 at 2 59 25 PM

**Review by schrockn — APPROVED** [review]
Ok

**Pull request merged**
