### PR TITLE
[dagster-deltalake] Fix GcsConfig() ImportError and TypeError for partitioned assets

### PR DESCRIPTION
**Pull request by thmswt**
## Summary & Motivation

Closes [[dagster-deltalake] GcsConfig ImportError and TypeError for partitioned assets #22053](https://github.com/dagster-io/dagster/issues/22053)

## How I Tested These Changes

`python -m pytest python_modules/libraries/dagster-deltalake/dagster_deltalake_tests`

### CODE REVIEW

**Comment by cmpadden** [comment]
Hi @ion-elgreco - I see that you last worked on this section of code, and wanted to get your input. Does this look good to you?

**Comment by ion-elgreco** [comment]
@cmpadden the config one is fine, but changing the expression param in the filter seems to not solve anything. Pyarrow11+ supports the filter method, and they all use expression as a parameter.

But I would say these are the least of the issues, there are many issues and missing implementations in the current io manager.

I tried upstreaming this a while ago but there was no traction, so I now internally maintain the improved versions

**Comment by cmpadden** [comment]
Thanks for the insight, @ion-elgreco ; sorry to hear that getting it upstream has been difficult.

@thmswt the build kite tests pass, however it looks like `ruff` needs to be run to format/sort the imports. Would you be able to do that when you get the chance, please?

**Comment by thmswt** [comment]
@cmpadden imports are sorted now as suggested by `ruff`.

@ion-elgreco thanks for your input. Tested it with Pyarrow12+. Version 16.1.0 works with expression param though.

**Review by cmpadden — APPROVED** [review]

**Pull request merged**
