### PR TITLE
[dagster-aws] delete dummy Pipes classes

### PR DESCRIPTION
**Pull request by danielgafni**
## Summary & Motivation

Deleting dummy Pipes classes from AWS Pipes. These classes didn't provide any functionality and their introduction was questionable from the start. 

Context:
- https://github.com/dagster-io/dagster/pull/23353#issuecomment-2271460342
- https://github.com/dagster-io/dagster/pull/22968

I decided to keep `PipesGlueLambdaEventContextInjector`, because unlike the the other classes, it's actually used for a unique purpose: injecting variables into Lambda event input (it might be a bit confusing because it inherits from `PipesEnvContextInjector` but doesn't actually do anything with environment variables). 

@schrockn let me know if you think if it makes sense 

## How I Tested These Changes

Nothing was really using these classes

### CODE REVIEW

**Comment by danielgafni** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23441?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23441** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23441?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#23353** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23353?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#23440](https://github.com/dagster-io/dagster/pull/23440) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23440?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @danielgafni and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
Curious to hear what @cmpadden thinks, but I think these wrapper classes actually obscure what is actually happening. If we imagine the implementations diverging more, that is another thing. But I think we should be explicit that we are fetching logs from CloudWatch or injecting context via S3 in a standardized way in these cases.

**Comment by cmpadden** [comment]
> Curious to hear what @cmpadden thinks, but I think these wrapper classes actually obscure what is actually happening. If we imagine the implementations diverging more, that is another thing. But I think we should be explicit that we are fetching logs from CloudWatch or injecting context via S3 in a standardized way in these cases.

I'm in agreement -- I don't see the benefit of the wrapper classes in their current form. It's more clear to have the full context of where logs are being fetched without the added layer of abstraction.

**Comment by danielgafni** [comment]
Seems like this is good to go then? 

@schrockn any idea why `graphite` doesn't propagate the pyright error fix from #23353 to this branch? I tried `gt restack` but it doesn't seem to help

**Comment by schrockn** [comment]
No idea on your graphite issue.

Were these public or in docs? Do we need to go through a deprecation cycle?

**Comment by cmpadden** [comment]
> Seems like this is good to go then?
> 
> @schrockn any idea why `graphite` doesn't propagate the pyright error fix from #23353 to this branch? I tried `gt restack` but it doesn't seem to help

You may need to do a `gt get` -- I'm by no means a graphite guru, but that's been helping me with rebase issues.

**Comment by danielgafni** [comment]
> Were these public or in docs? Do we need to go through a deprecation cycle?

They weren't. 

Also, the Glue client is marked as Experimental.

**Review by schrockn — APPROVED** [review]
Great!

**Pull request merged**
