### PR TITLE
[fix] Update Airbyte assets to avoid name collisions

### PR DESCRIPTION
**Pull request by maximearmstrong**
## Summary & Motivation

Fixes [DS-417](https://linear.app/dagster-labs/issue/DS-417/avoid-name-collisions-for-dagster-airbyte-assets)

This PR updates the Airbyte assets naming template to include the full connection ID. Previously, we were truncating the connection ID to keep only the first 5 characters in the asset name, which created name collisions for some users.

## How I Tested These Changes

Updated tests + BK

## Changelog [New | Bug | Docs]

Bug:

[dagster-airbyte] Update the Airbyte asset naming template to include the full connection ID, avoiding name collisions.

### CODE REVIEW

**Comment by maximearmstrong** [comment]
* **#24058** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24058?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gibsondan — COMMENTED** [review]
This makes a lot of sense to me but I don't have any historical context on why the prefixing was chosen

The other idea that i had thrown out was appending some kind of hash to the end to make sure they are unique, but if the size here is bounded and not crazy then this seems fine. Other reviewers have any thoughts or concerns?

**Comment by sryza** [comment]
@benpankow or @OwenKephart  - do you have context on why we limited it to 5 characters?

**Comment by OwenKephart** [comment]
Sad as it is, I believe this was an aesthetic choice back in the days when people would be seeing the op name more often. I have no concerns over this particular change

**Review by OwenKephart — APPROVED** [review]

**Pull request merged**
