### PR TITLE
Fix upstream context handling in fs_asset_io_manager

### PR DESCRIPTION
**Pull request by aroig**
### Summary & Motivation

This is another attempt at solving #7900 after what we discussed in #7958

### How I Tested These Changes

Added a test related to what we try to fix. core_tests are happy, black and pylint are happy.

### CODE REVIEW

**Review by sryza — COMMENTED** [review]
Thanks for the contribution @aroig. s3_pickle_asset_io_manager, gcs_pickle_asset_io_manager, and adls2_pickle_asset_io_manager also have similar logic. I wonder if there would be a way to factor this code that would make it require less duplicated code when we want to fix those in the future.  E.g. what if `InputContext` and `OutputContext` both had a `get_asset_identifier` method? So then `_get_path` wouldn't need to check which type it was dealing with and call the appropriate method?

**Comment by aroig** [comment]
> s3_pickle_asset_io_manager, gcs_pickle_asset_io_manager, and adls2_pickle_asset_io_manager also have similar logic

Ah, sorry about that, I should have checked.

> I wonder if there would be a way to factor this code that would make it require less duplicated code when we want to fix those in the future. E.g. what if InputContext and OutputContext both had a get_asset_identifier method?

You are right, that seems much better!

Actually, what is the purpose of having the upstream_output field? Having a lot of optional state is kind of error-prone for the consumers. I wonder if we could expose a uniform enough API for InputContext and OutputContext as you suggested, for just the pieces of upstream_output needed, and get rid of upstream_output entirely.

Anyway, I will prepare another version of the PR.

**Comment by aroig** [comment]
I pushed the changes @sryza suggested. Let me know if you prefer a cleaned up history on a new PR for review.

I ran tests, pylint and black locally, which are all ok. I did not test the s3, gcs & azure IOManagers though. I assume they will be exercised in CI?

Finally, in order to preserve filesystem paths for `VersionedPickledFilesystemIOManager` (on memoizable_io_manager.py), I had to special case on input and output context there. The reason is that the existing filesystem layout for that IOManager does not match the output of context.get_identifier(). Using the fields of that identifier seemed brittle as opposed to building the path directly from the context. If breaking this class were ok (which I assume is not), we could simplify it through use of get_identifier().

**Comment by aroig** [comment]
Ah, one more thing: we are breaking compatibility with `_get_path` (before it always took an OutputContext, now it takes either InputContext or OutputContext). Since `_get_path` is private I assumed it is ok, but we may still break people who overrides it on their classes.

**Review by sryza — APPROVED** [review]
This looks great. I just kicked off a build.

**Comment by sryza** [comment]
@aroig I'm seeing a few test failures:

mypy errors (I can help you with how to run mypy locally if it would be helpful):
```
[2022-05-25T23:03:34Z] dagster/core/storage/memoizable_io_manager.py:47: error: Incompatible types in assignment (expression has type "Optional[OutputContext]", variable has type "OutputContext")  [assignment]
--
  | [2022-05-25T23:03:34Z] dagster/core/execution/context/input.py:306: error: <nothing> has no attribute "time_window_for_partition_key"  [attr-defined]
  | [2022-05-25T23:03:34Z] dagster/core/execution/context/input.py:309: error: <nothing> has no attribute "time_window_for_partition_key"  [attr-defined]
  | [2022-05-25T23:03:34Z] dagster/core/execution/context/input.py:334: error: Item "None" of "Optional[OutputContext]" has no attribute "get_identifier"  [union-attr]
```

And a failure in the `dagster-test` library, which contains Dagster examples:
```
[2022-05-25T23:07:15Z] AttributeError: 'InputContext' object has no attribute 'get_output_identifier'
--
  | [2022-05-25T23:07:15Z]
  | [2022-05-25T23:07:15Z] Stack Trace:
  | [2022-05-25T23:07:15Z]   File "/workdir/python_modules/dagster/dagster/core/execution/plan/utils.py", line 47, in solid_execution_error_boundary
  | [2022-05-25T23:07:15Z]     yield
  | [2022-05-25T23:07:15Z]   File "/workdir/python_modules/dagster/dagster/core/execution/plan/inputs.py", line 713, in _load_input_with_input_manager
  | [2022-05-25T23:07:15Z]     value = input_manager.load_input(context)
  | [2022-05-25T23:07:15Z]   File "/workdir/python_modules/dagster/dagster/core/storage/fs_io_manager.py", line 151, in load_input
  | [2022-05-25T23:07:15Z]     filepath = self._get_path(context)
  | [2022-05-25T23:07:15Z]   File "/workdir/python_modules/dagster-test/dagster_test/graph_job_op_toys/asset_lineage.py", line 71, in _get_path
  | [2022-05-25T23:07:15Z]     keys = context.get_output_identifier()

```

**Comment by aroig** [comment]
@sryza I pushed changes to fix the typing and dagster-test errors. I have not run dagster-test locally because of a dependency issue I am not sure how to solve, I am relying on ci.

By the way, if we need another iteration, I have no problem in rebasing after #8074

**Comment by aroig** [comment]
@sryza rebase done, there was a conflict on system.py, in case you want to take a final look there.

**Pull request merged**
