### PR TITLE
Perform flake8 tests for syntax errors and undefined names

### PR DESCRIPTION
**Pull request by cclauss**
**STOP!** Did you remember to make changes to the release notes reflecting any changes to public
APIs or new user-facing functionality introduced in this diff?

[flake8](http://flake8.pycqa.org) testing of https://github.com/dagster-io/dagster on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./python_modules/dagit/dagit/app.py:34:5: F821 undefined name 'Dict'
    # type: (Exception) -> Dict[str, Any]
    ^
./python_modules/dagit/dagit/app.py:34:5: F821 undefined name 'Any'
    # type: (Exception) -> Dict[str, Any]
    ^
./python_modules/dagit/dagit/app.py:36:54: F821 undefined name 'Dict'
    formatted_error = {'message': text_type(error)}  # type: Dict[str, Any]
                                                     ^
./python_modules/dagit/dagit/app.py:36:54: F821 undefined name 'Any'
    formatted_error = {'message': text_type(error)}  # type: Dict[str, Any]
                                                     ^
./python_modules/dagster/dagster/seven/__init__.py:64:12: F821 undefined name 'reload'
    return reload(module)  # pylint: disable=undefined-variable
           ^
./python_modules/dagster/dagster_tests/core_tests/test_composites.py:84:16: F632 use ==/!= to compare str, bytes, and int literals
        assert context.solid_config is 'yes'
               ^
./python_modules/dagster/dagster_tests/core_tests/test_composites.py:112:16: F632 use ==/!= to compare str, bytes, and int literals
        assert one is 1
               ^
./python_modules/dagster/dagster_tests/core_tests/test_composites.py:146:16: F632 use ==/!= to compare str, bytes, and int literals
        assert one is 1
               ^
./python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_composites.py:83:12: F632 use ==/!= to compare str, bytes, and int literals
    assert len(handle_map) is 10
           ^
4     F632 use ==/!= to compare str, bytes, and int literals
5     F821 undefined name 'Dict'
9
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by mgasner** [comment]
We should probably run flake8 on all of our packages if we're going to do this. I like restricting it to a few key messages (so we don't conflict with black). The typing imports are also great but I think we should namespace them under dagster.seven.typing

**Comment by cclauss** [comment]
The test results that I pasted into the commit message is __flake8 running against the entire repo__.

I really do not understand seven and chose to just to exclude it in these tests.

There are only one or two error codes where Black and Flake8 will actually disagree with each other.  And those are about Python style which the selected Flake8 tests do not touch.

The typing module is builtin in Python 3.5+ but it can also be [imported from PyPI for Python 2.7](https://pypi.org/project/typing) so with only 168 daze left until Python 2 EoL, Iwould steer clear of a nonstandard redefinition

**Comment by mgasner** [comment]
`seven` is our extended py23 compatibility library ("a little more than six"). However, on reflection, rather than introduce a new dependency on `typing`, I'd prefer to drop the type hints from `dagit/app.py` entirely, until we either break compatibility with py2 or introduce mypy-style annotations across the entire codebase. This will fix the black errors.

I'm happy to add these flake8 checks for the remaining projects in a follow-on diff, or you can feel free to edit the remaining tox.ini files to add flake8.

If we then rebase (b/c of https://github.com/dagster-io/dagster/issues/1574), we should be good to merge this.

Thanks very much!

**Comment by mgasner** [comment]
@cclauss I'd like to merge this but will have to make a few changes per the above

**Comment by cclauss** [comment]
> rather than introduce a new dependency on typing

This PR does not introduce a new dependency on __typing__.  Instead, it attempts to import typing from the Python Standard Library and fail gracefully if we are running on a version of Python that does not include __typing__.  The fact that the code tries is enough to silence flake8.

The __black__ error was about missing whitespace, and not about the try / except block itself.

**Pull request merged**
