### PR TITLE
Add docstring detailing factory use case for ConfigurableResource

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Per https://github.com/dagster-io/dagster/discussions/17551 adding docblock description of using `ConfigurableResource` to produce different object type at runtime.

## How I Tested These Changes

Screenshot 2023-11-01 at 4 52 02 PM

Read

### CODE REVIEW

**Comment by schrockn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17613** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17613" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17613?utm_source=stack-comment).

**Review by yuhan — APPROVED** [review]
docstring looks good.


the docs build failure is likely because your base master branch is outdated. if you want to get it green, you can rebase latest master.

**Review by benpankow — APPROVED** [review]

**Comment by emirkmo** [comment]
@schrockn The docs for ConfigurableResourceFactory still remain, should they be removed as well? Or is that usecase still valid?

**Comment by schrockn** [comment]
`ConfigurableResourceFactory` is not exported publicly, so I would recommend using `ConfigurableResource`. The functionality is the same. Agree that we should merge content of `ConfigurableResourceFactory` and `ConfigurableResource` docblock on `ConfigurableResource`

**Pull request merged**
