### PR TITLE
[RFC] execute_in_process input values

### PR DESCRIPTION
**Pull request by dpeng817**
Add input values to execute_in_process. If the top level graph/job has inputs, previously, you would provide them by using config, which is cumbersome in most scenarios. This adds an argument which allows them to be added more conveniently. 

It does have weird collisions with config unfortunately, which are mapped out in the errors. If you provide input config, or any config mapping, then providing input values becomes difficult.

### CODE REVIEW

**Review by sryza — COMMENTED** [review]
Will this work with values that are not parse-able as config values? E.g. passing a DataFrame as an input value? I think that functionality is important.

**Comment by dpeng817** [comment]
@sryza - it will not. An alternative strategy that could enable that is adding an ephemeral input manager to the constructed job that's able to load the values.

**Comment by sryza** [comment]
> An alternative strategy that could enable that is adding an ephemeral input manager to the constructed job that's able to load the values.

If we can make that work, that sounds good to me. It might be tough, because not all inputs declare root input manager keys.

**Comment by dpeng817** [comment]
@sryza we would have to foist them into the job.

**Comment by alangenfeld** [comment]
Im suspicious of this threading via config approach. I think if we want to support this its worth adding deeper support. We already have default values on input definitions that allow loading from an in memory bound value, so something that binds values to the job def that then point at inputs that are exposed on the top level graph feels reasonable. The core code already handles an enum of different input sources so an additional one isn't that substantial.

**Comment by dpeng817** [comment]
Closing to investigate other approaches

**Pull request closed without merging**
