### PR TITLE
Update modes-resources.mdx

### PR DESCRIPTION
**Pull request by madhur-tandon**

### CODE REVIEW

**Comment by dpeng817** [comment]
Does `-d` no longer work to specify a mode? If not, it seems like we might want to get that working again rather than change the docs.
Unless `-d` has changed meaning somehow.

**Comment by madhur-tandon** [comment]
According to `dagster pipeline execute -h`

-   -d, --working-directory TEXT  Specify working directory to use when loading the repository or pipeline. Can
                                only be used along with -f/--python-file
- --mode TEXT                   The name of the mode in which to execute the pipeline.

**Review by dpeng817 — APPROVED** [review]

**Comment by madhur-tandon** [comment]
What's stopping this to be merged?

**Comment by dpeng817** [comment]
Apologies for lateness, Still figuring out github workflow. Thanks for your contribution @madhur-tandon !

**Pull request merged**
