### PR TITLE
lazy load instance run coordinator

### PR DESCRIPTION
**Pull request by prha**
## Summary & Motivation
Make it easier to build the instance from ref, without necessarily having the dependencies loaded.

Simplifies / combines the lazy load tests.

## How I Tested These Changes
BK

### CODE REVIEW

**Review by johannkm — APPROVED** [review]
What dependencies does the run coordinator have?

**Comment by prha** [comment]
I guess none... do users write their own run coordinators?  or do we just have default and queued?

**Comment by johannkm** [comment]
we have one we inject in cloud, and I know one customer that wrote a custom one to inject a user run tag in oss

**Comment by johannkm** [comment]
I don't mind this for consistency though

**Comment by gibsondan** [comment]
What this would let somebody do is write a custom run coordinator without
needing to make sure that the code is also included in their user code
images as well

**Pull request merged**
