### PR TITLE
[pipes] move subprocess tests to core, fix pyright reqs

### LINKED ISSUE #16753: Dagster should not depend on dagster-ext-process
### Dagster version

1.4.16

### What's the issue?

There is a circular dependency:

`dagster-ext-process` depends on `dagster`
`dagster` depends on `dagster-ext-process`

Is it temporary? Can't the code be separated out properly?

### What did you expect to happen?

I would expect dagster to not depend on the dagster-ext-process, like it is the case for dagster-graphql, dagster-webserver, and all the other extensions.

### How to reproduce?

_No response_

### Deployment type

None

### Deployment details

_No response_

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

- Move subprocess tests from `dagster-pipes` to core. This gets rid of any dependencies, even test dependencies, of `dagster-pipes`. Resolves #16753 
- Update pyright pins

In a follow-up I will move tests using S3 message reader/writer to dagster-aws.

## How I Tested These Changes

Existing test suite.

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16769" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16769?utm_source=stack-comment).

**Review by schrockn — COMMENTED** [review]
Why are there so many version bumps?

**Comment by smackesey** [comment]
>Why are there so many version bumps?

This happens whenever you run `make rebuild_pyright_pins`, it's just all the new releases of dependencies that are consistent with our version constraints.

**Review by schrockn — APPROVED** [review]
kk

**Pull request merged**
