### PR TITLE
[docs] Pass on kind docs

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Updates kind docs to foreground the `kinds=` argument and de-emphasize `compute_kind`.

A couple questions:
- Should we mark `compute_kind` as a `hidden_param` or `deprecated`/`superseded` in code?
- Should we un-`experimental_param` the `kinds` param?

### CODE REVIEW

**Comment by benpankow** [comment]
* **#25596** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25596?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
My proposal: for superceded we should hide the parameter but not aggressive warn. It is low cost for us to continue to support it and no need to thrash people.

**Comment by schrockn** [comment]
And with this change we should un-experimentalize kinds. I think we can be high confidence that this is good.

**Review by schrockn — APPROVED** [review]

**Comment by marvintensuan** [comment]
If it helps, the code snippets from the [ETL pipeline tutorial](https://docs.dagster.io/etl-pipeline-tutorial/create-and-materialize-assets) has `compute_kind`, i.e.,

```python
@dg.asset(
    compute_kind="duckdb",
    group_name="ingestion",
)
```

**Pull request merged**
