### PR TITLE
Enable auto materialize sensors with Helm

### PR DESCRIPTION
**Pull request by thiagoazcampos**
## Summary & Motivation
In order to enable auto materialize sensors, it's needed to set this configuration on `dagster.yaml`:
```
auto_materialize:
  use_sensors: true
```
See: https://docs.dagster.io/concepts/assets/asset-auto-execution#auto-materialize-sensors

This PR implements that configuration on the Helm chart to be enabled if wanted. Auto materialize sensors will be disabled by default.

## How I Tested These Changes
* Added two unit-tests, one for each possible case (enabled or disabled)
* Verified by changing `values.yaml` and running: `helm template --show-only templates/configmap-instance.yaml .`

### CODE REVIEW

**Comment by kristianandre** [comment]
Very useful! Didn't know one could specify auto-materialize sensors, but we would definitely use this in our k8s deployment. However, it seems like auto-materialize policies will be deprecated with 1.8 in favor of "declarative automation". See discussion https://github.com/dagster-io/dagster/discussions/22811.

**Comment by thiagoazcampos** [comment]
That's great! I wasn't aware of that, thanks for pointing @kristianandre.

Meanwhile, it's been useful to use the auto materialize sensors on my setup - but I could wait for Declarative Automation if it makes more sense.

**Comment by ion-elgreco** [comment]
@kristianandre @thiagoazcampos In the mean time you can just do this:
```
additionalInstanceConfig:
    auto_materialize:
        use_sensors: true
```

**Comment by thiagoazcampos** [comment]
thank you @ion-elgreco - I'll close the PR then

**Pull request closed without merging**
