### PR TITLE
add flag to configure asset_sensor to fire for every materialization

### PR DESCRIPTION
**Pull request by prha**
The existing implementation gets the most recent materialization for each sensor interval.  This change allows the materialization function to get called for every materialization, regardless of distribution across intervals.

Addresses: https://github.com/dagster-io/dagster/issues/5699

## Test Plan
BK

### CODE REVIEW

**Comment by mgasner** [comment]
I agree that we should provide this switch and that the default behavior should be to fire only on the last event. Did you consider any other names for the flag, or reversing its polarity? e.g. `on_every_event=False`

**Comment by prha** [comment]
I am not tied to `last_event_only`.  It did tickle my brain to have a default True value, and would be open to suggestions for names.  I don't love `on_every_event` for some reason but I don't feel strongly.

Here are some options that have default False behavior:
`on_every_event`
`every_event`
`fetch_all_events`
`fetch_every_materialization`
`all_events`

We could also use some sort of enum (e.g. `AssetSensorEvents.LAST_EVENT`, `AssetSensorEvents.EVERY_EVENT`).

**Comment by mgasner** [comment]
i don't hate the enums, even verbosities like `event_policy=AssetSensorEventPolicy.ON_MOST_RECENT` -- they're terrible in docstrings but make what's going on very clear. did consider enums for the multi/any asset sensors as well.

`for_every_event`

Might it also be reasonable to call this something like `catch_up`?

**Comment by schrockn** [comment]
Did you consider implementing this as a callback instead of bools/enums. I would be concerned about the implementation in core function getting very messy in a non-composable way.

**Comment by prha** [comment]
@schrockn can you say more?  I don't understand what you're suggesting

**Comment by schrockn** [comment]
What I am suggesting is having a policy that is essentially a callback where the contract is to fetch N AssetMaterializations.

```
def _on_every_event(context, asset_key):
                return context.instance.get_event_records(
                    EventRecordsFilter(
                        event_type=DagsterEventType.ASSET_MATERIALIZATION,
                        asset_key=asset_key,
                        after_cursor=after_cursor,
                    ),
                    ascending=False,
                    limit=None,
                   )
 ```
 
 Or something to that effect. That way you have N implementation of fetches rather than one super complicated one that can handle all different combinations. The "policy" ends up being a callback that returns N materializations. This is composable and more flexible.

**Pull request closed without merging**
