### PR TITLE
Add port lookup to dagit, fixes #2107

### LINKED ISSUE #2107: dagit should politely offer to find a port if the one it expects it taken
```Something is already running at port 8000
✔ Would you like to run the app at another port instead? … no```

### PR DESCRIPTION
**Pull request by rparrapy**
Port lookup is made the default behavior of dagit CLI.

### CODE REVIEW

**Comment by mgasner** [comment]
🙏 thank you so much! will run the remaining tests

**Comment by mgasner** [comment]
tiny formatting nit: https://buildkite.com/dagster/dagster/builds/10471#2975a973-f253-4af0-aace-c32f5ca6c7c4

```
--- a/python_modules/dagit/dagit_tests/test_app.py
+++ b/python_modules/dagit/dagit_tests/test_app.py
@@ -1,7 +1,7 @@
 import pytest
-
 from dagit.app import create_app
 from dagit.cli import host_dagit_ui
+
 from dagster import ExecutionTargetHandle
 from dagster.core.instance import DagsterInstance
 from dagster.seven import mock
```

**Comment by rparrapy** [comment]
Sorry, somehow my editor config must have done that. It should be fixed now.

**Comment by mgasner** [comment]
Thanks very much!

**Comment by alangenfeld** [comment]
Hmmm, I am concerned about the prompt firing when `dagit` is not launched by a human, such as the entrypoint/cmd of a Docker image. You shouldn't normally be contending for ports in these type of situations - but if it does occur it's unfortunate to debug a stalled container and find it waiting for an input prompt.

**Comment by alangenfeld** [comment]
that shouldn't necessarily block this PR but it's something to consider

**Comment by mgasner** [comment]
That's fair, I think it may make sense to add a flag for noninteractive behavior, but we can do that in a follow-on diff.

**Comment by mgasner** [comment]
We may want to have this be the behavior for an invocation of `dagit` where `-p` is not set, and if `-p` is set, then just bail if the port is already taken.

**Pull request merged**
