### PR TITLE
Ruff docstrings D202 (NoBlankLineAfterFunction)

### PR DESCRIPTION
**Pull request by smackesey**

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10900** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10900" target="_blank">Graphite</a> 
    * **PR #10901** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10901" target="_blank">Graphite</a> 
      * **PR #10907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10907" target="_blank">Graphite</a> 
        * **PR #10992** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10992" target="_blank">Graphite</a>  👈
          * **PR #10993** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10993" target="_blank">Graphite</a> 
        * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10992?utm_source=stack-comment).

**Review by schrockn — CHANGES_REQUESTED** [review]
This is one where I'd like to get buy in from some other engineers since I can imagine some people feel that this makes code feel "crowded."

**Comment by smackesey** [comment]
>This is one where I'd like to get buy in from some other engineers since I can imagine some people feel that this makes code feel "crowded."

@sryza @gibsondan @alangenfeld 

Even though this is my PR I don't particularly like this rule-- it was included because it was part of the preset config for Google-style docstrings, but taking a closer look I think this probably should be in the list of [Ruff's disabled doc-rules](https://github.com/charliermarsh/ruff#does-ruff-support-numpy--or-google-style-docstrings) for Google-style docstrings since AFAICT it's not part of the Google docstring spec. But it's nbd to me either way since Ruff auto-adds it.

**Comment by sryza** [comment]
I am personally in favor of this one - partly because I think it's more aesthetic in most situations and partly because I like standardizing so I don't have to think about it

**Comment by smackesey** [comment]
>I am personally in favor of this one - partly because I think it's more aesthetic in most situations and partly because I like standardizing so I don't have to think about it

Works for me-- @schrockn?

**Review by schrockn — APPROVED** [review]

**Review by schrockn — APPROVED** [review]

**Comment by smackesey** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: AncAnsoKDhLPxZ3352Xl.
See details on [graphite.dev](https://app.graphite.dev/github/pr/dagster-io/dagster/10992)

**Pull request merged**
