### PR TITLE
[docs] include resource_defs in example call to with_resources

### PR DESCRIPTION
**Pull request by cmpadden**
## Summary & Motivation

- Includes `resource_defs` as a required parameter to `with_resources` in the code example
- This example renders to our documentation, causing some confusion amongst users

https://docs.dagster.io/_apidocs/resources#dagster.with_resources

## How I Tested These Changes

- Confirmed example has no errors in Pyright

### CODE REVIEW

**Review by tacastillo — COMMENTED** [review]
Not going to lie, I can't remember how to trigger sphinx to render this in our docs. @erinkcochran87 do you know?

**Comment by erinkcochran87** [comment]
Running `make apidoc-build` in `/docs` aughta do it!

**Comment by cmpadden** [comment]
Ran `make apidoc-build`! Thanks for pointing that out @tacastillo & @erinkcochran87. 🙏

**Comment by cmpadden** [comment]
@erinkcochran87 - rebased with master and re-ran `make apidoc-build` to resolve the conflicts.

**Comment by cmpadden** [comment]
Moving to https://github.com/dagster-io/dagster/pull/19922 as branch name breaks web deployments.

**Pull request closed without merging**
