### PR TITLE
Eliminate python-2-only codepath in seven.wait_for_process

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

As title

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by schrockn** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22658?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22658** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22658?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#22657** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22657?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gibsondan — APPROVED** [review]
It seems like you can remove the initial if too (which means this can be codemodded to process.communicate() in every callsite)

**Comment by gibsondan** [comment]
Although I kind of like the default behavior having a timeout

**Review by schrockn — COMMENTED** [review]
Good call @gibsondan https://app.graphite.dev/github/pr/dagster-io/dagster/22660/Eliminate-seven-wait_for_process

**Comment by schrockn** [comment]
### Merge activity

* **Jun 22, 8:41 AM EDT**: @schrockn started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22658).

**Pull request merged**
