### PR TITLE
fix serialization of TableRecord

### PR DESCRIPTION
**Pull request by sryza**

### CODE REVIEW

**Comment by C0DK** [comment]
You should probably update related documentation too, if this works. But i'd be nicer if the inner method just unpacks the dict - not sure if that is possible with how they do pickling

**Comment by danielgafni** [comment]
Would the `TableRecord` work correctly with column names that contain `[` and `.`?

**Comment by sryza** [comment]
@danielgafni yes - it should

**Review by smackesey — APPROVED** [review]

**Comment by sryza** [comment]
@smackesey - what do you think of the comment from @C0DK:

> You should probably update related documentation too, if this works. But i'd be nicer if the inner method just unpacks the dict - not sure if that is possible with how they do pickling

**Comment by smackesey** [comment]
@sryza Just want to make sure this merges for 1.2-- not sure if you've looked at the failing tests but if you like I can push to this and get it to green

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10731** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10731" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10731?utm_source=stack-comment).

**Pull request merged**
