### PR TITLE
[dagster-airlift] unorchestrated_defs passthrough

### PR DESCRIPTION
**Pull request by dpeng817**
Allow passthrough via "defs" argument on builder.

Adds test for the passthrough behavior.

### CODE REVIEW

**Comment by dpeng817** [comment]
* **#23848** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23848?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23846?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23871** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23871?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23870** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23870?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#23869** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23869?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by schrockn — COMMENTED** [review]
Hmm I was assuming that non-orchestrated defs would have to be passed through a separate Definitions object. Would that be simpler?

**Review by schrockn — CHANGES_REQUESTED** [review]
q mgmt here. Might be simpler and clearer to have "non-orchestrated defs" in a separate Definitions object

**Comment by dpeng817** [comment]
@schrockn my only thought to the contrary is it may be a bit awkward to force people to specify things that might apply to defs that are "orchestrated", ie scheduling components, asset checks, to a separate argument than the things they're immediately responsible for.

My conviction isn't super high there, though.

**Review by schrockn — APPROVED** [review]

**Pull request merged**
