### PR TITLE
refactor: clarify the top level graphene query/mutation/subscription

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary
Open source change to accompany https://github.com/dagster-io/internal/pull/507. Felt these names were ungreppable and confusing (are they our implementations, or are they imported from the Graphene library?)

## Test Plan
See what breaks, and fix.

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5782**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

**Review by gibsondan — CHANGES_REQUESTED** [review]
fully support renaming the python class name - renaming the Graphql type name will require some changes on the JS side (grep for "Query" or "Mutation", some tests use it and check the typename) - I don't think it will be a user-facing breaking change though unless they have some strange queries?

**Comment by rexledesma** [comment]
Updated https://github.com/dagster-io/internal/pull/507 as the corresponding change to unbreak internal

**Comment by hellendag** [comment]
You may also need to change the `Query:` in `AppCache`, but I'm actually thinking maybe we don't need that `typePolicies` anymore anyway...

**Review by gibsondan — APPROVED** [review]
internal builds are failing but i assume there's a separate PR for that

**Pull request merged**
