### PR TITLE
Prefer ECS secrets to environment variables of the same name when both are set

### PR DESCRIPTION
**Pull request by jmsanders**
https://github.com/dagster-io/dagster/issues/11622 describes a situation where we try to register a task definition with a secret and an environment variable with identical names.

This can happen because of something you do explicitly: you set both a secret and an env var in your container context.

It can also happen for more subtle and unexpected reasons: you set an environment variable but don't realize that you have a "tagged" secret with the same name, you set a secret but don't realize that an environment variable has been inherited from a "parent" task definition, etc.

I'm not entirely sure what the right fix is here. For now, I've opted to always prefer the secret to the env var if the two overlap. Of course, that raises the question of "what if I want to prefer the env var." Perhaps the best answer there for now is "rename one of the two."

### CODE REVIEW

**Review by gibsondan — COMMENTED** [review]
now that we know the cause of the report i'm unsure about this one - it sounds like in the attached task that the error was actually identifying an invalid state (env vars specified in the dagster.yaml and also tagged dagster secrets) - it may be better to fail here with a reasonably clear message vs. overwrite the same environment variable?

**Comment by jmsanders** [comment]
We can probably just rely on the AWS message for now - let ECS do the heavy lifting of validating the request.

I'm going to scale this back to just represent changes to our ECS stub since it brings it ever so slightly in line with actual ECS behavior.

**Review by gibsondan — CHANGES_REQUESTED** [review]
finally catching back up on my queue - you were going to pull this back to just the stub yeah?

**Comment by jmsanders** [comment]
Yep - just low priority.

**Pull request closed without merging**
