### PR TITLE
[wip] Add whitelist_for_serdes to partitions subsets

### PR DESCRIPTION
**Pull request by clairelin135**
This PR contains a set of changes to refactor `PartitionsSubset` objects to be serialized via `whitelist_for_serdes`. This is still a work in progress, so detailing a set of changes to more easily gather early thoughts from reviewers:

1. This PR stacks on top of https://github.com/dagster-io/dagster/pull/17660, which makes `TimeWindowPartitionsDefinition`s serializable/deserializable

2. Supports making `TimeWindowPartitionsSubset` serializable. This includes:
    - Making it a named tuple
    - Adding a new `before_pack` method to the `NamedTupleSerializer`. `TimeWindowPartitionsSubsets` currently have a lot of performance improvement logic that keeps contents in partition key format when possible, and during serialization we want to transform these contents into time windows
    - Renaming the `included_time_windows` and `num_partitions` methods that return resolved values to not conflict with name tuple field names
        - The new named tuple field names `included_time_windows` and `num_partitions` conflict with existing methods with the same names. Unfortunately the logic in each is different -- in some cases the `num_partitions` and `included_time_window` named tuple fields are unpopulated for performance, while the methods fully resolve the value by loading `included_partition_keys` as time windows. 
        - This PR (admittedly confusingly) renames the "resolution" methods" to be `get_included_time_windows()` and `get_num_partitions()` to be called when the resolved value is needed.

3. Removes `partitions_def` as a field from `DefaultPartitionsSubset` in order to make it serializable
    - Unfortunately, this means that partitions subsets methods that require the partitions def (`get_partition_key_ranges`, `get_partition_keys_not_in_subset`, etc.) now must accept a partitions def
    - `PartitionMapping`s that previously just accepted a subset now must accept a partitions def too (corresponding to the subset) which requires threading the partitions def through the `get_upstream...` and `get_downstream...` methods

4. Removes the `MultiPartitionsSubset` class
    - This class previously subclassed `DefaultPartitionsSubset` and was responsible for casting partition key strings into `MultiPartitionKey` objects
    - Named tuple inheritance sucks (so can't accept extra constructor params, and overriding methods didn't work when I tried it). This PR changes callsites that expect `MultiPartitionKey`s to instead perform this conversion per-callsite.

Unknowns:
- This changes the concept of partition subset equivalence (since previously the partitions def needed to be the same in order to be equivalent). Not sure if there are any breakages here

### CODE REVIEW

**Comment by clairelin135** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17521** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17521" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17521?utm_source=stack-comment).

**Comment by sryza** [comment]
> Making it a named tuple

Makes sense

> Adding a new before_pack method to the NamedTupleSerializer. TimeWindowPartitionsSubsets currently have a lot of performance improvement logic that keeps contents in partition key format when possible, and during serialization we want to transform these contents into time windows

Would it make sense to just override `pack` to do the conversion to time window-based subset and then call the superclass pack? I think it's worth explaining what's going on here to Alex and seeing how this fits into any grand theory he has of how our serdes library should work.

> Renaming the included_time_windows and num_partitions methods that return resolved values to not conflict with name tuple field names. The new named tuple field names included_time_windows and num_partitions conflict with existing methods with the same names. Unfortunately the logic in each is different -- in some cases the num_partitions and included_time_window named tuple fields are unpopulated for performance, while the methods fully resolve the value by loading included_partition_keys as time windows. This PR (admittedly confusingly) renames the "resolution" methods" to be get_included_time_windows() and get_num_partitions() to be called when the resolved value is needed.

I'm concerned that this makes it easy for a caller to get `get_included_time_windows` and `included_time_windows` confused. I wonder if there are ways we can mitigate this? I think the most principled thing might be to have two different classes, one based on partition keys and one based on partition keys and the other based on time windows. Could chat through how this would work. If that's too gnarly, an uglier but maybe easier option could be to call the properties something like `internal_included_time_windows`.

> Removes partitions_def as a field from DefaultPartitionsSubset in order to make it serializable

Makes sense.

> Unfortunately, this means that partitions subsets methods that require the partitions def (get_partition_key_ranges, get_partition_keys_not_in_subset, etc.) now must accept a partitions def. PartitionMappings that previously just accepted a subset now must accept a partitions def too (corresponding to the subset) which requires threading the partitions def through the get_upstream... and get_downstream... methods.

Makes sense.

> Removes the MultiPartitionsSubset class

The code impact of this doesn't look so bad. Should we be worried about perf impact? Potentially means `get_partition_key_from_str` at each caller instead of on construction?

**Comment by sryza** [comment]
> This changes the concept of partition subset equivalence (since previously the partitions def needed to be the same in order to be equivalent). Not sure if there are any breakages here

What's an example of a case where they'd no longer be the same?

**Comment by clairelin135** [comment]
> Would it make sense to just override pack to do the conversion to time window-based subset and then call the superclass pack? I think it's worth explaining what's going on here to Alex and seeing how this fits into any grand theory he has of how our serdes library should work.

This sounds fine, I don't feel strongly between either option. I implemented `before_pack` because it pairs nicely with an existing `after_pack` method (where we already enable a hook)

> I'm concerned that this makes it easy for a caller to get get_included_time_windows and included_time_windows confused. I wonder if there are ways we can mitigate this? I think the most principled thing might be to have two different classes, one based on partition keys and one based on partition keys and the other based on time windows. Could chat through how this would work. If that's too gnarly, an uglier but maybe easier option could be to call the properties something like internal_included_time_windows.

Definitely agree that this is confusing and not a desirable endstate. I'll take a stab and see if it's easy to separate into two classes

> The code impact of this doesn't look so bad. Should we be worried about perf impact? Potentially means get_partition_key_from_str at each caller instead of on construction?

I'm not worried about performance here. That method just splits the string wherever there is the "|" delimiter to create a MultiPartitionKey, it doesn't do any validation.

Previously we called it for every multipartitions subset on construction, but looking at it now, it seems like the places where we actually need the `MultiPartitionKey` are pretty isolated. Would not be surprised if we ended up with net fewer calls than before

> What's an example of a case where they'd no longer be the same?

I.e. if you created two subsets from different partitions defs `DefaultPartitionsSubset({"a", "b", "c"})` where the keys exist in both partitions defs.

Previously it would return False (because the partitions defs are different) but now it returns true

**Pull request closed without merging**
