### PR TITLE
[DA] Rename AutoMaterializeSensorDefinition

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

As title. Decided not to touch the SensorType stuff here, as that's not user facing.

### CODE REVIEW

**Comment by OwenKephart** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22879?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22880** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22880?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#22879** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22879?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#22863** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22863?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by erinkcochran87 — COMMENTED** [review]
Should the API docs also be updated here? Specifically, in `/docs/sphinx/sections/api/apidocs/assets.rst`, in the **Auto-materialize and freshness policies** section.

**Comment by OwenKephart** [comment]
> Should the API docs also be updated here? Specifically, in `/docs/sphinx/sections/api/apidocs/assets.rst`, in the **Auto-materialize and freshness policies** section.
> 

Whoops good call, updated!

**Comment by erinkcochran87** [comment]
Did the API doc changes get pushed? I don't see them in the files list

**Comment by OwenKephart** [comment]
@erinkcochran87 🤦 my bad, forgot to push

**Comment by erinkcochran87** [comment]
All good - it looks like you'll also need to run `make apidoc-watch-build` to rebuild the other Sphinx files. Happy to run this for ya and push up the files if that helps.

**Review by erinkcochran87 — APPROVED** [review]
🎉

**Comment by OwenKephart** [comment]
### Merge activity

* **Jul 19, 1:14 PM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22879).

**Pull request merged**
