### PR TITLE
Install ipython dagster kernel if not present

### LINKED ISSUE #908: Dagstermill tests fail on a fresh install when no kernel "dagster" is available
See also #839 

```2019-03-13 11:12:10 - dagster - ERROR - orig_message="There was an error when Papermill tried to execute the notebook. The process stderr is 'b'Traceback (most recent call last):\\n  File \"/Users/max/.virtualenvs/dagster/bin/papermill\", line 10, in <module>\\n    sys.exit(papermill())\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/click/core.py\", line 764, in __call__\\n    return self.main(*args, **kwargs)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/click/core.py\", line 717, in main\\n    rv = self.invoke(ctx)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/click/core.py\", line 956, in invoke\\n    return ctx.invoke(self.callback, **ctx.params)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/click/core.py\", line 555, in invoke\\n    return callback(*args, **kwargs)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/papermill/cli.py\", line 165, in papermill\\n    cwd=cwd,\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/papermill/execute.py\", line 96, in execute_notebook\\n    start_timeout=start_timeout,\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/papermill/engines.py\", line 56, in execute_notebook_with_engine\\n    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/papermill/engines.py\", line 296, in execute_notebook\\n    nb = cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/papermill/engines.py\", line 352, in execute_managed_notebook\\n    preprocessor.preprocess(nb_man, kwargs)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/papermill/preprocess.py\", line 24, in preprocess\\n    with self.setup_preprocessor(nb_man.nb, resources, km=km):\\n  File \"/Users/max/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py\", line 112, in __enter__\\n    return next(self.gen)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py\", line 297, in setup_preprocessor\\n    self.km, self.kc = self.start_new_kernel(cwd=path)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/papermill/preprocess.py\", line 37, in start_new_kernel\\n    km, kc = super(PapermillExecutePreprocessor, self).start_new_kernel(**kwargs)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py\", line 246, in start_new_kernel\\n    km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/jupyter_client/manager.py\", line 246, in start_kernel\\n    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/jupyter_client/manager.py\", line 170, in format_kernel_cmd\\n    cmd = self.kernel_spec.argv + extra_arguments\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/jupyter_client/manager.py\", line 82, in kernel_spec\\n    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)\\n  File \"/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/jupyter_client/kernelspec.py\", line 236, in get_kernel_spec\\n    raise NoSuchKernel(kernel_name)\\njupyter_client.kernelspec.NoSuchKernel: No such kernel named dagster\\n''" log_message_id="806aa399-fed4-428e-b40e-5c1c52b247cf" log_timestamp="2019-03-13T18:12:10.149381" run_id="948fd09e-ec2f-4b25-a946-d34bf6e40f96" pipeline="repo_registration_error" step_key="no_repo_reg.transform" solid="no_repo_reg" solid_definition="no_repo_reg"```

### PR DESCRIPTION
**Pull request by mgasner**
Resolves #908

### CODE REVIEW

**Comment by schrockn** [comment]
we should document what is going on here. this is only for the development environment correct? we don't assume the "dagster" kernel name in the dagstermill core

**Comment by mgasner** [comment]
Dagstermill tests invoke notebooks that look for an ipython kernel called dagster -- if this is not already present, then the tests fail with a cryptic error (#839). In the status quo, this will generally happen on first download / install -- with this diff, that kernel is created if it is not already present before tests run.

**Comment by mgasner** [comment]
ping @schrockn

**Comment by schrockn** [comment]
So we are committing to the fact that the user must have a hardcoded kernel named dagster in the system?

**Comment by mgasner** [comment]
I could look for a kernel named dagster, and if we don't find one, then overwrite the kernel in the test notebooks with a kernel that they do have (?) -- then rewrite it at test cleanup.

**Comment by mgasner** [comment]
https://github.com/nteract/papermill/issues/338

**Comment by schrockn** [comment]
Where would be a good spot to communicate to the user what we are doing. Somewhere that prints out "We have automatically created a kernel named "dagster". <Insert some explanation of what a kernel is. If you have your own kernels you want to use, please edit the notebook to do it"

Or something of the sort.

**Comment by mgasner** [comment]
I've added a warning... the nice thing about warnings is they do print by default in pytest.

**Pull request merged**
