### PR TITLE
AssetsDefinition property name changes

### PR DESCRIPTION
**Pull request by sryza**
### Summary & Motivation

* group_names -> group_names_by_key
* asset_keys_by_input_name -> keys_by_input_name
* asset_keys_by_output_name -> keys_by_output_name

### How I Tested These Changes

bk

### CODE REVIEW

**Review by OwenKephart — COMMENTED** [review]
I think this makes sense. I wonder if we could make our lives easier by changing all these args to "..._by_key" (in the same vein as the other pr)

just seems so wordy if you want to set all these parameters manually

**Comment by shalabhc** [comment]
This makes sense. From buildkite, there's a couple of fixes needed in asset_layer and test_external_data

**Review by shalabhc — COMMENTED** [review]
Added a comment.

**Review by OwenKephart — APPROVED** [review]
nice

**Pull request merged**
