### PR TITLE
feat(metadata): mark column lineage as experimental

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
We should let column lineage stabilize for at least a minor release.

## How I Tested These Changes
N/A

### CODE REVIEW

**Comment by rexledesma** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20756?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#20756** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20756?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#20697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20697?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#20696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20696?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#20695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20695?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#20682** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20682?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rexledesma and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rexledesma — COMMENTED** [review]
Adding experimental warnings on metadata is incredibly noisy for the user.

To reduce the noise, I'll only mark `TableMetadataEntries` and `TableColumnLineage` as experimental, which are the main user entrypoints.

If users decide to plug into this API themselves, they will be met with experimental warnings.

In dbt, we could also consider suppressing the experimental warning for each materialization event, in favor of a single experimental warning at CLI invocation time.

**Comment by sryza** [comment]
> To reduce the noise, I'll only mark TableMetadataEntries and TableColumnLineage as experimental, which are the main user entrypoints.

Makes sense. `TableMetadataEntries` isn't yet public, so I don't think we need to mark it experimental.

> In dbt, we could also consider suppressing the experimental warning for each materialization event, in favor of a single experimental warning at CLI invocation time.

Yeah I think an experimental warning per event would definitely be too much.

I'm wondering if we should entirely suppress experimental warnings at all for column lineage dbt?

Aside from column lineage, is/should the column schema stuff be considered experimental?  If not, it seems undesirable that someone turning on column schema would get hit with experimental warnings (because column lineage also gets turned on).

In general, the value of raising experimental warnings is that it gives us license to make future breaking changes. I imagine that we might want to changes to the `TableColumnLineage` API, but having more trouble imagining what breaking changes a dbt user would encounter.

**Comment by rexledesma** [comment]
Ok, I'm only adding `TableColumnLineage` to experimental.

And I agree with you -- column lineage in dbt is an implementation detail for our users, so they should be sheltered from whatever (experimental) changes are happening in the backend. I completely suppressed the experimental warning there.

**Review by sryza — APPROVED** [review]

**Comment by rexledesma** [comment]
### Merge activity

* **Mar 28, 1:13 PM PDT**: @rexledesma merged this pull request with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/20756).

**Pull request merged**
