### PR TITLE
[gql] Add user tag to reported runless event

### PR DESCRIPTION
**Pull request by clairelin135**
This PR tags runless events reported via graphQL with a tag corresponding to the cloud user. This enables displaying which user reported a specific event.

Prior, the user tag was only used on runs. This PR is the first place where we will begin storing the user tag on events.

Test added in internal: https://github.com/dagster-io/internal/pull/7122

### CODE REVIEW

**Comment by clairelin135** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17019** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17019" target="_blank">Graphite</a> 
    * **PR #17042** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17042" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17042?utm_source=stack-comment).

**Review by sryza — COMMENTED** [review]
Any idea why we chose not to use the system tag prefix for the user tag? I'm wondering if we should use the prefix on the materialization even if we don't use it on the runs.

**Comment by clairelin135** [comment]
@sryza to my knowledge it was an oversight from long ago. I'm happy to use the prefix on the events

**Comment by clairelin135** [comment]
Actually, not sure if we should use a new tag... 

We would have to fork implementation to apply a different tag to events vs runs/backfills, and then also handle the read side differently too which could cause confusion

**Comment by sryza** [comment]
I thought about this a little more and I think the clearest tag might actually be something like "dagster/reporting_user" or "dagster/user_who_reported". This makes it clear that the user is the user who reported the materialization, not the user who kicked off the computation that carried out the materialization.

**Comment by sryza** [comment]
> But in case if we decided to tag events in the future, I would ideally like the same tag on each event

Can you describe this case that you're imagining in a little more detail? What would the relationship between the user and the event be?

**Comment by clairelin135** [comment]
@sryza We currently tag runs with the user that launched the run, but say that we decided to also tag the event with the same user (to avoid doing a join)

**Comment by sryza** [comment]
Imagine that Alice launches a run in Airflow that materializes an asset and Bob reports that materialization in Dagster. If we're imagining a world where we have a tag that represents the person who launched the run, I think we'd want tags for both Alice and Bob on the event.

E.g. 
```
{
    "dagster/launching_user": "alice",
    "dagster/reporting_user": "bob",
}
```

**Comment by clairelin135** [comment]
It makes sense that we'd want to enable people to log who launched vs reported an event. 

However, IMO asset event tags are a way to persist dagster-constructed execution metadata, and it feels a bit odd to add `launching_user` when Dagster isn't aware of the run's existence. I think `launching_user` would make more sense as event metadata, since the user needs to explicitly populate that data

**Comment by sryza** [comment]
> I think launching_user would make more sense as event metadata, since the user needs to explicitly populate that data

Interesting point. When I first read this, it sounded right to me. When I started to think about some other situations though, I had second thoughts.

Imagine that, when reporting a materialization, a user wants to be able to tell us what code version that materialization.  And they want that code version to be treated like any other code version, for purposes of showing labels on the asset graph, etc.

I would think that we'd want that reported code version to to go in the system code version tag.

I.e. one way to think about asset materialization tags is that we could alternatively have made them properties on `AssetMaterialization`. We allow the `description` and `partition_key` properties to be set when an event is reported, so I think it's reasonable to allow other properties to be set as well.

**Comment by clairelin135** [comment]
I agree that we should allow the user to specify tags like code version / partition key. 

I'm resistant though to defining `launching_user` as a tag because I think the use case is narrow: (a) I don't imagine us needing to query for it independently of the event and (b) in many cases it won't make sense to specify in the context of reported events (i.e. some data already exists in a table, so there wasn't an external run). I think we could probably get away with it just being metadata that the user conditionally supplies if desired

That being said, I do agree that `dagster/reporting_user` is clearer -- I'm open to `dagster/user` or `dagster/reporting_user`or `user` (to reduce surface area)

**Comment by sryza** [comment]
> I'm resistant though to defining launching_user as a tag because I think the use case is narrow: (a) I don't imagine us needing to query for it independently of the event and (b) in many cases it won't make sense to specify in the context of reported events (i.e. some data already exists in a table, so there wasn't an external run). I think we could probably get away with it just being metadata that the user conditionally supplies if desired

Yeah I don't think this is something we need to decide on now.  My main point was that I wanted to go with a name here that makes it clear that the user we're tracking in this PR _not_ the launching user.

> That being said, I do agree that dagster/reporting_user is clearer -- I'm open to dagster/user or dagster/reporting_useror user (to reduce surface area)

Let's go with `dagster/reporting_user` (or something similar with the same meaning if you have a better idea), so that the relationship between the user and the materialization is unambiguous.

**Review by sryza — APPROVED** [review]

**Pull request merged**
