### PR TITLE
Fix intro docs

### PR DESCRIPTION
**Pull request by adeboyed**

### CODE REVIEW

**Comment by jamiedemaria** [comment]
cc @erinkcochran87  - when i run the tutorial install command, i just get a folder named `tutorial` (ie not `tutorial_project` or `my_tutorial_project` - can you confirm what the right name should be?

**Comment by erinkcochran87** [comment]
@jamiedemaria Yep, I also get `tutorial`:

```
erincochran@erins-mbp Desktop % dagster project from-example --example tutorial
Downloading example 'tutorial'. This may take a while.
Success! Created tutorial at /Users/erincochran/Desktop/tutorial/.
```

**Comment by jamiedemaria** [comment]
ok, i updated the PR to reflect the `tutorial` name. @erinkcochran87  the doc deploy on this (and another community pr) are failing with a git issue. I already tried rebasing the prs and that hasn't helped. Any other ideas for things to try?

**Review by erinkcochran87 — APPROVED** [review]

**Comment by erinkcochran87** [comment]
@jamiedemaria Thanks for doing that! To fix that deploy issue, I usually pull in the latest from master and then push again - it almost always fixes it for me.

As long as BK is green, this should be good to go. The docs deploy step is just a preview of the site and won't have any impact on the build.

**Pull request merged**
