### PR TITLE
feat(dbt): enforce all-or-nothing opt-in for asset checks

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
As the title.

## How I Tested These Changes
pytest

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16852** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16852" target="_blank">Graphite</a>  👈
    * **PR #16801** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16801" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16852?utm_source=stack-comment).

**Comment by rexledesma** [comment]
> If this is a global setting, might it make sense as an argument to dbt_assets or somehow on the DagsterDbtTranslator, instead as test-level config?

We could probably consider adding it to `DagsterDbtTranslator`, since that's already threaded through the system. That should probably go into its own change though.

**Comment by sryza** [comment]
> We could probably consider adding it to DagsterDbtTranslator, since that's already threaded through the system. That should probably go into its own change though.

With that change, would we also need this change?

**Comment by rexledesma** [comment]
Unless we want to break users who have been enabling asset checks using their dbt project's metadata, we will still need this change.

**Comment by sryza** [comment]
> Unless we want to break users who have been enabling asset checks using their dbt project's metadata, we will still need this change.

I think we should be comfortable breaking them if we think it's the right direction. We expect users who sign up to be design partners for features before their public release to be able to sustain breaking changes to those features.

**Pull request closed without merging**
