### PR TITLE
:loud_sound: return the missing debub log message when loading partitions with PolarsDeltaIOManager

### PR DESCRIPTION
**Pull request by danielgafni**
## Summary & Motivation

This log message was accidentally removed in my last dagster-polars PR. Fixing this.

### CODE REVIEW

**Review by garethbrickman — APPROVED** [review]

**Comment by danielgafni** [comment]
Yep I know, unfortunately, my dev setup is broken right now + I'm moving right now, so might take a while to do it

**Comment by danielgafni** [comment]
@garethbrickman I'm back! :)

**Comment by garethbrickman** [comment]
@danielgafni 

```
FAILED dagster_polars_tests/test_deltalake.py::test_polars_delta_io - TypeError: dataframe contains unsupported data types: {Null}
--
FAILED dagster_polars_tests/test_polars_delta.py::test_polars_delta_io_manager - pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

**Comment by danielgafni** [comment]
Uhh, probably a polars update... will take a look

**Comment by danielgafni** [comment]
Apologies for the wrong label, I messed up git. The label can be removed now.

**Comment by danielgafni** [comment]
Tests passing locally

**Pull request merged**
