### PR TITLE
Solving issue #17409 with InputContext and Multipartitions

### PR DESCRIPTION
**Pull request by cyberosa**
## Summary & Motivation
A bug was detected when implementing MultiPartitionsDefinition with one time-partitioned dimension. The input context was not able to access the start and end time of the partitioned asset. The issue was reported and explained here:

https://github.com/dagster-io/dagster/issues/17409

## How I Tested These Changes
The proposed change is easy and it was tested with the same multipartition implementation that was giving the error before. I can access the start and end time of the partitioned asset from the input context, the same as from the output context.

### CODE REVIEW

**Comment by sryza** [comment]
@clairelin135 mind taking a look at this one?

**Review by clairelin135 — COMMENTED** [review]
Hey @cyberosa thanks for adding this fix!

This looks good, but it would be nice to add a test before merging to preserve this behavior. Would you mind adding a test? `dagster/python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py` is probably a good spot for it

**Comment by cyberosa** [comment]
Ok. Cool. Will work on it this weekend.

**Comment by cyberosa** [comment]
I added a test and it runs perfectly on my local. Let me know @clairelin135 if I am missing sth here :)

**Comment by clairelin135** [comment]
@cyberosa this looks great to me! I added a commit that adds formatting. Will merge once tests pass.

**Comment by cyberosa** [comment]
Thanks for accepting it. It was my pleasure to contribute and it will be probably not the last time :)

**Pull request merged**
