### PR TITLE
pin deltalake

### PR DESCRIPTION
**Pull request by clairelin135**
Deltalake 0.19.0 is causing test failures: https://buildkite.com/dagster/dagster-dagster/builds/90827#0191576f-e904-4619-9cfd-5afeba81a258

### CODE REVIEW

**Comment by clairelin135** [comment]
* **#23681** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23681?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @clairelin135 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ion-elgreco** [comment]
@clairelin135 pass delta_write_options={"writer_engine": "rust"} and they will work.

**Review by sryza — APPROVED** [review]

**Comment by alangenfeld** [comment]
missed this PR, made https://github.com/dagster-io/dagster/pull/23708

**Review by alangenfeld — CHANGES_REQUESTED** [review]
handled in previous linked PR

**Comment by clairelin135** [comment]
@alangenfeld sounds good, thanks

**Pull request closed without merging**
