### PR TITLE
[blueprints] Add CLI command to generate JSON schemas

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Adds a CLI entrypoint for the `dagster-blueprints` package, and implements a command which loads `YamlBlueprintsLoader` objects from a provided module (or the current Dagster project, via `pyproject.toml`) and generates the corresponding JSON schemas for the Blueprint types they specify.

## Test Plan

Unit test.

### CODE REVIEW

**Comment by benpankow** [comment]
* **#22186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22186?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#22369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22369?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by benpankow** [comment]
* **#22186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22186?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#22369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22369?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — COMMENTED** [review]
I think we should provide a simple version of this that just prints the JSON schema to standard out. At least in some situations, it will be nice to have this simple utility without too many moving parts. Users can take the question of where to put it into their own hands - or just pipe it into `less` and inspect it.

We should also provide the fancier thing, but might be simplest to start with the print-y thing, to get the basics in place before needing to debate where the files should go and what they should be called.

**Comment by benpankow** [comment]
> I think we should provide a simple version of this that just prints the JSON schema to standard out. At least in some situations, it will be nice to have this simple utility without too many moving parts. Users can take the question of where to put it into their own hands - or just pipe it into `less` and inspect it.
> 
> We should also provide the fancier thing, but might be simplest to start with the print-y thing, to get the basics in place before needing to debate where the files should go and what they should be called.

the tricky part here is that each loader produces a different schema - are you envisioning a CLI where the user has to provide the module to load and a specific loader name?

**Comment by sryza** [comment]
>  are you envisioning a CLI where the user has to provide the module to load and a specific loader name?

right. and if there's just one loader in the module they wouldn't need to provide the name

**Comment by benpankow** [comment]
Added in #22479!

**Pull request closed without merging**
