### PR TITLE
Reorganize dsl example into subfolders

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Reorganizing files that each DSL variant will live in its own folder.

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by schrockn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16117** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16117" target="_blank">Graphite</a>  👈
    * **PR #16118** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16118" target="_blank">Graphite</a> 
      * **PR #16119** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16119" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16117?utm_source=stack-comment).

**Review by slopp — COMMENTED** [review]
Lgtm 

though I personally prefer to make the example an installable package and then use an absolute import instead of a relative one since users often mess up their working directory while trying stuff out

**Comment by schrockn** [comment]
@slopp this is an installable package. See the test cases that import like: `from examples.experimental.assets_yaml_dsl.assets_yaml_dsl.domain_specific_dsl.stocks_dsl`

Is there some other spot where absolute imports could be used?

**Review by alangenfeld — APPROVED** [review]
stamp

**Comment by schrockn** [comment]
### Merge Activity

* **Aug 28, 1:32 PM**: @schrockn started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16117).

**Pull request merged**
