### PR TITLE
refactor(metadata): sort and de-duplicate `deps_by_column`

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
Title says all.

## How I Tested These Changes
pytest

### CODE REVIEW

**Comment by rexledesma** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20695?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#20697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20697?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#20696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20696?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#20695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20695?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#20682** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20682?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rexledesma and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — COMMENTED** [review]
Elsewhere in the system, we use sequences for lists of dependencies. E.g.
- `AssetSpec.deps`
- `ExternalAssetNode.dependencies`

`DependencyMapping` is a little different and uses a dict: `Mapping[T_DependencyKey, Mapping[str, "IDependencyDefinition"]]`

An advantage those approaches is that it gives us to opportunity to add additional fields to dependency objects.  I think it's probably worth preserving that optionality here.

**Comment by rexledesma** [comment]
Ok I'm fine with keeping it a sequence. I'll just do the de-duplication and sorting when the object is instantiated.

**Comment by rexledesma** [comment]
@sryza I realized your feedback wasn't related to whether `deps` was an `Set` or `Sequence`. It was about having an intermediate object.

I added that intermediate object in the form of `TableColumnLineageInput`. Still going to refactor `deps` as an `FrozenSet` though.

**Comment by sryza** [comment]
I think the concern I raised in my original comment still does apply here. I.e. if we wanted to add additional fields to the dependency object, I think using a set would still bite us.

What's the advantage of adding an intermediate object?

**Comment by rexledesma** [comment]
> I think the concern I raised in my original comment still does apply here. I.e. if we wanted to add additional fields to the dependency object, I think using a set would still bite us.

I'm not following why a set would bite us -- the objects in the set are serializable tuples, so they always have to be hashable anyways. So a set would always work.

I essentially want the `Sequence[TableColumnDep]` to be unique by asset_key/column_name. And being able to compare two `Sequence[TableColumnDep]` for equality without needing to convert both to some unordered representation would be nice for testing.

> What's the advantage of adding an intermediate object?

I'm thinking about the scenario if we want to track the lineage of column-tagged metadata (e.g. PII). But maybe that could live on the `TableColumnDep` object itself.

**Comment by sryza** [comment]
> I'm not following why a set would bite us -- the objects in the set are serializable tuples, so they always have to be hashable anyways. So a set would always work.

It wouldn't bit us by erroring, but the set would no longer meaningfully dedupe if it had both `TableColumnDep(asset_key=x, column_name=y, partition_mapping=z1)` and `TableColumnDep(asset_key=x, column_name=y, partition_mapping=z2)`

**Comment by rexledesma** [comment]
> > I'm not following why a set would bite us -- the objects in the set are serializable tuples, so they always have to be hashable anyways. So a set would always work.
> 
> It wouldn't bit us by erroring, but the set would no longer meaningfully dedupe if it had both `TableColumnDep(asset_key=x, column_name=y, partition_mapping=z1)` and `TableColumnDep(asset_key=x, column_name=y, partition_mapping=z2)`

Ahhh got it -- ok I think I was very confused when you mentioned:

> DependencyMapping is a little different and uses a dict: Mapping[T_DependencyKey, Mapping[str, "IDependencyDefinition"]]

I thought you were recommending having something equivalent to a `dict` (which I interpreted as an intermediate object)

Apologies for the back and forth here. Will go back to the ordered + de-duplicated `Sequence`

**Review by sryza — APPROVED** [review]
Nice

**Comment by rexledesma** [comment]
### Merge activity

* **Mar 27, 11:18 AM PDT**: @rexledesma merged this pull request with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/20695).

**Pull request merged**
