### PR TITLE
Add API methods to Datadog integration

### PR DESCRIPTION
**Pull request by shivonchain**
## Summary & Motivation

This PR addresses #8050 by adding the `api` submodule from `datadogpy`. This allows users of the `dagster-datadog` library to use Datadog directly via `api` methods instead of having to rely on `dogstatsd` to push metrics to Datadog.

## How I Tested These Changes

I followed the directions outlined in CONTRIBUTING.md to test the project. There were some failing tests which seem unrelated to the changes in this PR.

### CODE REVIEW

**Comment by alangenfeld** [comment]
can you add a test in `python_modules/libraries/dagster-datadog/dagster_datadog_tests/test_resources.py` ? 

looks like we dont set a floor version for `datadog` in `setup.py`. Do you know if this `api` import has been available for a long time?

**Comment by shivonchain** [comment]
Thanks @alangenfeld I'll look into adding tests.

> looks like we dont set a floor version for `datadog` in `setup.py`. Do you know if this `api` import has been available for a long time?

Going off the commit history it looks like it has been around for a while.

**Comment by shivonchain** [comment]
@alangenfeld is it acceptable to modify the existing `assert_datadog_client_class()` function this way:

```python
#...

datadog_client.api.Event.create(title="Something happened!", text="Event text", tags=["version:1", "application:web"])
Event.create.assert_called_with(title="Something happened!", text="Event text", tags=["version:1", "application:web"])

datadog_client.api.Event.query(start=1313769783, end=1419436870, priority="normal", tags=["application:web"])
Event.query.assert_called_with(start=1313769783, end=1419436870, priority="normal", tags=["application:web"])

# add other classes from datadog.api: Metric, Distribution, ServiceCheck, Metadata below
# ...
```

and add `@mock.patch("datadog.api.Event")` to each test below? Let me know if I am on the right track.

I also realize `Event` from `datadog.api` may get confused with `event` from `datadog.statsd`. I am just mirroring the naming from `datadogpy` API, but open to any guidance here too.

**Comment by alangenfeld** [comment]
extending the existing pattern for tests should be fine. Make sure to run `make ruff` in the repo root to fix formatting.

**Comment by shivonchain** [comment]
Thanks @alangenfeld !

**Review by alangenfeld — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
