### PR TITLE
[blueprints] add properties for source file info

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Small PR which adds property getters to the `Blueprint` class to grab things like the source file name.

### CODE REVIEW

**Comment by benpankow** [comment]
* **#22180** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22180?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sryza — COMMENTED** [review]
Thoughts on making these properties of `HasSourcePositionAndKeyPath`?

**Comment by benpankow** [comment]
> Thoughts on making these properties of `HasSourcePositionAndKeyPath`?

good call

**Review by sryza — APPROVED** [review]
Nice

**Pull request merged**
