### PR TITLE
[ruff] Enable D415 (docstring period)

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

Turns on Ruff `D415` docstring header punctuation (required by Google-style docstrings). This was supposed to be turned on in the past (see https://github.com/dagster-io/dagster/pull/11001) but I had not finished correcting the old violations in part because IIRC the autofix at the time was bugged for some cases. Autofix works well now so we can have this on, ensuring docstrings shown in docs and LSP service are well-formatted, with little-to-no additional effort required for devs.

In a few cases I had to add a suitable header docstring if the existing one wasn't a summary.

---

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12889** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12889" target="_blank">Graphite</a> 
    * **PR #12890** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12890" target="_blank">Graphite</a> 
      * **PR #12891** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12891" target="_blank">Graphite</a> 
        * **PR #12892** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12892" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12892?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #12889** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12889" target="_blank">Graphite</a> 
    * **PR #12890** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12890" target="_blank">Graphite</a> 
      * **PR #12891** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12891" target="_blank">Graphite</a> 
        * **PR #12892** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12892" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12892?utm_source=stack-comment).

**Review by alangenfeld — APPROVED** [review]

**Comment by smackesey** [comment]
@smackesey queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12892).

**Comment by smackesey** [comment]
[Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12892) rebased this pull request as part of a merge.

**Comment by smackesey** [comment]
@smackesey merged this pull request with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12892).

**Pull request merged**
