### PR TITLE
Adjust how we describe empty gaps in the AMP timeline

### PR DESCRIPTION
**Pull request by gibsondan**
Summary:
We are moving to a world where evaluation IDs don't auto-increment by 1 for each tick, and it's not clear that showing the exact number of evaluations is that useful (esp now that we have a timeline view with per-tick information). So instead of showing "2k evaluations", show "From time A to time B".

### CODE REVIEW

**Comment by gibsondan** [comment]
image

**Comment by OwenKephart** [comment]
If you have the following sequence:

Tick 1: `launched`
Tick 2: nothing
Tick 3: nothing
...
Tick 20: nothing
Tick 21: `launched`

Then I'd argue that if you were going to give a time range for when "nothing happened" (to populate this A -> B statement), that time range would be:

A = end time of Tick 1 (as no matter when tick 2 starts, we know nothing happened between the end of tick 1 and the start of tick 2)
B = end time of Tick 20 (as we can't know when exactly something happened, we just know that it happened between the end of Tick 20 and the start of Tick 21) However, it's not the end of the world if this is just computed as the start time of Tick 21, as we generally won't have easy access to the end time of Tick 20

All that's to say that I think the added information we get from giving absolute timestamps is fairly limited (as at least the A time is going to be duplicated, and the B timestamp will generally be quite similar to the next one), and is a bit messy visually. Instead, we could just compute the time difference and give a subtler `24 hours, no conditions changed` message.

**Comment by gibsondan** [comment]
that makes sense... i'm sure we have some utility function that takes in two timestamps and produces such a string but I don't immediately know where, maybe other reviewers on this PR do

**Review by bengotow — APPROVED** [review]

**Comment by gibsondan** [comment]
@bengotow any thoughts on the question in the comments about adjusting the text to describe the relative time vs. the absolute difference?

**Comment by bengotow** [comment]
Ahh sorry I missed the discussion @gibsondan  - I think I agree with Owen. In general, the absolute times aren't super interesting and seem overly detailed if you can infer the general time range by looking at the ticks on each side of the gap manually.

Maybe you could use this code (from AssetMaterializationUpstreamData.tsx)?

```
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);

// need to double check that endTimestamp is in milliseconds here
dayjs(evaluation.endTimestamp).from(evaluation.startTimestamp, true /* true removes the "ago" suffix */)
```

**Comment by gibsondan** [comment]
Hmmm I tried this and it looks a little weird to me still 
image

**Comment by gibsondan** [comment]
Latest take is to remove the "nothing changed" rows altogether: 
image

**Review by bengotow — APPROVED** [review]
The code changes here look great to me, I think the screenshot you posed looks good @gibsondan, and it's also nice that the code is so much simpler with the empty tick spans removed.

**Comment by sryza** [comment]
@gibsondan is the description here still accurate? Asking because a user is experiencing difficulty with the design prior to this PR, so wanted to link this to them.

**Comment by gibsondan** [comment]
I updated it a bit to make it more accurate (originally we were showing the relative time between evaluations where something changed, now we just leave out the rows that were basically saying that nothing has changed)

**Pull request merged**
