### PR TITLE
0.2.8.post0 hot fix - remove config value logging when invalid config value occurs

### PR DESCRIPTION
**Pull request by Aylr**
## What's Here

* bump version to 0.2.8.post1
* add tox to dev-requirements

## Known Issues

- I'm not sure what branch to issue this PR against.

### CODE REVIEW

**Comment by schrockn** [comment]
We'll need to fix the 0.2.8.post0 tag, branch off of that, and then merge this PR into that branch.

**Comment by schrockn** [comment]
This looks eminently reasonable though! I'll make the same change in 0.3.xx

**Comment by Aylr** [comment]
I'm happy to do any of that legwork, with a little guidance. What do you mean "fix the tag"?

**Comment by Aylr** [comment]
This was branched from the tag v0.2.8.post0

**Comment by schrockn** [comment]
Oh what I mean is that this change should not be merged back into master. We should make a branch called "0.2.8.post1" branched off of the git hash of the commit tagged "v0.2.8.post0". This PR should be based of off branch 0.2.8.post1

**Comment by Aylr** [comment]
Done. Thanks for the guidance.

**Comment by schrockn** [comment]
Released has been pushed to pypi. Typically it takes pypi about 5 mins to clear some sort of DNS caching before it's installable.

**Comment by schrockn** [comment]
https://pypi.org/manage/project/dagster/release/0.2.8.post1/

**Pull request merged**
