### PR TITLE
Return storage ID when adding to the event log

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Bubble up storage ID returned when inserting into the event log

## Test Plan

New event storage suite test

### CODE REVIEW

**Comment by benpankow** [comment]
* **#23206** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23206?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by prha** [comment]
I think one area where this would get a little confusing is that we have two different storage ids for events in sqlite, depending on whether it refers to the run shard or the index shard.

I think most of the time, we would to return the index shard storage id for things like asset, run status events.

**Comment by prha** [comment]
As discussed, I think one thing we can do here is make the type signature return an `Optional[int]`.  In the SQLite case, we can return the index shard storage id for asset events, and return `None` for all the run-sharded storage ids.

We'll have to handle the `None` case from a typing perspective inside of the sensor, but even with the SQLite implementation, the asset events should have non-None storage ids that should be stable with our `fetch_X` APIs.

**Review by gibsondan — DISMISSED** [review]
for @prha's feedback which seems reasonable to me

**Comment by benpankow** [comment]
Updated & added unit test for sqlite storage to ensure that we don't erroneously return an event ID for non-asset events

**Review by gibsondan — APPROVED** [review]

**Pull request merged**
