### PR TITLE
unpin pendulum in dagster-airflow

### PR DESCRIPTION
**Pull request by sryza**
## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by alangenfeld — APPROVED** [review]
The internal compat failure is from rebase issue - think this is good to go

**Review by prha — CHANGES_REQUESTED** [review]
I think our tests are probably still running 1.4.4, due to the tox pin

**Comment by prha** [comment]
Can you get rid of the pin in `examples/airflow-ingest` and rerun?

**Comment by sryza** [comment]
> Can you get rid of the pin in `examples/airflow-ingest` and rerun?

👍

**Pull request merged**
