### PR TITLE
[docs] Add apidocs for dagster definitions validate

### PR DESCRIPTION
**Pull request by maximearmstrong**
## Summary & Motivation

As title

## How I Tested These Changes

Docs preview

## Changelog

[dagster-cli] A guide on how to validate Dagster definitions using `dagster definitions validate` have been added.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [x] `DOCS` _(added or updated documentation)_

### CODE REVIEW

**Comment by maximearmstrong** [comment]
* **#24815** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24815?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by PedramNavid — COMMENTED** [review]
Thanks for creating this Maxime!

One thing I am not sure about is if this command needs an entire guide, I think it would be better to document this within the CLI as API docs instead. 

For example, the debug command is documented here: https://github.com/dagster-io/dagster/blob/89431cdf20e557ed9d232ba7bd417c7cccb7fbc0/python_modules/dagster/dagster/_cli/debug.py#L34

My concern with having this as a guide is that it's a pretty niche use case and it's a simple enough command that API docs should serve us well. Let me know what you think.

**Comment by maximearmstrong** [comment]
> My concern with having this as a guide is that it's a pretty niche use case and it's a simple enough command that API docs should serve us well. Let me know what you think.

@PedramNavid That's fair. I moved the description/guide to the API docs.

**Review by PedramNavid — APPROVED** [review]
Very nice!

**Pull request merged**
