### PR TITLE
Fix `dagster_slack` documentation examples

### LINKED ISSUE #9124: Documentation issue with `make_slack_on_run_failure_sensor` and `make_slack_on_pipeline_failure_sensor` examples
### What's the issue or suggestion?

Documentation issue with `make_slack_on_run_failure_sensor` and `make_slack_on_pipeline_failure_sensor `
They expect `text_fn` parameter but the documentation examples have `message_fn`

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by ssingh13-rms**
Fixes #9124 

### Summary & Motivation
Was implementing Slack notification on my job failures when I noticed the documentation examples for `make_slack_on_run_failure_sensor` and `make_slack_on_pipeline_failure_sensor` were using the `message_fn` parameter instead of `text_fn`.
I've been deeply impressed by Dagster and will contribute whatever I can with the time I have

### How I Tested These Changes
I didn't. Just updated a couple of documentation examples.

### CODE REVIEW

**Comment by OwenKephart** [comment]
hi @ssingh13-rms, thanks for the contribution! This fix looks great, but we actually just removed the make_slack_on_pipeline_failure_sensor (only keeping make_slack_on_run_failure_sensor), which is why you're getting the merge conflict.

If you don't mind just updating your commit to fix that conflict, I can get this merged in. Thanks again!

**Comment by ssingh13-rms** [comment]
Hi @OwenKephart, I've resolved the conflict

**Comment by ssingh13-rms** [comment]
Hi @OwenKephart, let me know if any more changes are required to get this merged!

**Review by OwenKephart — APPROVED** [review]

**Comment by OwenKephart** [comment]
hi @ssingh13-rms ! Thanks for the contribution -- I just merged this in.

**Pull request merged**
