### PR TITLE
shift pydantic upper bound to 3.0.0

### PR DESCRIPTION
**Pull request by alangenfeld**
resolves https://github.com/dagster-io/dagster/issues/26203

## How I Tested These Changes

bk

### CODE REVIEW

**Review by gibsondan — COMMENTED** [review]
2.10 rather than 3.0 was added somewhat intentionally after 2.9 broke us, fwiw

**Review by gibsondan — APPROVED** [review]
Options:

- switch to 2.11 rather than 2.10
- switch to 3.0 under the assumption that the 2.9 was a weird fluke that won't be replicated
- switch to 2.11 with a test a la https://github.com/dagster-io/dagster/blob/fd45397a7169e11582b96ef1fe6cc587817b6758/python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_version.py#L38-L45 that prompts us to remember to bump the pin proactively every time a new 2.x is released

**Comment by gibsondan** [comment]
hm some tests appear to be failing on 2.10? If they're legit would lend credence to the 'be conservative' angle

**Comment by alangenfeld** [comment]
it appears the original pinning away from `2.9.0` was due to this bug https://github.com/pydantic/pydantic/issues/10336 fixed in `2.9.1` 

Since it was a bug and not a breaking API change i am inclined to be optimistic and just have major version ceiling 

Test failures were some snapshot tests in an experimental package around how `Literal` gets encoded in the json schema.

**Pull request merged**
