### PR TITLE
fix(dbt-cloud): query run artifacts from correct step on materialization

### PR DESCRIPTION
**Pull request by rexledesma**
### Summary & Motivation
We should be querying the run artifacts from the build/run step in the dbt Cloud job. 

Otherwise, in the instance that the dbt Cloud job is generating docs, we query the run results from this generate docs step. This erroneously tells us that all the models were materialized successfully, when in fact, this may not be the case since filter options could be passed to the run/build step.

### How I Tested These Changes
existing pytest?

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10776** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10776" target="_blank">Graphite</a> 
    * **PR #10777** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10777" target="_blank">Graphite</a> 
      * **PR #10778** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10778" target="_blank">Graphite</a> 
        * **PR #10779** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10779" target="_blank">Graphite</a> 
          * **PR #10825** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10825" target="_blank">Graphite</a>  👈
            * **PR #10826** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10826" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10825?utm_source=stack-comment).

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10776** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10776" target="_blank">Graphite</a> 
    * **PR #10777** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10777" target="_blank">Graphite</a> 
      * **PR #10778** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10778" target="_blank">Graphite</a> 
        * **PR #10779** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10779" target="_blank">Graphite</a> 
          * **PR #10825** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10825" target="_blank">Graphite</a>  👈
            * **PR #10826** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10826" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10825?utm_source=stack-comment).

**Review by benpankow — APPROVED** [review]
Is there a good way we can test this?

**Comment by rexledesma** [comment]
> Is there a good way we can test this?

We could have different mocks for `run_results.json` when querying other steps, but I don't think it's a big deal right now. I can add a comment in the test suite about this.

**Pull request merged**
