### PR TITLE
Add hostname to dagster-github for GitHub enterprise users

### PR DESCRIPTION
**Pull request by metinsenturk**
## Summary

`dagster-github` package is a great way to connect GitHub to dagster. However, the current implementation only supports `github.com` users. This PR is to make `dagster-github` package usable for [Github Enterprise ](https://docs.github.com/en/enterprise-server@3.1/developers/apps/managing-github-apps/installing-github-apps)users as well.

As seen in the [GitHub Enterprise documentation](https://docs.github.com/en/enterprise-server@3.1/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-an-installation) for authenticating as an installation, the domain must be taken from the user with a slight difference in the URL.

> http(s)://[hostname]/api/v3/app/installations

This PR proposes to add an optional `hostname` variable to satisfy the functionality. Therefore you can do the below.

``` py
GithubResource(
        client=requests.Session(),
        app_id=context.resource_config["github_app_id"],
        app_private_rsa_key=context.resource_config["github_app_private_rsa_key"],
        default_installation_id=context.resource_config["github_installation_id"],
        hostname=context.resource_config.get("github_hostname", None),
)
```

## Test Plan

I added a test to receive responses from `https://github.contoso.com/api/v3/app/installations`.

## Checklist

- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by metinsenturk** [comment]
Hi! My first time so go easy on me! I have a couple more ideas regarding this package, but I think they can be a separate PR.

- An optional argument for request_kwargs on `.get()` and `.post()` methods
- At the moment `github_installation_id` has to be provided in the config even tough it is not required. 

Let me know if there are things to be updated. Cheers!

**Comment by sryza** [comment]
@metinsenturk - thanks for the contribution, and apologies for missing this.  It looks good.  Would you mind rebasing or merging in the latest master?  I think that should fix the test failures.

**Comment by metinsenturk** [comment]
> @metinsenturk - thanks for the contribution, and apologies for missing this. It looks good. Would you mind rebasing or merging in the latest master? I think that should fix the test failures.

@sryza I just did now. Let me know if there anything else comes up!

**Comment by sryza** [comment]
Thanks for the contribution @metinsenturk !

**Pull request merged**
