### PR TITLE
Allow asset observations in IO Managers

### PR DESCRIPTION
**Pull request by clairelin135**
Enables logging asset observations in `handle_output` and `load_input` methods of IO managers.

In `load_input`, observations will only be able to be logged via `context.log_event(AssetObservation("blah"))` and not via `yield`. This is because `load_input` methods are currently not generators and have a return value.

### CODE REVIEW

**Review by sryza — CHANGES_REQUESTED** [review]
I think that the main reason to log an AssetObservation inside a load_input call is to record metadata about the asset being loaded. If that's the case, then it's redundant for the user to need to specify an AssetKey when they yield the AssetObservation.

I think an ideal solution would be an analog of `OutputContext.add_output_metadata`, which automatically pulls the asset key from the asset definition.

**Comment by dpeng817** [comment]
Also fwiw, I think it is likely possible to have a return from a generator in our supported python versions, but probably more trouble than it is worth: https://stackoverflow.com/questions/16780002/return-in-generator-together-with-yield-in-python-3-3

**Comment by clairelin135** [comment]
@sryza @dpeng817 I modified this PR to exclusively handle asset observations occurring in `load_input` (removing utility for `store_output`) through a new `InputContext.observe_metadata` function on that accepts observation metadata and description. Partition and asset key are auto-populated from the `InputContext` object.

Asset observations are admittedly less useful in `store_output`, especially because you could just attach metadata entries to your materialization. I think that we don't need to implement it at the moment, though I'll defer to @sryza's judgment.

**Comment by clairelin135** [comment]
@sryza `add_output_metadata` applies to op outputs and asset materializations, so my concern with changing the name to `add_input_metadata` will mislead users into thinking that the method adds metadata to an `InputDefinition`.

I think if we want to clarify the behavior of the `observe_metadata` method, we can change the name to `observe_asset_metadata`.

**Comment by clairelin135** [comment]
@sryza -- wanted to follow up with you this. Thoughts on changing `observe_metadata` to `observe_asset_metadata`?

**Comment by sryza** [comment]
Sorry for the delay in responding here.

> my concern with changing the name to add_input_metadata will mislead users into thinking that the method adds metadata to an InputDefinition.

Is there not an analogous concern with add_output_metadata? That it would mislead users into thinking that the method adds metadata to an OutputDefinition? Arguably we should change that method name as well?

**Comment by clairelin135** [comment]
@sryza I think that `add_output_metadata` is fine, because it directly references the `Output` instance that will contain the new metadata, whereas it is unclear what input object `add_input_metadata` is referring to. I think that a clearer name is still `observe_asset_metadata` which I think most intuitively matches the behavior of the function.

**Comment by dpeng817** [comment]
Just wanted to leave my thoughts regarding `add_input_metadata`. I think that it does end up being analogous to `add_output_metadata` in the case of implicit AssetObservations? But if so, we should also make sure the metadata ends up on the HANDLED_INPUT and STEP_INPUT events.

**Comment by sryza** [comment]
Sorry for being so slow on this. I think `add_output_metadata` is referring to the general notion of the output, rather than the `Output` object.  I.e. the `output` in the `handle_output` function name (similar to the `input` in the `load_input` function name). In most cases, there won't actually be an `Output` object.

**Comment by clairelin135** [comment]
@sryza @dpeng817 ok, I'm convinced now that we should name the method `add_input_metadata`. I'm going to attach the metadata to the `loaded_input` event and test with the root input manager as well. @dpeng817 -- why `step_input` event? To me, it makes sense to attach metadata to the `loaded_input` event, but less so the `step_input` event. Similarly, `add_output_metadata` adds the metadata to the `handled_output` event, but not the `step_output` event.

**Comment by dpeng817** [comment]
@clairelin135 I believe both the step output and handled output events end up with the metadata on them. I mentioned step output, because I think that has more semantic value to the user, but perhaps handled output is more accurate to the location that the metadata is logged.

**Comment by clairelin135** [comment]
@dpeng817 Hm.. I just tried running this myself and it seems like the metadata entries are attached only to `handled_output` and not `step_output` (as this [docstring](https://github.com/dagster-io/dagster/blob/404a7c1d901a0e9394f58ca7c9bdd966f9b95517/python_modules/dagster/dagster/core/execution/context/output.py#L468) mentions)? But I think that this makes sense since it is the location where the metadata is logged, and aligns with the behavior I intuitively expect. Anyhow, I've updated the `loaded_input` event to also contain the input metadata and added tests for the root input manager.

**Review by sryza — APPROVED** [review]
lgtm! thanks for rolling with the slowness and name-nitpickness on this one

**Pull request merged**
