### PR TITLE
[RFC] feat(metadata): add table spec metadata

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
Reopening https://github.com/dagster-io/dagster/pull/20477 under my name for review/approval purposes.

- Under `NamespacedMetadataEntries` (which needs to be unpluralized), add a metadata object to store information about observed table columns and those columns' dependencies.
- Allow this metadata object to be structured when served over GraphQL

## How I Tested These Changes
pytest, stacked on https://github.com/dagster-io/dagster/pull/20569

### CODE REVIEW

**Comment by rexledesma** [comment]
@sryza responding to https://github.com/dagster-io/dagster/pull/20477#pullrequestreview-1949625389 here:

> "Spec" is general enough that I think it could be interpreted to include schema, but that's in a separate metadata value.

I agree that column schema and column dependencies should be modeled as separate metadata values.

> With AssetSpec and AssetCheckSpec, we use the word "spec" for definitions. I think this could lead to confusion.

I understand that "spec" is associated with definitions. Our metadata here is a snapshot of that "spec", as observed after materialization time. 

I initially wanted to use "spec" as to be general enough to encapsulate "column schema", "table identifier", "column tags", etc in the future. But that might not be the wisest choice, especially since we're agreeing that column schema and column dependencies should be separate metadata.

> A couple ideas for names for the top-level object that avoid these issues and also avoid plurals:
>
> - TableColumnDepMap
> - TableColumnParentage
> - TableColumnLevelParentage

Sounds like we need to get rid of the intermediate `TableColumnSpec`, and just have it be a map on the top level object, with the key being the column name.

I'm not a fan of "DepMap" or "Parentage" since the former leaks type information into the class name, and the latter is just a synonym for "Lineage".

Can we just use "Lineage", even though we're specifying just one level of dependencies of the current columns and not the full dependency tree?

In fact, OpenLineage uses "Column Lineage" in this regard: https://openlineage.io/docs/spec/facets/dataset-facets/column_lineage_facet/. 

| Current ontology | Proposal 1 (use "DepMap") | Proposal 2 (use "ColumnLineage") |
|--------|--------|--------|
| `TableSpec` | `TableColumnDepMap` | `TableColumnLevelLineage` |
| `TableColumnSpec` | `TableColumnDep` | `TableColumnDep` |
| `TableColumnDep` | - | - |

**Comment by sryza** [comment]
If I understand correctly, you're advocating for Proposal 2 (i.e. "column lineage") over Proposal 1? I buy it - let's go with that.

**Comment by rexledesma** [comment]
Cool, refactored to `TableColumnLineage` and `TableColumnDep`.

**Review by sryza — APPROVED** [review]
Nice

**Comment by rexledesma** [comment]
### Merge activity

* **Mar 20, 4:11 PM PDT**: @rexledesma started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/20597).

**Pull request merged**
