### PR TITLE
docs: make the rhs nav 'ON THIS PAGE' sticky

### PR DESCRIPTION
**Pull request by yuhan**
## Summary
two changes:
1. make the "ON THIS PAGE" sidebar sticky
2. highlight the current section in the right nav as you scroll

this should improve the site experience when digesting long content.

## Test Plan

https://user-images.githubusercontent.com/4531914/143813617-0d316481-6756-4f8f-bf35-66f8c96b1a00.mov

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by braunjj — COMMENTED** [review]
LGTM!

**Comment by sryza** [comment]
This is a great change

**Comment by prha** [comment]
for very short screens, where the RHS content overflows, what happens to the content?

**Comment by yuhan** [comment]
on short screen:
https://user-images.githubusercontent.com/4531914/144287284-d7a5a732-0476-45c6-962d-4af7f0c09141.mov

**Review by prha — APPROVED** [review]

**Pull request merged**
