### PR TITLE
Make inputs config-driven

### PR DESCRIPTION
**Pull request by schrockn**
This one thing that could be improved here is to materialize the inputs lazily.

### CODE REVIEW

**Comment by schrockn** [comment]
Rerunning tests because of periodic failure. See https://github.com/dagster-io/dagster/issues/432

**Comment by mgasner** [comment]
Going to rerun the failing check. Only last question is whether we want this in 0.3.0

**Comment by mgasner** [comment]
hm, confused by the coverage result -- would think these new lines would be covered by the tests you showed me https://coveralls.io/builds/20683461/source?filename=python_modules%2Fdagster%2Fdagster%2Fcore%2Fexecution_plan.py#L629

**Comment by schrockn** [comment]
I confirmed that the code you pointed to was executed. I replicated the tests (without the dataframe) in dagster core which should have been done anyways.

**Pull request merged**
