### PR TITLE
integration docs beta 3/ integration sidebar and landing page [DS-479]

### PR DESCRIPTION
**Pull request by yuhan**
## Summary & Motivation

this PR:
- organizes the integration sidebar into category groups
- adds a "Community Supported" section at the end
- autogenerate landing page using https://docusaurus.io/docs/sidebar/autogenerated

## How I Tested These Changes
https://dagster-docs-beta-bkrir8phx-elementl.vercel.app/integrations/

## Changelog
`NOCHANGELOG`

### CODE REVIEW

**Comment by yuhan** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24393?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24393** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24393?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#24391** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24391?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24330?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yuhan and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by slopp** [comment]
I am generally a fan of option 3 as well. As a user, I think they don't really care that much about whether an integration is community supported or not. They want the quickest path to go from "the tool I have" to "page about that tool". 

Down the road, it may be useful to signal to them that the maturity of an integration might depend a bit on who contributed it? We could signal this with another semi-redundant sidebar, as you do in option 3, or we could just note community integrations with a tag or something on their docs page.

**Comment by erinkcochran87** [comment]
**Option 1**

I like how tidy this is but I'm not sure users will have the easiest time finding things, since how we label integrations vs how they do may be different.

**Option 2**

> all flattened in dagster owned vs community supported; maybe should make the former open by default

I agree with this.

**Option 3**

I'm actually not a fan of the non-collapsible sections here, since the sidebar is so long. What if these items were open by default but still collapsible?

---

This may be overkill, but tossing it in for feedback anyway. What about something like this, which offers a few options for navigating?

```
- All integrations
  - Complete list in alphabetical order; maybe group AWS and GCP
- Type
  - ETL
  - Storage
  - Compute
  - ... rest of Option 1 sidebar
- Dagster-owned
- Community supported
```

**Comment by erinkcochran87** [comment]
**Option 1**

I like how tidy this is but I'm not sure users will have the easiest time finding things, since how we label integrations vs how they do may be different.

**Option 2**

> all flattened in dagster owned vs community supported; maybe should make the former open by default

I agree with this.

**Option 3**

I'm actually not a fan of the non-collapsible sections here, since the sidebar is so long. What if these items were open by default but still collapsible?

---

This may be overkill, but tossing it in for feedback anyway. What about something like this, which offers a few options for navigating?

```
- All integrations
  - Complete list in alphabetical order; maybe group AWS and GCP
- Type
  - ETL
  - Storage
  - Compute
  - ... rest of Option 1 sidebar
- Dagster-owned
- Community supported
```

**Review by cmpadden — APPROVED** [review]
Approved - spoke offline about limitations of using `autogenerated` for integrations that exist in two categories.

There may be a way to make this more robust moving forward. Including adding some form of validation.

**Comment by yuhan** [comment]
### Merge activity

* **Sep 18, 2:04 PM PDT**: @yuhan started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/24393).

**Pull request merged**
