### PR TITLE
[pyright] [dagster-airflow] misc

### PR DESCRIPTION
**Pull request by smackesey**
### Summary & Motivation

Pure typing PR to eliminate pyright type errors in `dagster-airflow`.

### How I Tested These Changes

BK

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank">Graphite</a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank">Graphite</a> 
        * **PR #11717** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11717" target="_blank">Graphite</a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank">Graphite</a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank">Graphite</a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank">Graphite</a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank">Graphite</a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank">Graphite</a> 
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank">Graphite</a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank">Graphite</a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank">Graphite</a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank">Graphite</a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank">Graphite</a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank">Graphite</a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank">Graphite</a> 
                                * **PR #11720** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11720" target="_blank">Graphite</a> 
                                  * **PR #11721** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11721" target="_blank">Graphite</a> 
                                    * **PR #11722** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11722" target="_blank">Graphite</a> 
                                      * **PR #11723** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11723" target="_blank">Graphite</a> 
                                        * **PR #11724** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11724" target="_blank">Graphite</a> 
                                          * **PR #11725** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11725" target="_blank">Graphite</a> 
                                            * **PR #11726** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11726" target="_blank">Graphite</a> 
                                              * **PR #11727** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11727" target="_blank">Graphite</a> 
                                                * **PR #11728** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11728" target="_blank">Graphite</a> 
                                                  * **PR #11729** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11729" target="_blank">Graphite</a>  👈
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11729?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank">Graphite</a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank">Graphite</a> 
        * **PR #11717** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11717" target="_blank">Graphite</a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank">Graphite</a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank">Graphite</a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank">Graphite</a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank">Graphite</a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank">Graphite</a> 
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank">Graphite</a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank">Graphite</a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank">Graphite</a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank">Graphite</a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank">Graphite</a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank">Graphite</a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank">Graphite</a> 
                                * **PR #11720** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11720" target="_blank">Graphite</a> 
                                  * **PR #11721** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11721" target="_blank">Graphite</a> 
                                    * **PR #11722** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11722" target="_blank">Graphite</a> 
                                      * **PR #11723** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11723" target="_blank">Graphite</a> 
                                        * **PR #11724** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11724" target="_blank">Graphite</a> 
                                          * **PR #11725** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11725" target="_blank">Graphite</a> 
                                            * **PR #11726** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11726" target="_blank">Graphite</a> 
                                              * **PR #11727** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11727" target="_blank">Graphite</a> 
                                                * **PR #11728** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11728" target="_blank">Graphite</a> 
                                                  * **PR #11729** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11729" target="_blank">Graphite</a>  👈
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11729?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank">Graphite</a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank">Graphite</a> 
        * **PR #11717** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11717" target="_blank">Graphite</a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank">Graphite</a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank">Graphite</a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank">Graphite</a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank">Graphite</a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank">Graphite</a> 
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank">Graphite</a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank">Graphite</a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank">Graphite</a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank">Graphite</a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank">Graphite</a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank">Graphite</a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank">Graphite</a> 
                                * **PR #11720** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11720" target="_blank">Graphite</a> 
                                  * **PR #11721** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11721" target="_blank">Graphite</a> 
                                    * **PR #11722** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11722" target="_blank">Graphite</a> 
                                      * **PR #11723** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11723" target="_blank">Graphite</a> 
                                        * **PR #11724** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11724" target="_blank">Graphite</a> 
                                          * **PR #11725** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11725" target="_blank">Graphite</a> 
                                            * **PR #11726** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11726" target="_blank">Graphite</a> 
                                              * **PR #11727** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11727" target="_blank">Graphite</a> 
                                                * **PR #11728** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11728" target="_blank">Graphite</a> 
                                                  * **PR #11729** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11729" target="_blank">Graphite</a>  👈
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11729?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank">Graphite</a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank">Graphite</a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank">Graphite</a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank">Graphite</a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank">Graphite</a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank">Graphite</a> 
        * **PR #11717** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11717" target="_blank">Graphite</a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank">Graphite</a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank">Graphite</a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank">Graphite</a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank">Graphite</a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank">Graphite</a> 
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank">Graphite</a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank">Graphite</a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank">Graphite</a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank">Graphite</a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank">Graphite</a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank">Graphite</a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank">Graphite</a> 
                                * **PR #11720** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11720" target="_blank">Graphite</a> 
                                  * **PR #11721** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11721" target="_blank">Graphite</a> 
                                    * **PR #11722** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11722" target="_blank">Graphite</a> 
                                      * **PR #11723** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11723" target="_blank">Graphite</a> 
                                        * **PR #11724** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11724" target="_blank">Graphite</a> 
                                          * **PR #11725** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11725" target="_blank">Graphite</a> 
                                            * **PR #11726** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11726" target="_blank">Graphite</a> 
                                              * **PR #11727** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11727" target="_blank">Graphite</a> 
                                                * **PR #11728** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11728" target="_blank">Graphite</a> 
                                                  * **PR #11729** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11729" target="_blank">Graphite</a>  👈
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11729?utm_source=stack-comment).

**Review by sryza — APPROVED** [review]

**Pull request merged**
