### PR TITLE
[dagit] Add Instance Overview

### PR DESCRIPTION
**Pull request by hellendag**
## Summary

Create a first pass at the Instance Overview page.

There are a lot of things here that are just placeholders and other things that don't match current designs, so don't dig too deeply yet. :)

## Test Plan

View `/instance/overview` with flag disabled. Verify redirect. View with the flag enabled, verify that the page loads. Verify correct rendering/behavior for:

- Job bucketing by latest run
- Repository filtering
- Job name filtering
- Schedule/sensor information
- Latest run info

### CODE REVIEW

**Comment by hellendag** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5936**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

**Comment by hellendag** [comment]
Screen Shot 2021-12-10 at 2 38 03 PM

**Comment by sryza** [comment]
Awesome!

Feel free to disregard these if you're not looking for feedback at this level of detail yet.
* Is "trigger" a word we use in other places? Might be better to just say "Schedule or Sensor".
* The formatting of the durations strikes me as somewhat inconsistent. Thoughts on rendering "02:03:42" as "2h, 3m, 52s"?
* Would it be clearer to rename "Health" to "Daemons"? Arguably, the overview page is job health.

**Comment by hellendag** [comment]
> The formatting of the durations strikes me as somewhat inconsistent. Thoughts on rendering "02:03:42" as "2h, 3m, 52s"?

This reuses the same duration formatting component as elsewhere in the app. It's also worth keeping in mind that these often show ongoing durations, so the "clock" formatting works pretty well for that.

**Comment by sryza** [comment]
> This reuses the same duration formatting component as elsewhere in the app. It's also worth keeping in mind that these often show ongoing durations, so the "clock" formatting works pretty well for that.

Ah, got it.

**Review by bengotow — APPROVED** [review]
This looks solid to me! There's definitely a lot of business logic inline in the component, but I imagine we can refactor and polish that once we've finalized exactly what we need for this page!

**Pull request merged**
