### PR TITLE
feat(dbt): add setting to allow duplicate source asset keys

### PR DESCRIPTION
**Pull request by hello-world-bfree**
## Summary & Motivation

Resolves https://github.com/dagster-io/dagster/issues/19950. 

Provides a flag in `DagsterDbtTranslatorSettings` called `enable_duplicate_source_asset_keys` that relaxes the duplicate asset key constraint for dbt sources.

Duplicate asset keys are only allowed for dbt sources with this flag enabled. If duplicate asset keys are detected for dbt models, an exception will still be raised.

## How I Tested These Changes

pytest:
- Before enabling the flag, duplicate source asset keys raise an exception
- After enabling the flag, duplicate source asset keys do not raise an exception
- After enabling the flag, duplicate source and model asset keys still raise an exception

### CODE REVIEW

**Comment by hello-world-bfree** [comment]
@rexledesma Friendly bump! Saw there was another release today and I'd love to get this into a release asap so I can update our version. Until then we're stuck. Thanks!

**Comment by rexledesma** [comment]
@hello-world-bfree Hey, apologies for the delay. 

While this code change solves your problem, I have hesitations about accepting this since this may cause confusion with users who are not expecting this behavior with their dbt sources.

I am imagining the experience of someone who accidentally does the following, not knowing about dbt config inheritance (which is a common mistake, when working with users).

Take the example `dbt_project.yml`:

```yaml
models:
  +meta:
    dagster:
      asset_key: ["same", "asset_key"]
      
sources:
  +meta:
    dagster:
      asset_key: ["source", "same", "asset_key"]
```

Before, this would return an error. Now, potentially after this change, it will not.

If a  user actually wants to enforce uniqueness amongst their source asset keys, they would not have an ergonomic option to do so. These users would now have to understand there is a subtle difference how models and sources can be represented in Dagster.

If we were to accept this, I would prefer some mechanism where you must explicitly opt-in to this behavior. For example, by a setting in `DagsterDbtTranslator`.

---

FYI: to unblock your own use case without needing to merge this PR, you could probably just modify your own dbt manifest in code and ensure all dbt sources are represented by a single unique id.

```python
import json

# Iterate through model/snapshot/seed dependencies
manifest = json.loads(MANIFEST_PATH.read_bytes())
for model, dbt_resource_props in manifest["nodes"].items():
    # replace all source unique ids with a single source id
    dbt_resource_props["depends_on"] = ...


@dbt_assets(manifest=manifest)
def my_dbt_assets():
    ...
```

**Comment by hello-world-bfree** [comment]
> I am imagining the experience of someone who accidentally does the following, not knowing about dbt config inheritance (which is a common mistake, when working with users).
> 
> Take the example `dbt_project.yml`:
> 
> ```yaml
> models:
>   +meta:
>     dagster:
>       asset_key: ["same", "asset_key"]
>       
> sources:
>   +meta:
>     dagster:
>       asset_key: ["source", "same", "asset_key"]
> ```

No worries @rexledesma! The above example does raise an error! Models are still checked for dupes, so the `dbt_project.yml` config you show above wouldn't fly. 

Sources are the only dbt resources that would be able to be associated with same asset key. Users would have to go out of their way to intentionally invoke this, and even if they did due to misconfiguration, it wouldn't cause them any meaningful issues. The only potential issue I can think of is that they would expect a different upstream  asset to be the dependency of a dbt model and that could _potentially_ cause the asset materialization order to get out of whack. But that would occur just the same if they were to configure the wrong asset upstream today.

> If a user actually wants to enforce uniqueness amongst their source asset keys, they would not have an ergonomic option to do so. These users would now have to understand there is a subtle difference how models and sources can be represented in Dagster.

Wouldn't the default behavior work just the same? Unlike models, the sources having the same asset key doesn't cause conflicts or functional issues. If users don't specify overlapping asset key assignments, they get uniqueness out-of-the-box. 

I'm also not sure why users would need or want to enforce uniqueness amongst their source asset keys. There wouldn't be anything stopping them from doing so, of course, but what would be the value in ensuring it's that enforcement is the default?

I'd suggest that there already is a subtle difference in how models and sources are represented in Dagster. For instance, a dbt model will never be a Dagster source asset, yet by default, a dbt source **is** a Dagster source asset.  dbt sources are only references, not definitions, so why not allow them to reference whichever Dagster assets the user sees fit?

**Comment by rexledesma** [comment]
> The above example does still raise an error! Models are still checked for dupes, so the dbt_project.yml config you show above wouldn't fly.

Whoops, they were meant to be separate. Fixed.

> Unlike models, the sources having the same asset key doesn't cause conflicts or functional issues, but if that configuration were stumbled into, the users would find out fairly quick from the asset graph.

I don't think an experience where you find this out manually at run time is an ideal experience. I would want a clear error to be raised at definition time. 

> I'm also not sure why users would need or want to enforce uniqueness amongst their source asset keys. There wouldn't be anything stopping them from doing so, of course, but what would be the value in ensuring that enforcement is the default?

With our asset abstraction, you can view historical metadata (e.g. when it was last updated, how long did take, etc) for a given asset. Uniqueness allows the history to be separated for each dbt source since they are materialized tables.

In your case, you don't care about this distinction. But other users want this distinction.

**Comment by hello-world-bfree** [comment]
> I don't think an experience where you find this out manually at run time is an ideal experience. I would want a clear error to be raised at definition time.

IMO it'd be the same if you mistyped the asset key name in the meta config of the yaml - which you'd also find out at runtime. There's nothing inherently wrong with what you submitted in a technical sense, it just might not be what you want. I know you disagree but for what it's worth.

> 
> With our asset abstraction, you can view historical metadata (e.g. when it was last updated, how long did take, etc) for a given asset. Uniqueness allows the history to be separated for each dbt source since they are materialized tables.
> 
> In your case, you don't care about this distinction. But other users want this distinction.

For sure! Completely get and appreciate it. Tying multiple dbt sources to the same Dagster asset wouldn't prohibit that. That's my big rub. I updated the code so that `disable_source_uniqueness_checks` has to be specified via `DagsterDbtTranslatorSettings`. All I ask is that it's possible and not explicitly prohibited. 🙏

**Comment by rexledesma** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20022?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#20022** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20022?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#20287** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20287?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hello-world-bfree and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rexledesma — COMMENTED** [review]
@hello-world-bfree I'm going to commandeer this PR and bring it to the finish line to hopefully get it in this week's release. You'll still receive authorship credit when it gets merged!

**Comment by hello-world-bfree** [comment]
Thanks @rexledesma! I really appreciate you being open and flexible with this. Much appreciated!

**Pull request merged**
