### PR TITLE
Fix helm

### PR DESCRIPTION
**Pull request by dpeng817**
## Summary & Motivation
Didn't forward the new prop to helm. This fixes

## How I Tested These Changes
Previously failing tests now pass on local

### CODE REVIEW

**Comment by dpeng817** [comment]
* **#26752** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26752?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26752?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by yuhan** [comment]
pr's bk seems still broken

**Comment by dpeng817** [comment]
@yuhan should be fixed now (just needed to reorder schema)

**Review by gibsondan — APPROVED** [review]

**Comment by gibsondan** [comment]
@dpeng817 note that there is a CLI command that you need to run for tests to pass before landing to regenerate the JSON schema

**Pull request merged**
