### PR TITLE
[1.0] Get rid of pipeline/solid in backcompat tests

### PR DESCRIPTION
**Pull request by dpeng817**
Given that they are no longer supported in 1.0

### CODE REVIEW

**Review by alangenfeld — CHANGES_REQUESTED** [review]
i assume this is automated? I think its useful to include in the pr summary how you performed it if thats the case. Sending back to you since theres merge conflicts.

**Comment by dpeng817** [comment]
cc @alangenfeld massive file list was from a different PR.

**Comment by smackesey** [comment]
`pipeline`/`solid` are unsupported in 1.0 but aren't these backcompat tests about cross-process communication between different `dagit` and `dagster` versions? In the test matrix there are four combos:

```
RELEASE_TEST_MAP = {
    "dagit-earliest-release": [EARLIEST_TESTED_RELEASE, DAGSTER_CURRENT_BRANCH],
    "user-code-earliest-release": [DAGSTER_CURRENT_BRANCH, EARLIEST_TESTED_RELEASE],
    "dagit-latest-release": [MOST_RECENT_RELEASE_PLACEHOLDER, DAGSTER_CURRENT_BRANCH],
    "user-code-latest-release": [DAGSTER_CURRENT_BRANCH, MOST_RECENT_RELEASE_PLACEHOLDER],
}
```

Looks like `repo.py` is part of the user code, which sometimes in "user-code-earliest-release" is running older dagster versions that still support pipeline.

IIUC seems like the solution here is to actually use a different repo.py for user code earliest release (which should still be pipeline-based) and user cade latest release (which would contain your changes).

**Comment by dpeng817** [comment]
> `pipeline`/`solid` are unsupported in 1.0 but aren't these backcompat tests about cross-process communication between different `dagit` and `dagster` versions? In the test matrix there are four combos:
> 
> ```
> RELEASE_TEST_MAP = {
>     "dagit-earliest-release": [EARLIEST_TESTED_RELEASE, DAGSTER_CURRENT_BRANCH],
>     "user-code-earliest-release": [DAGSTER_CURRENT_BRANCH, EARLIEST_TESTED_RELEASE],
>     "dagit-latest-release": [MOST_RECENT_RELEASE_PLACEHOLDER, DAGSTER_CURRENT_BRANCH],
>     "user-code-latest-release": [DAGSTER_CURRENT_BRANCH, MOST_RECENT_RELEASE_PLACEHOLDER],
> }
> ```
> 
> Looks like `repo.py` is part of the user code, which sometimes in "user-code-earliest-release" is running older dagster versions that still support pipeline.
> 
> IIUC seems like the solution here is to actually use a different repo.py for user code earliest release (which should still be pipeline-based) and user cade latest release (which would contain your changes).

cc @alangenfeld for opinions here, but my take was that we would stop explicitly supporting using pipeline/solid and having that being interpretable by the front end post-1.0. As in, if you upgrade your user code deployment and you can no longer use pipeline/solid, it seems silly that the front-end has to explicitly support functionality which is gone in the current version. But maybe it's always necessary for the purpose of interpreting old snapshots, so willing to be overridden here.

**Comment by alangenfeld** [comment]
ya i think we should continue to back compat test pipeline/solid in the "earliest version" and explicitly change that if we hit a breaking change we feel we need to make.

One argument is that if `dagster._legacy` is in `1.0` and has `pipeline` and `solid` in it, and we want to say we support user code from any `1.0` release then they should continue to work in dagit. 

We should probably add `1.0.0` entries to the test matrix too around launch. 

I doubt we will want to break these cross process loading structures anytime soon, but I do think itll be nice for the tests to make that decision explicit.

**Comment by sryza** [comment]
> One argument is that if dagster._legacy is in 1.0 and has pipeline and solid in it, and we want to say we support user code from any 1.0 release then they should continue to work in dagit.

We don't want to support users importing from dagster._legacy, full stop. The only reason for it is to save us from migrating all our tests immediately.

**Comment by alangenfeld** [comment]
Got it - my misunderstanding. Then I suppose the utility of continuing to test that we don't break legacy user code in current host processes is catching it earlier than internal variants of the test, until we ensure all of our cloud customers are  running >= 1.0 (or at least have no more active legacy definitions).

**Review by alangenfeld — APPROVED** [review]

**Pull request merged**
