### PR TITLE
Asset checks polish

### PR DESCRIPTION
**Pull request by salazarm**
## Summary & Motivation
Screenshot 2024-03-05 at 1 42 03 PM

1. Lowercase "result" in "Evaluation result".
2. Move the collapse arrows to the right side
3. Don't show the latest execution in the table since we already show it above

### CODE REVIEW

**Comment by sryza** [comment]
This version of the design has the metadata fields for the latest check evaluation in their own table, rather than gated by a modal:

image

https://dagsterlabs.slack.com/archives/C03CCE471E0/p1709310817804649?thread_ts=1709310142.884309&cid=C03CCE471E0

I like that direction, because it necessitates fewer clicks to get to the data that gives context to the check. Any reservations about this @salazarm?  cc @braunjj in case I am missing a later version of the design.

**Review by bengotow — APPROVED** [review]
Looks good to me!

**Comment by braunjj** [comment]
Love it

**Comment by salazarm** [comment]
@sryza updated:
Screenshot 2024-03-06 at 3 07 13 PM

**Pull request merged**
