### PR TITLE
add CLI command to print the storage schema version

### PR DESCRIPTION
**Pull request by prha**
### Summary & Motivation
Provide easy way to view schema version per storage

### How I Tested These Changes
BK

### CODE REVIEW

**Review by gibsondan — CHANGES_REQUESTED** [review]
this looks good, might we want to include the head version as well though? That's the other piece of info that was in the error that we just removed

I wonder if we would ever want a single command that people could run that gives us an overview for debugging? that would also cover the question we always ask, which is what dagster version they are on

**Comment by prha** [comment]
Yeah, I thought about combining this into the `dagster instance info` command, but that looks like a dump of the instance config.  Wasn't exactly sure if we were fine lumping non-config into that command as well.

I can add the head version as well.

**Comment by gibsondan** [comment]
I like lumping it in with instance info, but not strongly held

**Comment by prha** [comment]
Okay, I didn't lump it in with the `info_dict`, since dagit presents that whole mess as `Instance configuration`.  Kept the `schema_str` method, and now when you run the CLI command `dagster instance info`, it will display both the config as well as the schema state:

```
[dagster-3.9.10] ➜  dagster git:(prha/instance_schema_cli) dagster instance info
$DAGSTER_HOME: /Users/prha/dagster


Instance configuration:
-----------------------
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: /Users/prha/dagster
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_url: postgresql://prha:prha@localhost:5432/prha
event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_url: postgresql://prha:prha@localhost:5432/prha
compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir: /Users/prha/dagster/storage
schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_url: postgresql://prha:prha@localhost:5432/prha
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler
  config: {}
run_coordinator:
  module: dagster.core.run_coordinator
  class: DefaultRunCoordinator
  config: {}
run_launcher:
  module: dagster
  class: DefaultRunLauncher
  config: {}
telemetry:
  enabled: true
  experimental_dagit: true


Storage schema state:
---------------------
schema:
  event_log_storage:
    current: 721d858e1dda
    latest: 721d858e1dda
  run_storage:
    current: 721d858e1dda
    latest: 721d858e1dda
  schedule_storage:
    current: 721d858e1dda
    latest: 721d858e1dda
```

**Review by gibsondan — APPROVED** [review]

**Pull request merged**
