### PR TITLE
Expose field doc string in a new config hover tooltip and in autocompletion

### PR DESCRIPTION
**Pull request by bengotow**
This PR integrates config field `description` text into the type-ahead autocompletion in the YAML editor and into hover tooltips. It turns out we were already doing the tooltips entirely from scratch, so it wasn't too big a jump to put the descriptions in there.

If it's preferable I think we could move this to a block at the bottom of the editor. I think that we'll need to add some top-level events to the CodeMirror React editor so that we can track the insertion point and pull context at that location.

image

image

### CODE REVIEW

**Comment by schrockn** [comment]
Whoops somehow accidentally removed other reviewers!

**Comment by schrockn** [comment]
@natekupp curious for you to maybe try this out with the spark config or to show @bengotow how do to that. I want to make sure this looks reasonable with long documentation strings, which do happen.

**Comment by schrockn** [comment]
Ok this is pretty epic:

Screenshot 2019-04-04 15 53 03

Screenshot 2019-04-04 15 52 13

**Comment by natekupp** [comment]
This is so so so cool! nice work!

**Pull request merged**
