### PR TITLE
docs(dbt): add API docs for `dagster-dbt project scaffold`

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
Resolves https://github.com/dagster-io/dagster/issues/15484.

## How I Tested These Changes

```bash
~/elementl/dagster/docs rl/dbt-scaffold-cli-api-docs 8s
dagster ❯ dagster-dbt project scaffold --help

 Usage: dagster-dbt project scaffold [OPTIONS]

 This command will initialize a new Dagster project and create directories and files that load assets from an existing dbt project.

╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *  --project-name             TEXT       The name of the Dagster project to initialize for your dbt project. [required]                                        │
│    --dbt-project-dir          DIRECTORY  The path of your dbt project directory. This path must contain a dbt_project.yml file. By default, this command will  │
│                                          assume that the current working directory contains a dbt project, but you can set a different directory by setting    │
│                                          this option.                                                                                                          │
│    --help             -h                 Show this message and exit.                                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```

https://dagster-b63yqqebz-elementl.vercel.app/_apidocs/libraries/dagster-dbt#dagster-dbt

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #15500** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15500" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15500?utm_source=stack-comment).

**Review by erinkcochran87 — COMMENTED** [review]
For `--dbt-project-dir`, should we be more specific about when this flag is needed? I'm thinking of the copy in @sryza's [PR](https://github.com/dagster-io/dagster/pull/15402) that updates the dbt tutorial, specifically:

> If that's a different directory from where your dbt_project.yaml lives, then you'll need to provide a value for the `--dbt-project-dir` option so that Dagster knows where to look for your dbt project.

Do we need to mention we're looking for `dbt_project.yaml`? And/or include something like "Required only if the project doesn't reside in the current working directory"?

**Comment by rexledesma** [comment]
@erinkcochran87 That makes sense to me -- I made the `--dbt-project-dir` help text more specific and actionable with your feedback!

**Review by erinkcochran87 — APPROVED** [review]
Love it - ty Rex!

**Pull request merged**
