### PR TITLE
refactor: move community health files to `.github/`

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
Colocate the community files in `.github/`, as documented in https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file.

## How I Tested These Changes
N/A

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #14401** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14401" target="_blank">Graphite</a> 
    * **PR #14402** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14402" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14402?utm_source=stack-comment).

**Comment by yuhan** [comment]
i think the docs refer to contributing (maybe) - worth testing the docs before landing

**Comment by tacastillo** [comment]
Docs are safe, I believe, but I think our issue templates point to our `CODE_OF_CONDUCT.md`, so those would need to get updated
image

**Review by yuhan — CHANGES_REQUESTED** [review]
q mgmt: issue template depends on the old link

**Review by yuhan — APPROVED** [review]

**Pull request merged**
