### PR TITLE
[dagster-dbt] clean up unnecessary quotes in relation identifier metadata

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

By default, dbt's `relation_name` metadata quotes each component of the relation name, e.g. `"my_database"."my_schema"."my_table"`.

This is a defensive measure to deal with cases where one component might have special chars - e.g. in the case of some of our test code, the table name can have a period in it.

Unfortunately, this quoted format doesn't work nicely with many tools out of the box, for example, Snowflake errors trying to query a quoted table name.

This PR adds a helper method to strip these quotes unless a component has special characters.

## Test Plan

Unit tests.

### CODE REVIEW

**Comment by benpankow** [comment]
* **#22304** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22304?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rexledesma — COMMENTED** [review]
Hmm that's annoying. If we have access to the SQL dialect here, we could instead use `sqlglot`'s `to_table` so that we don't have to do this regex.

Here's an example
https://github.com/dagster-io/dagster/blob/6c3cbc8e1a069872467f66c2fcf7b2a5514f91c6/python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py#L811

**Review by rexledesma — CHANGES_REQUESTED** [review]
Back to you. My hunch is that this regex is making things more complex than it should be. We should either keep the quotes, or just manually append the db, schema, table together.

**Comment by sryza** [comment]
No strong opinions on how to do so, but I do think the quotes are quite ugly and we should endeavor to get rid of them

**Comment by benpankow** [comment]
Closing in favor of #22484

**Pull request closed without merging**
