### PR TITLE
[dagster-ge] Update to latest version of Great Expectations (<=0.13.10)

### PR DESCRIPTION
**Pull request by pacha**
## Summary
A change in the codebase of Great Expectations has broken the compatibility with the `dagster-ge` library in recent versions (since v0.13.0). This is a small PR that tries to solve the problematic import to allow `dagster-ge` to be use with the latest version of this package.

The PR tries to keep compatibility with previous versions of GE too, however, I'm a bit unsure if the `try/except ImportError` approach is the right one here since I couldn't find a similar case among the other Dagster libraries. (In the worst case, the PR at least may raise awareness on the issue :slightly_smiling_face:).

Tests for `dagster-ge` are passing in my local environment.

## Checklist
* The change doesn't require any change in the documentation
* The change doesn't require any new tests

### CODE REVIEW

**Comment by catherinewu** [comment]
hi @pacha thank you for the contribution! Triggering the full test suite now ✔️

**Comment by catherinewu** [comment]
hey, i think after running `make isort`, this should be good to merge

**Comment by pacha** [comment]
> hey, i think after running `make isort`, this should be good to merge

@catherinewu Oh, damn, missed that :sweat_smile: Updated now.

**Comment by rexledesma** [comment]
thanks @pacha! Merging - the errors from buildkite look like rebase errors.

**Comment by pacha** [comment]
Thanks @rexledesma! I was a bit confused about the error :smile: (just didn't have the time to follow up). Great to see it merged!

**Pull request merged**
