### PR TITLE
pin polars <0.20.17

### PR DESCRIPTION
**Pull request by johannkm**
https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1711648459441669

Latest version is breaking tests. Could land this to get the build green unless the fix is easy

### CODE REVIEW

**Comment by johannkm** [comment]
* **#20796** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20796?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @johannkm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gibsondan — APPROVED** [review]

**Comment by ion-elgreco** [comment]
@johannkm What were the errors?

Polars iterates extremely fast so dagster-polars shouldn't be pinned to a lower version, the surface interaction with polars is minimal at best so it does not make sense to limit your whole environment here

**Comment by johannkm** [comment]
@ion-elgreco 
Seems like it's the introduction of decimal:

`dagster._check.CheckError: Value in dict mismatches expected type for key col0. Expected value of type (<class 'str'>, <class 'float'>, <class 'int'>, <class 'bool'>, <class 'NoneType'>). Got value 0 of type <class 'decimal.Decimal'>.`

```
2024-03-28T17:10:31Z] FAILED dagster_polars_tests/test_deltalake.py::test_polars_delta_io - Exception: Parser error: can't parse the string value 0.0 to decimal
[2024-03-28T17:10:31Z] FAILED dagster_polars_tests/test_polars_delta.py::test_polars_delta_io_manager - dagster._check.CheckError: Value in dict mismatches expected type for key c...
[2024-03-28T17:10:31Z] FAILED dagster_polars_tests/test_polars_parquet.py::test_polars_parquet_io_manager_read_write - dagster._check.CheckError: Value in dict mismatches expected type for key c...
[2024-03-28T17:10:31Z] FAILED dagster_polars_tests/test_polars_parquet.py::test_polars_parquet_io_manager_read_write_full_lazy - dagster._check.CheckError: Value in dict mismatches expected type for key c...
```

If you're able to PR a fix that'd be great. This pin was just to quickly unbreak our build.

**Comment by ion-elgreco** [comment]
@johannkm 
`Parser error: can't parse the string value 0.0 to decimal` this one is caused because our parser in delta-rs is relying on the arrow-rs parser, which currently has some flaws. So will ignore this type in the testing since it's unrelated to dagster-polars

**Comment by ion-elgreco** [comment]
@johannkm please check this pr :) https://github.com/dagster-io/dagster/pull/20897

**Pull request merged**
