### PR TITLE
Add auto_materialize_policy to load_assets_from_*

### PR DESCRIPTION
**Pull request by johannkm**
Replicate https://github.com/dagster-io/dagster/pull/13120 for auto materialize policy

### CODE REVIEW

**Comment by johannkm** [comment]
Current dependencies on/for this PR:
* master
  * **PR #13587** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13587" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13587?utm_source=stack-comment).

**Comment by johannkm** [comment]
Do we also need a with_auto_materialize_policy? I don't see an equivalent for freshness

**Review by sryza — APPROVED** [review]
Nice

**Comment by sryza** [comment]
> Do we also need a with_auto_materialize_policy? I don't see an equivalent for freshness

Not for 1.3, though I suspect people are going to want it. I think it will be more common to set a uniform AutoMaterializePolicy than a uniform FreshnessPolicy.

**Pull request merged**
