### PR TITLE
[docs] - Update tutorial(s) to include assets

### PR DESCRIPTION
**Pull request by erinkcochran87**
This PR updates the docs for the 0.15.0 release.

### CODE REVIEW

**Comment by sryza** [comment]
@erinkcochran87 - I'm excited about these changes! We generally try to break up pull requests into small-ish chunks that can be easily reviewed and merged on their own.

E.g. the "non-argument deps" changes look ready to merge.  So we could split that them out into their own pull request and then merge that, while leaving room to iterate separately on "customizing asset storage" etc. I'd be happy to help with whatever git wrangling is required to make that happen.

**Comment by erinkcochran87** [comment]
@sryza Thanks for the info! I'll take care of wrangling the non-argument deps content into its own PR today.

**Comment by erinkcochran87** [comment]
Moved `non_argument_deps` over to https://github.com/dagster-io/dagster/pull/7962. I'll work on cleaning the rest of this up.

**Comment by erinkcochran87** [comment]
This branch went bananas at some point - I'm moving things over to https://github.com/dagster-io/dagster/pull/8241 to clean it up.

**Pull request closed without merging**
