### PR TITLE
[Docs][Minor] Typo and update latest screenshot of `configuring-solids.mdx`

### PR DESCRIPTION
**Pull request by keypointt**
## Summary

Just doc updates, no code logic change.

Typo and update latest screenshot during reading through the tutorial. :)

Note: my screenshot might seem not be the same pixel compared to rest of screenshot images, I'd be happy to remove it while the original screenshot-er can take a new one and update it.

## Test Plan
Manual/Visual check.

### CODE REVIEW

**Comment by keypointt** [comment]
hi any update needed ?

or I can revert to only fix the typo `fai` to `fail` to get it merged quickly :D

thanks 😄

**Comment by helloworld** [comment]
Sorry for the delay here, thank you for this! Merging now

**Comment by helloworld** [comment]
@keypointt Do you mind rebasing on master? I'm unable to push to your branch to do this for you. Once that's done I can merge!

**Comment by helloworld** [comment]
Thanks!

**Comment by keypointt** [comment]
@helloworld  just rebased. thanks Sashank!

BTW, you have a nice username haha 😄

**Pull request merged**
