### PR TITLE
[dagster-powerbi] Gracefully handle datasets without datasource IDs

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Some semantic model types hold references to data sources that lack an ID - add some code to gracefully handle this case.

## Test Plan

Updated unit test to include sample data source without an ID.

### CODE REVIEW

**Comment by benpankow** [comment]
* **#25136** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25136?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sryza** [comment]
What's the user-facing behavior difference without this change?

**Comment by benpankow** [comment]
> What's the user-facing behavior difference without this change?

It breaks, since we attempt to access a value that doesn't exist in the dict

**Review by sryza — APPROVED** [review]
Using UUID was a little bit confusing to me here because I assumed we were generating a random ID but we're actually using a hash. Using `non_secure_md5_hash_str` would be more consistent with what we do elsewhere.

Otherwise LGTM.

**Pull request merged**
