### PR TITLE
add index to query by range

### PR DESCRIPTION
**Pull request by prha**
Saw that the RunTimelineQuery was doing table scans.

This diff adds an index on the runs table to do timestamp range queries.

Before:
Sort  (cost=1736.60..1736.60 rows=1 width=1414)
  Sort Key: id DESC
  ->  Seq Scan on runs  (cost=0.00..1736.59 rows=1 width=1414)
        Filter: ((update_timestamp > '2022-01-20 13:29:36.183'::timestamp without time zone) AND (create_timestamp < '2022-01-20 20:29:36.183'::timestamp without time zone) AND ((status)::text = ANY ('{FAILURE,SUCCESS,CANCELED}'::text[])))

After:
Sort  (cost=197.35..197.35 rows=1 width=1414)
  Sort Key: id DESC
  ->  Index Scan using idx_run_range on runs  (cost=0.28..197.34 rows=1 width=1414)
        Index Cond: ((create_timestamp < '2022-01-20 20:29:36.183'::timestamp without time zone) AND (update_timestamp > '2022-01-20 13:29:36.183'::timestamp without time zone))
        Filter: ((status)::text = ANY ('{FAILURE,SUCCESS,CANCELED}'::text[]))

### CODE REVIEW

**Review by gibsondan — COMMENTED** [review]
test failure is real, got another migration coming?

Would we ever want an index on just create_timestamp too? Or this same index minus status? How much future-proofing do we want to do here?

**Comment by prha** [comment]
Well, we will always have status in the queries, but we might not always have an update_timestamp constraint.

Is it not sufficient to have the superset in the index?

**Review by gibsondan — COMMENTED** [review]
I don't actually know, indices are very mysterious to me

**Review by alangenfeld — COMMENTED** [review]
is this intentionally front end changes and migrations/reindexing ?

**Comment by prha** [comment]
No, I'm trying to stack this on top of the `prha/run_timeline` branch and failing.

**Comment by prha** [comment]
Corresponding cloud diff here: https://github.com/dagster-io/internal/pull/936

**Review by gibsondan — APPROVED** [review]
it would be nice to have a clear answer on if other indices are going to be needed for indices just on create_timestamp (or time range queries with no status filter) - could do some explain queries on postgreS?

**Comment by prha** [comment]
I need to change the order of these columns in the index.  We should order the index columns from most selective to least selective, so I think the correct order should be:
status, update_timestamp DESC, create_timestamp

We'll need to create a separate index for the create timestamp query:
status, create_timestamp.

This means that we can't blindly query runs without providing some status check on it, but that seems fine.

**Comment by prha** [comment]
Ideally, we'd have an index using update_timestamp descending, but I think we're hitting a mysql bug in sqlalchemy, where it's not interacting well with the mysql_length argument.

**Pull request merged**
