### PR TITLE
[dagster-dbt][DA] Add get_automation_condition method to DagsterDbtTranslator

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

Adds a `get_automation_condition` method to DagsterDbtTranslator, and updates some docs references.

### CODE REVIEW

**Comment by OwenKephart** [comment]
* **#23389** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23389?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rexledesma — COMMENTED** [review]
Can we remove `get_auto_materialize_policy` and associated tests as well? We're removing those docs anyways.

**Review by rexledesma — CHANGES_REQUESTED** [review]
requesting changes for ^

**Comment by OwenKephart** [comment]
@rexledesma I was keeping the `get_auto_materialize_policy` method because we didn't want to introduce truly breaking changes to AMP in the 1.8 release (that removal will happen in 1.9). Figured I'd keep the tests around to make sure that this change didn't break any existing users bc of that -- seem reasonable or is there a more aggressive thing you'd like to see here?

**Review by rexledesma — APPROVED** [review]
got it, makes sense. we can wait to deprecate the other methods once `AutomationCondition` becomes GA in 1.9.

**Pull request merged**
