### PR TITLE
Move Definitions to init in dbt scaffold

### PR DESCRIPTION
**Pull request by maximearmstrong**
## Summary & Motivation

This PR moves the `Definitions` object from `definitions.py` to `__init__.py` in our dbt scaffold.

Why?
- Our documentation recommends including the `Definitions` object in `__init__.py` 
    - See [here](https://docs.dagster.io/guides/dagster/recommended-project-structure) and [here](https://docs.dagster.io/guides/understanding-dagster-project-files)
- When using Dagster Cloud, the following exception may be thrown if the `dagster_cloud.yaml` file is not formatted to point to the `definitions.py` file.
    - Most of our `dagster_cloud.yaml` examples ([dagster/examples](https://github.com/dagster-io/dagster/tree/master/examples) and [docs](https://docs.dagster.io/dagster-cloud/managing-deployments/dagster-cloud-yaml)) include a `package_name` parameter, expecting the `Definitions` object to be in `__init__.py`
    - The exception
    image

## How I Tested These Changes
Scaffold test
BK

### CODE REVIEW

**Comment by maximearmstrong** [comment]
* **#20675** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20675?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maximearmstrong and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rexledesma — CHANGES_REQUESTED** [review]
> Our documentation recommends including the Definitions object in __init__.py

I think we should move away from this pattern. In the general case, other implementations use `__init__.py` for configuring package dependencies, not initializing object definitions.

We actually mention this usage here in our blog: https://dagster.io/blog/python-packages-primer-1#what-is-__init__py.

If we want to move to the `package_name` pattern, then we should just have a single statement in `__init__.py`: 

```python
from .definitions import defs
```

**Comment by maximearmstrong** [comment]
> > Our documentation recommends including the Definitions object in **init**.py
> 
> I think we should move away from this pattern. In the general case, other implementations use `__init__.py` for configuring package dependencies, not initializing object definitions.
> 
> We actually mention this usage here in our blog: https://dagster.io/blog/python-packages-primer-1#what-is-__init__py.
> 
> If we want to move to the `package_name` pattern, then we should just have a single statement in `__init__.py`:
> 
> ```python
> from .definitions import defs
> ```

Thanks @rexledesma for the feedback. That's a good point. 

The goal here would be to make the experience as seamless as possible for users. Our Dagster scaffold is generating the `Definitions` object directly in `__init__.py`, so I wonder if adopting the same behavior here would just make the experience more consistent. Or maybe the behavior in the Dagster scaffold should be updated?

@yuhan @sryza Do you have an opinion on this?

**Comment by sryza** [comment]
So these are the three options we're considering?
1. All scaffolds use init.py
2. dbt scaffold uses definitions.py and other scaffolds use init.py
3. All scaffolds use definitions

I strongly prefer either (1) or (3) over (2), because I think consistency is important here.

I see the argument for definitions.py over init.py, but don't feel strongly either way. Fine with this change if others do.

Whatever we do, we need to make sure any changes we make to the scaffold match our docs. E.g. https://docs.dagster.io/guides/dagster/recommended-project-structure, but also places like https://docs.dagster.io/guides/dagster/transitioning-data-pipelines-from-development-to-production.

**Comment by rexledesma** [comment]
If we go with (3), I believe this change can land with the one-line addition to `__init__.py`, as well as changes to the `dagster-dbt` docs so that we can maintain velocity. `dagster-dbt project scaffold` has been using `definitions.py` since its inception, and nobody from our community has had an issue with that.

Then in a downstream PR, we can make the switch over to `definitions.py` for our other examples. We should also ensure that the change is propagated to Dagster University. We should mention this change to dev rel to make them aware that we're considering this change, just in case there's other spots we're missing.

I'm strongly in favor of `definitions.py` since it's not intuitive for `__init__.py` to contain any Dagster code.

**Comment by sryza** [comment]
> I'm strongly in favor of definitions.py since it's not intuitive for __init__.py to contain any Dagster code.

If all else is equal, I think I'm with @rexledesma on this.

**Comment by yuhan** [comment]
Given this affects almost every single example, should we get more eyes before we make the final decision here?

I'm fine with definitions.py and import it in `__init__.py` but I just don't want to make other teams surprised

**Comment by maximearmstrong** [comment]
> If all else is equal, I think I'm with @rexledesma on this.

The options you mentioned are correct and all else is equal. I agree - using `definitions.py` makes a lot of sense. 

> Given this affects almost every single example, should we get more eyes before we make the final decision here?

I think we should. I mainly asked for other opinions before updating the PR because this means we would have to update all our examples, docs and Dagster University courses.

**Comment by maximearmstrong** [comment]
After discussion with the team, we will update our examples, docs and Dagster University courses to recommend initializing the Definitions object in definitions.py instead of __ini__.py.

Closing this PR as there is no real value in adopting a package pattern in that case.

**Pull request closed without merging**
