### PR TITLE
support location_name in chart

### PR DESCRIPTION
**Pull request by pcherednichenko**
## Summary

We wanted to use multiple repositories at the same address, but different ports. We had this configuration:
```yaml
...
    dagit:
      workspace:
        enabled: true
         servers:
         - host: "dagster"
           port: 4000
         - host: "dagster"
           port: 4001
...
```
as a result overlaying values into template, we got the following configuration:
```yaml
    load_from:
      - grpc_server:
          host: dagster
          port: 4000
          location_name: dagster
      - grpc_server:
          host: dagster
          port: 4001
          location_name: dagster
```

**Problem:** As you can see you are using host as location_name:
https://github.com/dagster-io/dagster/blob/35a4511289614da7530503cc36d221be0b113408/helm/dagster/templates/configmap-workspace.yaml#L25-L28

And we got this error:
```
dagster.check.CheckError: Invariant failed. 
Description: Cannot have multiple locations with the same name, got multiple “dagster”
```

**Solution:** in my pr I made it possible to specify the name separately:

```yaml
      - grpc_server:
          host: {{ $deploymentHost }}
          port: {{ $deployment.port }}
          location_name: {{ $deployment.name }}
```

## Test Plan

I updated current test with name instead of host and we tested this configuration on our k8s cluster

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] I have **updated** tests to cover my changes.

### CODE REVIEW

**Review by gibsondan — DISMISSED** [review]
Hi @pcherednichenko - thanks for sending this out and thanks for adding tests! 

This looks like a great change, the only problem that I see is that it isn't backwards-compatible (so the helm chart will break for people who don't add this new field after upgrading). 

Is it possible to make the field optional, and have it fall back to the old behavior if name isn't set (ideally with a test case that covers that behavior)? Thanks again!

**Comment by gibsondan** [comment]
As an aside for your use case - I'm assuming from this PR that you're not using our subchart to set up your servers? Since those set up a separate service and deployment for each server, so the hostname would be different by default.

The other thing I want to be sure you're aware of is that you can serve multiple repositories from the same server if you want (as long as multiple @repository decorators are in the same file or package, Dagster will pick up all of them). But it's still reasonable to have separate servers if you want.

**Comment by pcherednichenko** [comment]
Hi @gibsondan ! Thank you very much for good comments!

> This looks like a great change, the only problem that I see is that it isn't backwards-compatible (so the helm chart will break for people who don't add this new field after upgrading).

You are right, I updated my pr with this logic:
```yaml
           {{- if $deployment.name }}
           location_name: {{ $deployment.name }}
           {{else}}
           location_name: {{ $deploymentHost }}
           {{end}}
```

> ideally with a test case that covers that behavior

Yes I added a new test for this

> I'm assuming from this PR that you're not using our subchart to set up your servers?

Yes, we are not using you subchart because we are using [flux](https://fluxcd.io) for automated deployments, so new images of code repo released automatically

> The other thing I want to be sure you're aware of is that you can serve multiple repositories from the same server if you want (as long as multiple @repository decorators are in the same file or package, Dagster will pick up all of them)

That's really good, and how then to solve the issue with dependencies? For example, one repository needs the pandas package, the other does not, can I split these dependencies across repositories?

**Comment by gibsondan** [comment]
Apologies for the delay here - I made one small change to this (making the new field optional in the schema) and brought it in into https://github.com/dagster-io/dagster/pull/5881 - will land it as soon as tests pass. Thanks again for the contribution, will make sure you get credited in the release notes! I'll close this as soon as the attached PR is merged.

**Comment by gibsondan** [comment]
landed! thanks again

**Pull request closed without merging**
