### PR TITLE
Schrockn/better required field error message

### PR DESCRIPTION
**Pull request by schrockn**
Before:

Screenshot 2019-04-10 10 58 17

After:

Screenshot 2019-04-10 10 58 47

### CODE REVIEW

**Comment by mgasner** [comment]
Might it not make more sense to display the required fields in this message?

**Comment by schrockn** [comment]
I went back and forth on this. I found it useful to know approximately where I was in the document hierarchy.

**Comment by schrockn** [comment]
available fields is a good, minimalist clue for that

**Comment by mgasner** [comment]
There are some legit test failures here

**Pull request merged**
