### PR TITLE
add tests for asset and op decorators with kwargs and context

### PR DESCRIPTION
**Pull request by sryza**
### Summary & Motivation

Motivated by this issue: https://github.com/dagster-io/dagster/issues/10659

### CODE REVIEW

**Review by dpeng817 — CHANGES_REQUESTED** [review]
Should add tests that actually materialize to ensure that behavior is the same across invocation + materialization

**Comment by sryza** [comment]
@dpeng817 this PR is only adding tests - there are no behavior changes. I agree that those additional tests would be helpful, but I don't think we need to block new test coverage on even more test coverage.

**Review by dpeng817 — CHANGES_REQUESTED** [review]
Apologies for the long cycle on this. I understand that the PR is just adding tests, I meant that within the context of each of these tests, it would be good to test feature congruency with actual execution. IE, testing that invocation works correctly is not enough, because there is a completely separate code path to normal execution.

**Review by dpeng817 — APPROVED** [review]
will accept bc more tests better than less tests

**Pull request merged**
