### PR TITLE
migrate concept docs code snippet paths to graph/job/op

### PR DESCRIPTION
**Pull request by sryza**
## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by yuhan** [comment]
the docs snippet test failure looks real

**Review by dpeng817 — CHANGES_REQUESTED** [review]
to your q to resolve conflicts + failures

**Comment by sryza** [comment]
@dpeng817 @yuhan I fixed up the issues. Mind taking another look?

**Review by yuhan — APPROVED** [review]
this is lord's work.

approving but there's few errors left here: https://buildkite.com/dagster/dagster/builds/29107#ca9459cf-cacd-4bb0-80b6-bc8bb5e88ff4 - make sure to fix the build before landing!

**Pull request merged**
