### PR TITLE
Minimal Windows test for CI/CD -- dagster and py36 only

### PR DESCRIPTION
**Pull request by mgasner**

### CODE REVIEW

**Comment by mgasner** [comment]
Builds do have a tendency to queue/take a minute -- this will especially be an issue when we start matrixing python versions & testing more than one of our packages.  I still think this is much more attractive than rolling our own MSBuild fleet or whatever. See https://ci.appveyor.com/billing for our scaling options. (GitHub login)

**Comment by schrockn** [comment]
Should we be considering azure devops?

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
Probably -- the free parallelism is better. https://ci.appveyor.com/project/mgasner/dagster/builds/22233915 shows how long matrixed builds are going to take on appveyor.

**Comment by mgasner** [comment]
Ok, Azure pipelines is much nicer. Going to close this.

**Pull request closed without merging**
