### PR TITLE
[dagster-powerbi] Add option to auth using a Service Principal

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Moves the PowerBI auth to a nested resource, which now has two options: direct API credential, or credentials for a Service Principal.

## Test Plan

New unit tests.

### CODE REVIEW

**Comment by benpankow** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24374?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24374** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24374?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#24361** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24361?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24334** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24334?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sryza** [comment]
> Moves the PowerBI auth to a nested asset

You mean nested resource, right?

**Review by sryza — COMMENTED** [review]
Is it standard to use "Auth" as a noun like this? If not, is there some naming pattern we can cop from somewhere? Should it be `Authenticator`?

**Comment by benpankow** [comment]
Updated to call the parameter `credentials` and dropped the suffix from the resources, so

`credentials=PowerBIToken(...)` or `credentials=PowerBIServicePrincipal(...)`, which I think feels pretty good - what do you think?

**Review by sryza — APPROVED** [review]

**Comment by benpankow** [comment]
### Merge activity

* **Sep 16, 10:07 AM PDT**: @benpankow started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/24374).

**Pull request merged**
