### PR TITLE
[du-dbt] adding starter project to quickstart templates (DEV-168)

### PR DESCRIPTION
**Pull request by tacastillo**

### CODE REVIEW

**Comment by tacastillo** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20308?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#20308** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20308?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#20307** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#20162** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20162?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#20163](https://github.com/dagster-io/dagster/pull/20163) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20163?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tacastillo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by erinkcochran87 — APPROVED** [review]
Stamping to unblock

QQ - in the next section of this lesson, on line 13, we say:

> `dagster-dbt` - Dagster’s integration library for dbt. This will also install `dbt-core` and `dagster` as dependencies.
 
D'you think we should make this `This will also install dbt-core as a dependency`? Feels kinda weird to say they'll be installing Dagster _again_

**Comment by tacastillo** [comment]
> Stamping to unblock
> 
> QQ - in the next section of this lesson, on line 13, we say:
> 
> > `dagster-dbt` - Dagster’s integration library for dbt. This will also install `dbt-core` and `dagster` as dependencies.
>  
> D'you think we should make this `This will also install dbt-core as a dependency`? Feels kinda weird to say they'll be installing Dagster _again_
> 
> 

@erinkcochran87 good eye! that only could've been caught by someone who has read through this content a ridiculous amount of times... just updated it!

**Comment by tacastillo** [comment]
@erinkcochran87 oops, realized this never merged. updated it a little bit because I saw it's been de-synced from the other repo. mind if I get another pair of eyes on this?

**Review by erinkcochran87 — APPROVED** [review]
Looks good to me!

**Pull request merged**
