### PR TITLE
Add `op_retry_policy` to `define_asset_job`

### PR DESCRIPTION
**Pull request by kennycontreras**
## Summary & Motivation

This exposes the op_retry_policy when defining an asset job. The new argument (to keep consistency) is called `op_retry_policy`, and can be used the same when passing a global policy to a `@job`

This solves the issue #15313 

## How I Tested These Changes

Tests were doing `pytest` and, at the same time defining "toy" assets with the retry policy.

Screenshot 2023-11-19 at 11 13 42

```python
default_retry = RetryPolicy(max_retries=3, delay=60)


@asset(group_name="basic_assets")
def basic_asset_1():
    raise Exception

.
.
.

basic_assets_job = define_asset_job(
    "basic_assets_job",
    selection=AssetSelection.groups("basic_assets"),
    metadata={"owner": "data team", "link": MetadataValue.url(url="https://dagster.io")},
    op_retry_policy=default_retry,
)
```

### CODE REVIEW

**Comment by vkhanhqui** [comment]
Thanks @kennycontreras . Hope they have a look soon 👍🏻

**Comment by benpankow** [comment]
Thanks for the contribution! Tagging @sryza & @clairelin135 to take a look

**Comment by sryza** [comment]
Thanks for submitting this @kennycontreras ! I think we should call this `op_retry_policy` instead of `asset_retry_policy`, because, if there are multiple assets covered by a single op, the retries will be at the op level, not the asset level.

**Comment by kennycontreras** [comment]
Thank you @sryza for taking the time to review! I'm going to make the changes suggested and update the PR during the day 🙇🏻‍♂️

**Comment by kennycontreras** [comment]
PR updated, and added docstrings for `op_retry_policy` :)

**Comment by sryza** [comment]
@kennycontreras mind taking a look at the issues reported in the build? The mysql error looks unrelated, but the ruff errors are likely related.

**Comment by kennycontreras** [comment]
@sryza all ruff errors are fixed 🙇🏻‍♂️ thanks for pointing that out.

**Review by sryza — APPROVED** [review]
LGTM! Merging

**Pull request merged**
