### PR TITLE
try to remove legacy nbconvert pinning

### PR DESCRIPTION
**Pull request by stonebig**
## Summary
I wish to have latest nbconvert, so this is to see where it fails

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by stonebig** [comment]
no failure !?!

**Comment by nancydyc** [comment]
Hi @stonebig , buildkite tests failed. If there's a version conflict issue, pip may not error. Have you tested it manually?

**Comment by stonebig** [comment]
No, I didn't test manually

**Comment by stonebig** [comment]
well, it's a lot of little things, as lot of dependancies  are 1 generation late.. no courage

**Pull request closed without merging**
