### PR TITLE
[ui] Fix error when accessing unpartitioned assets

### PR DESCRIPTION
**Pull request by OwenKephart**
## Summary & Motivation

Fixes error raised in the backend that has essentially no impact on UI experience.

## Changelog

NOCHANGELOG

### CODE REVIEW

**Comment by OwenKephart** [comment]
* **#25818** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25818?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gibsondan — COMMENTED** [review]
should this maybe be actual None rather than the string "None"? Just seems a little weird to return a sentinel value from this from an API expected to return partition keys

**Comment by OwenKephart** [comment]
@gibsondan it is definitely a bit weird, but I think this is the simplest way to achieve the desired end result here -- if we return None then we have to consider a separate UI experience for unpartitioned assets in this flow (which is just when you hover over a "N True" tag, it shows you a list of what was true), and for now just showing "None" there would do the job.

My thinking is basically that this is a bit inelegant and doesn't fully accurately model what's going on, but that this is such a tiny interaction that it's ok to be lazy here -- open to pushback

**Review by gibsondan — APPROVED** [review]
given that this endpoint appears to be very specific to this specific UI / flow, i'll defer to you here

**Pull request merged**
