### PR TITLE
[dagster-io/ui] Move ConfigEditor to ui

### PR DESCRIPTION
**Pull request by hellendag**
### Summary & Motivation

Move `ConfigEditor` and associated components to `@dagster-io/ui`. This includes the `ConfigEditorDialog` and `ConfigEditorWithSchema` components as well.

- `ConfigEditor` now has a manually maintained schema type that it expects to receive for display in the schema pane.
  - Consumers are expected to provide an object that conforms to this type, which (if they just use the patterns we already have for config schema) should be straightforward.
  - Cloud use cases have been updated accordingly.
- The yaml and lint modes have been moved as well.
- `DagitCodeMirror` has also been moved, and has been renamed.

With this change published, admin can start to use the config editor.

I can see it making sense at some point for these editor components to be part of a library separate from `ui` if they start to require more bells and whistles, but this is probably fine at this point.

### How I Tested These Changes

View Launchpad in Dagit, verify proper rendering and behavior. Verify that linting and validation works.

Tested Cloud editors as well.

### CODE REVIEW

**Comment by hellendag** [comment]
Current dependencies on/for this PR:
* master
  * **PR #8413** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8413" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/8413?utm_source=stack-comment).

**Comment by hellendag** [comment]
Still need to make some changes here to clean up `ConfigTypeSchema`.

**Comment by hellendag** [comment]
Moved `ConfigTypeSchema` to be a `ui` export, and updated dagit-core queries to match it.

**Comment by salazarm** [comment]
looks good still a couple errors though
```
 src/components/configeditor/ConfigEditorHelp.tsx:1:22 - error TS2307: Cannot find module '@dagster-io/ui' or its corresponding type declarations.
```

**Review by salazarm — APPROVED** [review]

**Pull request merged**
