### PR TITLE
[chore] ruff: ban relative imports

### PR DESCRIPTION
**Pull request by danielgafni**
## Summary & Motivation

Internal discussion: https://github.com/dagster-io/internal/discussions/11157

Relative imports are discouraged in Python. 

1. From `ruff` [docs](https://docs.astral.sh/ruff/rules/relative-imports/): 

>Why is this bad?
Absolute imports, or relative imports from siblings, are recommended by [PEP 8](https://peps.python.org/pep-0008/#imports):
Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path)

~2. I'm trying to migrate to `uv` for packaging  in #23814. Currently, `uv` only supports `src`-based project layout (https://github.com/astral-sh/uv/issues/5328), and some of the current relative imports break after switching to it (code smell!). Using absolute imports should fix this issue.~

Edit: this turned out to be wrong

---

Steps performed to produce this PR:

1. [x] Ban relative imports in the whole project. Ignore this only in `docs/` and `examples/`. 
```diff
diff --git a/pyproject.toml b/pyproject.toml
index 92761add36..8ae75a70c6 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -211,6 +211,9 @@ select = [
   # (isort) detect improperly sorted imports
   "I001",
 
+  # ban relative imports
+  "TID252",
+
   # (performance) perflint rules
   "PERF",
 
@@ -269,6 +272,10 @@ split-on-trailing-comma = false
 # per line. Useful for __init__.py files that just re-export symbols.
 force-wrap-aliases = true
 
+[tool.ruff.lint.flake8-tidy-imports]
+# Disallow all relative imports.
+ban-relative-imports = "all"
+
 [tool.ruff.lint.per-file-ignores]
 
 # Don't format docstrings in alembic migrations.

```

```diff
diff --git a/docs/pyproject.toml b/docs/pyproject.toml
new file mode 100644
index 0000000000..2144bf49e8
--- /dev/null
+++ b/docs/pyproject.toml
@@ -0,0 +1,8 @@
+[tool.ruff]
+extend = "../pyproject.toml"
+
+[tool.ruff.lint]
+extend-ignore = [
+    # (relative imports): relative imports are acceptable in examples & docs
+    "TID252"
+]
```

```diff
diff --git a/examples/pyproject.toml b/examples/pyproject.toml
index 473c4b9319..4966ec6706 100644
--- a/examples/pyproject.toml
+++ b/examples/pyproject.toml
@@ -4,3 +4,8 @@
 # has the effect of making each example package treated as first-party, where `dagster` and
 # integrations will be treated as third-party. This is appropriate for example code.
 extend = "../pyproject.toml"
+
+[tool.ruff.lint]
+extend-ignore = [
+    "TID252"
+]
```
2. [x] run `ruff check --fix --unsafe-fixes`
This produces most of the automatic changes in this PR. 

3. [x] fix a single pytest error
4. [x] fix a few pyright errors

## How I Tested These Changes

Existing tests should pass. The only test which required tweaking was testing line numbers lol

```diff
diff --git a/python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py b/python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
index 2f9dae2684..b643b5ba93 100644
--- a/python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
+++ b/python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
@@ -26,7 +26,7 @@
 EXPECTED_ORIGINS = {
     "james_brown": DAGSTER_PACKAGE_PATH + PATH_IN_PACKAGE + "asset_package/__init__.py:12",
     "chuck_berry": (
-        DAGSTER_PACKAGE_PATH + PATH_IN_PACKAGE + "asset_package/module_with_assets.py:16"
+        DAGSTER_PACKAGE_PATH + PATH_IN_PACKAGE + "asset_package/module_with_assets.py:18"
     ),
     "little_richard": (DAGSTER_PACKAGE_PATH + PATH_IN_PACKAGE + "asset_package/__init__.py:4"),
     "fats_domino": DAGSTER_PACKAGE_PATH + PATH_IN_PACKAGE + "asset_package/__init__.py:16",
@@ -36,15 +36,14 @@
         + "asset_package/asset_subpackage/another_module_with_assets.py:6"
     ),
     "graph_backed_asset": (
-        DAGSTER_PACKAGE_PATH + PATH_IN_PACKAGE + "asset_package/module_with_assets.py:39"
+        DAGSTER_PACKAGE_PATH + PATH_IN_PACKAGE + "asset_package/module_with_assets.py:41"
     ),
 }
 
 
 def test_asset_code_origins() -> None:
     from dagster_tests.asset_defs_tests import asset_package
-
-    from .asset_package import module_with_assets
+    from dagster_tests.asset_defs_tests.asset_package import module_with_assets
 
     collection = load_assets_from_modules([asset_package, module_with_assets])
 
@@ -107,8 +106,7 @@ def test_asset_code_origins() -> None:
 
 def test_asset_code_origins_source_control() -> None:
     from dagster_tests.asset_defs_tests import asset_package
-
-    from .asset_package import module_with_assets
+    from dagster_tests.asset_defs_tests.asset_package import module_with_assets
 
     collection = load_assets_from_modules([asset_package, module_with_assets])
 
@@ -164,8 +162,7 @@ def test_asset_code_origins_source_control_custom_mapping() -> None:
     # test custom source_control_file_path_mapping fn
 
     from dagster_tests.asset_defs_tests import asset_package
-
-    from .asset_package import module_with_assets
+    from dagster_tests.asset_defs_tests.asset_package import module_with_assets
 
     collection = load_assets_from_modules([asset_package, module_with_assets])
 
@@ -226,4 +223,4 @@ def convert_to_source_control_path(self, local_path: Path) -> str:
                     asset.metadata_by_key[key]["dagster/code_references"].code_references[-1],
                 )
 
-                assert meta.url == expected_url
+                assert meta.url == expected_url, f"op {op_name} key {key} code reference is wrong"

```

## Changelog [New | Bug | Docs]

> `NOCHANGELOG`

### CODE REVIEW

**Comment by danielgafni** [comment]
* **#23816** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23816?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @danielgafni and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by danielgafni** [comment]
Nevermind, it looks like the `src` layout is not required by `uv`. So we can continue living with relative imports in our codebase. I can finish this work if we decide to get rid of them for other reasons.

**Comment by danielgafni** [comment]
How many pairs of eyes do we want for a diff as huge as this one?

**Review by schrockn — APPROVED** [review]
Ok let's do this. I can announce in eng heads up.

You will also want to do this in `internal` as well.

**Comment by danielgafni** [comment]
All CI failures are also [happening](https://buildkite.com/dagster/dagster-dagster/builds/91879) in `main`, so merging anyway.

**Pull request merged**
