### PR TITLE
[docs] add references to StepLauncher supersession announcement

### PR DESCRIPTION
**Pull request by danielgafni**
## Changelog

> Insert changelog entry or delete this section.

### CODE REVIEW

**Comment by danielgafni** [comment]
* **#25702** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25702?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @danielgafni and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by danielgafni — COMMENTED** [review]
@yuhan I believe the migration guide isn't part of the latest docs - how do we make it show up there? 

Also, how do we add it to `1.9.0` release notes?

**Review by cmpadden — APPROVED** [review]
tyvm!

**Comment by danielgafni** [comment]
### Merge activity

* **Nov 3, 2:51 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/25702).

**Pull request merged**
