### PR TITLE
Remove "solids" alias for "ops" in run config

### PR DESCRIPTION
**Pull request by smackesey**
## Summary & Motivation

Remove the "solids" alias for "ops" in run config. Update the execution plan snapshot backcompat test to use a snapshot from 1.0 using "ops" instead of "solids" (w/out this change the test cannot pass).

## How I Tested These Changes

Existing test suite. Note that many snapshots had to be updated since this alias was part of the default run config schema.

### CODE REVIEW

**Comment by alangenfeld** [comment]
The relevant test comes from https://dagster.phacility.com/D7129

I think it makes sense to rerecord it with `1.0.0` and swap out the old `0.11.1` snapshot with that.

**Comment by smackesey** [comment]
>I think it makes sense to rerecord it with 1.0.0 and swap out the old 0.11.1 snapshot with that.

Done

**Comment by alangenfeld** [comment]
I have some hesitancy to land this due to changing all job snapshots for users who update to a version including this change.

The most material consequence is cloud users having to re-upload all their job snapshots for their workspace. I am not sure this is material enough to be that meaningful yet but I do think its something that we probably need to be more mindful of.

**Review by alangenfeld — APPROVED** [review]
i think its likely fine

**Pull request merged**
