### PR TITLE
[components] TemplateParamsRenderer

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Refactor DSL evaluation into a class. This is to prepare for threading this through the stack, "stacking" contexts, and doing some unit testing, and being able apply consistent policy to all templating.

## How I Tested These Changes

BK

### CODE REVIEW

**Comment by schrockn** [comment]
* **#26339** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26339?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26339?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by OwenKephart — APPROVED** [review]
Internal class, so can punt on this, but not a huge fan of "DSL" and "Evaluator" in this class name. Not sure the scope of where this might be used in the future, but my instinct was to call it something like "ComponentRenderer"

**Comment by schrockn** [comment]
Let's do some bikeshedding in standup

**Review by schrockn — COMMENTED** [review]
So specifically on the name `ComponentRenderer` I don't like that sentence this only applies to components that have the DSL frontend and that won't be true for all components.

What this class does is resolve/eval a param that contains a template. 

`TemplatedParamResolver`
`ParamResolver`
`ParamTemplateRenderer`

Some combination of things like that.

**Comment by OwenKephart** [comment]
`TemplatedParamResolver` seems totally fine to me 👍

**Pull request closed without merging**
