### PR TITLE
RFC: Higher-level pattern for state-backed definitions and an adapter to expose them as CacheableAssetsDefinition

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

@smackesey Just wanted to show you what a slightly higher-level, opt-in pattern would look like. It's a little "Java-y", but it makes an adapter pattern quite straightforward in terms of the _inverse_ adapter where we want to write loaders in the new style but provide a backwards-compat version for people who do not want to migrate to the new entry point style. I think that will make the transition smoother. This adapter also provides an escape hook for people who do not want to thread context objects through.

## How I Tested These Changes

BK

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

### CODE REVIEW

**Comment by schrockn** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24496?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24496** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24496?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#24403** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24403?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24395** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24395?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24490** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24397** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24397?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24337** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24337?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
It's also pretty straightforward to imagine a functional variant of this that operates on a couple callbacks.

**Comment by smackesey** [comment]
Nice, I like this. Two questions:

- In this PR you have `load_powerbi_defs` just use this internally, but seems like it might make sense to just expose `PowerBIDefinitionsLoader` to the user and cut out `load_powerbi_defs`?
- Did you want to try to land this (presumably after moving the `StateBackedDefinitionsLoader` ABC into core) or is it just for illustrative purposes

**Comment by schrockn** [comment]
I think this should be an implementation detail only known to the integration authors. A single function call is easier for people consuming integrations IMO.

**Pull request closed without merging**
