### PR TITLE
feat: adding --ngrok/--expose flag to dagster-dev/dagster-webserver t…

### PR DESCRIPTION
**Pull request by chollinger93**
### What

This PR adds an optional flag to `dagster dev` to expose the dagster web server via [ngrok](https://ngrok.com), as `--ngrok`, aliased to `--expose`.

Technically also adds the same functionality to `dagster-webserver`.

Also adds documentation. 

### Why

While `dagster dev` doesn't replace a proper deployment and/or Dagster Cloud, it's still super useful to have the resulting web server available on the internet, quickly. 

My personal main use case is having the dagster ui available when working on our own dagster deployment, since we use headless Linux VMs as dev machines. 

It's also very useful to simply share a working branch of e.g. assets that rely on local infra and/or data with colleagues by simply handing them an ngrok link. You can, of course, also use some of the advanced features (traffic inspection, oauth, static domains etc) if you want to, which is neat.

But it's worth noting that this works just as well with just a free ngrok account, which I suspect most devs would use.

### 

```bash
export NGROK_AUTHTOKEN=your_token_here
dagster dev --ngrok # or dagster dev --expose
# dagster-webserver - INFO - Serving dagster-webserver on https://XXX.ngrok.app in process 89732 with ngrok
```

The resulting URL can be shared and stays valid until the dev server is closed. 

To use a static domain:

```bash 
export NGROK_AUTHTOKEN=your_token_here
export NGROK_DAGSTER_DOMAIN=mydomain.ngrok.dev
dagster dev --ngrok
```

We could also add more options later (e.g., auth) but this is the most barebones usage pattern that I think is most useful for most developers. I don't love the environment variables, but the token is a secret that shouldn't wind up on git + I did not want to pollute the CLI.

### Bad Setup

```bash
unset NGROK_AUTHTOKEN
dagster dev --ngrok
...
2024-02-29 16:02:34 -0500 - dagster - INFO - Launching Dagster services...
2024-02-29 16:02:38 -0500 - dagster.daemon - INFO - Instance is configured with the following daemons: ['AssetDaemon', 'BackfillDaemon', 'SchedulerDaemon', 'SensorDaemon']
2024-02-29 16:02:39 -0500 - dagster-webserver - WARNING - Port 3000 is in use - using port 64293 instead
Usage: python -m dagster_webserver [OPTIONS]
Try 'python -m dagster_webserver --help' for help.

Error: The --ngrok/--expose flag requires the NGROK_AUTHTOKEN environment variable to be set. You can find your auth token at https://https://dashboard.ngrok.com/get-started/your-authtoken
2024-02-29 16:02:39 -0500 - dagster - ERROR - An unexpected exception has occurred
Traceback (most recent call last):
  File "/Users/christian/workspace/dagster/python_modules/dagster/dagster/_cli/dev.py", line 219, in dev_command
    raise Exception(
Exception: dagster-webserver process shut down unexpectedly with return code 2
2024-02-29 16:02:39 -0500 - dagster - INFO - Shutting down Dagster services...
2024-02-29 16:02:39 -0500 - dagster.daemon - INFO - Received interrupt, shutting down daemon threads...
2024-02-29 16:02:39 -0500 - dagster.daemon - INFO - Daemon threads shut down.
2024-02-29 16:02:39 -0500 - dagster - INFO - Dagster services shut down.
```

### Happy Path

```bash
export NGROK_AUTHTOKEN=token
dagster dev --ngrok                           ...
2024-02-29 16:04:39 -0500 - dagster - INFO - Launching Dagster services...
2024-02-29 16:04:43 -0500 - dagster.daemon - INFO - Instance is configured with the following daemons: ['AssetDaemon', 'BackfillDaemon', 'SchedulerDaemon', 'SensorDaemon']
2024-02-29 16:04:43 -0500 - dagster-webserver - WARNING - Port 3000 is in use - using port 64318 instead
2024-02-29 16:04:44 -0500 - dagster-webserver - INFO - Serving dagster-webserver on https://1e6ab2401606.ngrok.app in process 54965 with ngrok
```

Opening the resulting domain gets me access to the dagster environment + I see my tunnel in the ngrok web UI:

image

image

### W/o the flag

Since this is 100% optional, this all work as it did before.

```bash
dagster dev         
...
2024-02-29 16:13:20 -0500 - dagster - INFO - Launching Dagster services...
2024-02-29 16:13:24 -0500 - dagster.daemon - INFO - Instance is configured with the following daemons: ['AssetDaemon', 'BackfillDaemon', 'SchedulerDaemon', 'SensorDaemon']
2024-02-29 16:13:24 -0500 - dagster-webserver - WARNING - Port 3000 is in use - using port 64696 instead
2024-02-29 16:13:24 -0500 - dagster-webserver - INFO - Serving dagster-webserver on http://127.0.0.1:64696 in process 65471
```

### Test w/ separate services/processes

This is only necessary for the web server, since everything else actually still runs locally. 

Setup

```bash
mkdir .dagster-home
export DAGSTER_HOME="$(pwd)/.dagster_home"
```

UI

```bash
dagster-webserver --expose -f complex_job.py                            
...
2024-02-29 16:20:01 -0500 - dagster-webserver - WARNING - Port 3000 is in use - using port 65000 instead
2024-02-29 16:20:01 -0500 - dagster-webserver - INFO - Serving dagster-webserver on https://7d3ff9e4ed1a.ngrok.app in process 75516 with ngrok
```

No services:

image

And

```bash
dagster-daemon run
```

image

### Static Domain Test

```bash
export NGROK_DAGSTER_DOMAIN=XYZ.ngrok.dev # valid domain
dagster dev  --expose
...
Serving dagster-webserver on https://XYZ.ngrok.dev in process 31871 with ngrok
```

```bash
export NGROK_DAGSTER_DOMAIN=invaliddomain.ngrok.dev # invalid domain / not one i have registered
dagster dev  --expose
...
ValueError: ('failed to start listener', "You must reserve a custom hostname for your account before it can be bound.\nFailed to bind the domain 'invaliddomain.ngrok.dev' for the account 'XXX@example.org''.\nReserve this name on your dashboard: https://dashboard.ngrok.com/cloud-edge/domains/new", 'ERR_NGROK_319')
2024-02-29 17:01:18 -0500 - dagster - ERROR - An unexpected exception has occurred
2024-02-29 17:01:18 -0500 - dagster - INFO - Shutting down Dagster services...
2024-02-29 17:01:18 -0500 - dagster.daemon - INFO - Received interrupt, shutting down daemon threads...
2024-02-29 17:01:18 -0500 - dagster.daemon - INFO - Daemon threads shut down.
2024-02-29 17:01:19 -0500 - dagster - INFO - Dagster services shut down.
```

### CODE REVIEW

**Comment by OwenKephart** [comment]
Hi @chollinger93, thanks for putting this together -- after talking about this internally, it feels like this sort of deeper integration is somewhat overkill considering you can get similar functionality from running ngrok in a separate terminal. That being said, I'm sure other users would find this workflow useful, and so a Github discussion outlining how to do that would likely be valuable to the community. Are you open to that alternative?

**Comment by chollinger93** [comment]
Hey @OwenKephart , that's fair! I think a native `--expose` flag is nice, since it'll hook onto the `dagster dev` process' lifecycle and can deal with port conflicts, so I do think this adds something on top of running the agent separately. It's been really nice for my workflow.

In case I can't convince you and the team 🙂 : Are you open to adding examples using the ngrok agent to the official docs? I feel that helps with discoverability, rather than using GH discussions.

**Comment by erinkcochran87** [comment]
Howdy @chollinger93! Keeper of the Dagster docs here. I hear ya on wanting more examples, but I'd prefer to start with a GH discussion and move it to the docs if it gets a lot of traction.  I can add links to the discussion in the appropriate docs to help with discoverability. This will also ensure there's a result for this in the search on the docs site.

**Comment by chollinger93** [comment]
Hey @erinkcochran87 sounds good, I'll put that together soon!

**Comment by chollinger93** [comment]
I finally got around to it: https://github.com/dagster-io/dagster/discussions/21053

**Comment by PedramNavid** [comment]
#21053

**Pull request closed without merging**
