### PR TITLE
[ui] Yarn 4.5.0

### PR DESCRIPTION
**Pull request by hellendag**
## Summary & Motivation

Stay on top of Yarn updates, upgrade packages to 4.5.0.

## How I Tested These Changes

Buildkite

### CODE REVIEW

**Comment by hellendag** [comment]
* **#25225** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25225?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hellendag and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by cmpadden — APPROVED** [review]
Confirmed that previews for DU, docs, and beta docs look as expected.

**Comment by cmpadden** [comment]
Note that the `Deploy Docs Revamp` failed with:
```
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module '/home/runner/work/dagster/dagster/docs/docs-beta/.yarn/releases/yarn-4.5.0.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.20.4```

**Comment by hellendag** [comment]
Thanks for flagging that, taking a look now.

**Pull request merged**
