### PR TITLE
Add __init__.py

### LINKED ISSUE #1149: cannot run "pytest dagster-framework" from python_modules even though the dagster-framework folder exists
This breaks:

Screenshot 2019-04-06 06 55 25

This works:

Screenshot 2019-04-06 06 56 40

### PR DESCRIPTION
**Pull request by mgasner**
Resolves #1149, though I confess I'm a little confused why we don't also need python_modules/dagster-framework/snowflake/__init__.py -- in fact, adding this file reproduces the error.

### CODE REVIEW

**Comment by schrockn** [comment]
did you do init.py instead of __init__.py

**Comment by mgasner** [comment]
No, and I just confirmed locally that adding `__init__.py` breaks it. Can you confirm that this PR fixes for you?

**Comment by schrockn** [comment]
Some behavior on my box confirmed. Very strange

**Comment by mgasner** [comment]
probably https://www.python.org/dev/peps/pep-0420/ because we're running py >3.3

**Pull request closed without merging**
