### PR TITLE
Add hidden_param and use it on non_argument_deps

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

We have functions with tons of parameters. This can be super noisy in typeahead can be contribute to Parameter Anxiety.

However there is lots of code written against Dagster's APIs and changing them is hard.

This PR proposes a compromise solution that 1) hides parameter from type signatures while 2) preserving backwards compatibility at the cost of 3) users catching some errors at runtime that could have been caught by the typechecker.

This is best demonstrated with a simple example.

Imagine we had a function `foo` that takes a parameter `baz`. 

```python
def foo(bar: Optional[str] = None) -> bool:
   ...
```

Now we make the determination that `bar` was a mistake, and that we want to ignore it. We don't want to break existing code, but we want to strongly discourage users adding callsites. We can accomplish this with the hidden param.

```python
@hidden(param="baz", breaking_version="2.0")
def foo(**kwargs) -> bool:
    # only_allow_hidden_params_in_kwargs gives high qualtiy error messages
    only_allow_hidden_params_in_kwargs(with_hidden_args, kwargs)
    # with this check call you can leave the rest of the function unmodified since bar is Optional[bar] as before
    bar = check.opt_str_param("bar", kwargs.get("bar"))
    ...
```

In this contrived example it doesn't make sense to that, but in a function like `asset` with 25 (!!!) parameters it makes much more sense.

This PR then applies this new option to `non_argument_deps` on `asset` and `multi_asset`.

## How I Tested These Changes

Before:

After:

### CODE REVIEW

**Comment by schrockn** [comment]
* **#22385** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22385?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by schrockn** [comment]
I've floated this before but I'm much more serious about it now. 

```python
    freshness_policy: Optional[FreshnessPolicy] = None,
    auto_materialize_policy: Optional[AutoMaterializePolicy] = None,
    backfill_policy: Optional[BackfillPolicy] = None,
```

All three of the above can/should be hidden ASAP IMO so this is timely.

**Comment by schrockn** [comment]
Adding @rexledesma since `load_assets_from_dbt_manifest` and friends is a target-rich environment for this.

**Review by sryza — COMMENTED** [review]
Generally positive about this direction.

Main questions:
- How does it show up in API docs / how would we ideally like it to show up in API docs?
- Would we do this for all deprecated parameters? If not, what's our rule for when we do vs. don't do it?

**Comment by sryza** [comment]
Sidenote: the `backfill_policy` arg on `@asset` can be hidden?

**Comment by schrockn** [comment]
> Sidenote: the `backfill_policy` arg on `@asset` can be hidden?

Not currently, but in a post-backfill world where everything is a run we will almost certainly rename it.

**Comment by schrockn** [comment]
> How does it show up in API docs / how would we ideally like it to show up in API docs?

An excellent question. I am not sure. For now I was just assuming put them at the end of the argument list with text that indicates they are hidden. However we could more formally support them.

> Would we do this for all deprecated parameters? If not, what's our rule for when we do vs. don't do it?

I think we should talk this through. Without in-depth analysis my first instinct that we can generally hide whenever we deprecate and we should default to that when there is non-experimental functionality the supplants it (although not sure we should ever all that tbh).  However loosening typing guarantees is not without cost so I could imagine some cases that cost outweighs the benefits.

**Comment by schrockn** [comment]
Another example: https://app.graphite.dev/github/pr/dagster-io/dagster/22387/load_assets_from_dbt_manifest#

**Comment by sryza** [comment]
Not saying this is necessarily a bad thing, but to add some specifics to the API docs discussion, one consequence is that it will presumably affect this auto-generated list:

image

https://docs.dagster.io/_apidocs/assets#dagster.asset

I.e. presumably "kwargs" will show up there, and the hidden parameters won't.

**Comment by schrockn** [comment]
Hey all I started an [internal discussion](https://github.com/dagster-io/internal/discussions/10315) to drive conversation here. I want to make a decision whether to ship this or not by the end of next week.

**Review by OwenKephart — APPROVED** [review]
I am very supportive of this pattern and would love to start using it immediately in service of hiding deprecated `auto_materialize_policy` parameters.

**Comment by PedramNavid** [comment]
I am also largely supportive. I do think we will need some way of ensuring that we can test that doc strings do not become outdated. 

We already have had issues where the docstrings don't match the actual keyword arguments in a function or the types are wrong. This will get even harder if the arguments are hidden under a kwargs. But those arent blocking issues, so happy with this direction.

**Comment by cmpadden** [comment]
Also in favor of this approach. Others have indicated my concerns already (re: rendering this in docs).

I suspect we'll be able to customize doc generation to indicate or hide the hidden params. 👍

**Comment by schrockn** [comment]
### Merge activity

* **Oct 21, 8:06 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22385).

**Comment by schrockn** [comment]
@OwenKephart FYI merged.

Also this PR is so old that it predated your new great changelog process. Is there a good way to add it to the automated process after the fact?

**Comment by OwenKephart** [comment]
@schrockn After merging, there's no great way of getting it scooped up automatically bc we use the git history, but for future reference you can just add:

```
## Changelog

<your entry>
```

to the PR.

But if you write a changelog entry in this discussion, then the person assembling the changelog will be able to find it

**Comment by danielgafni** [comment]
@schrockn you could use 

```python
from typing import TypeDict
from typing_extensions import Unpack


class MyKwargs(TypedDict):
    foo: str
    bar: int

def my_func(**kwargs: Unpack[MyKwargs]):
    ...
```

to add typing information to `**kwargs`. We could also extract it when building docs.

**Comment by schrockn** [comment]
Changelog entry:  On `asset` and `multi_asset`, `non_argument_deps` has been hidden. It can still be passed as a keyword arg, but it will no longer appear in explicit argument list and in-IDE typeaheads.

**Pull request merged**
