### PR TITLE
stale_assets_only doesnt support partitions (#18921)

### PR DESCRIPTION
**Pull request by the4thamigo-uk**

### CODE REVIEW

**Comment by sryza** [comment]
Hey @the4thamigo-uk - thanks for you patience. I pinged @smackesey about this.

**Comment by the4thamigo-uk** [comment]
No review yet?

**Comment by schrockn** [comment]
Is there more context here? Why is the motivation behind this change? Is there an issue?

**Comment by the4thamigo-uk** [comment]
Hi @schrockn, the scenario is here https://github.com/dagster-io/dagster/issues/18921.

**Comment by smackesey** [comment]
This looks OK given that it's such a small change and nothing broke, but I'm wondering whether you tested this manually at all?

**Comment by the4thamigo-uk** [comment]
I suppose I should write a unit test for this, I will try to find the time.

**Pull request closed without merging**
