### PR TITLE
Change tutorial to use dag_defs

### PR DESCRIPTION
**Pull request by schrockn**
## Summary & Motivation

Use `dbt_defs` and `task_defs` in tutorial

## How I Tested These Changes

BK

## Changelog [New | Bug | Docs]

NOCHANGELOG

### CODE REVIEW

**Comment by schrockn** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23883?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23883** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23883?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#23881** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23881?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by benpankow — APPROVED** [review]

**Comment by schrockn** [comment]
@dpeng817 would like your thoughts before I commit

**Review by dpeng817 — APPROVED** [review]
LGTM

**Comment by schrockn** [comment]
### Merge activity

* **Aug 26, 2:31 PM EDT**: @schrockn started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/23883).

**Pull request merged**
