### PR TITLE
Move celery k8s test suite to buildkite docker queue

### PR DESCRIPTION
**Pull request by gibsondan**
Summary:
[test-all]
Python 3.11 and 3.12 use more resources and crash the agent unless we run them on beefier boxes. We should decide if we think the additional coverage is worth the increased resource usage.

Test Plan: BK

### CODE REVIEW

**Review by alangenfeld — COMMENTED** [review]
should we pare down `pytest_tox_factors` to sort of balance out? I am not sure they all make sense still, especially after you paired things down

**Review by alangenfeld — APPROVED** [review]
I think it's worth a little time checking if you can drop some pytest factors but wouldn't waste too much time on it

**Comment by gibsondan** [comment]
that turned this into a nice red PR, any objections?

**Comment by alangenfeld** [comment]
😍  ship it

**Pull request merged**
