### PR TITLE
feat(logging): apply log format to user logs

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
As the title.

## How I Tested These Changes
pytest, `dagster dev --log-format=rich` and run `hammer` job. See user logs come in rich format.

### CODE REVIEW

**Comment by rexledesma** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18948?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #18936** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18936?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #18937** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18937?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #18948** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/18948?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/18948?utm_source=stack-comment).

**Review by dpeng817 — COMMENTED** [review]
Unit tests would be nice here. default_system_loggers seems like a nice place to plug in given that it's exported at top level.

Trying to think through whether we need to worry about the env var getting propogated through to new containerized environments (IE, using k8s, ecs, docker executors), since loggers will be re-initialized in every step. I guess we probably just need to communicate to users that they need to propogate that env var in their image.

**Comment by rexledesma** [comment]
> Unit tests would be nice here. default_system_loggers seems like a nice place to plug in given that it's exported at top level.
> 
> Trying to think through whether we need to worry about the env var getting propogated through to new containerized environments (IE, using k8s, ecs, docker executors), since loggers will be re-initialized in every step. I guess we probably just need to communicate to users that they need to propogate that env var in their image.

Yeah, this will be configured by env var. In Dagster Cloud, they could just set the env var in the UI/agent.

An env var is our best shot at global configuration of these logs, since when users are just configuring their user code business logic, we don't require them to have another global configuration file like `dagster.yaml`.

**Review by dpeng817 — APPROVED** [review]
Only thing that comes to mind is making sure that nonsensical format strings are properly handled.

**Comment by slopp** [comment]
Are we landing this PR with docs or is that a follow up?

**Comment by rexledesma** [comment]
> Are we landing this PR with docs or is that a follow up?

It's a follow up. We want to internally validate the user experience of setting this up before exposing this feature.

**Pull request closed without merging**
