### PR TITLE
interpret MaterializeResult return type annotation as Nothing

### PR DESCRIPTION
**Pull request by jamiedemaria**
## Summary & Motivation
Before if you wrote this asset 
```python
@asset 
def my_asset() -> MaterializeResult:
   return MaterializeResult(metadata={"foo":"bar"})
```
you would get a type error 
```
dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "MaterializeResult". Description: Value of type <class 'NoneType'> failed type check for Dagster type MaterializeResult, expected value to be of Python type dagster._core.definitions.result.MaterializeResult.
```

This is because we coerce returned `MaterializeResult`s to `Output(None)` but we do not update the expected return type.

This PR interprets the return type annotation `MaterializeResult` as a `Nothing` return type annotation. This will also allow the IO managers to skip storing `MaterializeResult`

This PR does not address when no type annotation is given. The asset 
```python
@asset 
def my_asset():
   return MaterializeResult(metadata={"foo":"bar"})
```
will get the implied return type `Any`, which means the IO managers may try to store the `MaterializeResult` type. I think we can add special logic to skip IO manager invocation when the return value is a `MaterializeResult` but that will need to be explored in another PR

### CODE REVIEW

**Comment by jamiedemaria** [comment]
Current dependencies on/for this PR:
* master
  * **PR #16883** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16883" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16883?utm_source=stack-comment).

**Comment by jamiedemaria** [comment]
This is my first foray into the type checking system. please let me know if there is a more sane way to do this. I considered writing a new `MaterializeResultType` type annotation that we could coerce to, but that wouldn't give us the ability to skip IO managers without updating all of the IO managers 

Wholesale converting `MaterializeResult` type annotations to `Nothing`s seems like something that could have unintended consequences that I'm unaware of due to unfamiliarity with this part of the system

**Review by schrockn — APPROVED** [review]
Per video call let's move forward with this mitigation.

@jamiedemaria Please add a link to an issue re: adding value support to `MaterializeResult` to dagster_type.py#875 so we have a place to collect feedback and have discussions on this topic.

**Comment by schrockn** [comment]
@jamiedemaria this does not work on direct invocation of assets. We should fix that tmrw.

**Pull request merged**
