### PR TITLE
Feature: add Dynatrace resource

### PR DESCRIPTION
**Pull request by JPeer264**
We made a basic Dynatrace resource for dagster to communicate with the [Dynatrace API](https://www.dynatrace.com/support/help/dynatrace-api/)

### CODE REVIEW

**Comment by alangenfeld** [comment]
Hey apologies for the slow response here, we haven't nailed down our policy on taking on externally submitted libraries in to this core repo, and the maintenance of those libraries that that would entail.

**Comment by JPeer264** [comment]
No worries, I bet this is a hard decision.

Regarding the maintenance:
I think we can take care of updates regarding the Dynatrace API. When it is about changing the core of Dagster (like breaking changes in the core, so our library is needs a refactor), I cannot guarantee that we are always up-to-date. I hope this helps a little with your decisions.

**Comment by mgasner** [comment]
Hi @JPeer264, I think we are facing some test failures -- can we resolve those so we can push this forward?

**Review by mgasner — CHANGES_REQUESTED** [review]
Resolve test failures

**Comment by JPeer264** [comment]
Sure feel free to push :)

**Comment by mgasner** [comment]
hm, i don't think I can rebase your branch for you --

**Comment by PedramNavid** [comment]
Closing stale PR.

**Pull request closed without merging**
