### PR TITLE
[refactor] remove @solid decorator

### PR DESCRIPTION
**Pull request by smackesey**
### Summary & Motivation

Remove the `@solid` decorator and update all references of it to `@op`. This also involved updating `input_defs` and `output_defs` to `ins` and `out` respectively.

Internal companion PR: https://github.com/dagster-io/internal/pull/4900

One GQL snapshot (for `dynamic_pipeline` around line ~950 of `graphql/repo.py`) updated as a result of switch to `DynamicOut`.

### How I Tested These Changes

BK

### CODE REVIEW

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10811** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10811" target="_blank">Graphite</a> 
    * **PR #10861** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10861" target="_blank">Graphite</a> 
    * **PR #10846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10846" target="_blank">Graphite</a> 
      * **PR #10847** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10847" target="_blank">Graphite</a> 
        * **PR #10848** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10848" target="_blank">Graphite</a> 
          * **PR #10850** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10850" target="_blank">Graphite</a> 
            * **PR #10857** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10857" target="_blank">Graphite</a> 
              * **PR #10919** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10919" target="_blank">Graphite</a> 
                * **PR #10920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10920" target="_blank">Graphite</a> 
                  * **PR #10833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10833" target="_blank">Graphite</a> 
                  * **PR #10816** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10816" target="_blank">Graphite</a> 
                    * **PR #10952** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10952" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10952?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10811** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10811" target="_blank">Graphite</a> 
    * **PR #10861** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10861" target="_blank">Graphite</a> 
    * **PR #10846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10846" target="_blank">Graphite</a> 
      * **PR #10847** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10847" target="_blank">Graphite</a> 
        * **PR #10848** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10848" target="_blank">Graphite</a> 
          * **PR #10850** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10850" target="_blank">Graphite</a> 
            * **PR #10857** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10857" target="_blank">Graphite</a> 
              * **PR #10919** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10919" target="_blank">Graphite</a> 
                * **PR #10920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10920" target="_blank">Graphite</a> 
                  * **PR #10833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10833" target="_blank">Graphite</a> 
                  * **PR #10816** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10816" target="_blank">Graphite</a> 
                    * **PR #10952** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10952" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10952?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10811** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10811" target="_blank">Graphite</a> 
    * **PR #10861** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10861" target="_blank">Graphite</a> 
    * **PR #10846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10846" target="_blank">Graphite</a> 
      * **PR #10847** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10847" target="_blank">Graphite</a> 
        * **PR #10848** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10848" target="_blank">Graphite</a> 
          * **PR #10850** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10850" target="_blank">Graphite</a> 
            * **PR #10857** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10857" target="_blank">Graphite</a> 
              * **PR #10919** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10919" target="_blank">Graphite</a> 
                * **PR #10920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10920" target="_blank">Graphite</a> 
                  * **PR #10833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10833" target="_blank">Graphite</a> 
                  * **PR #10816** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10816" target="_blank">Graphite</a> 
                    * **PR #10952** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10952" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10952?utm_source=stack-comment).

**Comment by smackesey** [comment]
Current dependencies on/for this PR:
* master
  * **PR #10811** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10811" target="_blank">Graphite</a> 
    * **PR #10861** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10861" target="_blank">Graphite</a> 
    * **PR #10846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10846" target="_blank">Graphite</a> 
      * **PR #10847** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10847" target="_blank">Graphite</a> 
        * **PR #10848** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10848" target="_blank">Graphite</a> 
          * **PR #10850** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10850" target="_blank">Graphite</a> 
            * **PR #10857** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10857" target="_blank">Graphite</a> 
              * **PR #10919** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10919" target="_blank">Graphite</a> 
                * **PR #10920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10920" target="_blank">Graphite</a> 
                  * **PR #10833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10833" target="_blank">Graphite</a> 
                  * **PR #10816** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10816" target="_blank">Graphite</a> 
                    * **PR #10952** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10952" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10952?utm_source=stack-comment).

**Review by alangenfeld — APPROVED** [review]

**Comment by sryza** [comment]
!!!!!!!!!!

**Comment by sryza** [comment]
very exciting

**Pull request merged**
