### PR TITLE
[dagster-azure] fix azure compute log manager credentialing

### PR DESCRIPTION
**Pull request by dpeng817**
Using this PR to accumulate downstack before landing.

ORIGINAL PR MESSAGE:
## Summary & Motivation
I think the existing credentialing here is busted - `BlobServiceClient` doesn't accept a bare secret string anymore - instead, in order to pass a secret, you need a fully qualified dictionary.

Technically this is a breaking change but I don't see how it could be working right now anyway.

## How I Tested These Changes
Tested manually with a local dagster installation running the compute log manager live. Downstream I'll add actual integration tests.

### CODE REVIEW

**Review by mlarose — APPROVED** [review]

**Comment by dpeng817** [comment]
### Merge activity

* **Dec 5, 1:18 PM PST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/26157).

**Comment by ion-elgreco** [comment]
@dpeng817 why did you remove the functionality to use azure access keys????!

According to the docs it's still supported: https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobserviceclient?view=azure-python#parameters

**Comment by ion-elgreco** [comment]
Honestly, this is extremely annoying. @dpeng817 now I have to override the class again

**Comment by dpeng817** [comment]
@ion-elgreco apologies if this was a breaking change for you. When this was originally contributed, it was done so without integration tests, and the existing parameter name of "credential" is confusing given that it only accepts a SAS token. I assumed (seemingly incorrectly) that the original intent here was to accept an azure credential class rather than a SAS token. Would you find it acceptable if we added support for auth by SAS token under a different parameter, to keep things less confusing?

Again, sorry for the thrash here.

**Comment by ion-elgreco** [comment]
> @ion-elgreco apologies if this was a breaking change for you. When this was originally contributed, it was done so without integration tests. In the process of putting it under integration test, i found the existing parameter name of "credential" is confusing given that it only accepts a SAS token. I assumed (seemingly incorrectly) that the original intent here was to accept an azure credential class rather than a SAS token. Would you find it acceptable if we added support for auth by SAS token under a different parameter, to keep things less confusing?
> 
> Again, sorry for the thrash here.

If it's under a different parameter, I am completely fine with that. The BlobServiceClient can accept a string which can be an accesskey or sas token.

**Comment by dpeng817** [comment]
@ion-elgreco I'll prioritize getting that added under a new parameter (under integration test this time, so there's no further confusion). Thanks for bearing with us here, and I'll make sure to tag you on the new PR so you can take a look if you're interested.

**Comment by ion-elgreco** [comment]
Thanks! @dpeng817 feel free to ping me

**Comment by dpeng817** [comment]
@ion-elgreco ; here's the PR which adds back support for both access key and sas token: https://github.com/dagster-io/dagster/pull/26653

**Pull request merged**
