### PR TITLE
Set up basic coverage reporting

### PR DESCRIPTION
**Pull request by mgasner**
This doesn't aggregate the coverage reports

### CODE REVIEW

**Comment by schrockn** [comment]
Will this surface itself in github? Having it in the developer workflow is pretty critical.

**Comment by mgasner** [comment]
Not as written. Things to do to get this in github are:
1) Figure out how to append the coverage reports from tox (i.e., aggregate coverage in py2.7, py3.5, py3.6)
2) Upload the coverage reports as artifacts
3) Combine the coverage artifacts for the subprojects
4) Report coverage back to GH with a tool such as https://github.com/vivlabs/coverage-github-reporter

**Comment by mgasner** [comment]
Closing until we can get results back in GH

**Comment by schrockn** [comment]
Oh I don't thing we should close this.

**Comment by mgasner** [comment]
Just want to make a few notes to record future to-dos:
- This does not yet aggregate JS coverage reports (from dagit-webapp), but those coverage reports are still visible in terminal output when running tests on Circle
- We may want to track coverage for a specific python version rather than, as now, reporting the union of coverage across all versions back to Github. (That is to say, right now, if something is covered under 2.7 but not under 3.6, it is reported as covered. Limitations of the 3rd party systems we're working with will make it difficult to report each separately back to GitHub -- we can still preserve the coverage reports as build artifacts.)
- We may want to preserve the HTML coverage reports as well as the raw .coverage files so that we can get a pretty view of coverage on a per-job basis in the CircleCI interface.

**Pull request merged**
