### PR TITLE
chore(sdf): temporarily remove `uv`

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary & Motivation
As the title. Until some `pip` or `uv` stuff gets sorted out.

## How I Tested These Changes
bk

### CODE REVIEW

**Comment by rexledesma** [comment]
* **#23306** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23306?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rexledesma and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by cmpadden — APPROVED** [review]
😢

**Comment by gibsondan** [comment]
Adding [test-all] maybe a good idea to see if it actually fixes the problem on 3.12?

**Comment by rexledesma** [comment]
@gibsondan I added it here: https://github.com/dagster-io/dagster/pull/23306/commits/6d2bdb96c96a947aa04be3df31ca35434cd288fc

The tests ran: https://buildkite.com/dagster/dagster-dagster/builds/89230

**Pull request merged**
