### PR TITLE
Add sidebar asset node menu to asset graph node as context menu

### PR DESCRIPTION
**Pull request by salazarm**
## Summary & Motivation
Refactors the existing Sidebar popover menu so that it can be reused by the asset graph itself for a context menu that appears on the individual asset graph nodes when you right click. 

## How I Tested These Changes
locally right click on a node in the asset graph and see the menu appear

Screenshot 2023-11-14 at 2 46 43 PM

### CODE REVIEW

**Comment by salazarm** [comment]
@braunjj wdyt of this? I think inevitably people will ask for an easy to only check only the ones that are missing or stale for the upstream of particular asset so maybe we can find a nice way to add that ability?

**Comment by sryza** [comment]
We were chatting about this yesterday in the Core + UI weekly. Is there a reason we don't think clicking "Show upstream graph" and then clicking the normal "Materialize All" button would be sufficient? In general, I think it's a better experience to see a set of assets on the asset graph before materializing them than to see them in a list. I'm also concerned about adding more clutter to that menu.

Separately, I'm a little worried about the discoverability of that menu. Would it make sense to also have a context menu on the asset nodes themselves?

**Comment by salazarm** [comment]
> Would it make sense to also have a context menu on the asset nodes themselves?

This PR is doing that, it adds the same menu from the sidebar to show up as a context menu

**Comment by salazarm** [comment]
> We were chatting about this yesterday in the Core + UI weekly. Is there a reason we don't think clicking "Show upstream graph" and then clicking the normal "Materialize All" button would be sufficient? In general, I think it's a better experience to see a set of assets on the asset graph before materializing them than to see them in a list. I'm also concerned about adding more clutter to that menu.


The reason I did make the dialog is because based off the issue it sounded like we wanted a two-step process so this is more of a confirmation dialog.

**Comment by salazarm** [comment]
Though I do think that the flattened list makes it a little easier to select assets rather than having to pan/scroll around and click on assets, though you can also shift click from the sidebar to do that or just click on materialize changed and missing from the top right 🤔 which is probably what you want to do so I think I convinced myself maybe this button isn't necessary since we have that

**Comment by salazarm** [comment]
Updated the PR

**Review by hellendag — APPROVED** [review]

**Pull request merged**
