### PR TITLE
[docs][pythonic_resources] Update remaining refs to fs_io_manager

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Fixes some stray docs references to the non-pythonic `fs_io_manager`

### CODE REVIEW

**Comment by benpankow** [comment]
Current dependencies on/for this PR:
* master
  * **PR #14035** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14035" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14035?utm_source=stack-comment).

**Review by erinkcochran87 — COMMENTED** [review]
I found a few more when I pulled the branch down - some in the I/O managers page you updated, and another one in the PySpark guide. I left comments on the Vercel preview; let me know if you can't see them!

**Review by erinkcochran87 — COMMENTED** [review]
I still see `fs_io_manager` being used in code examples - specifically here:

- `/examples/docs_snippets/docs_snippets/concepts/assets/asset_different_io_managers.py` - This shows up in the I/O managers page in the [**Per-asset I/O manager** section](https://dagster-at4mnh8gh-elementl.vercel.app/concepts/io-management/io-managers#per-asset-io-manager)
- `/examples/docs_snippets/docs_snippets/concepts/io_management/io_manager_per_output.py` - This shows up in the I/O managers page in the [**Per-output I/O manager** section](https://dagster-at4mnh8gh-elementl.vercel.app/concepts/io-management/io-managers#per-output-io-manager). This section (in `/concepts/io-management/io-managers`) also contains a reference on line 279.

I think these snippets might be shared with the legacy I/O managers page, so there might need to be some example separation here.

Additionally, since this PR was started, a new section was added to the tutorial that uses `fs_io_manager`: `/tutorial/saving-your-data.mdx`. I can ask Tim to take a look at updating that guy if you like, but just thought I'd mention it.

**Comment by benpankow** [comment]
Thanks for that, updated to get those last few references! The one in I/O managers per asset just uses `fs_io_manager` as the resource name, so it's kept for now. The actual reference to the `fs_io_manager` import is gone.

**Review by erinkcochran87 — APPROVED** [review]

**Pull request merged**
